// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.33/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/ReportPlayer/core/annotations/shape/_ShapeElementRenderer",["dojo/dom-construct","esri/dijit/geoenrichment/utils/ShapeUtil","./ShapeBarFlowDirections","./ShapeScaleAnchorPositions"],function(q,u,m,n){function w(c){function b(a){function b(a,b){"number"===typeof a&&(a=Math.round(a)+"px");"string"===typeof a&&(h.style[b]=a)}var h=q.create("div",{"class":"esriGEAbsoluteStretched shapeContainer_svgContainer shapeContainer_svgContainerShowAsBar"},c.content),f=a?e.bg:e.v;
b(f.t,"top");b(f.r,"right");b(f.b,"bottom");b(f.l,"left");b(f.w,"width");b(f.h,"height");var d=r(c,a?c.bgStyle:c.shapeStyle,h);d.style.top="auto";d.style.left="auto";switch(c.bar.flowDirection){case m.UP:d.style.bottom=(a?-f.b:0)-f.childBox.t+"px";d.style.left=f.childBox.l+"px";break;case m.DOWN:d.style.top=(a?-f.t:0)+f.childBox.t+"px";d.style.left=f.childBox.l+"px";break;case m.LEFT:d.style.top=f.childBox.t+"px";d.style.right=(a?-f.r:0)-f.childBox.l+"px";break;default:d.style.top=f.childBox.t+"px",
d.style.left=(a?-f.l:0)+f.childBox.l+"px"}}var e=x(c);c.bar.showBackground&&b(!0);b()}function x(c){var b=Math.max(0,Math.min(1,c.value)),e={t:0,r:0,b:0,l:0,w:void 0,h:void 0,childBox:{l:0,t:0}},a={t:0,r:0,b:0,l:0,w:void 0,h:void 0,childBox:{l:0,t:0}},g=c.shapeW,h=c.shapeH,f=t(c),d=c.borderWidth/2;switch(c.bar.flowDirection){case m.UP:g=f.b+b*f.h;e.t="auto";e.h=g+d;e.l=-d;e.r=-d;e.b=-d;e.childBox.t=-d;e.childBox.l=d;a.t="auto";a.b=g;a.h=h-g+d;a.l=-d;a.r=-d;a.childBox.t=0;a.childBox.l=d;break;case m.DOWN:g=
f.y+b*f.h;e.b="auto";e.h=g+d;e.l=-d;e.r=-d;e.t=-d;e.childBox.t=d;e.childBox.l=d;a.b="auto";a.t=g;a.h=h-g+d;a.l=-d;a.r=-d;a.childBox.t=0;a.childBox.l=d;break;case m.LEFT:h=f.r+b*f.w;e.l="auto";e.w=h+d;e.t=-d;e.b=-d;e.r=-d;e.childBox.t=d;e.childBox.l=-d;a.l="auto";a.r=h;a.w=g-h+d;a.t=-d;a.b=-d;a.childBox.t=d;a.childBox.l=0;break;default:h=f.x+b*f.w,e.r="auto",e.w=h+d,e.t=-d,e.b=-d,e.l=-d,e.childBox.t=d,e.childBox.l=d,a.r="auto",a.l=h,a.w=g-h+d,a.t=-d,a.b=-d,a.childBox.t=d,a.childBox.l=0}return{v:e,
bg:a}}function y(c){function b(b){function f(d){var f=r(c,b?c.bgStyle:c.shapeStyle,h);f.style.top="auto";f.style.left="auto";var g=c.bar.spaceBetween||0;switch(c.bar.flowDirection){case m.UP:f.style.bottom=d*(a+g)+(b?-k.b:0)-k.childBox.t+"px";f.style.left=k.childBox.l+"px";break;case m.DOWN:f.style.top=d*(a+g)+(b?-k.t:0)+k.childBox.t+"px";f.style.left=k.childBox.l+"px";break;case m.LEFT:f.style.top=k.childBox.t+"px";f.style.right=d*(e+g)+(b?-k.r:0)-k.childBox.l+"px";break;default:f.style.top=k.childBox.t+
"px",f.style.left=d*(e+g)+(b?-k.l:0)+k.childBox.l+"px"}}function d(a,b,c){"number"===typeof a&&(a=Math.round(a+b)+"px");"string"===typeof a&&(h.style[c]=a)}var h=q.create("div",{"class":"esriGEAbsoluteStretched shapeContainer_svgContainer shapeContainer_svgContainerShowAsBar"},c.content),k=b?g.bg:g.v;d(k.t,k.offset.t,"top");d(k.r,k.offset.r,"right");d(k.b,k.offset.b,"bottom");d(k.l,k.offset.l,"left");d(k.w,0,"width");d(k.h,0,"height");for(var p=b?g.bg.numShapes:g.v.numShapes,n=0;n<p;n++)f(n)}var e=
c.shapeW,a=c.shapeH,g=z(c);c.bar.showBackground&&b(!0);b()}function z(c){var b=t(c),e=Math.max(0,Math.min(1,c.value)),a=1,g=1,h=c.bar.spaceBetween||0,f=!c.bar.flowDirection||m.isHorizontal(c.bar.flowDirection),d=f?c.shapeW:c.shapeH,g=Math.max(1,Math.floor(((f?c.width:c.height)+h)/(d+h))),a=c.bar.wholeIcons?Math.round(e*g):Math.ceil(e*g),a={t:0,r:0,b:0,l:0,w:void 0,h:void 0,offset:{t:0,r:0,b:0,l:0},childBox:{l:0,t:0},numShapes:a},l={t:0,r:0,b:0,l:0,w:void 0,h:void 0,offset:{t:0,r:0,b:0,l:0},childBox:{l:0,
t:0},numShapes:g},k=(c.shapeW+h)*(f?g:1)-h,p=(c.shapeH+h)*(f?1:g)-h,n=Math.floor(g*e),e=g*e-n;c.bar.wholeIcons&&(e=Math.round(e));g=0;switch(c.bar.flowDirection){case m.UP:g=b.b;break;case m.DOWN:g=b.y;break;case m.LEFT:g=b.r;break;default:g=b.x}e=(n*(d+h)+g+b[f?"w":"h"]*e)/(f?k:p);h=(c.width-c.shapeW)/2;f=(c.height-c.shapeH)/2;b=c.borderWidth/2;switch(c.bar.flowDirection){case m.UP:k=e*p;a.t="auto";a.h=k+b;a.offset.l=h;a.l=-b;a.r=-b;a.b=-b;a.childBox.t=-b;a.childBox.l=b;l.t="auto";l.b=k;l.h=p-k+
b;l.offset.l=h;l.l=-b;l.r=-b;l.childBox.t=0;l.childBox.l=b;break;case m.DOWN:k=e*p;a.b="auto";a.h=k+b;a.offset.l=h;a.l=-b;a.r=-b;a.t=-b;a.childBox.t=b;a.childBox.l=b;l.b="auto";l.t=k;l.h=p-k+b;l.offset.l=h;l.l=-b;l.r=-b;l.childBox.t=0;l.childBox.l=b;break;case m.LEFT:p=e*k;a.l="auto";a.w=p+b;a.offset.t=f;a.t=-b;a.b=-b;a.r=-b;a.childBox.t=b;a.childBox.l=-b;l.l="auto";l.r=p;l.w=k-p+b;l.offset.t=f;l.t=-b;l.b=-b;l.childBox.t=b;l.childBox.l=0;break;default:p=e*k,a.r="auto",a.w=p+b,a.offset.t=f,a.t=-b,
a.b=-b,a.l=-b,a.childBox.t=b,a.childBox.l=b,l.r="auto",l.l=p,l.w=k-p+b,l.offset.t=f,l.t=-b,l.b=-b,l.childBox.t=b,l.childBox.l=0}return{v:a,bg:l}}function A(c){function b(a){var b=q.create("div",{"class":"esriGEAbsoluteStretched shapeContainer_svgContainer"},c.content),h=a?{l:0,t:0}:e,f=c.borderWidth/2;f&&(b.style.left=-f+"px",b.style.top=-f+"px",b.style.right=-f+"px",b.style.bottom=-f+"px",h.t+=f,h.l+=f);r(c,a?c.bgStyle:c.shapeStyleBuilder(e),b,h)}var e=B(c);c.scale.showBackground&&b(!0);b()}function B(c){var b=
t(c),e=Math.max("number"===typeof c.scale.minScale?c.scale.minScale:v.MIN_SCALE,Math.min(1,c.value)),a=c.shapeW,g=c.shapeH,h=a*e,f=g*e,d={t:0,l:0,w:h,h:f};switch(c.scale.anchorPosition){case n.TOP_LEFT:d.t=b.y*(1-e);d.l=b.x*(1-e);break;case n.TOP:d.t=b.y*(1-e);d.l=(a-h)/2;break;case n.TOP_RIGHT:d.t=b.y*(1-e);d.l=a-h-b.r*(1-e);break;case n.LEFT:d.t=(g-f)/2;d.l=b.x*(1-e);break;case n.CENTER:d.t=(g-f)/2;d.l=(a-h)/2;break;case n.RIGHT:d.t=(g-f)/2;d.l=a-h-b.r*(1-e);break;case n.BOTTOM_LEFT:d.t=g-f-b.b*
(1-e);d.l=b.x*(1-e);break;case n.BOTTOM_RIGHT:d.t=g-f-b.b*(1-e);d.l=a-h-b.r*(1-e);break;default:d.t=g-f-b.b*(1-e),d.l=(a-h)/2}return d}function r(c,b,e,a){var g=a?a.l:0,h=a?a.t:0,f=a&&a.w||c.shapeW;a=a&&a.h||c.shapeH;e=q.create("div",{"class":"shapeContainer_svgContainerElement"},e);e.style.top=h+"px";e.style.left=g+"px";e.style.width=f+"px";e.style.height=a+"px";b=u.createSVGFromJson({viewBox:c.viewBox,g:c.g},f,a,b,{noDefaults:!0,preserveAspectRatio:c.preserveAspectRatio,overrideFillOpacity:!0,borderScale:!c.supportNonScalingStroke});
q.place(b,e);c._svgNode=b;return e}function t(c){return u.calcContentBox({viewBox:c.viewBox,g:c.g},c.shapeW,c.shapeH,c.shapeStyle,{preserveAspectRatio:c.preserveAspectRatio})}var v={renderElements:function(c){if(c.bar)c.bar.singleIcon?w(c):y(c);else if(c.scale)A(c);else{var b=q.create("div",{"class":"esriGEAbsoluteStretched shapeContainer_svgContainer"},c.content),e,a=c.borderWidth/2;a&&(b.style.left=-a+"px",b.style.top=-a+"px",b.style.right=-a+"px",b.style.bottom=-a+"px",e={l:a,t:a});r(c,c.shapeStyle,
b,e)}},MIN_SCALE:.2};return v});