// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.33/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/ReportPlayer/core/annotations/shape/ShapeContainer","dojo/_base/declare dojo/_base/lang dojo/sniff dojo/dom-class dojo/dom-construct ../../grid/valueField/ValueField esri/dijit/geoenrichment/utils/MathUtil esri/dijit/geoenrichment/utils/ObjectUtil ../utils/AnnotationsUtil ./ShapeThemeUtil ./_ShapeElementRenderer dojo/i18n!esri/nls/jsapi".split(" "),function(m,h,n,p,k,q,r,g,t,l,u,v){return m(q,{isShape:!0,viewModel:null,theme:null,currentFeatureIndex:null,shapeJson:null,
alignParams:null,applyThemeStyle:!0,getPreviewValueFunction:null,parentWidget:null,_g:!1,_viewBox:!1,_shapeStyle:null,_preserveAspectRatio:void 0,_isPlaceholder:!1,_angle:0,_shapeThemeStyle:null,_needSaveShapeThemeStyle:!0,_backgroundThemeStyle:null,_needSaveBackgroundThemeStyle:!0,_showAsBar:!1,_bar_singleIcon:!1,_bar_wholeIcons:!1,_bar_flowDirection:null,_bar_spaceBetween:null,_scaleByValue:!1,_scale_minScale:null,_scale_anchorPosition:null,_useRange:!1,_rangeMin:null,_rangeMax:null,_showBackground:!1,
_backgroundStyle:null,_supportNonScalingStroke:!1,postCreate:function(){this.content=k.create("div",{"class":"shapeContainer_content"});this.fieldStyle=this.fieldStyle||{};this.fieldStyle.width=this.shapeJson.style.width;this.fieldStyle.height=this.shapeJson.style.height;this._g=this.shapeJson.g;this._viewBox=this.shapeJson.viewBox;this._shapeStyle=this.shapeJson.style||{};this._preserveAspectRatio=this.shapeJson.preserveAspectRatio;this._isPlaceholder=this.shapeJson.isPlaceholder;this._angle=this.shapeJson.style.angle||
0;this._processThemeStyle();this._showAsBar=this.shapeJson.showAsBar;this._bar_singleIcon=this.shapeJson.bar_singleIcon;this._bar_wholeIcons=this.shapeJson.bar_wholeIcons;this._bar_flowDirection=this.shapeJson.bar_flowDirection;this._bar_spaceBetween=this.shapeJson.bar_spaceBetween;this._scaleByValue=this.shapeJson.scaleByValue;this._scale_minScale=this.shapeJson.scale_minScale;this._scale_anchorPosition=this.shapeJson.scale_anchorPosition;this._useRange=this.shapeJson.useRange;this._rangeMin=this.shapeJson.rangeMin;
this._rangeMax=this.shapeJson.rangeMax;this._backgroundStyle=this.shapeJson.backgroundStyle||{};this._showBackground=this.shapeJson.showBackground;(this._showAsBar||this._scaleByValue)&&this._processBackgroundThemeStyle();this.inherited(arguments);p.add(this.domNode,"esriGEShapeContainer");this.setPosition(this.shapeJson.style.left||0,this.shapeJson.style.top||0);this._applyRotation();this._lastAlignParams=this.alignParams},_processThemeStyle:function(){this.applyThemeStyle&&(this._shapeThemeStyle=
l.getThemeStylesFromShapeJson(this.shapeJson,this.parentWidget.parentGrid),this._needSaveShapeThemeStyle=!!this.shapeJson.themeStyle)},_processBackgroundThemeStyle:function(){this.applyThemeStyle&&(this._backgroundThemeStyle=l.getBackgroundThemeStylesFromShapeJson(this.shapeJson,this.parentWidget.parentGrid),this._needSaveBackgroundThemeStyle=!!this.shapeJson.backgroundThemeStyle)},getShapeStyle:function(){return this._getShapeStyle()},_getShapeStyle:function(a,b){var c={};g.copyOwnJsonProperties(this._shapeThemeStyle,
c);a&&a.color&&g.copyOwnJsonProperties({fillColor:a.color,borderColor:a.color},c);g.copyOwnJsonProperties(this._getOwnShapeStyleForRendering(b),c);return c},getBackgroundStyle:function(){var a={};g.copyOwnJsonProperties(this._backgroundThemeStyle,a);g.copyOwnJsonProperties(this._getOwnBackgroundStyleForRendering(),a);return a},setAngle:function(a){this._angle=r.angleTo180_180Range(Number(a)||0);this._applyRotation()},_applyRotation:function(){this._angle=0<this._angle||0>this._angle?this._angle:0;
var a=n("webkit")?"webkitTransform":"transform";this.content.style[a]=0!==this._angle?"rotate("+this._angle+"deg)":""},_lastAlignParams:null,resize:function(a,b){this.setWidth(a.w);this.setHeight(a.h);this._updateShapeNode();this._lastAlignParams=b||this._lastAlignParams;t.alignAnnotationContainer(this,this._lastAlignParams,this._calcGeometry().content)},scaleProportionallyWithinParent:function(a){this.resize({w:this.getWidth()*a.xScale,h:this.getHeight()*a.yScale});this.setPosition(this._left*a.xScale,
this._top*a.yScale)},getShapeBox:function(){return{w:this.getWidth(),h:this.getHeight(),l:this._left,t:this._top}},_left:0,_top:0,getLeft:function(){return this._left},getTop:function(){return this._top},setPosition:function(a,b){void 0!==a&&(this._left=a||0,this.domNode.style.left=this._left+"px");void 0!==b&&(this._top=b||0,this.domNode.style.top=this._top+"px")},_svgNode:null,getSvgNode:function(){return this._svgNode},_updateShapeNode:function(){var a=this,b=this._viewBox,c=this.getWidth(),d=
this.getHeight(),e=this._calcGeometry();this.content.innerHTML="";this.content.style.width=e.content.w+"px";this.content.style.height=e.content.h+"px";if(this._isPlaceholder)k.create("div",{"class":"shapeContainer_svgPlaceholder"},this.content);else{var f=this.getPreviewValueFunction&&this.getPreviewValueFunction(),b={content:this.content,preserveAspectRatio:this._preserveAspectRatio,supportNonScalingStroke:this._supportNonScalingStroke,viewBox:b,width:c,height:d,shapeW:e.shape.w,shapeH:e.shape.h,
borderWidth:this._getMaxBorderWidth(),g:this._g,value:f?f.normalizedValue:.6,shapeStyle:this._getShapeStyle(f&&f.conditionalStyling),shapeStyleBuilder:function(b){return a._getShapeStyle(f&&f.conditionalStyling,b)},bgStyle:this._showBackground&&this.getBackgroundStyle(),bar:this._showAsBar&&{singleIcon:this._bar_singleIcon,wholeIcons:this._bar_wholeIcons,flowDirection:this._bar_flowDirection,spaceBetween:this._bar_spaceBetween,showBackground:this._showBackground},scale:this._scaleByValue&&{minScale:this._scale_minScale,
anchorPosition:this._scale_anchorPosition,showBackground:this._showBackground}};u.renderElements(b);this._svgNode=b._svgNode}},_calcGeometry:function(){var a=this._viewBox,b=this.getWidth(),c=this.getHeight(),d=a.width/a.height,e=Math.min(b,c*d);"none"===this._preserveAspectRatio?(a=b,d=c):(a=e,d=e/d);e=this._showAsBar&&!this._bar_singleIcon;return{shape:{w:a,h:d},content:{w:e?b:a,h:e?c:d}}},_getOwnShapeStyleForRendering:function(a){return this._fixBorderStyle(this._shapeStyle,a)},_getOwnBackgroundStyleForRendering:function(){return this._fixBorderStyle(this._backgroundStyle)},
_fixBorderStyle:function(a,b){b=this._getBorderStrokeMultiplier(a,b);return 1!==b?h.mixin({},a,{borderWidth:a.borderWidth*b}):a},_getBorderStrokeMultiplier:function(a,b){if(0<a.borderWidth&&0<a.borderAlpha&&!this._supportNonScalingStroke){a=function(a,b){a/=b;return 1>a?1/a:a};var c=this._viewBox,d=b||this._calcGeometry().shape;b=d.w;d=d.h;return a(b,c.width)>a(d,c.height)?c.width/b:c.height/d}return 1},_getMaxBorderWidth:function(){return Math.max(0<this._shapeStyle.borderAlpha&&this._shapeStyle.borderWidth||
0,0<this._backgroundStyle.borderAlpha&&this._backgroundStyle.borderWidth||0)},toJson:function(){var a={id:"shape",g:this._g,viewBox:this._viewBox,preserveAspectRatio:this._preserveAspectRatio,isPlaceholder:this._isPlaceholder,style:h.mixin({},this._shapeStyle,{left:this._left,top:this._top,width:this.getWidth(),height:this.getHeight(),angle:this._angle}),themeStyle:this._needSaveShapeThemeStyle?this._shapeThemeStyle:void 0,showAsBar:this._showAsBar,bar_singleIcon:this._bar_singleIcon,bar_wholeIcons:this._bar_wholeIcons,
bar_flowDirection:this._bar_flowDirection,bar_spaceBetween:this._bar_spaceBetween,scaleByValue:this._scaleByValue,scale_minScale:this._scale_minScale,scale_anchorPosition:this._scale_anchorPosition,useRange:this._useRange,rangeMin:this._rangeMin,rangeMax:this._rangeMax,showBackground:this._showBackground,backgroundStyle:this._backgroundStyle,backgroundThemeStyle:this._needSaveBackgroundThemeStyle?this._backgroundThemeStyle:void 0};return h.clone(a)}})});