//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class accesslevel
    {
        public accesslevel()
        {
            this.Made100_VoteInformation = new HashSet<Made100_VoteInformation>();
        }
    
        public double code { get; set; }
        public string group_n { get; set; }
        public string parent { get; set; }
        public string user_n { get; set; }
        public string password { get; set; }
        public string name { get; set; }
        public string family { get; set; }
        public Nullable<int> c_semat { get; set; }
        public string nameSemat { get; set; }
        public string meli { get; set; }
        public string tel { get; set; }
        public string mob { get; set; }
        public Nullable<int> tarikh_exp { get; set; }
        public string email { get; set; }
        public string address { get; set; }
        public Nullable<bool> isparent { get; set; }
        public Nullable<bool> faal { get; set; }
        public Nullable<bool> hashed { get; set; }
        public byte[] signature { get; set; }
        public byte[] aks { get; set; }
        public byte[] finger { get; set; }
        public Nullable<bool> a1 { get; set; }
        public Nullable<bool> a2 { get; set; }
        public Nullable<bool> a3 { get; set; }
        public Nullable<bool> a4 { get; set; }
        public Nullable<bool> a5 { get; set; }
        public Nullable<bool> a6 { get; set; }
        public Nullable<bool> a7 { get; set; }
        public Nullable<bool> a8 { get; set; }
        public Nullable<bool> a9 { get; set; }
        public Nullable<bool> a10 { get; set; }
        public Nullable<bool> b1 { get; set; }
        public Nullable<bool> b2 { get; set; }
        public Nullable<bool> b3 { get; set; }
        public Nullable<bool> b4 { get; set; }
        public Nullable<bool> b5 { get; set; }
        public Nullable<bool> c1 { get; set; }
        public Nullable<bool> c2 { get; set; }
        public Nullable<bool> c3 { get; set; }
        public Nullable<bool> c4 { get; set; }
        public Nullable<bool> c5 { get; set; }
        public Nullable<bool> d1 { get; set; }
        public Nullable<bool> d2 { get; set; }
        public Nullable<bool> d3 { get; set; }
        public Nullable<bool> d4 { get; set; }
        public Nullable<bool> d5 { get; set; }
        public Nullable<bool> flag { get; set; }
        public string AksFileName { get; set; }
        public string FingerFileName { get; set; }
        public string SignFileName { get; set; }
        public string MCA_TerminalId { get; set; }
        public Nullable<int> MCA_Port { get; set; }
        public Nullable<int> MCA_TimeOut { get; set; }
        public Nullable<int> DefaultPOS { get; set; }
        public Nullable<bool> Pishkhan { get; set; }
        public string strOrganizationId { get; set; }
        public Nullable<int> DurationSendingParvandeh { get; set; }
        public Nullable<int> CountSendingParvandeh { get; set; }
        public Nullable<bool> GheyreFaalForMistakePassword { get; set; }
        public Nullable<System.DateTime> FaalUserAfterSeconds { get; set; }
        public Nullable<System.DateTime> GheyreFaalDatetime { get; set; }
        public string ResetPasswordCode { get; set; }
        public string Hash { get; set; }
        public Nullable<System.DateTime> LastModification { get; set; }
    
        public virtual ICollection<Made100_VoteInformation> Made100_VoteInformation { get; set; }
    }
}
