//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountType
    {
        public AccountType()
        {
            this.Dv_aghabneshini = new HashSet<Dv_aghabneshini>();
            this.Dv_karbari = new HashSet<Dv_karbari>();
            this.Dv_pishamadegi = new HashSet<Dv_pishamadegi>();
            this.masahat_khalaf = new HashSet<masahat_khalaf>();
            this.AccountTypeDetail = new HashSet<AccountTypeDetail>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public Nullable<int> BuildingUseCode { get; set; }
    
        public virtual ICollection<Dv_aghabneshini> Dv_aghabneshini { get; set; }
        public virtual ICollection<Dv_karbari> Dv_karbari { get; set; }
        public virtual ICollection<Dv_pishamadegi> Dv_pishamadegi { get; set; }
        public virtual ICollection<masahat_khalaf> masahat_khalaf { get; set; }
        public virtual ICollection<AccountTypeDetail> AccountTypeDetail { get; set; }
    }
}
