//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Agreement
    {
        public long Id { get; set; }
        public string Shop { get; set; }
        public string Shod { get; set; }
        public bool IsDelete { get; set; }
        public string AgreementText { get; set; }
        public Nullable<long> AgreementNumber { get; set; }
        public Nullable<System.DateTime> AgreementDate { get; set; }
        public string AgreementDescription { get; set; }
        public string AgreementType { get; set; }
        public Nullable<int> AgreementType_Code { get; set; }
        public Nullable<int> OfficialNotary { get; set; }
    }
}
