//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AmlakMostaghelatShardari
    {
        public int shop { get; set; }
        public Nullable<int> tarikhMozayedeh { get; set; }
        public Nullable<int> tarikhFishShahrdari { get; set; }
        public Nullable<long> mablaghFishShahrdari { get; set; }
    }
}
