//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Approvals
    {
        public long Id { get; set; }
        public string Shop { get; set; }
        public string Shod { get; set; }
        public bool IsDelete { get; set; }
        public string ApprovalText { get; set; }
        public Nullable<long> ApprovalNumber { get; set; }
        public Nullable<System.DateTime> ApprovalDate { get; set; }
        public string ApprovalDescription { get; set; }
        public string ApprovalType { get; set; }
        public Nullable<int> ApprovalType_Code { get; set; }
        public Nullable<bool> ApprovalStatus { get; set; }
    }
}
