//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArchiveReport
    {
        public int reportId { get; set; }
        public int treeScanCode { get; set; }
        public string reportName { get; set; }
        public string treeScanName { get; set; }
    }
}
