//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Article77ExpertsInvitation
    {
        public long Id { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<System.TimeSpan> Time { get; set; }
        public Nullable<int> ExpertId { get; set; }
        public string ExpertFullName { get; set; }
        public Nullable<byte> CommissionTypeId { get; set; }
        public string CommissionType { get; set; }
    }
}
