//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Arzesh_Amlak
    {
        public double ShoP { get; set; }
        public int Sal { get; set; }
        public int CodeJebhe { get; set; }
        public Nullable<double> CodeGhete { get; set; }
        public Nullable<double> CodeBand { get; set; }
        public string Address { get; set; }
        public Nullable<double> Arzesh { get; set; }
        public Nullable<bool> Flag { get; set; }
        public Nullable<double> MasahatJebhe { get; set; }
        public byte typeArzeshAmlak { get; set; }
        public Nullable<decimal> CommercialPrice { get; set; }
        public Nullable<decimal> OfficePrice { get; set; }
        public Nullable<decimal> OtherPrice { get; set; }
    }
}
