//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArzeshDaraei
    {
        public decimal adder { get; set; }
        public Nullable<double> code1 { get; set; }
        public Nullable<double> code2 { get; set; }
        public string addres { get; set; }
        public Nullable<int> arzesh1 { get; set; }
        public Nullable<int> arzesh2 { get; set; }
        public Nullable<int> arzesh3 { get; set; }
        public Nullable<int> arzesh4 { get; set; }
        public string saal { get; set; }
        public string FlgD { get; set; }
        public byte typeArzeshDaraei { get; set; }
    }
}
