//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArzeshMoamelatiSakhteman
    {
        public int Id { get; set; }
        public int shop { get; set; }
        public int shod { get; set; }
        public int c_noesakhteman { get; set; }
        public string noesakhteman { get; set; }
        public int c_karbari { get; set; }
        public string karbari { get; set; }
        public Nullable<long> ArzeshMoamelati { get; set; }
        public Nullable<double> masahat { get; set; }
        public string percentage { get; set; }
        public string Description { get; set; }
        public Nullable<int> userCode { get; set; }
        public Nullable<System.DateTime> systemDate { get; set; }
    }
}
