//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asnaf_Jobs
    {
        public int Term { get; set; }
        public int jobCode { get; set; }
        public int ID { get; set; }
        public string JobName { get; set; }
        public Nullable<int> GuildCode { get; set; }
        public string GuildName { get; set; }
        public Nullable<double> Rate { get; set; }
        public Nullable<decimal> Cash { get; set; }
        public Nullable<int> FormolCode { get; set; }
        public string FormolTitle { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public Nullable<int> MinPrice { get; set; }
        public Nullable<int> MaxPrice { get; set; }
    }
}
