//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asnaf_FormolItems
    {
        public int Term { get; set; }
        public int FormolCode { get; set; }
        public int FormolItemCode { get; set; }
        public string formolfarsi { get; set; }
        public string formolfield { get; set; }
        public Nullable<double> Meghdar { get; set; }
        public Nullable<bool> Deleted { get; set; }
    }
}
