//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asnaf_Shenase
    {
        public long ID { get; set; }
        public long Serial { get; set; }
        public int Term { get; set; }
        public long Shop { get; set; }
        public int JobCode { get; set; }
        public Nullable<decimal> FishPrice { get; set; }
        public Nullable<System.DateTime> DateFish { get; set; }
        public string ShGh { get; set; }
        public string ShPr { get; set; }
        public Nullable<bool> Flag { get; set; }
        public Nullable<long> UserCode { get; set; }
        public Nullable<int> DaramadMFishId { get; set; }
        public string Description { get; set; }
    }
}
