//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asnaf_Avarez
    {
        public int Term { get; set; }
        public long ShoP { get; set; }
        public int JobCode { get; set; }
        public string JobName { get; set; }
        public Nullable<long> Sh_darkhast { get; set; }
        public Nullable<decimal> TollAmount { get; set; }
        public Nullable<decimal> OpeningAmount { get; set; }
        public Nullable<decimal> RelocationAmount { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public Nullable<decimal> PaymentAmount { get; set; }
        public string UserPerform { get; set; }
        public string UserPerformName { get; set; }
        public bool Paid { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<long> AvalDoreAmount { get; set; }
        public Nullable<long> Discount { get; set; }
        public int TypeAvarez { get; set; }
        public Nullable<int> DateVosul { get; set; }
        public long IdAvarez { get; set; }
        public string FishDaramad { get; set; }
        public Nullable<long> JobListId { get; set; }
        public Nullable<decimal> ConstantNumber { get; set; }
        public Nullable<long> ParametricDiscount { get; set; }
    
        public virtual Dv_ListShoghl Dv_ListShoghl { get; set; }
    }
}
