//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asnaf_Formol
    {
        public int FormolCode { get; set; }
        public int Term { get; set; }
        public string Kod_Daramadi { get; set; }
        public string BodjeName { get; set; }
        public string MohasebeName { get; set; }
        public string Formol { get; set; }
        public string Fx { get; set; }
        public Nullable<int> FormolTypeCode { get; set; }
        public string FormolTypeName { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public Nullable<double> MaxPrice { get; set; }
        public Nullable<double> MinPrice { get; set; }
        public bool MohasebeArzeshAfzoode { get; set; }
    }
}
