//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Avarez
    {
        public long Radif { get; set; }
        public decimal shop { get; set; }
        public Nullable<int> RadifMalek { get; set; }
        public int IdMalek { get; set; }
        public decimal sal { get; set; }
        public Nullable<decimal> avarez1 { get; set; }
        public Nullable<decimal> badhesabi { get; set; }
        public Nullable<decimal> pelakkobi { get; set; }
        public Nullable<decimal> moavaghe { get; set; }
        public Nullable<decimal> sayer { get; set; }
        public string sharhsayer { get; set; }
        public Nullable<decimal> khadamat { get; set; }
        public Nullable<decimal> mafiyat { get; set; }
        public Nullable<decimal> khoshhesabi { get; set; }
        public Nullable<decimal> bed { get; set; }
        public Nullable<decimal> ghest { get; set; }
        public string fish { get; set; }
        public Nullable<int> tarikhfish { get; set; }
        public Nullable<int> mablaghfish { get; set; }
        public string sh_check { get; set; }
        public string sh_jari { get; set; }
        public Nullable<int> tarikhcheck { get; set; }
        public string bank { get; set; }
        public Nullable<int> tarikhsabt { get; set; }
        public Nullable<decimal> bes { get; set; }
        public string sharh { get; set; }
        public string user_n { get; set; }
        public string date_time { get; set; }
        public Nullable<bool> noesabt { get; set; }
        public string codeN { get; set; }
        public string CodeNg { get; set; }
        public string Auto { get; set; }
        public string Mahiyat { get; set; }
        public string Name { get; set; }
        public string Addres { get; set; }
        public Nullable<decimal> khoshhesabi_khadamat { get; set; }
        public string code_kasbi { get; set; }
        public string onvan_kasbi { get; set; }
        public string ShenaseGhabz { get; set; }
        public string ShenasePardakht { get; set; }
        public Nullable<double> ShishDong { get; set; }
        public string serial_fish { get; set; }
        public Nullable<int> ghestNum { get; set; }
        public Nullable<decimal> Education { get; set; }
        public Nullable<decimal> FireStation { get; set; }
        public Nullable<decimal> Tax { get; set; }
        public Nullable<decimal> MoafiatKhadamat { get; set; }
        public Nullable<decimal> FazayeSabz { get; set; }
        public Nullable<bool> Final { get; set; }
        public Nullable<decimal> differenceCalc { get; set; }
        public bool tasvieh { get; set; }
        public string TrackingNo { get; set; }
        public Nullable<int> shod { get; set; }
        public Nullable<bool> Archive { get; set; }
        public Nullable<int> CodeBank { get; set; }
        public Nullable<decimal> ArzeshArse { get; set; }
        public Nullable<decimal> ArzeshAyan { get; set; }
        public Nullable<bool> IsCumulative { get; set; }
        public Nullable<long> DelayInPaymentOfServices { get; set; }
        public Nullable<byte> RenovationType { get; set; }
        public Nullable<System.DateTime> LastModified { get; set; }
    }
}
