//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Barokaf
    {
        public int sh_darkhast { get; set; }
        public Nullable<int> User_Id { get; set; }
        public Nullable<double> MTA { get; set; }
        public Nullable<double> MTG { get; set; }
        public string Mizan { get; set; }
        public Nullable<long> C_noeharim { get; set; }
        public string Noeharim { get; set; }
        public string Fazayesabz { get; set; }
        public Nullable<long> C_zabeteh { get; set; }
        public string Zabeteh { get; set; }
        public Nullable<double> OTA { get; set; }
        public Nullable<double> OTG { get; set; }
        public Nullable<long> C_Marghob { get; set; }
        public string Marghob { get; set; }
        public Nullable<long> C_Ghatar { get; set; }
        public string Ghatar { get; set; }
        public Nullable<long> C_Khadamat { get; set; }
        public string Khadamat { get; set; }
        public Nullable<int> T_Kroki { get; set; }
        public string Molahezat_sanad { get; set; }
        public string sh_Kroki { get; set; }
        public string Description { get; set; }
        public string KorookiFileName { get; set; }
        public string KorookiNegarFileName { get; set; }
        public string KadastrFileName { get; set; }
    }
}
