//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Blocked_Malekin
    {
        public long ID { get; set; }
        public Nullable<int> c_noemalek { get; set; }
        public string noemalek { get; set; }
        public string name { get; set; }
        public string family { get; set; }
        public string father { get; set; }
        public string sh_sh { get; set; }
        public string sodor { get; set; }
        public string kodemeli { get; set; }
        public string tel { get; set; }
        public string mob { get; set; }
        public string address { get; set; }
        public string tozihat { get; set; }
        public string UserFullName { get; set; }
        public Nullable<System.DateTime> BlockDate { get; set; }
        public Nullable<System.DateTime> UnBlockDate { get; set; }
    }
}
