//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BuildingTypeDetail
    {
        public int Id { get; set; }
        public int BuildingTypeId { get; set; }
        public System.DateTime FromData { get; set; }
        public System.DateTime ToDate { get; set; }
        public decimal Coefficient { get; set; }
        public string Formula { get; set; }
        public Nullable<decimal> MaxAmount { get; set; }
        public Nullable<decimal> MinAmount { get; set; }
    
        public virtual BuildingType BuildingType { get; set; }
    }
}
