//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Check
    {
        public double Shop { get; set; }
        public Nullable<int> RadifMalek { get; set; }
        public int IdMalek { get; set; }
        public int Radif { get; set; }
        public string Name { get; set; }
        public string CodeN { get; set; }
        public string CodeNg { get; set; }
        public string ShCheck { get; set; }
        public string ShHesab { get; set; }
        public Nullable<int> DateSarresid { get; set; }
        public Nullable<int> DateDaryaft { get; set; }
        public Nullable<decimal> Bed { get; set; }
        public Nullable<decimal> Bes { get; set; }
        public string BankName { get; set; }
        public string mahiyat { get; set; }
        public string sharh { get; set; }
        public Nullable<int> DateVosol { get; set; }
        public string malekkasbi { get; set; }
        public Nullable<bool> bargashti { get; set; }
        public string sh_fish { get; set; }
        public Nullable<int> tarikh_vosol { get; set; }
        public string serial_fish { get; set; }
    }
}
