//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommonFields
    {
        public long ID { get; set; }
        public decimal Shop { get; set; }
        public decimal d_radif { get; set; }
        public Nullable<double> OutDepthArea { get; set; }
        public Nullable<double> OppositeSide { get; set; }
        public Nullable<long> gheymat_mOld { get; set; }
        public string Note_Shop { get; set; }
        public Nullable<bool> Tajme_Avarez { get; set; }
    }
}
