//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConflictFormulaDetails
    {
        public long Id { get; set; }
        public int Code { get; set; }
        public string FormulaEn { get; set; }
        public string FormulaFarsi { get; set; }
    }
}
