//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConflictFormula
    {
        public ConflictFormula()
        {
            this.ConflictFormulaDetails = new HashSet<ConflictFormulaDetails>();
        }
    
        public int Id { get; set; }
        public int Year { get; set; }
        public string FX { get; set; }
        public string Description { get; set; }
        public Nullable<bool> FinalFormula { get; set; }
    
        public virtual ICollection<ConflictFormulaDetails> ConflictFormulaDetails { get; set; }
    }
}
