//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Control_Map
    {
        public double ShoP { get; set; }
        public long Sh_Darkhast { get; set; }
        public Nullable<int> c_Mahal_Vogho { get; set; }
        public string Mahal_Vogho { get; set; }
        public Nullable<int> c_Olgo_Sakht { get; set; }
        public string Olgo_Sakht { get; set; }
        public Nullable<int> c_NoeNama { get; set; }
        public string NoeNama { get; set; }
        public Nullable<double> Ertefa { get; set; }
        public Nullable<int> c_Poshesh_Saghf { get; set; }
        public string Poshesh_Saghf { get; set; }
        public string Tozihat { get; set; }
        public Nullable<int> UserCode { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<bool> flag { get; set; }
        public Nullable<double> tarakom { get; set; }
        public Nullable<double> masahat_k { get; set; }
        public Nullable<double> masahat_r { get; set; }
        public Nullable<double> janpanah { get; set; }
        public Nullable<double> LengthGapComm { get; set; }
        public Nullable<double> HeightUnitComm { get; set; }
        public Nullable<int> ExpertDue { get; set; }
        public string KorookiFileName { get; set; }
        public string KorookiNegarFileName { get; set; }
    }
}
