//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class D_bargeh
    {
        public double shop { get; set; }
        public decimal IdMalek { get; set; }
        public string sh_daftar { get; set; }
        public string sh_nameh { get; set; }
        public string dang { get; set; }
        public string noe { get; set; }
        public string sh_pelak { get; set; }
        public string bakhsh { get; set; }
        public string kharidar { get; set; }
        public string sh_mojavaz { get; set; }
        public string ghesmat { get; set; }
        public string Arz { get; set; }
        public string molahezat { get; set; }
        public Nullable<decimal> jam1 { get; set; }
        public Nullable<decimal> jam2 { get; set; }
        public Nullable<decimal> jam3 { get; set; }
        public Nullable<decimal> jam4 { get; set; }
        public Nullable<decimal> jam5 { get; set; }
        public Nullable<decimal> jamkol { get; set; }
        public Nullable<decimal> jam6 { get; set; }
        public string CodeNosazi { get; set; }
        public string Karbari { get; set; }
        public Nullable<decimal> jam7 { get; set; }
    }
}
