//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class D_Traffic
    {
        public int shop { get; set; }
        public int shod { get; set; }
        public Nullable<int> c_ertefa { get; set; }
        public string strErtefa { get; set; }
        public Nullable<long> tarefe_Ertefa { get; set; }
        public Nullable<int> c_saghf { get; set; }
        public string strSaghf { get; set; }
        public Nullable<long> tarefe_Saghf { get; set; }
        public Nullable<int> c_beton { get; set; }
        public string strBeton { get; set; }
        public Nullable<long> tarefe_Beton { get; set; }
        public Nullable<long> tarefe_Divarboreshi { get; set; }
        public Nullable<int> userCode { get; set; }
        public Nullable<System.DateTime> systemDate { get; set; }
        public int radif { get; set; }
        public Nullable<int> c_traffic { get; set; }
        public string strTraffic { get; set; }
        public Nullable<long> tarefe_Traffic { get; set; }
        public Nullable<long> Sum_Tarefe_Traffic { get; set; }
    
        public virtual Traffic Traffic { get; set; }
    }
}
