//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DaramadFormulGardeshKar_Where
    {
        public long IDw_FormulGardeshKar { get; set; }
        public long IDDaramadFormulGardeshKar { get; set; }
        public Nullable<int> ComparOperator { get; set; }
        public Nullable<int> CodeFieldType { get; set; }
        public Nullable<double> Field1 { get; set; }
        public string TitleField1 { get; set; }
        public Nullable<double> Field2 { get; set; }
        public string TitleField2 { get; set; }
    }
}
