//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Daramad
    {
        public double Shop { get; set; }
        public double Sh_Darkhast { get; set; }
        public int Sh_Mohasebe { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<int> UserCode { get; set; }
        public string DescDaramad { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public Nullable<double> DeleteUser { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
        public Nullable<bool> Tasvieh { get; set; }
    }
}
