//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Daramad_jadvalArse
    {
        public long adder { get; set; }
        public Nullable<double> metrazh1 { get; set; }
        public Nullable<double> metrazh2 { get; set; }
        public Nullable<int> Type { get; set; }
        public int c_TypeMasahat { get; set; }
        public string TypeMasahat { get; set; }
        public Nullable<double> Zarib { get; set; }
    }
}
