//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Daramad_DF_parvande
    {
        public Daramad_DF_parvande()
        {
            this.Daramad_Factors = new HashSet<Daramad_Factors>();
        }
    
        public int sh_Darkhast { get; set; }
        public int Sh_Mohasebe { get; set; }
        public int Radif { get; set; }
        public long DRadif { get; set; }
        public decimal code { get; set; }
        public decimal saal { get; set; }
        public string Kod_Daramadi { get; set; }
        public string noemohasebeh { get; set; }
        public string formol { get; set; }
        public string FormolAdadi { get; set; }
        public string JadvalName { get; set; }
        public string Fx { get; set; }
        public Nullable<bool> Entekhab { get; set; }
        public Nullable<decimal> Meghdar { get; set; }
        public Nullable<decimal> Arzesh { get; set; }
        public string FlgF { get; set; }
        public Nullable<decimal> Takhfif { get; set; }
        public Nullable<decimal> Afzode { get; set; }
        public Nullable<decimal> Mabkol { get; set; }
        public Nullable<decimal> Pardakhti { get; set; }
        public string Tozihat { get; set; }
        public Nullable<bool> moafiyat { get; set; }
        public Nullable<double> MoafiatPrice { get; set; }
        public Nullable<int> Date_Mohasebe { get; set; }
        public string NullChecksFormulaField { get; set; }
        public Nullable<decimal> tax { get; set; }
    
        public virtual ICollection<Daramad_Factors> Daramad_Factors { get; set; }
    }
}
