//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DaramadFormulGardeshKar_Det
    {
        public long IDd_FormulGardeshKar { get; set; }
        public long IDDaramadFormulGardeshKar { get; set; }
        public decimal CodeFormul { get; set; }
        public decimal SaalFormul { get; set; }
    }
}
