//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Daramad_Formol
    {
        public long DRadif { get; set; }
        public decimal code { get; set; }
        public decimal saal { get; set; }
        public string Kod_Daramadi { get; set; }
        public string noemohasebeh { get; set; }
        public string formol { get; set; }
        public string JadvalName { get; set; }
        public string Fx { get; set; }
        public string Arzesh { get; set; }
        public Nullable<bool> Entekhab { get; set; }
        public string FlgF { get; set; }
        public string JadvalNum { get; set; }
        public Nullable<decimal> Hadeaghal { get; set; }
        public Nullable<decimal> HadeaghalJoz { get; set; }
        public Nullable<decimal> HadeAksarJoz { get; set; }
        public Nullable<bool> ESUPParvane { get; set; }
        public Nullable<double> Hadeaksar { get; set; }
    
        public virtual Daramad_t_formool_m Daramad_t_formool_m { get; set; }
    }
}
