//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Daramad_Shenase
    {
        public int Serial { get; set; }
        public string saal { get; set; }
        public string Noefish { get; set; }
        public Nullable<decimal> Mablagh { get; set; }
        public Nullable<decimal> DateSodor { get; set; }
        public string ShGh { get; set; }
        public string ShPr { get; set; }
        public Nullable<bool> Flag { get; set; }
        public string PCName { get; set; }
        public Nullable<decimal> SerialFish { get; set; }
    }
}
