//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Daramad_Factors
    {
        public int sh_Darkhast { get; set; }
        public int Sh_Mohasebe { get; set; }
        public int MRadif { get; set; }
        public int Radif { get; set; }
        public string formolfarsi { get; set; }
        public string formolfield { get; set; }
        public Nullable<double> Meghdar { get; set; }
    
        public virtual Daramad_DF_parvande Daramad_DF_parvande { get; set; }
    }
}
