//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Daramad_AccDocumentM
    {
        public long Id { get; set; }
        public Nullable<int> YearDocument { get; set; }
        public Nullable<System.DateTime> RegisterDate { get; set; }
        public Nullable<int> FromDate { get; set; }
        public Nullable<int> ToDate { get; set; }
        public Nullable<bool> Status { get; set; }
        public string Comments { get; set; }
        public Nullable<long> UserCode { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    }
}
