//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Daramad_t_formool_m
    {
        public Daramad_t_formool_m()
        {
            this.Daramad_Formol = new HashSet<Daramad_Formol>();
            this.IncomeFormulaDetection = new HashSet<IncomeFormulaDetection>();
        }
    
        public long radif { get; set; }
        public string onvan_avarez { get; set; }
        public string kod_daramadi { get; set; }
        public string onvan_daramadi { get; set; }
        public Nullable<bool> entekhab_m { get; set; }
        public Nullable<bool> TaxFlag { get; set; }
        public Nullable<bool> Special { get; set; }
        public Nullable<bool> IsPrint { get; set; }
        public Nullable<int> SortOrder { get; set; }
        public Nullable<bool> EducationFlag { get; set; }
        public Nullable<bool> FireStationFlag { get; set; }
        public Nullable<bool> TrafficCalculation { get; set; }
        public Nullable<bool> CalculateGreenSpace { get; set; }
        public Nullable<bool> CalculateGreenSpaceDevelopment { get; set; }
        public Nullable<bool> FormulaForApartments { get; set; }
        public bool Immunization { get; set; }
    
        public virtual ICollection<Daramad_Formol> Daramad_Formol { get; set; }
        public virtual ICollection<IncomeFormulaDetection> IncomeFormulaDetection { get; set; }
    }
}
