//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Daramad_Banks
    {
        public int Id { get; set; }
        public Nullable<long> CodeDaramadBodje { get; set; }
        public Nullable<int> Saal { get; set; }
        public string NameBank { get; set; }
        public Nullable<int> CodeBank { get; set; }
        public int AreaId { get; set; }
    }
}
