//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Daramad_MTaqsit
    {
        public long Radif { get; set; }
        public decimal SerialMFish { get; set; }
        public string SaalMFish { get; set; }
        public long sh_Darkhast { get; set; }
        public Nullable<decimal> CashPrice { get; set; }
        public Nullable<decimal> BedMFish { get; set; }
        public string Sharh { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public Nullable<double> DeleteUser { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
        public Nullable<System.DateTime> LastModified { get; set; }
    }
}
