//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Daramad_posht_formol
    {
        public long DRadif { get; set; }
        public decimal dcode_f { get; set; }
        public decimal code { get; set; }
        public decimal saal { get; set; }
        public string formolfarsi { get; set; }
        public string formolfield { get; set; }
        public string FlgPF { get; set; }
        public string Sing { get; set; }
        public Nullable<double> Meghdar { get; set; }
    }
}
