//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Daramad_DaftarBank
    {
        public long Radif { get; set; }
        public string Saal { get; set; }
        public string NameMalek { get; set; }
        public string Shomarebarge { get; set; }
        public Nullable<int> DateBarge { get; set; }
        public string Sh_Check { get; set; }
        public string ElamiyeBanki { get; set; }
        public string NameVariz { get; set; }
        public string NameGirande { get; set; }
        public string KodeBank { get; set; }
        public string NameBank { get; set; }
        public Nullable<decimal> MablaghBed { get; set; }
        public Nullable<int> Datevosol { get; set; }
        public Nullable<decimal> MablaghBes { get; set; }
        public Nullable<decimal> MablaghMande { get; set; }
        public string code { get; set; }
        public string CodeTajmi { get; set; }
        public string Onvan { get; set; }
        public string SanadBank { get; set; }
        public string NoFish { get; set; }
        public string FishNoeSr { get; set; }
        public Nullable<bool> Editable { get; set; }
    }
}
