//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Daramad_Bodje
    {
        public long Code { get; set; }
        public decimal Saal { get; set; }
        public string CodeFarei1 { get; set; }
        public string CodeFarei2 { get; set; }
        public string CodeFarei3 { get; set; }
        public string sharh { get; set; }
        public Nullable<decimal> Mosavab { get; set; }
        public Nullable<decimal> Motamam { get; set; }
        public Nullable<decimal> Amalkerd { get; set; }
        public Nullable<decimal> Kasrbodje { get; set; }
        public Nullable<decimal> mazadbodje { get; set; }
        public string Tsw { get; set; }
        public string Gsw { get; set; }
        public string Msw { get; set; }
        public string Kod_Daramadi { get; set; }
        public Nullable<bool> Asnaf { get; set; }
        public Nullable<bool> Khodro { get; set; }
        public Nullable<bool> Sayer { get; set; }
        public string Fb { get; set; }
        public string NameBank { get; set; }
        public string CodeBank { get; set; }
        public Nullable<bool> HasChild { get; set; }
        public Nullable<int> Parent { get; set; }
        public Nullable<short> State { get; set; }
        public string IAFAccCodingPath { get; set; }
        public string IAFAccCodingTitlePath { get; set; }
        public Nullable<int> MeasurementUnit { get; set; }
        public Nullable<int> IncomeTypeCode { get; set; }
        public Nullable<int> taxPercent { get; set; }
        public string ProductID { get; set; }
        public Nullable<bool> Taxable { get; set; }
        public string IncomeType { get; set; }
        public string MoadianDescription { get; set; }
    }
}
