//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Daramad_Jadval
    {
        public string Code { get; set; }
        public string Vaziyat { get; set; }
        public decimal Kol { get; set; }
        public decimal Moien { get; set; }
        public string Tafzil { get; set; }
        public string sharh { get; set; }
        public Nullable<decimal> Tarefe { get; set; }
        public string Ksw { get; set; }
        public string Msw { get; set; }
        public string Tsw { get; set; }
        public Nullable<bool> Entekhab { get; set; }
        public Nullable<double> Jarime { get; set; }
    }
}
