//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Daramad_MCheck
    {
        public double Sh_Darkhast { get; set; }
        public decimal ShFish { get; set; }
        public string name { get; set; }
        public string namebank { get; set; }
        public Nullable<int> DateFish { get; set; }
        public Nullable<decimal> Mablagh { get; set; }
        public Nullable<decimal> Naghd { get; set; }
        public Nullable<decimal> Mab_Check { get; set; }
        public string NoeFish { get; set; }
        public string Saal { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public Nullable<double> DeleteUser { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
        public Nullable<System.DateTime> LastModified { get; set; }
    }
}
