//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Daramad_DFish
    {
        public decimal DSerial { get; set; }
        public decimal Radif { get; set; }
        public string Saal { get; set; }
        public string NameMalek { get; set; }
        public string Shkhodro { get; set; }
        public Nullable<double> Fish { get; set; }
        public Nullable<int> DateFish { get; set; }
        public Nullable<int> DateSabt { get; set; }
        public string EteAsli { get; set; }
        public string CodeEteAsli { get; set; }
        public string SenfFari { get; set; }
        public string CodeSenfFari { get; set; }
        public string NameVariz { get; set; }
        public Nullable<int> KodeBank { get; set; }
        public string NameBank { get; set; }
        public Nullable<decimal> MablaghBed { get; set; }
        public Nullable<int> Datevosol { get; set; }
        public Nullable<decimal> mablaghBes { get; set; }
        public string ShParvande { get; set; }
        public string kod_daramadi { get; set; }
        public string CodeTajmi { get; set; }
        public string Onvan { get; set; }
        public string SanadBank { get; set; }
        public string NoFish { get; set; }
        public Nullable<decimal> mabent { get; set; }
        public Nullable<double> Darsad { get; set; }
        public string ShCheck { get; set; }
        public string ShHesab { get; set; }
        public string sh_parvande { get; set; }
        public string sh_mohasebe { get; set; }
        public string formol { get; set; }
        public Nullable<decimal> JamRadif { get; set; }
        public Nullable<double> sh_Darkhast { get; set; }
        public bool InterBankCheque { get; set; }
        public Nullable<long> IdAccDocument { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public Nullable<double> DeleteUser { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<System.DateTime> LastModified { get; set; }
        public Nullable<decimal> tax { get; set; }
    }
}
