//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Daramad_DTaqsit
    {
        public long Radif { get; set; }
        public long RadifM { get; set; }
        public Nullable<decimal> SerialFishQest { get; set; }
        public string SaalFishQest { get; set; }
        public Nullable<decimal> BedQest { get; set; }
        public string DateQest { get; set; }
        public string DateFishQest { get; set; }
        public string DateVosul { get; set; }
        public Nullable<decimal> BesQest { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public Nullable<double> DeleteUser { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
        public Nullable<decimal> BedQestBaKarmozd { get; set; }
        public Nullable<System.DateTime> LastModified { get; set; }
    }
}
