//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Darkhast
    {
        public Darkhast()
        {
            this.LevelJob = new HashSet<LevelJob>();
        }
    
        public double shop { get; set; }
        public long shodarkhast { get; set; }
        public string noedarkhast { get; set; }
        public Nullable<int> c_noedarkhast { get; set; }
        public string noemot { get; set; }
        public Nullable<int> c_noemot { get; set; }
        public string address { get; set; }
        public string tel { get; set; }
        public string mob { get; set; }
        public string shovek { get; set; }
        public Nullable<int> tarikhvek { get; set; }
        public string showdabir { get; set; }
        public Nullable<int> tarikhdabir { get; set; }
        public string shonaame { get; set; }
        public Nullable<int> tarikhnaame { get; set; }
        public string sahebname { get; set; }
        public string kharidar { get; set; }
        public string moteghazi { get; set; }
        public string codeposti { get; set; }
        public string email { get; set; }
        public string tozihat { get; set; }
        public Nullable<int> usercode { get; set; }
        public Nullable<int> date_rooz { get; set; }
        public string saat { get; set; }
        public string c_nosazi { get; set; }
        public bool Ebtal { get; set; }
        public Nullable<int> C_Estelam { get; set; }
        public string CERTIFId { get; set; }
        public string DescEstelam { get; set; }
        public string shparvandehOld { get; set; }
        public Nullable<long> FolderId { get; set; }
        public string MobileLawyer { get; set; }
        public Nullable<double> DangeMoredeEnteghal { get; set; }
        public Nullable<double> SahmeMoredeEnteghal { get; set; }
        public Nullable<double> SahmeKolleMoredeEnteghal { get; set; }
        public string CodeMeli { get; set; }
        public System.Data.Spatial.DbGeometry Shape { get; set; }
        public int Id { get; set; }
        public string AgreementType { get; set; }
        public Nullable<int> C_AgreementType { get; set; }
    
        public virtual Gardesh_Kar Gardesh_Kar { get; set; }
        public virtual ICollection<LevelJob> LevelJob { get; set; }
    }
}
