//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DarkhastGIS
    {
        public double shop { get; set; }
        public long shodarkhast { get; set; }
        public string codeN { get; set; }
        public string noedarkhast { get; set; }
        public Nullable<int> c_noedarkhast { get; set; }
        public string marhaleh { get; set; }
        public Nullable<int> c_marhaleh { get; set; }
        public string karbariAsli { get; set; }
        public Nullable<int> C_karbariAsli { get; set; }
        public string mahdodeh { get; set; }
        public Nullable<int> c_mahdodeh { get; set; }
        public Nullable<int> date_rooz { get; set; }
        public Nullable<decimal> mantaghe { get; set; }
        public Nullable<decimal> hoze { get; set; }
        public Nullable<decimal> blok { get; set; }
        public Nullable<decimal> shomelk { get; set; }
        public bool Ebtal { get; set; }
        public Nullable<int> Id { get; set; }
        public System.Data.Spatial.DbGeometry Shape { get; set; }
    }
}
