//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Darkhast_Melk
    {
        public string noedarkhast { get; set; }
        public string name { get; set; }
        public string family { get; set; }
        public string sh_sh { get; set; }
        public string kodemeli { get; set; }
        public string tel { get; set; }
        public string mob { get; set; }
        public string address { get; set; }
        public double shop { get; set; }
        public long shodarkhast { get; set; }
        public string Expr1 { get; set; }
        public string Expr2 { get; set; }
        public string Expr3 { get; set; }
        public string showdabir { get; set; }
        public string shonaame { get; set; }
        public Nullable<int> tarikhnaame { get; set; }
        public Nullable<int> tarikhdabir { get; set; }
        public string sahebname { get; set; }
        public string moteghazi { get; set; }
        public string c_nosazi { get; set; }
        public string Expr4 { get; set; }
        public Nullable<int> tarikh { get; set; }
        public string saat { get; set; }
        public Nullable<bool> anjam { get; set; }
        public string sabti { get; set; }
    }
}
