//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dastresi
    {
        public string code_user { get; set; }
        public long code_access { get; set; }
        public string name { get; set; }
        public string name_Source { get; set; }
        public string CtrlerName { get; set; }
        public string ActionName { get; set; }
        public Nullable<bool> Isweb { get; set; }
        public string Hash { get; set; }
    }
}
