//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DastresiForWeb
    {
        public long Id { get; set; }
        public long accessCode { get; set; }
        public long userCode { get; set; }
        public string userGroup { get; set; }
        public string MoreInfo { get; set; }
    }
}
