//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DecisionToVoteArticle77
    {
        public int Id { get; set; }
        public bool IsDelete { get; set; }
        public int Shop { get; set; }
        public int Shod { get; set; }
        public int DraftId { get; set; }
        public int CommisionId { get; set; }
        public Nullable<int> JudicialExpertId { get; set; }
        public string DescriptionJudicial { get; set; }
        public Nullable<int> CityCouncilExpertId { get; set; }
        public string DescriptionCityCouncil { get; set; }
        public Nullable<int> MinistryExpertId { get; set; }
        public string DescriptionMinistry { get; set; }
        public long DecisionNo { get; set; }
        public Nullable<System.DateTime> DecisionDate { get; set; }
        public string Description { get; set; }
        public int UserCode { get; set; }
        public Nullable<System.DateTime> SystemDate { get; set; }
        public Nullable<System.DateTime> FromDateTime { get; set; }
        public string Proceedings { get; set; }
        public Nullable<bool> IsIncompleted { get; set; }
        public Nullable<int> JusticeExpertId { get; set; }
        public string JusticeExpert { get; set; }
    }
}
