//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Defense
    {
        public int Id { get; set; }
        public int RequestId { get; set; }
        public string DefenseText { get; set; }
        public int FolderId { get; set; }
    }
}
