//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeliveryAndTransformation
    {
        public int Id { get; set; }
        public Nullable<int> Number { get; set; }
        public Nullable<System.DateTime> DeliveryMeetingDate { get; set; }
        public Nullable<int> DeliveryType { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public Nullable<int> DeliveryStatus { get; set; }
        public Nullable<int> CommunicatedNumber { get; set; }
        public Nullable<System.DateTime> CommunicatedDate { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<decimal> Shod { get; set; }
        public Nullable<decimal> Shop { get; set; }
        public string Description { get; set; }
    }
}
