//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DensitySettings
    {
        public int Id { get; set; }
        public Nullable<byte> StartCalculationFloorCode { get; set; }
        public string SeparateItems { get; set; }
        public Nullable<byte> CalculationBaseArea { get; set; }
    }
}
