//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DestMarhaleh
    {
        public long adder { get; set; }
        public Nullable<int> c_NoeGardeshkar { get; set; }
        public Nullable<int> c_Marhaleh { get; set; }
        public Nullable<int> Code { get; set; }
    
        public virtual Marahel Marahel { get; set; }
    }
}
