//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiscountTracker
    {
        public int Id { get; set; }
        public int Shop { get; set; }
        public int Shod { get; set; }
        public int DiscountId { get; set; }
        public string NationalId { get; set; }
        public Nullable<int> FishNumber { get; set; }
        public byte ShoMohasebeh { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public bool UseStatus { get; set; }
    }
}
