//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Document_Template
    {
        public long Id { get; set; }
        public long shop { get; set; }
        public long shDarkhast { get; set; }
        public long docNumber { get; set; }
        public string templateName { get; set; }
        public string semat { get; set; }
        public string signatory { get; set; }
    }
}
