//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Draft
    {
        public int Id { get; set; }
        public int Shop { get; set; }
        public int Shod { get; set; }
        public bool IsDelete { get; set; }
        public Nullable<int> CommissionCode { get; set; }
        public string CommissionText { get; set; }
        public string DraftNumber { get; set; }
        public System.DateTime DraftDate { get; set; }
        public string DraftDesc { get; set; }
        public Nullable<int> UserCode { get; set; }
        public string UserNameFamily { get; set; }
        public string Year { get; set; }
        public Nullable<System.DateTime> CommissionDate { get; set; }
        public string CommissionTime { get; set; }
        public string SessionNumber { get; set; }
    }
}
