//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DTaghsit_Info
    {
        public long Radif { get; set; }
        public decimal shop { get; set; }
        public Nullable<int> RadifMalek { get; set; }
        public int IdMalek { get; set; }
        public int GhestNumber { get; set; }
        public Nullable<decimal> Avarez { get; set; }
        public Nullable<decimal> Khadamat { get; set; }
        public Nullable<decimal> Education { get; set; }
        public Nullable<decimal> Firestation { get; set; }
        public Nullable<decimal> Tax { get; set; }
        public Nullable<decimal> mablagh_Ghest { get; set; }
        public Nullable<bool> Is_Paid { get; set; }
    }
}
