//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dv_AlodegiShoghli
    {
        public decimal Shop { get; set; }
        public decimal d_Radif { get; set; }
        public int M_ID { get; set; }
        public decimal id { get; set; }
        public string mtable_name { get; set; }
        public Nullable<int> c_NoeAlodegi { get; set; }
        public string NoeAlodegi { get; set; }
        public Nullable<int> DarajeAlodegi { get; set; }
    }
}
