//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dv_aghabneshini
    {
        public decimal shop { get; set; }
        public decimal d_radif { get; set; }
        public decimal id { get; set; }
        public string mtable_name { get; set; }
        public Nullable<int> c_aghab { get; set; }
        public string aghab { get; set; }
        public Nullable<double> meghdar { get; set; }
        public Nullable<double> LengthAghabNeshini { get; set; }
        public Nullable<double> WidthAghabNeshini { get; set; }
        public Nullable<bool> reayat { get; set; }
        public Nullable<double> AmountDone { get; set; }
        public Nullable<int> BuildingTypeId { get; set; }
        public Nullable<int> AccountTypeId { get; set; }
        public Nullable<int> DensityId { get; set; }
        public Nullable<int> TypeStructuresMaterialsId { get; set; }
        public Nullable<int> DateConstruction { get; set; }
    
        public virtual AccountType AccountType { get; set; }
        public virtual BuildingType BuildingType { get; set; }
        public virtual Density Density { get; set; }
        public virtual TypeStructuresMaterials TypeStructuresMaterials { get; set; }
    }
}
