//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dv_ductAndPatio
    {
        public int Id { get; set; }
        public int shop { get; set; }
        public int d_radif { get; set; }
        public string mtableName { get; set; }
        public Nullable<int> c_tabaghe { get; set; }
        public string tabaghe { get; set; }
        public string dimensions { get; set; }
        public Nullable<int> tedad { get; set; }
        public byte type { get; set; }
    }
}
