//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dv_divar
    {
        public decimal shop { get; set; }
        public decimal d_radif { get; set; }
        public decimal id { get; set; }
        public string mtable_name { get; set; }
        public Nullable<int> c_Jahat { get; set; }
        public string jahat { get; set; }
        public Nullable<double> tol { get; set; }
        public Nullable<double> ertefa { get; set; }
        public Nullable<int> salsakht { get; set; }
        public Nullable<int> c_jens { get; set; }
        public string jens { get; set; }
        public Nullable<double> masahat { get; set; }
    }
}
