//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dv_dahaneh
    {
        public decimal shop { get; set; }
        public decimal d_radif { get; set; }
        public decimal id { get; set; }
        public string mtable_name { get; set; }
        public Nullable<int> c_Jahat { get; set; }
        public string jahat { get; set; }
        public Nullable<double> tolbar { get; set; }
        public Nullable<double> masahat_h { get; set; }
        public Nullable<double> omgh_h { get; set; }
        public Nullable<double> arz_dahaneh { get; set; }
        public Nullable<int> DahaneCount { get; set; }
        public Nullable<int> UnitCount { get; set; }
        public Nullable<double> DahanehMojaz { get; set; }
        public Nullable<double> DahanehEhdasi { get; set; }
        public Nullable<double> MasahatTejari { get; set; }
        public Nullable<int> c_noeEstefade { get; set; }
        public string NoeEstefade { get; set; }
        public Nullable<double> Height { get; set; }
    }
}
