//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dv_darb
    {
        public decimal shop { get; set; }
        public decimal d_radif { get; set; }
        public decimal id { get; set; }
        public string Mtable_name { get; set; }
        public Nullable<int> c_noe { get; set; }
        public string noe { get; set; }
        public Nullable<int> tedad { get; set; }
        public Nullable<double> arz_m { get; set; }
        public Nullable<int> c_Jahat { get; set; }
        public string jahat { get; set; }
        public Nullable<double> omgh { get; set; }
    }
}
