//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dv_jahat
    {
        public decimal shop { get; set; }
        public decimal d_radif { get; set; }
        public decimal id { get; set; }
        public string mtable_name { get; set; }
        public Nullable<int> c_jahat_m { get; set; }
        public string jahat_m { get; set; }
        public Nullable<int> c_noe_m { get; set; }
        public string noe_m { get; set; }
        public string name_m { get; set; }
        public string azla_jahat { get; set; }
        public Nullable<double> tolbar { get; set; }
        public string tolzel { get; set; }
        public Nullable<double> arz_m { get; set; }
        public string azlanesbi { get; set; }
        public string tolzel_s { get; set; }
        public Nullable<double> tolbar_s { get; set; }
        public Nullable<double> mabar_d { get; set; }
        public Nullable<double> masahat1 { get; set; }
        public Nullable<double> masahat2 { get; set; }
        public Nullable<double> masahat3 { get; set; }
        public Nullable<double> masahatposht { get; set; }
        public string tolzeleslahi { get; set; }
        public string tolbareslahi { get; set; }
        public string tozihat { get; set; }
        public Nullable<double> Arz_Tariz { get; set; }
        public string OrginFrontDepth { get; set; }
        public Nullable<int> c_OrginFrontDepth { get; set; }
        public Nullable<int> c_noe_harim { get; set; }
        public string noe_harim { get; set; }
        public Nullable<double> faseleh_harim { get; set; }
        public string AdjacencyType { get; set; }
        public Nullable<int> c_AdjacencyType { get; set; }
        public Nullable<double> Retreat { get; set; }
    }
}
