//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dv_komision
    {
        public decimal shop { get; set; }
        public decimal d_radif { get; set; }
        public decimal id { get; set; }
        public string mtable_name { get; set; }
        public string shoray { get; set; }
        public Nullable<int> tarikhray { get; set; }
        public Nullable<int> c_noe_k { get; set; }
        public string noe_k { get; set; }
        public string shoersal { get; set; }
        public Nullable<int> tarikhersal { get; set; }
        public Nullable<int> c_noeray { get; set; }
        public string noeray { get; set; }
        public Nullable<int> tarikheblagh { get; set; }
        public Nullable<int> c_vaziyat_ejra { get; set; }
        public string vaziyat_ejra { get; set; }
        public Nullable<double> ezafe_bana { get; set; }
        public Nullable<double> Masahat { get; set; }
        public string Tozihat { get; set; }
        public Nullable<double> Parking { get; set; }
        public string pishnevis_Num { get; set; }
    }
}
