//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dv_karbariMojod
    {
        public decimal shop { get; set; }
        public decimal d_radif { get; set; }
        public decimal id { get; set; }
        public string mtable_name { get; set; }
        public string shosakhteman { get; set; }
        public Nullable<int> c_tabagheh { get; set; }
        public string tabagheh { get; set; }
        public Nullable<int> c_karbari { get; set; }
        public string karbari { get; set; }
        public Nullable<int> c_noeestefadeh { get; set; }
        public string noeestefadeh { get; set; }
        public Nullable<double> masahat_k { get; set; }
        public Nullable<int> tedadvahed { get; set; }
        public Nullable<int> c_noesakhteman { get; set; }
        public string noesakhteman { get; set; }
        public Nullable<int> c_noesaghf { get; set; }
        public string noesaghf { get; set; }
        public Nullable<int> c_noesazeh { get; set; }
        public string noesazeh { get; set; }
        public Nullable<int> c_marhaleh { get; set; }
        public string marhaleh { get; set; }
        public Nullable<int> tarikhehdas { get; set; }
        public Nullable<double> ehdasmazad { get; set; }
        public Nullable<double> ertefamofid { get; set; }
        public Nullable<int> ghedmataz { get; set; }
        public Nullable<int> ghedmatta { get; set; }
        public Nullable<double> zekhamat { get; set; }
        public Nullable<double> tedadomgh1 { get; set; }
        public string sh_vahed { get; set; }
        public Nullable<int> c_Khadamat { get; set; }
        public string Khadamat { get; set; }
        public string noenama { get; set; }
        public Nullable<int> c_noenama { get; set; }
        public Nullable<int> c_karbari_mojaz { get; set; }
        public string karbari_mojaz { get; set; }
        public Nullable<double> masahat_Karbar_Mojaz { get; set; }
        public string sharh { get; set; }
        public string percent_per_floor { get; set; }
        public Nullable<double> ErtefaEhdasi { get; set; }
        public Nullable<int> c_FazaySabz { get; set; }
        public string FazaySabz { get; set; }
    }
}
