//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dv_karbarimosavab
    {
        public decimal shop { get; set; }
        public decimal d_radif { get; set; }
        public decimal id { get; set; }
        public string mtable_name { get; set; }
        public Nullable<int> c_noetarh { get; set; }
        public string noetarh { get; set; }
        public Nullable<int> c_karbari { get; set; }
        public string karbari { get; set; }
        public string estefadeh_m { get; set; }
        public Nullable<double> darsad_t { get; set; }
        public Nullable<double> satheshghal { get; set; }
        public Nullable<int> c_mahalvogho { get; set; }
        public string mahalvogho { get; set; }
        public Nullable<double> Masahat { get; set; }
        public Nullable<double> MetrazhSatheshghal { get; set; }
        public Nullable<double> MetrazhTarakom { get; set; }
        public Nullable<long> C_Khadamat { get; set; }
        public string Khadamat { get; set; }
        public Nullable<int> BaseDensityPercentage { get; set; }
        public Nullable<int> BaseOccupancyLevel { get; set; }
        public Nullable<int> c_estefadeh_m { get; set; }
    }
}
