//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dv_KarbariChanges
    {
        public decimal shop { get; set; }
        public decimal d_radif { get; set; }
        public decimal id { get; set; }
        public string mtable_name { get; set; }
        public Nullable<int> c_KarbariPrimary { get; set; }
        public string KarbariPrimary { get; set; }
        public Nullable<int> c_KarbariSecondary { get; set; }
        public string KarbariSecondary { get; set; }
        public Nullable<double> Area { get; set; }
        public Nullable<bool> BafteFarsodeh { get; set; }
    }
}
