//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dv_malekin
    {
        public decimal shop { get; set; }
        public decimal d_radif { get; set; }
        public decimal id { get; set; }
        public int M_ID { get; set; }
        public string mtable_name { get; set; }
        public Nullable<int> c_noemalek { get; set; }
        public string noemalek { get; set; }
        public string name { get; set; }
        public string family { get; set; }
        public string father { get; set; }
        public string sh_sh { get; set; }
        public string sodor { get; set; }
        public string kodemeli { get; set; }
        public string tel { get; set; }
        public string mob { get; set; }
        public string sh_sanad { get; set; }
        public Nullable<double> sahm_a { get; set; }
        public Nullable<double> dong_a { get; set; }
        public Nullable<double> habbeh_a { get; set; }
        public Nullable<double> sahm_b { get; set; }
        public Nullable<double> dong_b { get; set; }
        public Nullable<double> habbeh_b { get; set; }
        public string address { get; set; }
        public Nullable<double> sahmkol_a { get; set; }
        public Nullable<double> sahmkol_b { get; set; }
        public Nullable<double> Darsad_a { get; set; }
        public Nullable<double> Darsad_b { get; set; }
        public string tozihat { get; set; }
        public Nullable<bool> MohasebeAvarez { get; set; }
        public Nullable<bool> MohasebeKhadamat { get; set; }
        public Nullable<double> ArzeshArse { get; set; }
        public Nullable<double> ArzeshAyan { get; set; }
        public Nullable<double> AvalDoreh { get; set; }
        public long Adder { get; set; }
        public Nullable<double> sir_a { get; set; }
        public Nullable<double> sir_b { get; set; }
        public Nullable<double> meghdarsahmarse { get; set; }
        public Nullable<double> meghdarsahmayan { get; set; }
        public Nullable<bool> chap_fish { get; set; }
        public Nullable<int> BirthYear { get; set; }
        public Nullable<bool> submitRequest { get; set; }
        public Nullable<decimal> mablaghDarkhast { get; set; }
        public string OldTradeCode { get; set; }
        public string ISIC { get; set; }
        public Nullable<System.DateTime> FromDateTime { get; set; }
        public Nullable<System.DateTime> ToDateTime { get; set; }
    }
}
