//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dv_mafasa
    {
        public decimal shop { get; set; }
        public decimal d_radif { get; set; }
        public decimal id { get; set; }
        public string mtable_name { get; set; }
        public Nullable<int> pardakht_end { get; set; }
        public Nullable<bool> nesbat1 { get; set; }
        public Nullable<bool> nesbat2 { get; set; }
        public Nullable<decimal> motalebat { get; set; }
        public string shofish { get; set; }
    }
}
