//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dv_MoshakhasatTablo
    {
        public decimal shop { get; set; }
        public decimal d_radif { get; set; }
        public int M_ID { get; set; }
        public decimal id { get; set; }
        public string mtable_name { get; set; }
        public Nullable<int> c_Jens { get; set; }
        public string Jens { get; set; }
        public Nullable<int> c_MozoTablo { get; set; }
        public string MozoTablo { get; set; }
        public Nullable<int> c_MakanTablo { get; set; }
        public string MakanTablo { get; set; }
        public Nullable<int> c_MalekiatTablo { get; set; }
        public string MalekiatTablo { get; set; }
        public Nullable<double> MasahatTablo { get; set; }
        public Nullable<int> Tol { get; set; }
        public Nullable<int> Arz { get; set; }
        public Nullable<int> TarikhShoro { get; set; }
        public Nullable<int> TarikhPayan { get; set; }
        public string Mojavez { get; set; }
    }
}
