//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dv_naameh
    {
        public decimal shop { get; set; }
        public decimal d_radif { get; set; }
        public decimal id { get; set; }
        public string mtable_name { get; set; }
        public Nullable<int> c_noe { get; set; }
        public string noe { get; set; }
        public string sh_na { get; set; }
        public Nullable<int> tarikh_na { get; set; }
        public string shosabt { get; set; }
        public Nullable<int> tarikhsabt { get; set; }
        public Nullable<int> c_onvan { get; set; }
        public string onvan { get; set; }
        public string kholaseh { get; set; }
        public Nullable<int> c_marja { get; set; }
        public string marja { get; set; }
        public string tozihat { get; set; }
        public Nullable<long> ConfirmationPassword { get; set; }
        public Nullable<bool> ShowInPrint { get; set; }
    }
}
