//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dv_pishamadegi
    {
        public decimal shop { get; set; }
        public decimal d_radif { get; set; }
        public decimal id { get; set; }
        public string mtable_name { get; set; }
        public string shosakhteman { get; set; }
        public Nullable<int> c_tabagheh { get; set; }
        public string shotabagheh { get; set; }
        public Nullable<int> c_noepish { get; set; }
        public string noepish { get; set; }
        public Nullable<double> masahat { get; set; }
        public Nullable<double> ertefa { get; set; }
        public Nullable<double> arz { get; set; }
        public Nullable<int> c_jahat { get; set; }
        public string jahat { get; set; }
        public Nullable<int> c_asli { get; set; }
        public string asli { get; set; }
        public Nullable<int> c_farei { get; set; }
        public string farei { get; set; }
        public Nullable<int> c_chegonegi { get; set; }
        public string chegonegi { get; set; }
        public Nullable<int> c_mahalvogho { get; set; }
        public string mahalvogho { get; set; }
        public Nullable<int> c_saghf { get; set; }
        public string saghf { get; set; }
        public Nullable<int> c_noeaslipish { get; set; }
        public string noeaslipish { get; set; }
        public Nullable<double> tomgh1 { get; set; }
        public Nullable<double> tomgh2 { get; set; }
        public Nullable<double> tomgh3 { get; set; }
        public Nullable<double> momgh1 { get; set; }
        public Nullable<double> momgh2 { get; set; }
        public Nullable<double> momgh3 { get; set; }
        public Nullable<double> tol { get; set; }
        public Nullable<double> omgh { get; set; }
        public Nullable<int> sh_vahed { get; set; }
        public Nullable<int> tarikhSakht { get; set; }
        public Nullable<int> c_marhaleh { get; set; }
        public string marhaleh { get; set; }
        public Nullable<int> BuildingTypeId { get; set; }
        public Nullable<int> AccountTypeId { get; set; }
        public Nullable<int> DensityId { get; set; }
        public Nullable<int> TypeStructuresMaterialsId { get; set; }
        public string UnitNumber { get; set; }
    
        public virtual AccountType AccountType { get; set; }
        public virtual BuildingType BuildingType { get; set; }
        public virtual Density Density { get; set; }
        public virtual TypeStructuresMaterials TypeStructuresMaterials { get; set; }
    }
}
