//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dv_parking
    {
        public decimal shop { get; set; }
        public decimal d_radif { get; set; }
        public decimal id { get; set; }
        public string mtable_name { get; set; }
        public Nullable<int> c_tabagheh { get; set; }
        public string tabagheh { get; set; }
        public Nullable<int> c_noetamin { get; set; }
        public string noetamin { get; set; }
        public Nullable<int> c_nahvetamin { get; set; }
        public string nahvetamin { get; set; }
        public Nullable<double> tedad { get; set; }
        public Nullable<int> c_noemalekiat { get; set; }
        public string noemalekiat { get; set; }
        public Nullable<double> masahat { get; set; }
        public Nullable<double> ertefa { get; set; }
    }
}
