//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dv_Parking2
    {
        public double ShoP { get; set; }
        public int Radif { get; set; }
        public int ID { get; set; }
        public string mTable_Name { get; set; }
        public Nullable<int> C_Karbari { get; set; }
        public string Karbari { get; set; }
        public Nullable<double> TedadParkingMoredeNiaz { get; set; }
        public Nullable<double> Kasri { get; set; }
        public Nullable<double> Kharidari { get; set; }
        public Nullable<double> Zarib { get; set; }
        public string Tozihat { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<int> usercode { get; set; }
        public Nullable<int> Sh_Darkhast { get; set; }
    }
}
