//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dv_pakh
    {
        public decimal shop { get; set; }
        public decimal d_radif { get; set; }
        public decimal id { get; set; }
        public string mtable_name { get; set; }
        public Nullable<int> c_mahal { get; set; }
        public string mahal { get; set; }
        public Nullable<double> abaad { get; set; }
        public Nullable<int> c_noepakh { get; set; }
        public string noepakh { get; set; }
        public Nullable<bool> reayat { get; set; }
        public Nullable<double> TolVatar { get; set; }
    }
}
