//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dv_savabegh
    {
        public decimal shop { get; set; }
        public decimal d_radif { get; set; }
        public decimal id { get; set; }
        public string mtable_name { get; set; }
        public Nullable<int> c_grouh { get; set; }
        public string grouh { get; set; }
        public Nullable<int> c_noe { get; set; }
        public string noe { get; set; }
        public string sho_g { get; set; }
        public Nullable<int> tarikh_g { get; set; }
        public Nullable<int> tarikh_e { get; set; }
        public string sh_serial { get; set; }
        public string tozih { get; set; }
        public Nullable<double> Area { get; set; }
        public Nullable<bool> ShowInPrint { get; set; }
    }
}
