//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dv_z_eshterak
    {
        public decimal shop { get; set; }
        public decimal d_radif { get; set; }
        public decimal id { get; set; }
        public string mtable_name { get; set; }
        public Nullable<int> c_tabagheh { get; set; }
        public string sh_tabagheh { get; set; }
        public Nullable<int> c_asli { get; set; }
        public string asli { get; set; }
        public Nullable<int> c_farei { get; set; }
        public string farei { get; set; }
        public Nullable<double> masahat { get; set; }
        public string vaziat_zirbana { get; set; }
        public Nullable<double> ertefa { get; set; }
    }
}
