//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dv_zavabet
    {
        public decimal shop { get; set; }
        public decimal shoDarkhast { get; set; }
        public long d_radif { get; set; }
        public long idZavabet { get; set; }
        public long id { get; set; }
        public Nullable<double> ArzGozar { get; set; }
        public Nullable<double> pakhSize { get; set; }
        public Nullable<double> pasraviSize { get; set; }
        public Nullable<int> c_zel { get; set; }
        public string zel { get; set; }
        public Nullable<double> EshghalMojaz_Per { get; set; }
        public Nullable<double> EshghalMojaz_Metr { get; set; }
        public Nullable<double> tarakomMojaz_Per { get; set; }
        public Nullable<double> tarakom_metr { get; set; }
        public Nullable<double> tedad_saghf { get; set; }
        public Nullable<double> Tashvighi_Sath_Eshghal { get; set; }
        public Nullable<double> Tashvighi_Tarakom { get; set; }
        public Nullable<double> TarakomPaye { get; set; }
        public Nullable<double> Tashvighi_Sath_Eshghal_Metr { get; set; }
        public Nullable<double> Tashvighi_Tarakom_Metr { get; set; }
        public Nullable<int> maxTabaghatMojaz { get; set; }
        public Nullable<double> HF_Shomal { get; set; }
        public Nullable<double> HF_Jonob { get; set; }
        public Nullable<double> HF_Shargh { get; set; }
        public Nullable<double> HF_Gharb { get; set; }
        public Nullable<double> pasraviSize2 { get; set; }
        public Nullable<int> c_zel2 { get; set; }
        public string zel2 { get; set; }
        public Nullable<double> ertefa { get; set; }
        public string janpanah { get; set; }
        public Nullable<decimal> Arc { get; set; }
        public Nullable<double> ExcessOccupancyLevelPercent { get; set; }
        public Nullable<double> ExcessOccupancyLevelMeter { get; set; }
        public Nullable<double> ExcessDensityPercent { get; set; }
        public Nullable<double> ExcessDensityMeter { get; set; }
        public Nullable<double> HadeAxarTedadVahedeSakhtemani { get; set; }
        public Nullable<double> HadeAxarTabaghe { get; set; }
    }
}
