//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ebtals
    {
        public int shop { get; set; }
        public int shod { get; set; }
        public Nullable<int> userId { get; set; }
        public string ellat { get; set; }
        public string tarikh { get; set; }
        public string tozihat { get; set; }
    }
}
