//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EkhtarMohandesan
    {
        public int Id { get; set; }
        public int mohandesId { get; set; }
        public int ekhtarId { get; set; }
        public string ekhtarType { get; set; }
        public Nullable<int> FromDate { get; set; }
        public Nullable<int> ToDate { get; set; }
        public string Description { get; set; }
        public int userId { get; set; }
        public string userName { get; set; }
        public System.DateTime ekhtarDate { get; set; }
        public bool Active { get; set; }
    }
}
