//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ElamBazdid
    {
        public long adder { get; set; }
        public decimal shodarkhast { get; set; }
        public Nullable<int> code { get; set; }
        public string name { get; set; }
        public Nullable<int> tarikh { get; set; }
        public string saat { get; set; }
        public Nullable<bool> anjam { get; set; }
        public bool Faghed_Kaeshenas { get; set; }
        public string ToTime { get; set; }
    }
}
