//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ElamMamor
    {
        public decimal code { get; set; }
        public string name { get; set; }
        public string tel { get; set; }
        public string mob { get; set; }
        public Nullable<int> max_b { get; set; }
        public string usercode { get; set; }
        public Nullable<bool> flag { get; set; }
    }
}
