//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ErjaShode
    {
        public int shPeygiri { get; set; }
        public int shop { get; set; }
        public string codeNosazi { get; set; }
        public string erjakonande { get; set; }
        public string phoneNumber { get; set; }
        public string serialNumber { get; set; }
        public string momayez { get; set; }
        public Nullable<int> momayezGetDate { get; set; }
        public string momayezGet { get; set; }
        public string momayezSend { get; set; }
        public Nullable<int> momayezSendDate { get; set; }
        public string bazbinGet { get; set; }
        public Nullable<int> bazbinGetDate { get; set; }
        public Nullable<int> bazbinSendDate { get; set; }
        public string taiidBazbin { get; set; }
        public string taiidsarparast { get; set; }
        public string taiidNazerSh { get; set; }
        public string endOfProcess { get; set; }
    }
}
