//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Erja
    {
        public long adder { get; set; }
        public Nullable<int> sh_darkhast { get; set; }
        public Nullable<int> tarikh_darkhast { get; set; }
        public int c_nodarkhast { get; set; }
        public string noedarkhast { get; set; }
        public Nullable<int> c_marhaleh { get; set; }
        public string marhaleh { get; set; }
        public string code_nosazi { get; set; }
        public Nullable<double> shop { get; set; }
        public string name_mot { get; set; }
        public int tarikh_erja { get; set; }
        public Nullable<int> c_grouh { get; set; }
        public string grouh { get; set; }
        public string ijadkonandeh_c { get; set; }
        public string ijadkonandeh { get; set; }
        public string ersalkonandeh_c { get; set; }
        public string ersalkonandeh { get; set; }
        public string girandeh_c { get; set; }
        public string girandeh { get; set; }
        public Nullable<bool> flag { get; set; }
        public string saat_erja { get; set; }
        public Nullable<int> c_vaziatErja { get; set; }
        public string vaziatErja { get; set; }
        public string Desc_Marhaleh { get; set; }
        public string SeenBy { get; set; }
    
        public virtual Gardesh_Kar Gardesh_Kar { get; set; }
        public virtual Marhaleh Marhaleh1 { get; set; }
    }
}
