//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExpertStaff
    {
        public int Id { get; set; }
        public Nullable<int> ExpertOfEstateId { get; set; }
        public string ExpertFullName { get; set; }
        public Nullable<int> Post { get; set; }
        public string ExpertComment { get; set; }
        public Nullable<int> Number { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<System.DateTime> CommentValidDate { get; set; }
        public Nullable<decimal> PricePerMeter { get; set; }
        public Nullable<decimal> PricePerMeterfield { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<int> NumOfExpert { get; set; }
    
        public virtual ExpertOfEstate ExpertOfEstate { get; set; }
    }
}
