//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExpertsOfArticle77
    {
        public ExpertsOfArticle77()
        {
            this.MeetingVoteArticle77 = new HashSet<MeetingVoteArticle77>();
            this.MeetingVoteArticle771 = new HashSet<MeetingVoteArticle77>();
            this.MeetingVoteArticle772 = new HashSet<MeetingVoteArticle77>();
        }
    
        public long Id { get; set; }
        public bool IsDelete { get; set; }
        public int OriginalCode { get; set; }
        public int Code { get; set; }
        public string Name { get; set; }
        public string Family { get; set; }
        public string Father { get; set; }
        public string BirthCertificateNumber { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public string NationalCode { get; set; }
        public string Degree { get; set; }
        public string Field { get; set; }
        public Nullable<System.DateTime> ObtainingDegreeDate { get; set; }
        public string Tel { get; set; }
        public string Addres { get; set; }
        public byte[] Image { get; set; }
        public byte[] Signature { get; set; }
        public byte[] Stamp { get; set; }
        public bool StatusExperts { get; set; }
        public Nullable<int> LevelID { get; set; }
        public string LevelName { get; set; }
        public Nullable<int> NumberOfUndergraduateCases { get; set; }
    
        public virtual ICollection<MeetingVoteArticle77> MeetingVoteArticle77 { get; set; }
        public virtual ICollection<MeetingVoteArticle77> MeetingVoteArticle771 { get; set; }
        public virtual ICollection<MeetingVoteArticle77> MeetingVoteArticle772 { get; set; }
    }
}
