//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExpertOpinion
    {
        public long Id { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<long> Shop { get; set; }
        public Nullable<long> Shod { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> C_Expert { get; set; }
        public string Expert { get; set; }
        public string Description { get; set; }
        public Nullable<long> OpinionNumber { get; set; }
        public Nullable<long> ScanId { get; set; }
        public Nullable<long> ScanRadif { get; set; }
        public Nullable<int> C_Commission { get; set; }
        public string Commission { get; set; }
    }
}
