//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExpertOfEstate
    {
        public ExpertOfEstate()
        {
            this.ExpertStaff = new HashSet<ExpertStaff>();
        }
    
        public int Id { get; set; }
        public string ActivityDescription { get; set; }
        public Nullable<int> MeetingNumber { get; set; }
        public Nullable<decimal> shod { get; set; }
        public Nullable<decimal> shop { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public string Description { get; set; }
        public Nullable<int> NumberOfExpert { get; set; }
        public Nullable<System.DateTime> MeetingDate { get; set; }
        public Nullable<decimal> BeforeFieldPrice { get; set; }
        public Nullable<decimal> BeforeAyanPrice { get; set; }
        public Nullable<decimal> BeforeTotalPrice { get; set; }
        public Nullable<decimal> AfterFieldPrice { get; set; }
        public Nullable<decimal> AfterAyanPrice { get; set; }
        public Nullable<decimal> AfterTotalPrice { get; set; }
        public Nullable<System.DateTime> CommentValidDate { get; set; }
        public Nullable<decimal> BeforeRightOfWayFee { get; set; }
        public Nullable<decimal> AfterRightOfWayFee { get; set; }
    
        public virtual ICollection<ExpertStaff> ExpertStaff { get; set; }
    }
}
