//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FinancialSituation
    {
        public long Id { get; set; }
        public string Shop { get; set; }
        public string Shod { get; set; }
        public bool IsDelete { get; set; }
        public string FinancialSituationText { get; set; }
        public Nullable<long> AccountingDocumentNumber { get; set; }
        public Nullable<long> CheckNumber { get; set; }
        public Nullable<long> Price { get; set; }
        public Nullable<System.DateTime> FinancialSituationDate { get; set; }
        public string FinancialSituationDescription { get; set; }
        public Nullable<long> RialValue { get; set; }
    }
}
