//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FireStationItem
    {
        public int Id { get; set; }
        public int FireStationId { get; set; }
        public int FireStationDefineItemId { get; set; }
        public Nullable<bool> CountVisitOne { get; set; }
        public Nullable<bool> CountVisitTwo { get; set; }
        public Nullable<bool> CountVisitThree { get; set; }
        public string Description { get; set; }
    
        public virtual FireStation FireStation { get; set; }
        public virtual FireStationDefineItem FireStationDefineItem { get; set; }
    }
}
