//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FireStation
    {
        public FireStation()
        {
            this.FireStationItem = new HashSet<FireStationItem>();
        }
    
        public int shop { get; set; }
        public long Sh_Darkhast { get; set; }
        public string DescFireStation { get; set; }
        public Nullable<short> Status { get; set; }
        public int Id { get; set; }
        public Nullable<int> Radif { get; set; }
        public Nullable<int> CountResidentialUnits { get; set; }
        public Nullable<int> CountBusinessUnits { get; set; }
        public string AccountType { get; set; }
        public Nullable<int> CountRazorOutput { get; set; }
        public string ExpertFinalTheory { get; set; }
        public Nullable<decimal> PriceOne { get; set; }
        public Nullable<decimal> PriceTwo { get; set; }
        public string ReceiptNumberOne { get; set; }
        public string ReceiptNumberTwo { get; set; }
        public string DateOne { get; set; }
        public string DateTwo { get; set; }
        public string ResponsibleFinalRegistration { get; set; }
        public string DateRegister { get; set; }
        public Nullable<bool> Address { get; set; }
        public string Phone { get; set; }
        public string OwnerName { get; set; }
        public string NoeEstelam { get; set; }
        public string PelakSabti { get; set; }
        public string CodeNosazi { get; set; }
        public string ShomreName { get; set; }
    
        public virtual ICollection<FireStationItem> FireStationItem { get; set; }
    }
}
