//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fish
    {
        public long AdderRadif { get; set; }
        public string shofish { get; set; }
        public Nullable<double> shop { get; set; }
        public Nullable<int> RadifMalek { get; set; }
        public Nullable<int> IdMalek { get; set; }
        public Nullable<int> sal { get; set; }
        public Nullable<int> mantaghe { get; set; }
        public Nullable<int> hoze { get; set; }
        public Nullable<int> blok { get; set; }
        public Nullable<int> shomelk { get; set; }
        public Nullable<int> sakhteman { get; set; }
        public Nullable<int> apar { get; set; }
        public Nullable<int> senfi { get; set; }
        public string ghabli { get; set; }
        public string mantagheg { get; set; }
        public string hozeg { get; set; }
        public string blokg { get; set; }
        public string shomelkg { get; set; }
        public string sakhtmang { get; set; }
        public string aparg { get; set; }
        public string Senfig { get; set; }
        public string ghablig { get; set; }
        public string asli { get; set; }
        public string fari { get; set; }
        public string azfari { get; set; }
        public Nullable<int> noesanad { get; set; }
        public string plak { get; set; }
        public string e_ab { get; set; }
        public Nullable<decimal> moavaghe { get; set; }
        public Nullable<decimal> khoshhesabi { get; set; }
        public string tedadmalek { get; set; }
        public Nullable<decimal> khadamat { get; set; }
        public Nullable<decimal> m_khadamat { get; set; }
        public Nullable<int> azsal { get; set; }
        public Nullable<int> tasal { get; set; }
        public Nullable<decimal> mablagh { get; set; }
        public string mablagh_farsi { get; set; }
        public string nam_malek { get; set; }
        public string address { get; set; }
        public Nullable<decimal> avarez { get; set; }
        public string noe_melk { get; set; }
        public string pelak_Sabti { get; set; }
        public string CodePostiF { get; set; }
        public Nullable<decimal> AvarezDong { get; set; }
        public string DateSodorF { get; set; }
        public string DateMohlatF { get; set; }
        public string vahedkasbi { get; set; }
        public string MohlatPardakht { get; set; }
        public string NameBank { get; set; }
        public string saatfish { get; set; }
        public string namekarbar { get; set; }
        public string vaz_melk { get; set; }
        public string ShenaseGhabz { get; set; }
        public string ShenasePardakht { get; set; }
        public string neshani_melk { get; set; }
        public string motesaref { get; set; }
        public string name_mostajer { get; set; }
        public string ghest { get; set; }
        public string avarez_ghest { get; set; }
        public string khadamat_ghest { get; set; }
        public string Serial { get; set; }
        public Nullable<int> shomelkj { get; set; }
        public Nullable<int> shomelkgh { get; set; }
        public Nullable<decimal> Mafiyat { get; set; }
        public Nullable<decimal> SahmMalek { get; set; }
        public string peygham { get; set; }
        public string ShPM { get; set; }
        public Nullable<int> ShomelkNumeric { get; set; }
        public string Mob { get; set; }
        public string CodeN { get; set; }
        public Nullable<bool> flag { get; set; }
        public Nullable<decimal> Sayer { get; set; }
        public Nullable<decimal> Education { get; set; }
        public string SharhSayer { get; set; }
        public Nullable<decimal> FireStation { get; set; }
        public Nullable<decimal> BadHesabi { get; set; }
        public string barcode { get; set; }
        public Nullable<decimal> Tax { get; set; }
        public Nullable<double> ArzeshArse { get; set; }
        public Nullable<double> ArzeshAyan { get; set; }
        public Nullable<double> RegionalPrice { get; set; }
        public Nullable<double> MasahatZamin { get; set; }
        public Nullable<double> MasahatSakh { get; set; }
        public string Vahed { get; set; }
        public string Tabaghe { get; set; }
        public string Jahat { get; set; }
        public string bakhsh { get; set; }
        public string tafkiki { get; set; }
        public string SharhAvaldore { get; set; }
        public Nullable<decimal> MoafiatKhadamat { get; set; }
        public Nullable<decimal> FireStationMoavagh { get; set; }
        public Nullable<decimal> khoshhesabi_khadamat { get; set; }
        public Nullable<long> DelayInPaymentOfServices { get; set; }
        public Nullable<long> GreenArea { get; set; }
        public Nullable<long> PlaqueHammering { get; set; }
        public decimal EducationJari { get; set; }
        public Nullable<byte> BillType { get; set; }
        public Nullable<int> ServiceTax { get; set; }
    }
}
