//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FishSabti
    {
        public int ID { get; set; }
        public string shomare { get; set; }
        public string tar { get; set; }
        public Nullable<double> date { get; set; }
        public Nullable<double> avarez { get; set; }
        public Nullable<double> khad { get; set; }
        public Nullable<double> khada { get; set; }
        public Nullable<double> shop { get; set; }
        public Nullable<int> RadifMalek { get; set; }
        public Nullable<int> IdMalek { get; set; }
        public string name { get; set; }
        public Nullable<double> tik { get; set; }
        public string mahiyat { get; set; }
        public string sh_check { get; set; }
        public Nullable<long> radif_ava { get; set; }
        public string serial_fish { get; set; }
        public string ShGh { get; set; }
        public string ShPr { get; set; }
        public string CodeN { get; set; }
        public Nullable<double> datevariz { get; set; }
        public Nullable<decimal> Sayer { get; set; }
        public string sharh { get; set; }
        public Nullable<decimal> Education { get; set; }
        public Nullable<decimal> FireStation { get; set; }
        public Nullable<decimal> Tax { get; set; }
        public Nullable<decimal> mafiyat { get; set; }
        public string POSDocument { get; set; }
        public Nullable<decimal> MoafiatKhadamat { get; set; }
        public string TrackingNo { get; set; }
        public Nullable<long> DelayInPayment { get; set; }
        public Nullable<long> DelayInPaymentOfServices { get; set; }
        public Nullable<long> GreenArea { get; set; }
        public Nullable<long> CreditWorthiness { get; set; }
        public Nullable<long> PlaqueHammering { get; set; }
        public Nullable<long> CreditWorthinessOfServices { get; set; }
    }
}
