//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Formol
    {
        public decimal detailcode { get; set; }
        public decimal code { get; set; }
        public string saal { get; set; }
        public string noemohasebeh { get; set; }
        public string formol1 { get; set; }
        public string formol_field { get; set; }
        public Nullable<bool> masahat1 { get; set; }
        public Nullable<bool> masahat2 { get; set; }
        public Nullable<bool> masahat3 { get; set; }
        public Nullable<bool> masahatp { get; set; }
        public Nullable<bool> arzesh1 { get; set; }
        public Nullable<bool> arzesh2 { get; set; }
        public Nullable<bool> arzesh3 { get; set; }
        public Nullable<bool> arzeshp { get; set; }
        public Nullable<bool> tabaghe { get; set; }
        public Nullable<bool> zirbana { get; set; }
        public Nullable<bool> k_nama { get; set; }
        public Nullable<bool> k_sakhteman { get; set; }
        public Nullable<double> zarib { get; set; }
        public string Fx { get; set; }
        public string Arzesh { get; set; }
        public string FlgF { get; set; }
        public Nullable<decimal> MinimumSign { get; set; }
        public Nullable<decimal> MaximumSign { get; set; }
        public Nullable<decimal> Minimum { get; set; }
        public Nullable<decimal> Maximum { get; set; }
        public string FunctionName { get; set; }
    }
}
