//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FoulDefinitionSetting
    {
        public int Id { get; set; }
        public Nullable<decimal> HeightResidentialFixed { get; set; }
        public Nullable<decimal> HeightCommercialFixed { get; set; }
        public Nullable<byte> CalculationTypeParking { get; set; }
        public Nullable<bool> HeightContradiction { get; set; }
        public Nullable<bool> ContrastDensityWithHeight { get; set; }
        public Nullable<decimal> AreaParkingUnit { get; set; }
        public Nullable<decimal> HeightBalconyFixed { get; set; }
        public Nullable<int> FetchPriority { get; set; }
        public string SeparateItemsSecondaryUseType { get; set; }
        public Nullable<byte> FetchWithoutLicense { get; set; }
    }
}
