//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gardesh_Kar
    {
        public Gardesh_Kar()
        {
            this.Darkhast = new HashSet<Darkhast>();
            this.Erja = new HashSet<Erja>();
            this.Marahel = new HashSet<Marahel>();
        }
    
        public int Code { get; set; }
        public string Sharh { get; set; }
    
        public virtual ICollection<Darkhast> Darkhast { get; set; }
        public virtual ICollection<Erja> Erja { get; set; }
        public virtual ICollection<Marahel> Marahel { get; set; }
    }
}
