//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Haffari
    {
        public decimal shop { get; set; }
        public long Sh_Darkhast { get; set; }
        public Nullable<double> AmountHaffari { get; set; }
        public bool HasBranchHaffari { get; set; }
        public string DescHaffari { get; set; }
    }
}
