//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class History
    {
        public long adder { get; set; }
        public string user_name { get; set; }
        public Nullable<int> tarikh { get; set; }
        public string saat { get; set; }
        public string sharh { get; set; }
        public string name_karbar { get; set; }
        public string name_form { get; set; }
        public string noeamal { get; set; }
        public Nullable<int> shop { get; set; }
        public Nullable<int> shod { get; set; }
        public Nullable<long> userCode { get; set; }
        public string IPAddress { get; set; }
        public string CNosazi { get; set; }
        public string Hash { get; set; }
        public string MoreInfo { get; set; }
    }
}
