//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IncomeFormulaDetection
    {
        public int Id { get; set; }
        public Nullable<byte> CodeTypeRequest { get; set; }
        public string TypeRequest { get; set; }
        public Nullable<byte> CodeOccupancyLevelOrDensity { get; set; }
        public string OccupancyLevelOrDensity { get; set; }
        public Nullable<byte> CodeAccountType { get; set; }
        public string AccountType { get; set; }
        public long DaramadTFormoolMRadif { get; set; }
    
        public virtual Daramad_t_formool_m Daramad_t_formool_m { get; set; }
    }
}
