//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Khalaf
    {
        public double shop { get; set; }
        public string sh_Darkhast { get; set; }
        public int Radif { get; set; }
        public Nullable<bool> Karbari_Tafzili { get; set; }
        public Nullable<int> Taghazay_Residegi { get; set; }
        public Nullable<bool> GozarBandi { get; set; }
        public Nullable<bool> Esteghrar_Sakhteman { get; set; }
        public Nullable<bool> Fasele_Norgir { get; set; }
        public Nullable<bool> OsolFani_Behdashti { get; set; }
        public Nullable<bool> Govahi_Estehkam { get; set; }
        public Nullable<bool> Gozaresh_Nazer { get; set; }
        public Nullable<int> Tarikh { get; set; }
        public string Tozihat { get; set; }
        public Nullable<int> user_Code { get; set; }
        public string user_NameFamily { get; set; }
        public string saat { get; set; }
        public string Mabar_Mosavab { get; set; }
        public string Mabar_Mojod { get; set; }
        public Nullable<bool> OsolShahrsazi { get; set; }
        public Nullable<bool> withoutlicense { get; set; }
        public Nullable<bool> EzafeBana { get; set; }
        public Nullable<bool> changeStatusBuilding { get; set; }
        public Nullable<bool> Escape_stairs { get; set; }
        public Nullable<bool> Taghazay_SodorRay { get; set; }
        public Nullable<double> masahat_OutofRange { get; set; }
        public Nullable<int> DateFirestation { get; set; }
        public string RadifOnvanFormul { get; set; }
        public string DescOnvanFormul { get; set; }
        public Nullable<bool> Taghazay_SodorRay2 { get; set; }
        public Nullable<long> BuildingViolation { get; set; }
    }
}
