//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoginHistory
    {
        public long Id { get; set; }
        public string user_n { get; set; }
        public string ip { get; set; }
        public string userAgent { get; set; }
        public Nullable<System.DateTime> CreateAt { get; set; }
        public Nullable<bool> IsForWrongPassword { get; set; }
        public string Hash { get; set; }
        public string Method { get; set; }
    }
}
