//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogSMS
    {
        public long Id { get; set; }
        public long Shop { get; set; }
        public string CodeN { get; set; }
        public Nullable<int> IdMalek { get; set; }
        public string TextSMS { get; set; }
        public string MobileSMS { get; set; }
        public Nullable<int> TypeSMS { get; set; }
        public string StatusSMS { get; set; }
        public Nullable<double> UserCode { get; set; }
        public Nullable<System.DateTime> DateTimeSMS { get; set; }
        public Nullable<long> MasterId { get; set; }
        public string TypeSMSDesc { get; set; }
    
        public virtual MLogSms MLogSms { get; set; }
    }
}
