//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class M100_ekhtariyeh
    {
        public double shop { get; set; }
        public double shod { get; set; }
        public int tarikh_d { get; set; }
        public string shoekhtar { get; set; }
        public Nullable<int> dt_ekhtar { get; set; }
        public string elat_ekhtar { get; set; }
        public string saathozor { get; set; }
        public Nullable<int> dt_hozor { get; set; }
        public string saattahvil { get; set; }
        public Nullable<int> dt_tahvil { get; set; }
        public Nullable<bool> malek { get; set; }
        public Nullable<bool> vabaste_malek { get; set; }
        public string nesbat_vbm { get; set; }
        public Nullable<bool> amel_ejra { get; set; }
        public string name_amelejra { get; set; }
        public Nullable<bool> nasb_mahal { get; set; }
        public string ostan { get; set; }
        public string shahr { get; set; }
    }
}
