//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class M100_karshenasan
    {
        public M100_karshenasan()
        {
            this.MeetingVoteMade100 = new HashSet<MeetingVoteMade100>();
            this.MeetingVoteMade1001 = new HashSet<MeetingVoteMade100>();
            this.MeetingVoteMade1002 = new HashSet<MeetingVoteMade100>();
        }
    
        public int kodasli { get; set; }
        public int code_kar { get; set; }
        public string name_kar { get; set; }
        public string family_kar { get; set; }
        public string father_kar { get; set; }
        public string id_kar { get; set; }
        public Nullable<int> datet_kar { get; set; }
        public string kodmeli_kar { get; set; }
        public string madrak_kar { get; set; }
        public string reshte_kar { get; set; }
        public Nullable<int> d_akhz_kar { get; set; }
        public string tel_kar { get; set; }
        public string addres_kar { get; set; }
        public byte[] aks_kar { get; set; }
        public byte[] emza_kar { get; set; }
        public byte[] mohr_kar { get; set; }
        public bool StatusKarshenas { get; set; }
        public Nullable<int> LevelID { get; set; }
        public string LevelName { get; set; }
        public long Id { get; set; }
        public Nullable<int> NumberOfUndergraduateCases { get; set; }
    
        public virtual ICollection<MeetingVoteMade100> MeetingVoteMade100 { get; set; }
        public virtual ICollection<MeetingVoteMade100> MeetingVoteMade1001 { get; set; }
        public virtual ICollection<MeetingVoteMade100> MeetingVoteMade1002 { get; set; }
    }
}
