//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class M100_D_Ray
    {
        public int Code { get; set; }
        public int Satr { get; set; }
        public int shop { get; set; }
        public int Shod { get; set; }
        public string tarikh_d { get; set; }
        public int Radif { get; set; }
        public Nullable<double> Takhlof { get; set; }
        public Nullable<double> Mabna { get; set; }
        public Nullable<double> zarib { get; set; }
        public Nullable<double> Mablagh { get; set; }
        public Nullable<int> code_para { get; set; }
        public string d_ray_tozih { get; set; }
    }
}
