//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class M100_Eslah
    {
        public decimal shop { get; set; }
        public decimal shod { get; set; }
        public int tarikh_d { get; set; }
        public Nullable<double> shoeslah { get; set; }
        public Nullable<int> dt_eslah { get; set; }
        public string sharh { get; set; }
        public string Ostan { get; set; }
        public string shahr { get; set; }
    }
}
