//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class M100_badvi
    {
        public double shop { get; set; }
        public double shod { get; set; }
        public int tarikh_d { get; set; }
        public Nullable<int> dt_jalase { get; set; }
        public string jalase { get; set; }
        public string malekname { get; set; }
        public string shosanad { get; set; }
        public string neshani { get; set; }
        public string shogozaresh { get; set; }
        public Nullable<int> dt_gozaresh { get; set; }
        public Nullable<double> masahatzamin { get; set; }
        public Nullable<double> masahat1 { get; set; }
        public Nullable<decimal> mabnay1 { get; set; }
        public Nullable<double> zarib1 { get; set; }
        public Nullable<decimal> mablagh1 { get; set; }
        public string tozih1 { get; set; }
        public Nullable<double> masahat2 { get; set; }
        public Nullable<decimal> mabnay2 { get; set; }
        public Nullable<double> zarib2 { get; set; }
        public Nullable<decimal> mablagh2 { get; set; }
        public string tozih2 { get; set; }
        public Nullable<double> masahat3 { get; set; }
        public Nullable<decimal> mabnay3 { get; set; }
        public Nullable<double> zarib3 { get; set; }
        public Nullable<decimal> mablagh3 { get; set; }
        public string tozih3 { get; set; }
        public Nullable<double> masahat4 { get; set; }
        public Nullable<decimal> mabnay4 { get; set; }
        public Nullable<double> zarib4 { get; set; }
        public Nullable<decimal> mablagh4 { get; set; }
        public string tozih4 { get; set; }
        public Nullable<double> masahat5 { get; set; }
        public Nullable<decimal> mabnay5 { get; set; }
        public Nullable<double> zarib5 { get; set; }
        public Nullable<decimal> mablagh5 { get; set; }
        public string tozih5 { get; set; }
        public Nullable<decimal> jammablagh { get; set; }
        public string farsimablagh { get; set; }
        public string shomare_rp { get; set; }
        public Nullable<bool> shahrsazi { get; set; }
        public Nullable<bool> fani { get; set; }
        public Nullable<bool> behdashti { get; set; }
        public Nullable<double> bana { get; set; }
        public string tozihat { get; set; }
        public Nullable<int> kod_name_vd { get; set; }
        public string name_vd { get; set; }
        public string nazariye_vd { get; set; }
        public Nullable<int> kod_name_vk { get; set; }
        public string name_vk { get; set; }
        public string nazariye_vk { get; set; }
        public Nullable<int> kod_name_shora { get; set; }
        public string name_shora { get; set; }
        public string nazariye_shora { get; set; }
        public Nullable<int> dt_badvi { get; set; }
        public Nullable<double> shobadvi { get; set; }
        public string ostan { get; set; }
        public string shahr { get; set; }
        public Nullable<int> idMalek { get; set; }
        public Nullable<int> radifMalek { get; set; }
        public Nullable<double> arz { get; set; }
        public string j_arz { get; set; }
        public string EblaghNum { get; set; }
        public Nullable<int> EblaghDate { get; set; }
        public string EblaghAttach { get; set; }
        public bool band1 { get; set; }
        public bool band2 { get; set; }
        public bool band3 { get; set; }
        public Nullable<int> dt_badvi_ghabli { get; set; }
        public Nullable<double> shobadvi_ghabli { get; set; }
    }
}
