//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class m_access
    {
        public string code { get; set; }
        public string name { get; set; }
        public Nullable<int> code_tree { get; set; }
        public Nullable<int> id_parent { get; set; }
        public Nullable<bool> sws { get; set; }
        public Nullable<int> indextree { get; set; }
        public int Id { get; set; }
        public string codeGroh_Dastresi { get; set; }
        public Nullable<int> AreaId { get; set; }
        public string AreaName { get; set; }
        public string Hash { get; set; }
    }
}
