//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Made100_eteraz
    {
        public double shop { get; set; }
        public double shod { get; set; }
        public int tarikh_d { get; set; }
        public string shoeteraz_m { get; set; }
        public Nullable<int> dt_eteraz_m { get; set; }
        public string matn_eteraz_m { get; set; }
        public string shoeteraz_sh { get; set; }
        public Nullable<int> dt_eteraz_sh { get; set; }
        public string matn_eteraz_sh { get; set; }
        public string ostan { get; set; }
        public string shahr { get; set; }
        public string OwnerObjectionFilePath { get; set; }
    }
}
