//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Made100_Ray
    {
        public Made100_Ray()
        {
            this.Made100_RayDetails = new HashSet<Made100_RayDetails>();
        }
    
        public long Id { get; set; }
        public int shop { get; set; }
        public int shod { get; set; }
        public int PishnevisId { get; set; }
        public int Raydate { get; set; }
        public int RayNo { get; set; }
        public string FormatRayNo { get; set; }
        public Nullable<int> c_Raytype { get; set; }
        public string Raytype { get; set; }
        public string Description { get; set; }
        public string EblaghNo { get; set; }
        public Nullable<int> EblaghDate { get; set; }
        public string EblaghDescription { get; set; }
        public Nullable<bool> IsDelivery { get; set; }
        public Nullable<int> DelivaryDate { get; set; }
        public int userId { get; set; }
        public string userFullName { get; set; }
        public System.DateTime systemdate { get; set; }
        public Nullable<bool> AutomaticVoting { get; set; }
        public Nullable<bool> VoteStstus { get; set; }
        public Nullable<bool> MeetingStatus { get; set; }
        public bool SystemConfirmation { get; set; }
    
        public virtual ICollection<Made100_RayDetails> Made100_RayDetails { get; set; }
    }
}
