//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Made100_VoteInformation
    {
        public long Id { get; set; }
        public Nullable<int> typeVote { get; set; }
        public string typeVoteText { get; set; }
        public Nullable<int> codeVote { get; set; }
        public string codeVoteText { get; set; }
        public Nullable<int> numberVote { get; set; }
        public string formatnumberVote { get; set; }
        public Nullable<System.DateTime> dateVote { get; set; }
        public string Description { get; set; }
        public double UserCode { get; set; }
        public System.DateTime SystemDate { get; set; }
    
        public virtual accesslevel accesslevel { get; set; }
    }
}
