//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Made100_Marahel_Bargasht
    {
        public int Id { get; set; }
        public int curentMarhaleId { get; set; }
        public int BeforeMarhaleId { get; set; }
        public int commissionId { get; set; }
    
        public virtual Made100_Marahel Made100_Marahel { get; set; }
    }
}
