//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Made100_GardeshKar
    {
        public int Id { get; set; }
        public int marhaleId { get; set; }
        public Nullable<int> nextMarhaleId { get; set; }
        public Nullable<int> beforeMarhaleId { get; set; }
        public Nullable<long> groupCode { get; set; }
    
        public virtual Made100_Marahel Made100_Marahel { get; set; }
        public virtual Made100_Marahel Made100_Marahel1 { get; set; }
        public virtual Made100_Marahel Made100_Marahel2 { get; set; }
    }
}
