//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Made100_Decision_to_vote
    {
        public int Id { get; set; }
        public int shop { get; set; }
        public int shod { get; set; }
        public int pishnevisId { get; set; }
        public int CommisionId { get; set; }
        public Nullable<int> KarshenasGhazaeeId { get; set; }
        public string DescriptionGhazaee { get; set; }
        public Nullable<int> KarshenasShoraId { get; set; }
        public string DescriptopnShora { get; set; }
        public Nullable<int> KarshenasVezaratId { get; set; }
        public string DescriptionVezarat { get; set; }
        public long decisionNo { get; set; }
        public System.DateTime decisionDate { get; set; }
        public string description { get; set; }
        public int UserCode { get; set; }
        public System.DateTime systemDate { get; set; }
        public Nullable<System.DateTime> FromDateTime { get; set; }
        public string Proceedings { get; set; }
        public Nullable<bool> IsIncompleted { get; set; }
        public Nullable<int> KarshenasDadgostariId { get; set; }
        public string KarshenasDadgostari { get; set; }
    }
}
