//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Made100_tajdid
    {
        public int shop { get; set; }
        public double shod { get; set; }
        public string tarikh_d { get; set; }
        public string dt_jalase { get; set; }
        public string jalase { get; set; }
        public Nullable<bool> malek { get; set; }
        public string malekname { get; set; }
        public string shoeteraz_m { get; set; }
        public string dt_eteraz_m { get; set; }
        public Nullable<bool> shahrdari { get; set; }
        public string shoeteraz_sh { get; set; }
        public string dt_eteraz_sh { get; set; }
        public string ray_sadere_kom { get; set; }
        public Nullable<bool> zinafmalek { get; set; }
        public Nullable<bool> zinafshahrdari { get; set; }
        public Nullable<double> masahat1 { get; set; }
        public Nullable<decimal> mabnay1 { get; set; }
        public Nullable<double> zarib1 { get; set; }
        public Nullable<decimal> mablagh1 { get; set; }
        public string tozih1 { get; set; }
        public Nullable<double> masahat2 { get; set; }
        public Nullable<decimal> mabnay2 { get; set; }
        public Nullable<double> zarib2 { get; set; }
        public Nullable<decimal> mablagh2 { get; set; }
        public string tozih2 { get; set; }
        public Nullable<double> masahat3 { get; set; }
        public Nullable<decimal> mabnay3 { get; set; }
        public Nullable<double> zarib3 { get; set; }
        public Nullable<decimal> mablagh3 { get; set; }
        public string tozih3 { get; set; }
        public Nullable<double> masahat4 { get; set; }
        public Nullable<decimal> mabnay4 { get; set; }
        public Nullable<double> zarib4 { get; set; }
        public Nullable<decimal> mablagh4 { get; set; }
        public string tozih4 { get; set; }
        public Nullable<double> masahat5 { get; set; }
        public Nullable<decimal> mabnay5 { get; set; }
        public Nullable<double> zarib5 { get; set; }
        public Nullable<decimal> mablagh5 { get; set; }
        public string tozih5 { get; set; }
        public Nullable<decimal> jammablagh { get; set; }
        public string farsimablagh { get; set; }
        public string hesab { get; set; }
        public string bank { get; set; }
        public string shobe { get; set; }
        public Nullable<bool> shahrsazi { get; set; }
        public Nullable<bool> behdashti { get; set; }
        public Nullable<bool> fani { get; set; }
        public Nullable<double> bana { get; set; }
        public string tozihat { get; set; }
        public Nullable<int> kod_name_vd { get; set; }
        public string name_vd { get; set; }
        public string nazariye_vd { get; set; }
        public Nullable<int> kod_name_vk { get; set; }
        public string name_vk { get; set; }
        public string nazariye_vk { get; set; }
        public Nullable<int> kod_name_shora { get; set; }
        public string name_shora { get; set; }
        public string nazariye_shora { get; set; }
        public Nullable<double> shotajdid { get; set; }
        public string dt_tajdid { get; set; }
        public string ostan_co { get; set; }
        public string shahr_co { get; set; }
        public Nullable<bool> Shod_Nashod { get; set; }
        public Nullable<double> arz { get; set; }
        public string j_arz { get; set; }
        public Nullable<int> idMalek { get; set; }
        public Nullable<int> radifmalek { get; set; }
        public string EblaghNum { get; set; }
        public Nullable<int> EblaghDate { get; set; }
        public string EblaghAttach { get; set; }
        public Nullable<bool> band1_tajdid { get; set; }
        public Nullable<bool> band2_tajdid { get; set; }
        public Nullable<bool> band3_tajdid { get; set; }
    }
}
