//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Made100_SodorRay
    {
        public long Id { get; set; }
        public Nullable<int> shop { get; set; }
        public Nullable<int> sh_darkhast { get; set; }
        public Nullable<int> Radif { get; set; }
        public Nullable<int> MasahatkhalafID { get; set; }
        public Nullable<long> VoteInformationId { get; set; }
        public Nullable<int> PishnevisId { get; set; }
        public Nullable<long> MabnayMohasebe { get; set; }
        public Nullable<double> mablaghJarime { get; set; }
        public Nullable<double> Zarib { get; set; }
        public Nullable<double> ArzeshSarghofli { get; set; }
        public Nullable<double> MazadParvaneh { get; set; }
    }
}
