//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Made100_Karshenasan_Comments
    {
        public long Id { get; set; }
        public long MasterId { get; set; }
        public int kodeasli { get; set; }
        public int code_kar { get; set; }
        public string Description { get; set; }
        public Nullable<int> c_type { get; set; }
        public string type { get; set; }
        public int userCode { get; set; }
        public System.DateTime systemDate { get; set; }
    }
}
