//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Made100_SendVoteCommission
    {
        public long Id { get; set; }
        public int shop { get; set; }
        public int shDarkhast { get; set; }
        public int PishnevisId { get; set; }
        public string SendVoteNumber { get; set; }
        public Nullable<System.DateTime> SendVoteDate { get; set; }
        public bool IsDelivery { get; set; }
        public Nullable<System.DateTime> DelivaryDate { get; set; }
        public string Description { get; set; }
        public int UserCode { get; set; }
        public System.DateTime systemDate { get; set; }
    }
}
