//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Made100_Formula
    {
        public int Id { get; set; }
        public int Kodeasli { get; set; }
        public int year { get; set; }
        public string Caption { get; set; }
        public string formulField { get; set; }
        public string formulField_En { get; set; }
        public string Fx { get; set; }
        public Nullable<byte> EnumFoulDefinitionType { get; set; }
    }
}
