//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Made100_ExpertComments
    {
        public int Id { get; set; }
        public long pishnevisId { get; set; }
        public int Shop { get; set; }
        public int ShDarkhast { get; set; }
        public string CertificationNo { get; set; }
        public string Supervisor { get; set; }
        public string ExpertReportNo { get; set; }
        public string Expert { get; set; }
        public Nullable<int> KarshenasGhazaeeId { get; set; }
        public string DescriptionGhazaee { get; set; }
        public Nullable<int> KarshenasShoraId { get; set; }
        public string DescriptopnShora { get; set; }
        public Nullable<int> KarshenasVezaratId { get; set; }
        public string DescriptionVezarat { get; set; }
    }
}
