//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Made100_Kartable
    {
        public long Id { get; set; }
        public long shoDarkhast { get; set; }
        public long Shop { get; set; }
        public Nullable<int> PishnevisID { get; set; }
        public string LevelName { get; set; }
        public int LevelID { get; set; }
        public long SenderUserID { get; set; }
        public long ReceiverUserID { get; set; }
        public bool Active { get; set; }
        public System.DateTime SystemDate { get; set; }
    }
}
