//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Made100_RayDetails
    {
        public long Id { get; set; }
        public long Made100RayId { get; set; }
        public int c_TabsareMade100 { get; set; }
        public string Tabsaremade100 { get; set; }
        public Nullable<double> khalaf { get; set; }
        public Nullable<decimal> MabnaMohasebe { get; set; }
        public Nullable<double> Zarib { get; set; }
        public Nullable<long> ArzeshSarghofli { get; set; }
        public Nullable<double> MazadParvaneh { get; set; }
        public Nullable<long> MablaghJarime { get; set; }
        public string Description { get; set; }
        public int UserId { get; set; }
        public string UserName { get; set; }
        public System.DateTime systemDate { get; set; }
        public Nullable<int> radifKhalaf { get; set; }
        public Nullable<int> masahatkhalafID { get; set; }
        public string strKhalaf { get; set; }
        public Nullable<int> c_RayDetailType { get; set; }
        public string RayDetailType { get; set; }
        public Nullable<decimal> UnauthorizedHeight { get; set; }
        public Nullable<decimal> CommissionScope { get; set; }
    
        public virtual Made100_Ray Made100_Ray { get; set; }
    }
}
