//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Made100_RayCalculated
    {
        public long Id { get; set; }
        public long Made100RayId { get; set; }
        public long Made100RayDetailId { get; set; }
        public long FormulaId { get; set; }
        public string FormulaCaption { get; set; }
        public double price { get; set; }
    }
}
