//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mailroom
    {
        public long Id { get; set; }
        public Nullable<long> Shod { get; set; }
        public Nullable<long> Shop { get; set; }
        public string PatternNoSetting { get; set; }
        public long MailRoomNo { get; set; }
        public Nullable<long> IdMailRoomSetting { get; set; }
        public System.DateTime DateTimeInsert { get; set; }
        public double UserCodeInsert { get; set; }
    }
}
