//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Marahel_Bargasht
    {
        public int ID { get; set; }
        public int Code_Gardeshkar { get; set; }
        public int Code_Marhaleh_Jari { get; set; }
        public int Code_Marhaleh_Ghabli { get; set; }
    
        public virtual Marahel Marahel { get; set; }
    }
}
