//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Marahel
    {
        public Marahel()
        {
            this.DestMarhaleh = new HashSet<DestMarhaleh>();
            this.Marahel_Bargasht = new HashSet<Marahel_Bargasht>();
            this.Marahel_Erja = new HashSet<Marahel_Erja>();
        }
    
        public long id { get; set; }
        public int c_NoeGardeshkar { get; set; }
        public int Code { get; set; }
    
        public virtual ICollection<DestMarhaleh> DestMarhaleh { get; set; }
        public virtual Gardesh_Kar Gardesh_Kar { get; set; }
        public virtual ICollection<Marahel_Bargasht> Marahel_Bargasht { get; set; }
        public virtual ICollection<Marahel_Erja> Marahel_Erja { get; set; }
        public virtual Marhaleh Marhaleh { get; set; }
    }
}
