//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class masahat_khalaf
    {
        public int shop { get; set; }
        public int sh_darkhast { get; set; }
        public int Radif { get; set; }
        public int ID { get; set; }
        public Nullable<int> Code_Khalaf { get; set; }
        public string Onvan_Khalaf { get; set; }
        public Nullable<decimal> parvaneh { get; set; }
        public Nullable<decimal> takhalof { get; set; }
        public Nullable<int> Code_Karbari_Asli_Mojod { get; set; }
        public string Onvan_Karbari_Asli_Mojod { get; set; }
        public Nullable<int> Code_Karbari_Farei_Mojod { get; set; }
        public string Onvan_Karbari_Farei_Mojod { get; set; }
        public Nullable<int> Code_Karbari_Asli_Mojaz { get; set; }
        public string Onvan_Karbari_Asli_Mojaz { get; set; }
        public Nullable<int> Code_Karbari_Farei_Mojaz { get; set; }
        public string Onvan_Karbari_Farei_Mojaz { get; set; }
        public Nullable<double> tarakom { get; set; }
        public Nullable<int> ostan_co { get; set; }
        public Nullable<int> shahr_co { get; set; }
        public Nullable<double> TedadVahed { get; set; }
        public string Tabaghe { get; set; }
        public Nullable<int> Tarikh { get; set; }
        public Nullable<double> Ekhtelaf { get; set; }
        public Nullable<bool> Made100 { get; set; }
        public Nullable<int> c_Tabaghe { get; set; }
        public Nullable<decimal> Ehdas { get; set; }
        public Nullable<double> tarakomMojaz { get; set; }
        public Nullable<double> tarakomMojod { get; set; }
        public Nullable<double> sathEshghalMojaz { get; set; }
        public Nullable<double> sathEshghalMojod { get; set; }
        public string sharh { get; set; }
        public Nullable<int> AccountTypeId { get; set; }
        public Nullable<int> BuildingTypeId { get; set; }
        public Nullable<int> DensityId { get; set; }
        public Nullable<int> RegionalPricesId { get; set; }
        public Nullable<int> TypeStructuresMaterialsId { get; set; }
        public Nullable<byte> ZavabetType { get; set; }
        public Nullable<byte> EnumFoulDefinitionType { get; set; }
        public Nullable<int> c_marhaleh { get; set; }
        public string marhaleh { get; set; }
        public Nullable<int> c_noesakhtemanMojaz { get; set; }
        public string noesakhtemanMojaz { get; set; }
        public Nullable<int> c_noesakhtemanMojod { get; set; }
        public string noesakhtemanMojod { get; set; }
        public Nullable<decimal> TradingValue { get; set; }
        public Nullable<byte> AllowedUnitsCount { get; set; }
        public Nullable<decimal> UnauthorizedHeight { get; set; }
        public Nullable<int> c_noepish { get; set; }
        public string noepish { get; set; }
        public Nullable<int> RowId { get; set; }
        public Nullable<int> BalconyRowId { get; set; }
        public Nullable<decimal> FoulUnitCounts { get; set; }
    
        public virtual AccountType AccountType { get; set; }
        public virtual BuildingType BuildingType { get; set; }
        public virtual Density Density { get; set; }
        public virtual RegionalPrices RegionalPrices { get; set; }
        public virtual TypeStructuresMaterials TypeStructuresMaterials { get; set; }
    }
}
