//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MeetingVoteArticle77
    {
        public long Id { get; set; }
        public bool IsDelete { get; set; }
        public long MeetingNumber { get; set; }
        public System.DateTime StartDateTime { get; set; }
        public Nullable<System.DateTime> EndDateTime { get; set; }
        public Nullable<long> JudicialExpertId { get; set; }
        public Nullable<long> MinistryExpertId { get; set; }
        public Nullable<long> CityCouncilExpertId { get; set; }
        public Nullable<byte> MeetingType { get; set; }
        public string CityCouncilExpert { get; set; }
        public string MinistryExpert { get; set; }
        public string JudicialExpert { get; set; }
    
        public virtual ExpertsOfArticle77 ExpertsOfArticle77 { get; set; }
        public virtual ExpertsOfArticle77 ExpertsOfArticle771 { get; set; }
        public virtual ExpertsOfArticle77 ExpertsOfArticle772 { get; set; }
    }
}
