//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Melk
    {
        public decimal shop { get; set; }
        public decimal radif { get; set; }
        public Nullable<int> c_mahal { get; set; }
        public string mahal { get; set; }
        public Nullable<int> c_meydan { get; set; }
        public string meydan { get; set; }
        public Nullable<int> c_pasaj { get; set; }
        public string pasaj { get; set; }
        public Nullable<int> c_khiaban { get; set; }
        public string khiaban { get; set; }
        public Nullable<int> c_bazar { get; set; }
        public string bazar { get; set; }
        public Nullable<int> c_bonbast { get; set; }
        public string bonbast { get; set; }
        public Nullable<int> c_kooche { get; set; }
        public string kooche { get; set; }
        public string pelakabi { get; set; }
        public string codeposti { get; set; }
        public string tel { get; set; }
        public string address { get; set; }
        public string tozihkroki { get; set; }
        public Nullable<double> masahat_s { get; set; }
        public Nullable<double> masahat_m { get; set; }
        public Nullable<double> masahat_e { get; set; }
        public Nullable<double> masahat_b { get; set; }
        public Nullable<int> c_vazsanad { get; set; }
        public string vazsanad { get; set; }
        public Nullable<int> c_noesanad { get; set; }
        public string noesanad { get; set; }
        public string sho_madar { get; set; }
        public string sabti { get; set; }
        public Nullable<int> c_vazmelk { get; set; }
        public string vazmelk { get; set; }
        public Nullable<int> c_noemalekiat { get; set; }
        public string noemalekiat { get; set; }
        public Nullable<int> c_noestakhr { get; set; }
        public string noestakhr { get; set; }
        public Nullable<int> c_mEstakhr { get; set; }
        public string mEstakhr { get; set; }
        public Nullable<double> masahatstakhr { get; set; }
        public Nullable<int> c_hEstakhr { get; set; }
        public string hEstakhr { get; set; }
        public Nullable<double> hajmestakhr { get; set; }
        public Nullable<int> c_noegolkhaneh { get; set; }
        public string noegolkhaneh { get; set; }
        public Nullable<int> tedadchah { get; set; }
        public Nullable<int> c_noechah { get; set; }
        public string noechah { get; set; }
        public string mamar { get; set; }
        public Nullable<double> tooldivar { get; set; }
        public string manteghhe_g { get; set; }
        public string hozeh_g { get; set; }
        public string blok_g { get; set; }
        public string shomelk_g { get; set; }
        public string sakhteman_g { get; set; }
        public string apar_g { get; set; }
        public string senfi_g { get; set; }
        public string shosanad_a { get; set; }
        public string shosanad_b { get; set; }
        public string shoghate { get; set; }
        public Nullable<int> c_mogheyat { get; set; }
        public string mogheyat { get; set; }
        public Nullable<int> c_mahdodeh { get; set; }
        public string mahdodeh { get; set; }
        public Nullable<int> c_vazkhas { get; set; }
        public string vazkhas { get; set; }
        public Nullable<int> c_noemelk { get; set; }
        public string noemelk { get; set; }
        public Nullable<int> c_marhaleh { get; set; }
        public string marhaleh { get; set; }
        public Nullable<int> c_noehesar { get; set; }
        public string noehesar { get; set; }
        public Nullable<long> jamiyat { get; set; }
        public Nullable<int> c_marja { get; set; }
        public string marja { get; set; }
        public string molahezeh_k { get; set; }
        public string tozih { get; set; }
        public Nullable<long> sh_Darkhast { get; set; }
        public string tafkiki { get; set; }
        public string azFari { get; set; }
        public string fari { get; set; }
        public string asli { get; set; }
        public string bakhsh { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<double> ArzeshArse { get; set; }
        public Nullable<int> c_masahatgolkhane { get; set; }
        public string masahatgolkhane { get; set; }
        public Nullable<double> mgolkhane { get; set; }
        public string ShoPArchive { get; set; }
        public Nullable<bool> Mojaz_Payankar { get; set; }
        public Nullable<int> Ghabli { get; set; }
        public string Resident { get; set; }
        public Nullable<int> c_Resident { get; set; }
        public string Sal { get; set; }
        public Nullable<bool> IsParvandehMadar { get; set; }
        public string properties { get; set; }
        public Nullable<bool> Separation { get; set; }
        public string OghafiContractNo { get; set; }
        public Nullable<int> OghafiContractDate { get; set; }
        public Nullable<double> masahat_Oghafi { get; set; }
        public Nullable<int> c_SpecialCases { get; set; }
        public string SpecialCases { get; set; }
        public Nullable<decimal> DateSabt { get; set; }
        public Nullable<bool> Ras_NonAssistance { get; set; }
        public Nullable<int> C_karbariAsli { get; set; }
        public string karbariAsli { get; set; }
        public Nullable<double> utmx { get; set; }
        public Nullable<double> utmy { get; set; }
        public Nullable<long> IdSurvey { get; set; }
        public Nullable<bool> ChangeByMomayezi { get; set; }
        public Nullable<bool> NonCooperation { get; set; }
        public Nullable<bool> Assumption { get; set; }
        public Nullable<bool> Nothing { get; set; }
        public Nullable<int> c_DensityArea { get; set; }
        public string DensityArea { get; set; }
        public Nullable<decimal> AppraisedPrice { get; set; }
        public Nullable<decimal> ExistingAccess { get; set; }
        public Nullable<decimal> PreConversionPrice { get; set; }
        public Nullable<decimal> PreSubdivisionArea { get; set; }
    }
}
