//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MLogSms
    {
        public MLogSms()
        {
            this.LogSMS = new HashSet<LogSMS>();
        }
    
        public long Id { get; set; }
        public string Title { get; set; }
        public int Status { get; set; }
    
        public virtual ICollection<LogSMS> LogSMS { get; set; }
    }
}
