//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mokatebat
    {
        public int shop { get; set; }
        public int shod { get; set; }
        public int id { get; set; }
        public Nullable<int> c_noeNameh { get; set; }
        public string noeNameh { get; set; }
        public string shoNameh { get; set; }
        public Nullable<int> tarikhNameh { get; set; }
        public string Tozihat { get; set; }
        public string shoSabtDabir { get; set; }
        public Nullable<int> tarikhSabtDabir { get; set; }
        public string onvanNameh { get; set; }
        public string kholaseNameh { get; set; }
        public string marjaSodorNameh { get; set; }
    }
}
