//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NosaziAllocateFormula
    {
        public long Id { get; set; }
        public long Shop { get; set; }
        public int YearFormula { get; set; }
        public int CodeFormula { get; set; }
        public string CaptionFormula { get; set; }
        public Nullable<decimal> d_radif { get; set; }
        public Nullable<decimal> IdDetailTable { get; set; }
        public string mtable_name { get; set; }
        public string DetailTableName { get; set; }
    }
}
