//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nosazi_Factors
    {
        public long Id { get; set; }
        public long RadifAvarez { get; set; }
        public decimal Shop { get; set; }
        public int IdMalek { get; set; }
        public decimal Sal { get; set; }
        public Nullable<decimal> CodeParamFormula { get; set; }
        public Nullable<decimal> CodeFormula { get; set; }
        public string TitleFormula { get; set; }
        public string FormulaField { get; set; }
        public string FormulaFarsi { get; set; }
        public Nullable<double> Meghdar { get; set; }
        public string DescMeghdar { get; set; }
    }
}
