//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParaTarefe_Zarib
    {
        public int codeAsli { get; set; }
        public int codeFari { get; set; }
        public int id { get; set; }
        public int sal { get; set; }
        public Nullable<double> t1 { get; set; }
        public Nullable<double> t2 { get; set; }
        public Nullable<int> typePara { get; set; }
    }
}
