//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParametricAccCoding
    {
        public long ID { get; set; }
        public Nullable<int> kodasli { get; set; }
        public Nullable<int> kodfarei { get; set; }
        public Nullable<int> YearAcc { get; set; }
        public string IAFAccCoingPath { get; set; }
        public string IAFAccCodingTitlePath { get; set; }
        public Nullable<int> PareshId { get; set; }
        public Nullable<int> PareshOrgId { get; set; }
    }
}
