//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parvandeh
    {
        public Parvandeh()
        {
            this.LevelJob = new HashSet<LevelJob>();
        }
    
        public double shop { get; set; }
        public Nullable<decimal> mantaghe { get; set; }
        public Nullable<decimal> hoze { get; set; }
        public Nullable<decimal> blok { get; set; }
        public Nullable<decimal> shomelk { get; set; }
        public Nullable<decimal> sakhteman { get; set; }
        public Nullable<decimal> apar { get; set; }
        public Nullable<decimal> senfi { get; set; }
        public Nullable<int> idparent { get; set; }
        public Nullable<int> code_tree { get; set; }
        public Nullable<bool> sws { get; set; }
        public Nullable<int> Formol { get; set; }
        public string e_code { get; set; }
        public string ghabli { get; set; }
        public string codeN { get; set; }
        public bool locked { get; set; }
        public Nullable<int> AreaId { get; set; }
        public long Id { get; set; }
        public string AssetBlock { get; set; }
        public bool Destructed { get; set; }
        public bool IsTajmi { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<LevelJob> LevelJob { get; set; }
    }
}
