//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class parvaneh
    {
        public long shop { get; set; }
        public long shodarkhast { get; set; }
        public string sho_parvaneh { get; set; }
        public Nullable<int> c_noeParvaneh { get; set; }
        public string noe_parvaneh { get; set; }
        public Nullable<int> tarikh_parvaneh { get; set; }
        public string serial_parvaneh { get; set; }
        public Nullable<int> c_noeMalekiat { get; set; }
        public string noe_malekiat { get; set; }
        public string noe_e_m_zamin { get; set; }
        public Nullable<double> masahat_m_s_tarakom { get; set; }
        public Nullable<double> masahat_m_esh_zamin { get; set; }
        public Nullable<bool> isChekList { get; set; }
        public Nullable<int> c_group_s { get; set; }
        public string group_s { get; set; }
        public Nullable<int> tedad_derakht { get; set; }
        public string tarikh_end_amaliat_s { get; set; }
        public string sho_bimenameh { get; set; }
        public Nullable<int> tarikh_e_bimeh { get; set; }
        public string shoFish { get; set; }
        public string avarez_Zirbana { get; set; }
        public string avarez_pazireh { get; set; }
        public string bime_kargaran { get; set; }
        public string tozihat_parvaneh { get; set; }
        public string shoFishTree { get; set; }
        public Nullable<bool> HasKasriParking { get; set; }
        public string NoedarkhastParvaneh { get; set; }
        public Nullable<int> TarikheSodoreBimeName { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    }
}
