//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payankar
    {
        public decimal Shop { get; set; }
        public string Sh_Darkhast { get; set; }
        public string Sh_Payankar { get; set; }
        public string ser_Payankar { get; set; }
        public Nullable<int> Tarikh_Payankar { get; set; }
        public string Tozihat { get; set; }
        public Nullable<int> user_code { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<bool> flag { get; set; }
        public string TozihNazer { get; set; }
        public Nullable<bool> HasKasriParking { get; set; }
        public string sho_bimenameh { get; set; }
        public Nullable<int> tarikh_e_bimeh { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    }
}
