//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pishnevis
    {
        public int Shop { get; set; }
        public int Shod { get; set; }
        public int Id { get; set; }
        public Nullable<int> Komission_Code { get; set; }
        public string Komission_Text { get; set; }
        public string pishnevis_Num { get; set; }
        public Nullable<int> Pishnevis_Date { get; set; }
        public string Pishnevis_Desc { get; set; }
        public Nullable<int> UserCode { get; set; }
        public string UserNameFamily { get; set; }
        public string Year { get; set; }
        public Nullable<int> Komission_Date { get; set; }
        public string Kommission_Time { get; set; }
        public string SessionNumber { get; set; }
    }
}
