//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class posht_formol
    {
        public decimal detailcode_para { get; set; }
        public decimal detailcode_formol { get; set; }
        public decimal code { get; set; }
        public string saal { get; set; }
        public string formolfarsi { get; set; }
        public string formolfield { get; set; }
        public string jadval { get; set; }
        public string FlgPF { get; set; }
        public Nullable<bool> Sign { get; set; }
    }
}
