//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PosInfo
    {
        public long Id { get; set; }
        public byte PosType { get; set; }
        public string Title { get; set; }
        public string IpAddress { get; set; }
        public string SerialNumber { get; set; }
        public string AcceptorId { get; set; }
        public string TerminalId { get; set; }
        public Nullable<int> Port { get; set; }
        public byte CompanyPosType { get; set; }
    }
}
