//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PositionRank
    {
        public PositionRank()
        {
            this.Dv_ListShoghl = new HashSet<Dv_ListShoghl>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public decimal Coefficient { get; set; }
    
        public virtual ICollection<Dv_ListShoghl> Dv_ListShoghl { get; set; }
    }
}
