//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RealEstateExpert
    {
        public long Id { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<long> MembershipNumber { get; set; }
        public string NationalCode { get; set; }
        public string Mobile { get; set; }
        public string Tell { get; set; }
    }
}
