//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegionalPrices
    {
        public RegionalPrices()
        {
            this.masahat_khalaf = new HashSet<masahat_khalaf>();
            this.RegionalPricesDetail = new HashSet<RegionalPricesDetail>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public Nullable<decimal> FromValue { get; set; }
        public Nullable<decimal> ToValue { get; set; }
    
        public virtual ICollection<masahat_khalaf> masahat_khalaf { get; set; }
        public virtual ICollection<RegionalPricesDetail> RegionalPricesDetail { get; set; }
    }
}
