//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegionalPrice_Temp
    {
        public int Id { get; set; }
        public string RenovationCode { get; set; }
        public string CommercialRegionalPrice { get; set; }
        public string AdministrativeRegionalPrice { get; set; }
        public string ResidentialRegionalPrice { get; set; }
    }
}
