//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RenovationCoefficientArea
    {
        public int Id { get; set; }
        public int YearId { get; set; }
        public int CodeSecondaryUseType { get; set; }
        public string SecondaryUseType { get; set; }
        public decimal Coefficient { get; set; }
    
        public virtual YearCoefficientRenovation YearCoefficientRenovation { get; set; }
    }
}
