//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rental
    {
        public Rental()
        {
            this.Reconciliators = new HashSet<Reconciliators>();
            this.Reconciliators1 = new HashSet<Reconciliators>();
        }
    
        public int Id { get; set; }
        public Nullable<int> ContractNum { get; set; }
        public Nullable<System.DateTime> ContractDate { get; set; }
        public Nullable<int> ContractType { get; set; }
        public Nullable<int> ContractStatus { get; set; }
        public Nullable<decimal> MortgagePrice { get; set; }
        public Nullable<decimal> RentPrice { get; set; }
        public string Address { get; set; }
        public Nullable<int> RentItem { get; set; }
        public Nullable<int> ExploitationType { get; set; }
        public Nullable<System.DateTime> ContractStartDate { get; set; }
        public Nullable<System.DateTime> ContractEndDate { get; set; }
        public string Description { get; set; }
        public string Shod { get; set; }
        public string Shop { get; set; }
        public bool IsDelete { get; set; }
    
        public virtual ICollection<Reconciliators> Reconciliators { get; set; }
        public virtual ICollection<Reconciliators> Reconciliators1 { get; set; }
    }
}
