//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RepBedTafzili
    {
        public Nullable<decimal> radif { get; set; }
        public Nullable<decimal> id { get; set; }
        public string name { get; set; }
        public string family { get; set; }
        public string NameFamily { get; set; }
        public string kodemeli { get; set; }
        public string father { get; set; }
        public string address { get; set; }
        public string codeposti { get; set; }
        public Nullable<bool> Active { get; set; }
        public string tafkiki { get; set; }
        public string azFari { get; set; }
        public string fari { get; set; }
        public string asli { get; set; }
        public string bakhsh { get; set; }
        public string sabti { get; set; }
        public Nullable<decimal> mantaghe { get; set; }
        public Nullable<decimal> hoze { get; set; }
        public Nullable<decimal> blok { get; set; }
        public Nullable<decimal> shomelk { get; set; }
        public Nullable<decimal> sakhteman { get; set; }
        public Nullable<decimal> apar { get; set; }
        public Nullable<decimal> senfi { get; set; }
        public string codeN { get; set; }
        public Nullable<double> AvalDoreh { get; set; }
        public string pelakabi { get; set; }
        public Nullable<bool> sws { get; set; }
        public string mob { get; set; }
        public string manteghhe_g { get; set; }
        public string hozeh_g { get; set; }
        public string blok_g { get; set; }
        public string shomelk_g { get; set; }
        public string sakhteman_g { get; set; }
        public string apar_g { get; set; }
        public string senfi_g { get; set; }
        public string e_code { get; set; }
        public Nullable<int> M_ID { get; set; }
        public string ShMadar { get; set; }
        public decimal jambed { get; set; }
        public decimal jambes { get; set; }
        public Nullable<decimal> jam { get; set; }
        public Nullable<decimal> jam_2 { get; set; }
        public decimal tasal { get; set; }
        public decimal assal { get; set; }
        public Nullable<double> shop { get; set; }
        public string CodeNg { get; set; }
        public Nullable<decimal> KhadamatBed { get; set; }
        public Nullable<decimal> KhadamatBes { get; set; }
        public Nullable<decimal> jamKhadamat { get; set; }
        public Nullable<decimal> jamAvarez { get; set; }
    }
}
