//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RercordsManagementCategory
    {
        public int Id { get; set; }
        public bool IsDelete { get; set; }
        public string Parametric { get; set; }
        public Nullable<int> ParametricId { get; set; }
        public Nullable<bool> IsMelk { get; set; }
        public Nullable<bool> IsSakhteman { get; set; }
        public Nullable<bool> IsAparteman { get; set; }
        public Nullable<bool> IsSenfi { get; set; }
    }
}
