//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RulesOfRegressAndOpening
    {
        public long Id { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<int> C_Direction { get; set; }
        public string Direction { get; set; }
        public Nullable<decimal> Regress { get; set; }
        public Nullable<bool> IsLightCatcher { get; set; }
        public Nullable<bool> IsOpenings { get; set; }
        public string Description { get; set; }
        public Nullable<long> Shop { get; set; }
        public Nullable<long> Shod { get; set; }
        public string TableName { get; set; }
        public string Openings { get; set; }
        public Nullable<int> C_Openings { get; set; }
        public Nullable<bool> IsLegal { get; set; }
    }
}
