//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RulesDetail
    {
        public long CodeRules { get; set; }
        public long ID { get; set; }
        public Nullable<long> CodeStaticParameter { get; set; }
        public Nullable<long> CodeRuleInFormul { get; set; }
        public Nullable<int> CodeSabetha { get; set; }
        public string CaptionRuleDetail { get; set; }
    }
}
