//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rules
    {
        public long CodeRules { get; set; }
        public int CodeTarh { get; set; }
        public int CodeTitleRules { get; set; }
        public string FormulaRules { get; set; }
        public string FarsiFormulaRules { get; set; }
        public string UnitRules { get; set; }
        public string DescRules { get; set; }
        public double CodeUserInsert { get; set; }
        public System.DateTime DateTimeInsert { get; set; }
    }
}
