//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sabetha
    {
        public long adder { get; set; }
        public int kodasli { get; set; }
        public int kodfarei { get; set; }
        public int kodfarei2 { get; set; }
        public string sharh { get; set; }
        public Nullable<double> baha1 { get; set; }
        public Nullable<double> baha2 { get; set; }
        public Nullable<bool> FlgP { get; set; }
        public Nullable<double> HadaghalMablagh { get; set; }
        public Nullable<double> HadaksarMablagh { get; set; }
    }
}
