//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sakhteman
    {
        public decimal shop { get; set; }
        public decimal radif { get; set; }
        public Nullable<double> masahatkol { get; set; }
        public Nullable<double> masahatnorgir { get; set; }
        public Nullable<double> masahatnama { get; set; }
        public Nullable<int> c_noenama { get; set; }
        public string noenama { get; set; }
        public Nullable<int> c_noesaghf { get; set; }
        public string noesaghf { get; set; }
        public Nullable<double> tarakom { get; set; }
        public Nullable<double> satheshghal { get; set; }
        public Nullable<int> c_mahalvogho { get; set; }
        public string mahalvogho { get; set; }
        public Nullable<int> c_olgo { get; set; }
        public string olgo { get; set; }
        public Nullable<int> c_marhaleh { get; set; }
        public string marhaleh { get; set; }
        public Nullable<double> ertefa_bala { get; set; }
        public Nullable<double> ertefa_pain { get; set; }
        public Nullable<double> ertefa_korsi { get; set; }
        public Nullable<double> ertefa_end { get; set; }
        public Nullable<double> janpanah { get; set; }
        public Nullable<int> tarikhshoro { get; set; }
        public Nullable<int> tarikhanjam { get; set; }
        public Nullable<int> ghedmat_a { get; set; }
        public Nullable<int> ghedmat_b { get; set; }
        public Nullable<int> c_vaziyattarikhi { get; set; }
        public string vaziyattarikhi { get; set; }
        public Nullable<int> c_estehkam { get; set; }
        public string estehkam { get; set; }
        public Nullable<int> c_bahrebardar { get; set; }
        public string bahrebardar { get; set; }
        public Nullable<double> t_parking_m { get; set; }
        public Nullable<double> t_parking_t { get; set; }
        public Nullable<double> kasrparking { get; set; }
        public Nullable<double> arz_dahaneh { get; set; }
        public Nullable<double> omgh_harim { get; set; }
        public Nullable<double> ramp { get; set; }
        public string tozihatkoli { get; set; }
        public Nullable<long> sh_Darkhast { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<int> c_NoeSakhteman { get; set; }
        public string NoeSaze { get; set; }
        public Nullable<int> c_NoeSaze { get; set; }
        public Nullable<int> TarikhEhdas { get; set; }
        public Nullable<double> ArzeshAyan { get; set; }
        public string NoeSakhteman { get; set; }
        public Nullable<bool> Mojaz_Payankar { get; set; }
        public Nullable<double> TedadTabaghe { get; set; }
        public Nullable<double> MasahatZirbana { get; set; }
        public string CheckProperties { get; set; }
        public Nullable<double> MasahatArse { get; set; }
        public Nullable<int> c_noemelk { get; set; }
        public string noemelk { get; set; }
        public Nullable<int> c_FazayeSabz { get; set; }
        public string FazayeSabz { get; set; }
        public Nullable<bool> IsYardParking { get; set; }
        public Nullable<double> YardArea { get; set; }
        public Nullable<decimal> DateSabt { get; set; }
        public Nullable<double> t_parking_kh { get; set; }
        public string manteghhe_g { get; set; }
        public string hozeh_g { get; set; }
        public string blok_g { get; set; }
        public string shomelk_g { get; set; }
        public string sakhteman_g { get; set; }
        public string apar_g { get; set; }
        public string senfi_g { get; set; }
        public Nullable<long> IdSurvey { get; set; }
        public Nullable<bool> ChangeByMomayezi { get; set; }
        public Nullable<bool> Shading { get; set; }
        public Nullable<bool> Overlooking { get; set; }
        public string ElevatorContractor { get; set; }
        public Nullable<int> c_group_s { get; set; }
        public string group_s { get; set; }
        public Nullable<double> GroundFloors { get; set; }
    }
}
