//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Senfi
    {
        public decimal shop { get; set; }
        public decimal radif { get; set; }
        public Nullable<int> c_mahal { get; set; }
        public string mahal { get; set; }
        public Nullable<int> c_meydan { get; set; }
        public string meydan { get; set; }
        public Nullable<int> c_pasaj { get; set; }
        public string pasaj { get; set; }
        public Nullable<int> c_khiaban { get; set; }
        public string khiaban { get; set; }
        public Nullable<int> c_bazar { get; set; }
        public string bazar { get; set; }
        public Nullable<int> c_bonbast { get; set; }
        public string bonbast { get; set; }
        public Nullable<int> c_kooche { get; set; }
        public string kooche { get; set; }
        public string pelakabi { get; set; }
        public string codeposti { get; set; }
        public string tel { get; set; }
        public string address { get; set; }
        public string manteghhe_g { get; set; }
        public string hozeh_g { get; set; }
        public string blok_g { get; set; }
        public string shomelk_g { get; set; }
        public string sakhteman_g { get; set; }
        public string apar_g { get; set; }
        public string senfi_g { get; set; }
        public Nullable<double> masahatkol { get; set; }
        public Nullable<double> masahatArse { get; set; }
        public Nullable<double> masahatTejari { get; set; }
        public Nullable<int> c_m_Zamin { get; set; }
        public string m_Zamin { get; set; }
        public Nullable<int> c_m_Tejari { get; set; }
        public string m_Tejari { get; set; }
        public Nullable<int> Tarikh_Tasis { get; set; }
        public Nullable<int> c_Mahal_Esteghrar { get; set; }
        public string Mahal_Esteghrar { get; set; }
        public string ShoMadar { get; set; }
        public Nullable<int> Tedad_Darband { get; set; }
        public Nullable<double> Ertefa_Mofid { get; set; }
        public string Tozihat { get; set; }
        public Nullable<long> sh_Darkhast { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<double> ArzeshAyan { get; set; }
        public Nullable<bool> Mohasebe_Formol { get; set; }
        public string tafkiki { get; set; }
        public string azFari { get; set; }
        public string fari { get; set; }
        public string asli { get; set; }
        public string bakhsh { get; set; }
        public string sabti { get; set; }
        public Nullable<int> PrePaidYear { get; set; }
        public Nullable<decimal> DateSabt { get; set; }
        public Nullable<long> IdSurvey { get; set; }
        public Nullable<double> MasahatFazayBaz { get; set; }
        public Nullable<int> ZaribMaber { get; set; }
        public Nullable<int> ZaribTabaghat { get; set; }
        public Nullable<bool> Harassment { get; set; }
        public Nullable<int> ShenaseShoghli { get; set; }
        public Nullable<int> Raste { get; set; }
        public Nullable<int> CodeNahveTasarof { get; set; }
        public string OldRenovationCode { get; set; }
    }
}
