//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Setting
    {
        public long Id { get; set; }
        public string BankAccountNumber { get; set; }
        public string BankName { get; set; }
        public string AnnouncementNumber { get; set; }
        public string AnnouncementDate { get; set; }
    }
}
