//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shenase
    {
        public int Serial { get; set; }
        public string saal { get; set; }
        public string shop { get; set; }
        public Nullable<int> RadifMalek { get; set; }
        public Nullable<int> IdMalek { get; set; }
        public string Code_Mostajer { get; set; }
        public Nullable<decimal> Mablagh { get; set; }
        public Nullable<decimal> MabAvarez { get; set; }
        public Nullable<decimal> MabKhadamat { get; set; }
        public Nullable<int> DateSodor { get; set; }
        public string ShGh { get; set; }
        public string ShPr { get; set; }
        public Nullable<bool> Flag { get; set; }
        public string PCName { get; set; }
        public string ShoFish { get; set; }
        public Nullable<byte> BillType { get; set; }
        public Nullable<long> CodeMTaqsit { get; set; }
        public Nullable<int> CodeDTaqsit { get; set; }
    }
}
