//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class signature
    {
        public long Id { get; set; }
        public int shop { get; set; }
        public int shod { get; set; }
        public int reportId { get; set; }
        public int userCode { get; set; }
        public string userFullName { get; set; }
        public byte[] sign { get; set; }
        public Nullable<System.DateTime> signDate { get; set; }
        public Nullable<System.DateTime> returnSignDate { get; set; }
        public string Description { get; set; }
        public bool Active { get; set; }
        public string properties { get; set; }
        public Nullable<int> subUserCode { get; set; }
        public string subUserName { get; set; }
    }
}
