//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SmsAuthorization
    {
        public long Id { get; set; }
        public string MobileNumber { get; set; }
        public System.DateTime DateTime { get; set; }
        public int LogInCode { get; set; }
    }
}
