//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpecialDiscountAmountUsed
    {
        public int Id { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<long> Shop { get; set; }
        public Nullable<long> Shod { get; set; }
        public string NationalCode { get; set; }
        public Nullable<int> CalculationNumber { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<long> DiscountMainCode { get; set; }
        public string Discount { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<bool> UsedStatus { get; set; }
        public Nullable<long> ReceiptNumber { get; set; }
        public Nullable<decimal> UsedArea { get; set; }
        public Nullable<System.DateTime> UsedDate { get; set; }
    }
}
