//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpecialDiscounts
    {
        public int Id { get; set; }
        public string DiscountName { get; set; }
        public Nullable<int> CodeAsli { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<decimal> Area { get; set; }
        public Nullable<byte> Floor { get; set; }
        public Nullable<byte> Unit { get; set; }
    }
}
