//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StaticParameter
    {
        public long CodeCategory { get; set; }
        public long CodeParameter { get; set; }
        public string NameParameter { get; set; }
        public string CaptionParameter { get; set; }
        public string DescParameter { get; set; }
    }
}
