//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SurveyUser
    {
        public long CodeSurvey { get; set; }
        public string NameSurvey { get; set; }
        public string FamilySurvey { get; set; }
        public string UserNameSurvey { get; set; }
        public string PassSurvey { get; set; }
        public string TypeUser { get; set; }
        public int TypeSurvey { get; set; }
        public string NationalCodSurvey { get; set; }
        public string FatherSurvey { get; set; }
        public string BirthDateSurvey { get; set; }
        public string TellSurvey { get; set; }
        public string MobileSurvey { get; set; }
        public string MailSurvey { get; set; }
        public string DeviceIDSurvey { get; set; }
        public bool Hashed { get; set; }
        public bool StatusSurvey { get; set; }
        public string DevicePNSurvey { get; set; }
    }
}
