//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class taAhodat
    {
        public int shop { get; set; }
        public int shod { get; set; }
        public int id { get; set; }
        public Nullable<int> c_noetaAhod { get; set; }
        public string noetaAhod { get; set; }
        public string shotaAhod { get; set; }
        public string shoDaftar { get; set; }
        public string tozihat { get; set; }
    }
}
