//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaeenEmza
    {
        public string TitleReport { get; set; }
        public string NemeFamily1 { get; set; }
        public string Semat1 { get; set; }
        public string NemeFamily2 { get; set; }
        public string Semat2 { get; set; }
        public string NemeFamily3 { get; set; }
        public string Semat3 { get; set; }
        public string NemeFamily4 { get; set; }
        public string Semat4 { get; set; }
        public int ID { get; set; }
        public int AreaId { get; set; }
    }
}
