//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Taghsit_Inform
    {
        public long Radif { get; set; }
        public decimal shop { get; set; }
        public Nullable<int> RadifMalek { get; set; }
        public int IdMalek { get; set; }
        public Nullable<decimal> Kasr_Nosazi { get; set; }
        public Nullable<decimal> Kasr_Khadamat { get; set; }
        public Nullable<decimal> Mande_Nosazi { get; set; }
        public Nullable<decimal> Mande_Khadamat { get; set; }
        public Nullable<decimal> ghestAkhar_Nosazi { get; set; }
        public Nullable<decimal> ghestAkhar_Khadamat { get; set; }
        public Nullable<int> Aghsat_count { get; set; }
        public Nullable<int> Remining_Ghest { get; set; }
        public Nullable<decimal> Mande_Education { get; set; }
        public Nullable<decimal> Mande_Firestation { get; set; }
        public Nullable<decimal> Mande_Tax { get; set; }
        public Nullable<decimal> Kasr_Education { get; set; }
        public Nullable<decimal> Kasr_Firestation { get; set; }
        public Nullable<decimal> Kasr_Tax { get; set; }
        public Nullable<decimal> ghestAkhar_Education { get; set; }
        public Nullable<decimal> ghestAkhar_Firestation { get; set; }
        public Nullable<decimal> ghestAkhar_Tax { get; set; }
    }
}
