//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TakhfifAsnaf
    {
        public long id { get; set; }
        public int shop { get; set; }
        public int IdMalek { get; set; }
        public int radifMalek { get; set; }
        public Nullable<int> sal { get; set; }
        public int kodeasli { get; set; }
        public int c_Takkhfif { get; set; }
        public string strTakhfif { get; set; }
        public Nullable<decimal> mablaghTakhfif { get; set; }
        public string sharh { get; set; }
        public int userCode { get; set; }
        public string userFullName { get; set; }
        public Nullable<System.DateTime> takhfifDate { get; set; }
    }
}
