//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Takhsis
    {
        public long radif { get; set; }
        public Nullable<int> d_code { get; set; }
        public string code_sakhtar { get; set; }
        public string d_sakhtar { get; set; }
        public string d_name { get; set; }
        public string d_family { get; set; }
        public Nullable<bool> d_entekhab { get; set; }
        public Nullable<bool> d_modir { get; set; }
        public Nullable<bool> d_faal { get; set; }
        public string d_user_code { get; set; }
        public Nullable<int> d_kod_karbar { get; set; }
        public Nullable<bool> tik_kol { get; set; }
    }
}
