//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDeviceDirectPrint
    {
        public int ID { get; set; }
        public string DeviceIP { get; set; }
        public string DeviceUser { get; set; }
        public string ImageAddress { get; set; }
        public bool FilePrinted { get; set; }
        public System.DateTime DateInsert { get; set; }
    }
}
