//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TemplateControl
    {
        public int Id { get; set; }
        public string Pattern { get; set; }
        public Nullable<int> PatternType { get; set; }
        public int Counter { get; set; }
        public bool IsDelete { get; set; }
        public string WaitingNumbers { get; set; }
        public Nullable<byte> AreaId { get; set; }
        public Nullable<int> TotalParvaneh { get; set; }
        public Nullable<int> Year { get; set; }
        public string Area { get; set; }
        public Nullable<int> NoeDarkhastId { get; set; }
        public string NoeDarkhast { get; set; }
    }
}
