//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class temp
    {
        public decimal shop { get; set; }
        public decimal radif { get; set; }
        public Nullable<int> c_mahal { get; set; }
        public string mahal { get; set; }
        public Nullable<int> c_meydan { get; set; }
        public string meydan { get; set; }
        public Nullable<int> c_pasaj { get; set; }
        public string pasaj { get; set; }
        public Nullable<int> c_khiaban { get; set; }
        public string khiaban { get; set; }
        public Nullable<int> c_bazar { get; set; }
        public string bazar { get; set; }
        public Nullable<int> c_bonbast { get; set; }
        public string bonbast { get; set; }
        public Nullable<int> c_kooche { get; set; }
        public string kooche { get; set; }
        public string pelakabi { get; set; }
        public string codeposti { get; set; }
        public string tel { get; set; }
        public string address { get; set; }
        public string manteghhe_g { get; set; }
        public string hozeh_g { get; set; }
        public string blok_g { get; set; }
        public string shomelk_g { get; set; }
        public string sakhteman_g { get; set; }
        public string apar_g { get; set; }
        public string senfi_g { get; set; }
        public Nullable<int> c_noesanad { get; set; }
        public string noesanad { get; set; }
        public Nullable<int> c_vazsanad { get; set; }
        public string vazsanad { get; set; }
        public Nullable<int> c_noemalekiyat { get; set; }
        public string noemalekiyat { get; set; }
        public Nullable<double> masahat1 { get; set; }
        public Nullable<double> masahat2 { get; set; }
        public Nullable<double> masahat3 { get; set; }
        public string sabti { get; set; }
        public Nullable<double> masahat4 { get; set; }
        public Nullable<int> c_noenama { get; set; }
        public string noenama { get; set; }
        public Nullable<int> jamiyat { get; set; }
        public Nullable<int> tedaddarb { get; set; }
        public Nullable<double> arzdahaneh { get; set; }
        public Nullable<int> c_bahrebardar { get; set; }
        public string bahrebardar { get; set; }
        public string tozihat { get; set; }
        public Nullable<int> Vahed { get; set; }
        public Nullable<int> Tabagheh { get; set; }
        public string jahat { get; set; }
        public Nullable<double> MasahatNama { get; set; }
        public string ShMadar { get; set; }
        public string manteghhe_g1 { get; set; }
        public string hozeh_g1 { get; set; }
        public string blok_g1 { get; set; }
        public string shomelk_g1 { get; set; }
        public string sakhteman_g1 { get; set; }
        public string apar_g1 { get; set; }
        public string senfi_g1 { get; set; }
        public Nullable<double> MasahatKol { get; set; }
        public Nullable<double> MasahatMoshtarak { get; set; }
        public Nullable<double> MasahatArse { get; set; }
        public Nullable<long> sh_Darkhast { get; set; }
        public string tafkiki { get; set; }
        public string azFari { get; set; }
        public string fari { get; set; }
        public string asli { get; set; }
        public string bakhsh { get; set; }
        public Nullable<bool> Active { get; set; }
        public string NoeSakhteman { get; set; }
        public Nullable<int> c_NoeSakhteman { get; set; }
        public string NoeSaze { get; set; }
        public Nullable<int> c_NoeSaze { get; set; }
        public Nullable<int> TarikhEhdas { get; set; }
        public Nullable<int> c_noesaghf { get; set; }
        public string noesaghf { get; set; }
        public Nullable<double> ArzeshAyan { get; set; }
    }
}
