//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tozihat
    {
        public int UserCode { get; set; }
        public int Code { get; set; }
        public string Onvan { get; set; }
        public string Matn { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<int> Marhaleh { get; set; }
        public Nullable<int> AreaId { get; set; }
    }
}
