//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrafficMaster
    {
        public TrafficMaster()
        {
            this.TrafficDetail = new HashSet<TrafficDetail>();
        }
    
        public int Id { get; set; }
        public int FolderId { get; set; }
        public Nullable<int> RequestNumber { get; set; }
        public string Caption { get; set; }
        public int TotalAmount { get; set; }
        public int Year { get; set; }
        public Nullable<int> ReceiptNumber { get; set; }
    
        public virtual Daramad_MFish Daramad_MFish { get; set; }
        public virtual ICollection<TrafficDetail> TrafficDetail { get; set; }
    }
}
