//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Traffic
    {
        public Traffic()
        {
            this.D_Traffic = new HashSet<D_Traffic>();
        }
    
        public int shop { get; set; }
        public int shod { get; set; }
        public Nullable<double> masahat { get; set; }
        public Nullable<double> takhfif { get; set; }
        public Nullable<long> mablagh { get; set; }
        public string c_car { get; set; }
        public string car { get; set; }
        public string pelak_car { get; set; }
        public Nullable<int> FishNo { get; set; }
        public Nullable<int> sal { get; set; }
        public Nullable<int> FishDate { get; set; }
        public Nullable<int> userCode { get; set; }
        public string description { get; set; }
        public Nullable<System.DateTime> systemDate { get; set; }
    
        public virtual ICollection<D_Traffic> D_Traffic { get; set; }
    }
}
