//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserPaymentInfo
    {
        public long Id { get; set; }
        public string BillingId { get; set; }
        public string PaymentId { get; set; }
        public string AppId { get; set; }
        public string UserId { get; set; }
        public bool IsPay { get; set; }
        public System.DateTime DateInsert { get; set; }
        public string NationalCode { get; set; }
        public string Mobile { get; set; }
        public byte Flag { get; set; }
        public string DeviceIP { get; set; }
        public string DeviceUser { get; set; }
    }
}
