//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserLogined
    {
        public int Id { get; set; }
        public string UserCode { get; set; }
        public string Ip { get; set; }
        public Nullable<System.DateTime> LoginDateTime { get; set; }
        public Nullable<System.DateTime> LogoutDatetime { get; set; }
        public string UserAgent { get; set; }
        public string FullName { get; set; }
        public string UserName { get; set; }
        public bool IsViewer { get; set; }
        public string Hash { get; set; }
        public string Method { get; set; }
        public Nullable<int> tarikh { get; set; }
    }
}
