//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsersLoginRestrictions
    {
        public int Id { get; set; }
        public string FromIP { get; set; }
        public string ToIP { get; set; }
        public Nullable<int> FromPort { get; set; }
        public Nullable<int> ToPort { get; set; }
        public Nullable<System.DateTime> FromDateTime { get; set; }
        public Nullable<System.DateTime> ToDateTime { get; set; }
    }
}
