//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UseTypeSyncTable
    {
        public int Id { get; set; }
        public Nullable<int> PrimaryUseTypeCode { get; set; }
        public string PrimaryUseType { get; set; }
        public Nullable<int> SecondaryUseTypeCode { get; set; }
        public string SecondaryUseType { get; set; }
    }
}
