//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_amlakShahrdari
    {
        public Nullable<int> tarikhMozayedeh { get; set; }
        public Nullable<int> tarikhFishShahrdari { get; set; }
        public Nullable<long> mablaghFishShahrdari { get; set; }
        public int shop { get; set; }
        public string NameFamily { get; set; }
        public string address { get; set; }
        public string codeposti { get; set; }
        public string codeN { get; set; }
        public Nullable<double> MasahatKol { get; set; }
        public Nullable<decimal> mantaghe { get; set; }
        public Nullable<decimal> hoze { get; set; }
        public Nullable<decimal> blok { get; set; }
        public Nullable<decimal> shomelk { get; set; }
        public Nullable<decimal> sakhteman { get; set; }
        public Nullable<decimal> apar { get; set; }
        public Nullable<decimal> senfi { get; set; }
    }
}
