//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_Apartman_Malkin
    {
        public decimal shop { get; set; }
        public decimal radif { get; set; }
        public string name { get; set; }
        public string family { get; set; }
        public decimal id { get; set; }
        public string NameFamily { get; set; }
        public string kodemeli { get; set; }
        public string father { get; set; }
        public string codeposti { get; set; }
        public Nullable<bool> Active { get; set; }
        public string tafkiki { get; set; }
        public string azFari { get; set; }
        public string fari { get; set; }
        public string asli { get; set; }
        public string bakhsh { get; set; }
        public string sabti { get; set; }
        public Nullable<double> AvalDoreh { get; set; }
        public Nullable<long> sh_Darkhast { get; set; }
        public Nullable<double> MasahatKol { get; set; }
        public string pelakabi { get; set; }
        public string mob { get; set; }
        public string address { get; set; }
        public Nullable<bool> Chap_Fish { get; set; }
        public string manteghhe_g { get; set; }
        public string hozeh_g { get; set; }
        public string blok_g { get; set; }
        public string shomelk_g { get; set; }
        public string sakhteman_g { get; set; }
        public string apar_g { get; set; }
        public string senfi_g { get; set; }
        public int M_ID { get; set; }
        public string ShMadar { get; set; }
        public string CodeN_gh { get; set; }
        public string sal { get; set; }
        public string mtable_name { get; set; }
        public Nullable<int> c_noemalek { get; set; }
        public string noemalek { get; set; }
        public Nullable<int> Ras_NonAssistance { get; set; }
        public Nullable<int> c_vazmelk { get; set; }
    }
}
