//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_ArzeshAmlak
    {
        public double ShoP { get; set; }
        public int Sal { get; set; }
        public int CodeJebhe { get; set; }
        public Nullable<double> CodeGhete { get; set; }
        public Nullable<double> CodeBand { get; set; }
        public string Address { get; set; }
        public Nullable<double> Arzesh { get; set; }
        public Nullable<double> MasahatJebhe { get; set; }
        public Nullable<decimal> mantaghe { get; set; }
        public Nullable<decimal> hoze { get; set; }
        public Nullable<decimal> blok { get; set; }
        public Nullable<decimal> shomelk { get; set; }
        public Nullable<decimal> sakhteman { get; set; }
        public Nullable<decimal> apar { get; set; }
        public Nullable<decimal> senfi { get; set; }
        public string codeN { get; set; }
    }
}
