//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_AsnafDaramadFish
    {
        public string Saal { get; set; }
        public string sh_parvande { get; set; }
        public string c_nosazi { get; set; }
        public decimal Serial { get; set; }
        public decimal AvarezSaliyaneBes { get; set; }
        public decimal AvarezSaliyaneBed { get; set; }
        public decimal OpeningBes { get; set; }
        public decimal OpeningBed { get; set; }
        public decimal RelocationBes { get; set; }
        public decimal RelocationBed { get; set; }
        public decimal KhadamatBed { get; set; }
        public decimal KhadamatBes { get; set; }
        public decimal MablaghBed { get; set; }
        public decimal mablaghBes { get; set; }
        public Nullable<int> Datevosol { get; set; }
        public string NameMalek { get; set; }
        public string Mobile { get; set; }
        public string Tel { get; set; }
        public string Neshani { get; set; }
        public Nullable<int> JobCode { get; set; }
        public string JobName { get; set; }
        public decimal AvarezSaliyane { get; set; }
        public decimal Opening { get; set; }
        public decimal Relocation { get; set; }
        public decimal mablagh { get; set; }
        public decimal Khadamat { get; set; }
        public Nullable<int> DateFish { get; set; }
    }
}
