//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_Avarez_Jobs_Formol
    {
        public int Term { get; set; }
        public long ShoP { get; set; }
        public int JobCode { get; set; }
        public Nullable<int> GuildCode { get; set; }
        public string GuildName { get; set; }
        public Nullable<int> FormolCode { get; set; }
        public string FormolTitle { get; set; }
        public string Kod_Daramadi { get; set; }
        public string BodjeName { get; set; }
        public string Formol { get; set; }
        public Nullable<int> FormolTypeCode { get; set; }
        public string FormolTypeName { get; set; }
        public Nullable<decimal> TollAmount { get; set; }
        public Nullable<decimal> OpeningAmount { get; set; }
        public Nullable<decimal> RelocationAmount { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public bool Paid { get; set; }
        public string JobName { get; set; }
        public Nullable<decimal> Cash { get; set; }
        public Nullable<double> Rate { get; set; }
        public int ID { get; set; }
        public Nullable<decimal> PaymentAmount { get; set; }
    }
}
