//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_AvalDoreAsnaf
    {
        public string mtable_name { get; set; }
        public string codeN { get; set; }
        public Nullable<long> AvalDoreAmount { get; set; }
        public Nullable<int> c_Asnaf { get; set; }
        public string Asnaf { get; set; }
        public Nullable<int> Term { get; set; }
        public decimal shop { get; set; }
        public decimal id { get; set; }
        public decimal d_Radif { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
    }
}
