//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_Baygani
    {
        public string ShoD { get; set; }
        public double shop { get; set; }
        public string Elat_Baygani { get; set; }
        public string Tozihat { get; set; }
        public Nullable<int> Date { get; set; }
        public Nullable<int> C_Elat_Baygani { get; set; }
        public int NoeBaygani { get; set; }
        public string noedarkhast { get; set; }
        public string c_nosazi { get; set; }
        public Nullable<int> date_rooz { get; set; }
        public string moteghazi { get; set; }
        public string UserName { get; set; }
        public Nullable<int> UserCode { get; set; }
        public Nullable<bool> flag { get; set; }
        public Nullable<int> c_marhaleh { get; set; }
        public string marhaleh { get; set; }
        public int Id { get; set; }
        public Nullable<long> Erja_Adder { get; set; }
        public Nullable<int> AreaId { get; set; }
    }
}
