//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_DaramadFormulGardeshKar
    {
        public long IDDaramadFormulGardeshKar { get; set; }
        public int CodeGardeshKar { get; set; }
        public string SharhGardeshKar { get; set; }
        public long RadifOnvanFormul { get; set; }
        public string onvan_avarez { get; set; }
        public string OnvanFormulGardeshKar { get; set; }
        public bool EffectOnDaramad_Factor { get; set; }
    }
}
