//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_DaramadFishExport
    {
        public decimal Serial { get; set; }
        public string Saal { get; set; }
        public Nullable<double> sh_Darkhast { get; set; }
        public string sh_mohasebe { get; set; }
        public string NameMalek { get; set; }
        public Nullable<decimal> MablaghBed { get; set; }
        public Nullable<decimal> mablaghBes { get; set; }
        public Nullable<int> DateFish { get; set; }
        public Nullable<int> DateSabt { get; set; }
        public Nullable<int> Datevosol { get; set; }
        public string c_nosazi { get; set; }
        public Nullable<decimal> besCheque { get; set; }
        public Nullable<int> AreaId { get; set; }
        public Nullable<decimal> sumTakhfif { get; set; }
        public Nullable<decimal> MabkolGhablTakhfif { get; set; }
        public Nullable<decimal> sumMeghdar { get; set; }
        public Nullable<bool> InterBankCheque { get; set; }
        public string ShCheck { get; set; }
        public string ShHesab { get; set; }
        public string TrackingNo { get; set; }
        public string DateDaryaftCheque { get; set; }
        public string DateVosolCheque { get; set; }
        public Nullable<decimal> bedCheque { get; set; }
        public Nullable<bool> GuaranteeCheque { get; set; }
        public string NameBank { get; set; }
        public string sharh { get; set; }
        public string IsPaid { get; set; }
    }
}
