//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_Darkhast_Malkin_Daramad
    {
        public double shop { get; set; }
        public string name { get; set; }
        public string family { get; set; }
        public string tel { get; set; }
        public string mob { get; set; }
        public string address { get; set; }
        public long shodarkhast { get; set; }
        public string noedarkhast { get; set; }
        public string Tarikh { get; set; }
        public string c_nosazi { get; set; }
        public int Sh_Mohasebe { get; set; }
    }
}
