//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_Daramad_DTaqsit
    {
        public long Radif { get; set; }
        public long RadifM { get; set; }
        public Nullable<decimal> BedQest { get; set; }
        public Nullable<double> sh_Darkhast { get; set; }
        public string DateQest { get; set; }
        public Nullable<decimal> SerialFishQest { get; set; }
        public string SaalFishQest { get; set; }
        public string DateFish { get; set; }
        public Nullable<decimal> MablaghBed { get; set; }
        public Nullable<decimal> mablaghBes { get; set; }
        public string Datevosol { get; set; }
        public string NoFish { get; set; }
        public Nullable<decimal> BedQestBaKarmozd { get; set; }
    }
}
