//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_Dastresi_groh_user
    {
        public string code { get; set; }
        public string name { get; set; }
        public string codeGroh_Dastresi { get; set; }
        public string username { get; set; }
        public decimal User_code { get; set; }
        public long code_access { get; set; }
    }
}
