//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_DarkhastMarahel
    {
        public decimal Shop { get; set; }
        public long Shod { get; set; }
        public string LevelNo { get; set; }
        public Nullable<int> LevelDate { get; set; }
        public Nullable<int> c_noedarkhast { get; set; }
        public string noedarkhast { get; set; }
        public string c_nosazi { get; set; }
        public string moteghazi { get; set; }
        public Nullable<int> date_rooz { get; set; }
        public string girandeh { get; set; }
        public string girandeh_c { get; set; }
        public int tarikh_erja { get; set; }
        public string saat_erja { get; set; }
        public string marhaleh { get; set; }
        public Nullable<int> c_vaziatErja { get; set; }
        public string vaziatErja { get; set; }
        public int LevelCode { get; set; }
        public double shopMelk { get; set; }
        public Nullable<double> masahat_m { get; set; }
        public Nullable<double> masahat_s { get; set; }
        public string SpecialCases { get; set; }
        public Nullable<int> c_SpecialCases { get; set; }
        public Nullable<int> c_vazmelk { get; set; }
        public string addressMelk { get; set; }
        public Nullable<int> c_mahdodeh { get; set; }
        public string mahdodeh { get; set; }
        public Nullable<double> masahat_k { get; set; }
        public string noe_parvaneh { get; set; }
        public Nullable<int> c_noesazeh { get; set; }
        public string noesazeh { get; set; }
        public string vazmelk { get; set; }
        public string BayganiState { get; set; }
        public string marhalehBaygani { get; set; }
        public Nullable<int> NoeBaygani { get; set; }
        public Nullable<double> masahatKarbari { get; set; }
        public Nullable<int> AreaId { get; set; }
        public string malekAddress { get; set; }
        public string malekName { get; set; }
        public Nullable<decimal> id { get; set; }
        public Nullable<decimal> sumTedadVahedWhitoutParking { get; set; }
        public Nullable<decimal> sumTedadVahed { get; set; }
        public Nullable<int> sumTedadTabaghe { get; set; }
        public Nullable<decimal> mabKol { get; set; }
        public Nullable<decimal> pardakhti { get; set; }
        public Nullable<double> sumMasahatKBazdid { get; set; }
        public Nullable<decimal> sumTedadVahedBazdid { get; set; }
        public Nullable<decimal> mablaghBes { get; set; }
        public Nullable<int> c_marhaleh { get; set; }
        public bool Ebtal { get; set; }
    }
}
