//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_DaramadTaqsitParvande
    {
        public decimal Serial { get; set; }
        public Nullable<int> Saal { get; set; }
        public Nullable<double> sh_Darkhast { get; set; }
        public string NameMalek { get; set; }
        public string Tel { get; set; }
        public string DateFish { get; set; }
        public string NameVariz { get; set; }
        public Nullable<int> KodeBank { get; set; }
        public string NameBank { get; set; }
        public Nullable<int> Datevosol { get; set; }
        public string ShParvande { get; set; }
        public string c_nosazi { get; set; }
        public Nullable<decimal> CashPrice { get; set; }
        public string Sharh { get; set; }
        public Nullable<int> QestCount { get; set; }
        public Nullable<decimal> BedMFish { get; set; }
        public Nullable<decimal> QestAllPrice { get; set; }
        public Nullable<decimal> mantaghe { get; set; }
        public Nullable<decimal> hoze { get; set; }
        public Nullable<decimal> blok { get; set; }
        public Nullable<decimal> shomelk { get; set; }
        public Nullable<decimal> sakhteman { get; set; }
        public Nullable<decimal> apar { get; set; }
        public Nullable<decimal> senfi { get; set; }
        public string DateQest { get; set; }
        public Nullable<int> AreaId { get; set; }
        public Nullable<int> Expr1 { get; set; }
    }
}
