//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_e_p_s
    {
        public decimal shop { get; set; }
        public decimal d_radif { get; set; }
        public string mtable_name { get; set; }
        public string noe { get; set; }
        public string sho_e { get; set; }
        public string tabagheh { get; set; }
        public Nullable<double> masahat { get; set; }
        public Nullable<double> ertefa { get; set; }
        public string noeMojavez { get; set; }
        public string shMojavez { get; set; }
        public Nullable<int> tarikhMojavez { get; set; }
    }
}
