//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_ebtals
    {
        public Nullable<int> sh_darkhast { get; set; }
        public Nullable<int> tarikh_darkhast { get; set; }
        public string noedarkhast { get; set; }
        public string marhaleh { get; set; }
        public string code_nosazi { get; set; }
        public Nullable<double> shop { get; set; }
        public string name_mot { get; set; }
        public int tarikh_erja { get; set; }
        public string ijadkonandeh { get; set; }
        public string ersalkonandeh { get; set; }
        public string girandeh { get; set; }
        public string ellat { get; set; }
        public string tarikh { get; set; }
        public string tozihat { get; set; }
        public string saat_erja { get; set; }
    }
}
