//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_Ekhtar_Mohandesan
    {
        public int ekhtarId { get; set; }
        public string ekhtarType { get; set; }
        public string Description { get; set; }
        public int userId { get; set; }
        public string userName { get; set; }
        public bool Active { get; set; }
        public string name { get; set; }
        public string family { get; set; }
        public string sh_parvaneh { get; set; }
        public string codememari { get; set; }
        public string code_shahrdari { get; set; }
        public string sh_ozviat { get; set; }
        public string noeSalahiat { get; set; }
        public Nullable<int> c_noesalahiat { get; set; }
        public string Mobile { get; set; }
        public System.DateTime ekhtarDate { get; set; }
    }
}
