//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_ElamBazdid_Darkhast
    {
        public double shop { get; set; }
        public long shodarkhast { get; set; }
        public string noedarkhast { get; set; }
        public Nullable<int> c_noedarkhast { get; set; }
        public Nullable<int> Tarikh_Darkhast { get; set; }
        public string c_nosazi { get; set; }
        public Nullable<int> code { get; set; }
        public string Karshenas { get; set; }
        public Nullable<int> Tarikh_Bazdid { get; set; }
        public Nullable<bool> Vaziat { get; set; }
        public bool Ebtal { get; set; }
        public string moteghazi { get; set; }
        public string address { get; set; }
        public string saat { get; set; }
        public long adder { get; set; }
        public string ToTime { get; set; }
        public Nullable<int> AreaId { get; set; }
    }
}
