//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_ExpertsFullInfo
    {
        public int PishnevisId { get; set; }
        public Nullable<long> Made100RayId { get; set; }
        public Nullable<long> Id { get; set; }
        public Nullable<long> MablaghJarime { get; set; }
        public int radifKhalaf { get; set; }
        public int masahatkhalafID { get; set; }
        public long Made100_RayId { get; set; }
        public Nullable<int> Tarikh { get; set; }
        public int RayNo { get; set; }
        public int Raydate { get; set; }
        public Nullable<int> c_Raytype { get; set; }
        public string Raytype { get; set; }
        public int sh_darkhast { get; set; }
        public string Malek { get; set; }
        public string address { get; set; }
        public Nullable<int> KarshenasGhazaeeId { get; set; }
        public Nullable<int> KarshenasVezaratId { get; set; }
        public Nullable<int> KarshenasShoraId { get; set; }
        public int shop { get; set; }
    }
}
