//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_GetDataForMapGIS_Sorkhrud
    {
        public decimal shop { get; set; }
        public Nullable<double> masahat_s { get; set; }
        public string address { get; set; }
        public Nullable<int> c_marhaleh { get; set; }
        public string marhaleh { get; set; }
        public string codeN { get; set; }
        public Nullable<int> c_vazmelk { get; set; }
        public string vazmelk { get; set; }
        public Nullable<int> c_vazsanad { get; set; }
        public string vazsanad { get; set; }
        public Nullable<int> c_noemalekiat { get; set; }
        public string noemalekiat { get; set; }
        public Nullable<int> c_noemelk { get; set; }
        public string noemelk { get; set; }
        public string nameFamily { get; set; }
        public string sho_g { get; set; }
        public string pelakabi { get; set; }
        public string codeposti { get; set; }
        public Nullable<double> masahatKol { get; set; }
        public string tafkiki { get; set; }
        public string fari { get; set; }
        public string azFari { get; set; }
        public string asli { get; set; }
        public string bakhsh { get; set; }
        public Nullable<int> tarikhpayankar { get; set; }
        public string shparvaneh { get; set; }
        public Nullable<int> tarikh_parvaneh { get; set; }
        public string ShoPArchive { get; set; }
        public string shoray { get; set; }
        public string noeray { get; set; }
        public Nullable<int> tarikhray { get; set; }
        public string vaziyat_ejra { get; set; }
    }
}
