//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_GetDataSakhtemanForGIS
    {
        public decimal shop { get; set; }
        public string codeN { get; set; }
        public Nullable<int> c_noenama { get; set; }
        public string noenama { get; set; }
        public Nullable<int> c_NoeSakhteman { get; set; }
        public string NoeSakhteman { get; set; }
        public Nullable<int> c_NoeSaze { get; set; }
        public string NoeSaze { get; set; }
        public Nullable<double> TedadTabaghe { get; set; }
        public Nullable<int> c_noesaghf { get; set; }
        public string noesaghf { get; set; }
        public Nullable<int> c_marhaleh { get; set; }
        public string marhaleh { get; set; }
        public Nullable<decimal> mantaghe { get; set; }
        public Nullable<decimal> hoze { get; set; }
        public Nullable<decimal> blok { get; set; }
        public Nullable<decimal> shomelk { get; set; }
        public Nullable<decimal> sakhteman { get; set; }
        public Nullable<decimal> apar { get; set; }
        public Nullable<decimal> senfi { get; set; }
        public Nullable<decimal> tedadvahedKarbari { get; set; }
        public Nullable<double> masahatkol { get; set; }
    }
}
