//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_gozaresh_made100
    {
        public int shop { get; set; }
        public int shod { get; set; }
        public int PishnevisId { get; set; }
        public Nullable<int> Code_Khalaf { get; set; }
        public string Onvan_Karbari_Asli_Mojod { get; set; }
        public Nullable<int> Code_Karbari_Asli_Mojod { get; set; }
        public string Tabaghe { get; set; }
        public Nullable<int> c_Tabaghe { get; set; }
        public Nullable<int> c_TabsareMade100 { get; set; }
        public string Tabsaremade100 { get; set; }
        public Nullable<long> Made100RayId { get; set; }
        public Nullable<long> Id { get; set; }
        public Nullable<decimal> MabnaMohasebe { get; set; }
        public Nullable<double> Zarib { get; set; }
        public Nullable<long> ArzeshSarghofli { get; set; }
        public Nullable<double> MazadParvaneh { get; set; }
        public Nullable<long> MablaghJarime { get; set; }
        public string Description { get; set; }
        public Nullable<int> UserId { get; set; }
        public string UserName { get; set; }
        public Nullable<System.DateTime> systemDate { get; set; }
        public Nullable<int> c_RayDetailType { get; set; }
        public string RayDetailType { get; set; }
        public Nullable<int> radifKhalaf { get; set; }
        public Nullable<int> masahatkhalafID { get; set; }
        public long Made100_RayId { get; set; }
        public string Onvan_Khalaf { get; set; }
        public Nullable<int> Tarikh { get; set; }
        public string sharh { get; set; }
        public Nullable<decimal> TradingValue { get; set; }
        public Nullable<byte> EnumFoulDefinitionType { get; set; }
        public Nullable<decimal> takhalof { get; set; }
        public int RayNo { get; set; }
        public string EblaghNo { get; set; }
        public Nullable<int> EblaghDate { get; set; }
        public int Raydate { get; set; }
        public Nullable<int> c_Raytype { get; set; }
        public string Raytype { get; set; }
        public Nullable<bool> VoteStstus { get; set; }
        public Nullable<bool> MeetingStatus { get; set; }
        public string moteghazi { get; set; }
        public Nullable<decimal> UnauthorizedHeight { get; set; }
        public Nullable<int> Code_Karbari_Farei_Mojod { get; set; }
        public string Onvan_Karbari_Farei_Mojod { get; set; }
        public Nullable<int> Code_Karbari_Asli_Mojaz { get; set; }
        public string Onvan_Karbari_Asli_Mojaz { get; set; }
        public Nullable<int> Code_Karbari_Farei_Mojaz { get; set; }
        public string Onvan_Karbari_Farei_Mojaz { get; set; }
        public Nullable<int> TypeStructuresMaterialsId { get; set; }
        public Nullable<byte> ZavabetType { get; set; }
        public Nullable<bool> IsIncompleted { get; set; }
        public Nullable<int> AreaId { get; set; }
        public string Komission_Text { get; set; }
        public Nullable<int> Pishnevis_Date { get; set; }
        public string TozihatVasat { get; set; }
        public bool SystemConfirmation { get; set; }
        public string c_nosazi { get; set; }
    }
}
