//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_Groh_Of_Marahel
    {
        public int Marahel_Code { get; set; }
        public Nullable<bool> flag { get; set; }
        public string Groh_Code { get; set; }
        public int Gardeshkar_Code { get; set; }
        public string groupName { get; set; }
        public Nullable<int> AreaId { get; set; }
        public string OrgName { get; set; }
    }
}
