//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_InfoMalekinForMahasebeKoli_Nosazi
    {
        public Nullable<decimal> shop { get; set; }
        public decimal radif { get; set; }
        public decimal id { get; set; }
        public string name { get; set; }
        public string family { get; set; }
        public string NameFamily { get; set; }
        public string kodemeli { get; set; }
        public string father { get; set; }
        public string address { get; set; }
        public string codeposti { get; set; }
        public Nullable<bool> Active { get; set; }
        public string tafkiki { get; set; }
        public string azFari { get; set; }
        public string fari { get; set; }
        public string asli { get; set; }
        public string bakhsh { get; set; }
        public Nullable<decimal> mantaghe { get; set; }
        public Nullable<decimal> hoze { get; set; }
        public Nullable<decimal> blok { get; set; }
        public Nullable<decimal> shomelk { get; set; }
        public Nullable<decimal> sakhteman { get; set; }
        public Nullable<decimal> apar { get; set; }
        public Nullable<decimal> senfi { get; set; }
        public string codeN { get; set; }
        public Nullable<bool> sws { get; set; }
        public int M_ID { get; set; }
        public Nullable<int> Formol { get; set; }
        public Nullable<int> code_tree { get; set; }
        public Nullable<int> idparent { get; set; }
        public string sal { get; set; }
    }
}
