//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_IncomeReceipts
    {
        public decimal Serial { get; set; }
        public string Saal { get; set; }
        public string NameMalek { get; set; }
        public Nullable<int> DateFish { get; set; }
        public Nullable<int> DateSabt { get; set; }
        public Nullable<int> Datevosol { get; set; }
        public string EteAsli { get; set; }
        public string CodeEteAsli { get; set; }
        public string Mobile { get; set; }
        public string NameBank { get; set; }
        public Nullable<int> KodeBank { get; set; }
        public string NameVariz { get; set; }
        public Nullable<decimal> MablaghBed { get; set; }
        public Nullable<decimal> mablaghBes { get; set; }
        public string NoFish { get; set; }
        public string sh_parvande { get; set; }
        public string sh_mohasebe { get; set; }
        public string c_nosazi { get; set; }
        public Nullable<int> AreaId { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public string IncomeCodes { get; set; }
        public string kodemeli { get; set; }
        public string Neshani { get; set; }
        public string sharh { get; set; }
        public string saalha { get; set; }
        public string SanadBank { get; set; }
        public Nullable<double> Fish { get; set; }
        public string Tel { get; set; }
        public Nullable<double> sh_Darkhast { get; set; }
    }
}
