//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_karbariFormulaSetting
    {
        public int id { get; set; }
        public int codeAsli { get; set; }
        public int codeFari { get; set; }
        public int sal { get; set; }
        public string strKarbari_asli { get; set; }
        public string strkarbari_farei { get; set; }
        public Nullable<double> fazaysabzId { get; set; }
        public string strFazaysabz { get; set; }
        public Nullable<double> pasmandId { get; set; }
        public string strPasmand { get; set; }
    }
}
