//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_karshenasan_Made100
    {
        public string FullName { get; set; }
        public string Description { get; set; }
        public Nullable<long> Id { get; set; }
        public string type { get; set; }
        public Nullable<int> c_type { get; set; }
        public string LevelName { get; set; }
        public Nullable<int> LevelID { get; set; }
        public bool StatusKarshenas { get; set; }
        public int kodasli { get; set; }
        public int code_kar { get; set; }
        public Nullable<long> MasterId { get; set; }
    }
}
