//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_Karbaran_Marahel
    {
        public double code { get; set; }
        public string user_n { get; set; }
        public string name { get; set; }
        public string family { get; set; }
        public string Description1 { get; set; }
        public long Groh_Code { get; set; }
        public int Marahel_Code { get; set; }
        public Nullable<bool> flag { get; set; }
    }
}
