//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_Karbaran_Groh_Marahel
    {
        public long Groh_Code { get; set; }
        public int Marahel_Code { get; set; }
        public string user_n { get; set; }
        public double code { get; set; }
        public int Gardeshkar_Code { get; set; }
        public string strOrganizationId { get; set; }
        public string Groh_Name { get; set; }
        public string Name { get; set; }
        public Nullable<int> groupAreaId { get; set; }
        public Nullable<bool> flag { get; set; }
        public string OrgName { get; set; }
    }
}
