//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_KartableM100
    {
        public long Id { get; set; }
        public long shodarkhast { get; set; }
        public double UserCodeSender { get; set; }
        public double UserCodeReceiver { get; set; }
        public string userNameSender { get; set; }
        public string userNameReceiver { get; set; }
        public double shop { get; set; }
        public string moteghazi { get; set; }
        public string c_nosazi { get; set; }
        public string LevelName { get; set; }
        public int LevelID { get; set; }
        public Nullable<int> PishnevisID { get; set; }
        public string address { get; set; }
        public string pelakSabti { get; set; }
        public bool Active { get; set; }
        public System.DateTime SystemDate { get; set; }
        public string noedarkhast { get; set; }
        public Nullable<int> c_noedarkhast { get; set; }
        public Nullable<int> Komission_Code { get; set; }
        public string Komission_Text { get; set; }
        public string pishnevis_Num { get; set; }
        public Nullable<int> Pishnevis_Date { get; set; }
        public string Pishnevis_Desc { get; set; }
        public Nullable<int> Komission_Date { get; set; }
    }
}
