//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_Khalaf_Daramad_Formol
    {
        public long ID { get; set; }
        public double shop { get; set; }
        public string sh_Darkhast { get; set; }
        public int RadifKhalaf { get; set; }
        public long Radif_t_formol_m { get; set; }
        public string onvan_avarez { get; set; }
        public decimal CodeFormol { get; set; }
        public decimal saalFormol { get; set; }
        public string noemohasebeh { get; set; }
        public string DescOnvanFormul { get; set; }
        public string DescKhalaf_Daramad_Formol { get; set; }
    }
}
