//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_ListShoghl
    {
        public decimal Shop { get; set; }
        public decimal d_Radif { get; set; }
        public decimal idShoghli { get; set; }
        public string mtable_name { get; set; }
        public string NameShoghl { get; set; }
        public Nullable<int> c_OnvanShoghl { get; set; }
        public string OnvanShoghl { get; set; }
        public Nullable<int> SalEftetahiye { get; set; }
        public Nullable<int> c_Daraje { get; set; }
        public string Daraje { get; set; }
        public Nullable<int> c_NahveTasarof { get; set; }
        public string NahveTasarof { get; set; }
        public Nullable<int> TabagheVogho { get; set; }
        public Nullable<int> c_NoeMahalKasb { get; set; }
        public string NoeMahalKasb { get; set; }
        public Nullable<int> Tarefe { get; set; }
        public Nullable<int> TedadKarkonan { get; set; }
        public Nullable<int> TarikhShoro { get; set; }
        public Nullable<int> TarikhPayan { get; set; }
        public Nullable<bool> flag { get; set; }
        public Nullable<int> c_Asnaf { get; set; }
        public string Asnaf { get; set; }
        public string address { get; set; }
        public string NameFamily { get; set; }
        public string codeN { get; set; }
        public long JobListId { get; set; }
    }
}
