//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_logMohasebeKoliNosazi
    {
        public long ID { get; set; }
        public long Shop { get; set; }
        public Nullable<int> IdMalek { get; set; }
        public Nullable<int> RadifMalek { get; set; }
        public Nullable<int> YearCalc { get; set; }
        public Nullable<int> StatusCalc { get; set; }
        public int TypeCalc { get; set; }
        public string ErrorCalc { get; set; }
        public Nullable<System.DateTime> DateTimeCalc { get; set; }
        public Nullable<long> JobId { get; set; }
        public string FullName { get; set; }
        public Nullable<double> shopMalekin { get; set; }
        public Nullable<decimal> idMalekin { get; set; }
        public Nullable<decimal> radif { get; set; }
        public Nullable<int> M_ID { get; set; }
        public string codeN { get; set; }
        public string shoFish { get; set; }
        public Nullable<decimal> mantaghe { get; set; }
        public Nullable<decimal> hoze { get; set; }
        public Nullable<decimal> blok { get; set; }
        public Nullable<decimal> shomelk { get; set; }
        public Nullable<decimal> sakhteman { get; set; }
        public Nullable<decimal> apar { get; set; }
        public Nullable<decimal> senfi { get; set; }
        public Nullable<int> userCode { get; set; }
        public string smsMessage { get; set; }
        public string mob { get; set; }
        public string smsStatus { get; set; }
        public Nullable<System.DateTime> smsDate { get; set; }
    }
}
