//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_LogTotalCalc
    {
        public long ID { get; set; }
        public long Shop { get; set; }
        public Nullable<int> IdMalek { get; set; }
        public Nullable<int> RadifMalek { get; set; }
        public Nullable<int> YearCalc { get; set; }
        public Nullable<int> StatusCalc { get; set; }
        public int TypeCalc { get; set; }
        public string ErrorCalc { get; set; }
        public Nullable<long> JobId { get; set; }
        public Nullable<System.DateTime> DateTimeCalc { get; set; }
        public string shoFish { get; set; }
        public Nullable<int> userCode { get; set; }
        public string user_n { get; set; }
        public string FullName { get; set; }
        public string nameSemat { get; set; }
        public string codeN { get; set; }
        public bool locked { get; set; }
        public Nullable<int> AreaId { get; set; }
    }
}
