//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_M100Bazdid_Apartman
    {
        public Nullable<double> shop { get; set; }
        public Nullable<long> shodarkhast { get; set; }
        public Nullable<int> tarikh_d { get; set; }
        public string c_nosazi { get; set; }
        public string name { get; set; }
        public Nullable<int> tarikh { get; set; }
        public string moteghazi { get; set; }
        public Nullable<double> shobadvi { get; set; }
        public Nullable<int> dt_badvi { get; set; }
        public Nullable<decimal> mablaghBadvi { get; set; }
        public Nullable<double> shotajdid { get; set; }
        public string dt_tajdid { get; set; }
        public Nullable<int> c_noesaghf { get; set; }
        public string noesaghf { get; set; }
        public Nullable<int> c_NoeSakhteman { get; set; }
        public string NoeSakhteman { get; set; }
        public Nullable<int> c_NoeSaze { get; set; }
        public string NoeSaze { get; set; }
        public decimal radif { get; set; }
        public Nullable<int> c_noetasisat { get; set; }
        public string noetasisat { get; set; }
        public Nullable<int> c_jens { get; set; }
        public string jens { get; set; }
        public Nullable<int> c_noesanad { get; set; }
        public string noesanad { get; set; }
        public Nullable<decimal> jammablaghTajdid { get; set; }
    }
}
