//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_M100_InFrontage
    {
        public double shop { get; set; }
        public double shod { get; set; }
        public int tarikh_d { get; set; }
        public string jalase { get; set; }
        public Nullable<double> VoteNo { get; set; }
        public string malekname { get; set; }
        public Nullable<decimal> jammablagh { get; set; }
        public string dateVote { get; set; }
        public double ViolationArea { get; set; }
        public Nullable<double> GroundArea { get; set; }
        public string address { get; set; }
        public Nullable<bool> Karbari_Tafzili { get; set; }
    }
}
