//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_Marhale_Desc
    {
        public string Sho_Darkhast { get; set; }
        public Nullable<double> Shop { get; set; }
        public string ersalkonandeh { get; set; }
        public string girandeh { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string MarhalehJari { get; set; }
        public string MarhalehMaghsad { get; set; }
        public string Description { get; set; }
    }
}
