//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_Made100_Ray_khalaf
    {
        public int shop { get; set; }
        public int shod { get; set; }
        public int Radif { get; set; }
        public bool OsolFani_Behdashti { get; set; }
        public bool OsolShahrsazi { get; set; }
        public bool withoutlicense { get; set; }
        public bool EzafeBana { get; set; }
        public Nullable<int> c_Raytype { get; set; }
        public string Raytype { get; set; }
        public int RayNo { get; set; }
        public int Raydate { get; set; }
        public string FormatRayNo { get; set; }
        public long RayId { get; set; }
    }
}
