//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_Made100_Ray
    {
        public string address { get; set; }
        public string c_nosazi { get; set; }
        public string noedarkhast { get; set; }
        public string moteghazi { get; set; }
        public int shop { get; set; }
        public int shod { get; set; }
        public int Raydate { get; set; }
        public int RayNo { get; set; }
        public string FormatRayNo { get; set; }
        public string Description { get; set; }
        public int PishnevisId { get; set; }
        public Nullable<int> c_Raytype { get; set; }
        public string Raytype { get; set; }
        public string EblaghNo { get; set; }
        public Nullable<int> EblaghDate { get; set; }
        public string EblaghDescription { get; set; }
        public Nullable<bool> IsDelivery { get; set; }
        public Nullable<int> DelivaryDate { get; set; }
        public long Id { get; set; }
        public string grouh { get; set; }
        public string sho_g { get; set; }
        public Nullable<int> tarikh_g { get; set; }
        public string codeposti { get; set; }
        public string tel { get; set; }
        public string mob { get; set; }
        public Nullable<int> date_rooz { get; set; }
        public Nullable<int> Komission_Code { get; set; }
        public string Komission_Text { get; set; }
        public string pishnevis_Num { get; set; }
        public Nullable<int> Pishnevis_Date { get; set; }
        public string Pishnevis_Desc { get; set; }
        public Nullable<int> Komission_Date { get; set; }
        public string Kommission_Time { get; set; }
    }
}
