//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_masahatBazdid
    {
        public decimal shop { get; set; }
        public decimal d_radif { get; set; }
        public decimal id { get; set; }
        public int sh_darkhast { get; set; }
        public string shosakhteman { get; set; }
        public string tabagheh { get; set; }
        public string karbari { get; set; }
        public string noeestefadeh { get; set; }
        public Nullable<double> masahat_k { get; set; }
        public Nullable<decimal> parvaneh { get; set; }
        public Nullable<decimal> takhalof { get; set; }
        public Nullable<double> tarakom { get; set; }
        public Nullable<decimal> tedadvahed { get; set; }
        public Nullable<double> Ekhtelaf { get; set; }
        public string Tabaghe { get; set; }
        public Nullable<int> c_Tabaghe { get; set; }
    }
}
