//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_Marahel_Erja
    {
        public int Gardeshkar_Code { get; set; }
        public int Marahel_Code { get; set; }
        public int Erja_Code { get; set; }
        public string Sharh { get; set; }
    }
}
