//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_NosaziFish
    {
        public Nullable<decimal> Avarez { get; set; }
        public Nullable<decimal> Khadamat { get; set; }
        public Nullable<decimal> Sayer { get; set; }
        public Nullable<decimal> Education { get; set; }
        public Nullable<decimal> FireStation { get; set; }
        public Nullable<decimal> BadHesabi { get; set; }
        public Nullable<decimal> Tax { get; set; }
        public Nullable<decimal> FazayeSabz { get; set; }
        public decimal shop { get; set; }
        public int IdMalek { get; set; }
    }
}
