//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_ParvandehHistory
    {
        public long IDParHistory { get; set; }
        public Nullable<double> shop { get; set; }
        public Nullable<decimal> mantaghe { get; set; }
        public Nullable<decimal> hoze { get; set; }
        public Nullable<decimal> blok { get; set; }
        public Nullable<decimal> shomelk { get; set; }
        public Nullable<decimal> sakhteman { get; set; }
        public Nullable<decimal> apar { get; set; }
        public Nullable<decimal> senfi { get; set; }
        public Nullable<int> idparent { get; set; }
        public Nullable<int> code_tree { get; set; }
        public Nullable<bool> sws { get; set; }
        public Nullable<int> Formol { get; set; }
        public string e_code { get; set; }
        public string ghabli { get; set; }
        public string codeN { get; set; }
        public Nullable<System.DateTime> DateUpdate { get; set; }
        public string DescUpdate { get; set; }
        public Nullable<int> TypeUpdate { get; set; }
        public int UserCode { get; set; }
        public string UserName { get; set; }
        public int LockStatus { get; set; }
        public string user_n { get; set; }
        public string FullName { get; set; }
        public string nameSemat { get; set; }
        public string Expr1 { get; set; }
        public bool locked { get; set; }
        public Nullable<int> AreaId { get; set; }
    }
}
