//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_Parvaneh_Erja
    {
        public Nullable<int> sh_darkhast { get; set; }
        public Nullable<double> shop { get; set; }
        public Nullable<int> tarikh_darkhast { get; set; }
        public int c_nodarkhast { get; set; }
        public string noedarkhast { get; set; }
        public Nullable<int> c_marhaleh { get; set; }
        public string marhaleh { get; set; }
        public string code_nosazi { get; set; }
        public string name_mot { get; set; }
        public string vaziatErja { get; set; }
        public string sho_parvaneh { get; set; }
        public Nullable<int> c_noeParvaneh { get; set; }
        public string noe_parvaneh { get; set; }
        public Nullable<int> tarikh_parvaneh { get; set; }
        public string serial_parvaneh { get; set; }
        public Nullable<int> c_vaziatErja { get; set; }
    }
}
