//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_RepInMapGIS
    {
        public decimal shop { get; set; }
        public Nullable<double> masahat_s { get; set; }
        public string address { get; set; }
        public Nullable<int> c_marhaleh { get; set; }
        public string marhaleh { get; set; }
        public string codeN { get; set; }
        public Nullable<decimal> mantaghe { get; set; }
        public Nullable<decimal> blok { get; set; }
        public Nullable<decimal> hoze { get; set; }
        public Nullable<decimal> shomelk { get; set; }
        public Nullable<int> c_vazmelk { get; set; }
        public string vazmelk { get; set; }
        public Nullable<int> c_vazsanad { get; set; }
        public string vazsanad { get; set; }
        public Nullable<int> c_noemalekiat { get; set; }
        public string noemalekiat { get; set; }
        public Nullable<int> c_noemelk { get; set; }
        public string noemelk { get; set; }
        public string nameFamily { get; set; }
        public Nullable<decimal> id { get; set; }
        public Nullable<decimal> sal { get; set; }
        public Nullable<decimal> bed { get; set; }
        public Nullable<decimal> Expr1 { get; set; }
        public Nullable<int> IdMalek { get; set; }
        public Nullable<decimal> avarez { get; set; }
    }
}
