//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_RepSodorRay
    {
        public string address { get; set; }
        public string c_nosazi { get; set; }
        public int Shop { get; set; }
        public int Shod { get; set; }
        public string sho_parvaneh { get; set; }
        public Nullable<int> tarikh_parvaneh { get; set; }
        public string formatnumberVote { get; set; }
        public string dateVote { get; set; }
        public string pishnevis_Num { get; set; }
        public Nullable<int> Pishnevis_Date { get; set; }
        public string moteghazi { get; set; }
        public string pelakSabti { get; set; }
        public string karshanasghoveGhazaee { get; set; }
        public string agentVazir { get; set; }
        public string agentShorayeshahr { get; set; }
        public Nullable<int> tarikh_d { get; set; }
        public string shoeteraz_m { get; set; }
        public Nullable<int> dt_eteraz_m { get; set; }
        public string shoeteraz_sh { get; set; }
        public Nullable<int> dt_eteraz_sh { get; set; }
        public Nullable<int> Komission_Code { get; set; }
        public Nullable<int> PishnevisId { get; set; }
        public long Id { get; set; }
        public string Description { get; set; }
    }
}
