//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_Rep_parvaneh
    {
        public double shop { get; set; }
        public string codeN { get; set; }
        public Nullable<decimal> mantaghe { get; set; }
        public Nullable<decimal> hoze { get; set; }
        public Nullable<decimal> blok { get; set; }
        public Nullable<decimal> shomelk { get; set; }
        public Nullable<decimal> sakhteman { get; set; }
        public Nullable<decimal> apar { get; set; }
        public Nullable<decimal> senfi { get; set; }
        public decimal radif { get; set; }
        public string NameFamily { get; set; }
        public string kodemeli { get; set; }
        public string mob { get; set; }
        public Nullable<double> MasahatKol { get; set; }
        public Nullable<double> Tedadkasri { get; set; }
        public Nullable<double> masahatTamin { get; set; }
        public Nullable<double> tedadTamin { get; set; }
        public Nullable<double> Ertefa { get; set; }
        public Nullable<double> tarakom { get; set; }
    }
}
