//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_Rep_Vosol_Ba_Tarikh
    {
        public decimal shop { get; set; }
        public string name { get; set; }
        public string family { get; set; }
        public string address { get; set; }
        public string codn { get; set; }
        public Nullable<decimal> mantaghe { get; set; }
        public Nullable<decimal> hoze { get; set; }
        public Nullable<decimal> blok { get; set; }
        public Nullable<decimal> shomelk { get; set; }
        public Nullable<decimal> apar { get; set; }
        public string fish { get; set; }
        public Nullable<decimal> bed { get; set; }
        public Nullable<decimal> bes { get; set; }
        public Nullable<decimal> khadamat { get; set; }
        public Nullable<decimal> avarez { get; set; }
        public string serial_fish { get; set; }
        public Nullable<int> tarikhsabt { get; set; }
        public string Mahiyat { get; set; }
        public decimal d_radif { get; set; }
        public long Radif { get; set; }
        public string tel { get; set; }
        public string mob { get; set; }
        public string noemalek { get; set; }
        public string sh_sh { get; set; }
        public string kodemeli { get; set; }
        public Nullable<decimal> senfi { get; set; }
    }
}
