//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_RuleCalculated
    {
        public long CodeRuleCalc { get; set; }
        public long CodeRules { get; set; }
        public long IDRuleDeclare { get; set; }
        public Nullable<double> RuleValue { get; set; }
        public Nullable<double> UserValue { get; set; }
        public decimal Shop { get; set; }
        public long Sh_Darkhast { get; set; }
        public int CodeTarh { get; set; }
        public string TitleTarh { get; set; }
        public int CodeTitleRules { get; set; }
        public string TitleRules { get; set; }
        public string FormulaRules { get; set; }
        public string UnitRules { get; set; }
        public string DescRules { get; set; }
        public string FarsiFormulaRuleCalc { get; set; }
        public string FarsiFormulaRules { get; set; }
    }
}
