//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_Sakhteman_Malekin
    {
        public decimal shopm { get; set; }
        public double shop { get; set; }
        public decimal radif { get; set; }
        public decimal id { get; set; }
        public string name { get; set; }
        public string family { get; set; }
        public string NameFamily { get; set; }
        public string kodemeli { get; set; }
        public string father { get; set; }
        public string address { get; set; }
        public string codeposti { get; set; }
        public Nullable<bool> Active { get; set; }
        public string tafkiki { get; set; }
        public string azFari { get; set; }
        public string fari { get; set; }
        public string asli { get; set; }
        public string bakhsh { get; set; }
        public string sabti { get; set; }
        public Nullable<double> AvalDoreh { get; set; }
        public Nullable<long> sh_Darkhast { get; set; }
        public Nullable<double> masahat_s { get; set; }
        public string pelakabi { get; set; }
        public string mob { get; set; }
        public Nullable<int> c_meydan { get; set; }
        public string noesanad { get; set; }
        public string vazsanad { get; set; }
        public Nullable<int> c_noestakhr { get; set; }
        public string vazmelk { get; set; }
        public string noemelk { get; set; }
        public Nullable<decimal> mantaghe { get; set; }
        public Nullable<decimal> hoze { get; set; }
        public Nullable<decimal> blok { get; set; }
        public Nullable<decimal> shomelk { get; set; }
        public Nullable<decimal> sakhteman { get; set; }
        public Nullable<decimal> apar { get; set; }
        public Nullable<decimal> senfi { get; set; }
        public string codeN { get; set; }
        public Nullable<bool> Chap_Fish { get; set; }
        public string manteghhe_g { get; set; }
        public string hozeh_g { get; set; }
        public string blok_g { get; set; }
        public string sakhteman_g { get; set; }
        public string shomelk_g { get; set; }
        public string apar_g { get; set; }
        public string senfi_g { get; set; }
        public string e_code { get; set; }
        public int M_ID { get; set; }
        public string shmadar { get; set; }
        public string CodeN_gh { get; set; }
        public string mtable_name { get; set; }
        public Nullable<int> c_noemalek { get; set; }
        public string noemalek { get; set; }
        public Nullable<bool> Ras_NonAssistance { get; set; }
        public Nullable<int> c_vazmelk { get; set; }
    }
}
