//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_Sakhteman_Info
    {
        public double shop { get; set; }
        public string address { get; set; }
        public Nullable<double> masahat_s { get; set; }
        public Nullable<double> masahat_m { get; set; }
        public Nullable<double> masahat_e { get; set; }
        public Nullable<double> masahat_b { get; set; }
        public string sabti { get; set; }
        public Nullable<int> c_vazsanad { get; set; }
        public string vazsanad { get; set; }
        public Nullable<int> c_noesanad { get; set; }
        public string noesanad { get; set; }
        public Nullable<int> c_vazmelk { get; set; }
        public string vazmelk { get; set; }
        public Nullable<int> c_marja { get; set; }
        public string marja { get; set; }
        public string jahat_m { get; set; }
        public string noe_m { get; set; }
        public string azla_jahat { get; set; }
        public Nullable<double> tolbar { get; set; }
        public string tolzel { get; set; }
        public Nullable<double> arz_m { get; set; }
        public Nullable<double> masahat1 { get; set; }
        public Nullable<double> masahat2 { get; set; }
        public Nullable<double> masahat3 { get; set; }
        public string tolzeleslahi { get; set; }
        public string tolbareslahi { get; set; }
        public string shoray { get; set; }
        public Nullable<int> tarikhray { get; set; }
        public string name { get; set; }
        public string family { get; set; }
        public Nullable<int> c_grouh { get; set; }
        public string grouh { get; set; }
        public Nullable<int> tarikh_g { get; set; }
        public string codeN { get; set; }
        public string shosakhteman { get; set; }
        public string tabagheh { get; set; }
        public Nullable<int> c_karbari { get; set; }
        public string karbari { get; set; }
        public Nullable<int> c_noeestefadeh { get; set; }
        public string noeestefadeh { get; set; }
        public Nullable<double> masahat_k { get; set; }
        public Nullable<int> c_noesakhteman { get; set; }
        public string noesakhteman { get; set; }
        public Nullable<int> c_noesaghf { get; set; }
        public string noesaghf { get; set; }
        public Nullable<int> c_noesazeh { get; set; }
        public string noesazeh { get; set; }
        public Nullable<int> tarikhehdas { get; set; }
        public string Expr1 { get; set; }
        public string shotabagheh { get; set; }
        public string noepish { get; set; }
        public Nullable<int> c_noepish { get; set; }
        public Nullable<double> masahat { get; set; }
        public Nullable<double> ertefa { get; set; }
        public Nullable<double> arz { get; set; }
        public long shodarkhast { get; set; }
        public string noedarkhast { get; set; }
        public string noe_k { get; set; }
        public Nullable<decimal> mantaghe { get; set; }
        public Nullable<decimal> hoze { get; set; }
        public Nullable<decimal> blok { get; set; }
        public Nullable<decimal> shomelk { get; set; }
        public Nullable<decimal> sakhteman { get; set; }
        public Nullable<decimal> apar { get; set; }
        public Nullable<decimal> senfi { get; set; }
    }
}
