//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_SelectFormula
    {
        public Nullable<decimal> Afzode { get; set; }
        public Nullable<decimal> Mabkol { get; set; }
        public Nullable<decimal> Pardakhti { get; set; }
        public string Tozihat { get; set; }
        public Nullable<bool> moafiyat { get; set; }
        public Nullable<decimal> Takhfif { get; set; }
        public Nullable<decimal> Arzesh { get; set; }
        public Nullable<decimal> Meghdar { get; set; }
        public string formol { get; set; }
        public string FormolAdadi { get; set; }
        public string noemohasebeh { get; set; }
        public string Kod_Daramadi { get; set; }
        public decimal saal { get; set; }
        public decimal code { get; set; }
        public int Sh_Mohasebe { get; set; }
        public int sh_Darkhast { get; set; }
        public string onvan_daramadi { get; set; }
        public int Radif { get; set; }
        public Nullable<bool> Special { get; set; }
        public string onvan_avarez { get; set; }
        public long radif_t_formul_m { get; set; }
        public Nullable<bool> Entekhab { get; set; }
        public decimal SalBodje { get; set; }
        public decimal MablaghTakhfifParam { get; set; }
        public string NameBank { get; set; }
        public Nullable<int> CodeBank { get; set; }
        public Nullable<int> AreaId { get; set; }
        public Nullable<decimal> tax { get; set; }
    }
}
