//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_SearchKarshenasanM100
    {
        public int shop { get; set; }
        public int shod { get; set; }
        public Nullable<byte> MeetingType { get; set; }
        public System.DateTime StartDateTime { get; set; }
        public Nullable<System.DateTime> EndDateTime { get; set; }
        public long MeetingNumber { get; set; }
        public string KarshenasShoraShahr { get; set; }
        public string KarshenasVezarat { get; set; }
        public string KarshenasGhazaee { get; set; }
        public long Id { get; set; }
        public Nullable<long> KarshenasGhazaeeId { get; set; }
        public Nullable<long> KarshenasShoraShahrId { get; set; }
        public Nullable<long> KarshenasVezaratId { get; set; }
    }
}
