//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_SearchReportMade100Ray
    {
        public int shop { get; set; }
        public int shod { get; set; }
        public int PishnevisId { get; set; }
        public long Made100RayId { get; set; }
        public long Id { get; set; }
        public Nullable<int> radifKhalaf { get; set; }
        public int c_TabsareMade100 { get; set; }
        public string Tabsaremade100 { get; set; }
        public Nullable<double> khalaf { get; set; }
        public string sharh { get; set; }
        public string Onvan_Khalaf { get; set; }
        public Nullable<int> Code_Khalaf { get; set; }
        public Nullable<decimal> takhalof { get; set; }
        public Nullable<int> Code_Karbari_Asli_Mojod { get; set; }
        public string Onvan_Karbari_Asli_Mojod { get; set; }
        public Nullable<byte> EnumFoulDefinitionType { get; set; }
        public Nullable<long> ArzeshSarghofli { get; set; }
        public Nullable<long> MablaghJarime { get; set; }
        public int UserId { get; set; }
        public Nullable<int> c_RayDetailType { get; set; }
        public string RayDetailType { get; set; }
        public int Raydate { get; set; }
        public int RayNo { get; set; }
        public Nullable<int> c_Raytype { get; set; }
        public string Raytype { get; set; }
        public string EblaghNo { get; set; }
        public Nullable<int> EblaghDate { get; set; }
        public System.DateTime systemdate { get; set; }
        public Nullable<bool> VoteStstus { get; set; }
    }
}
