//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_Shenase_SodorFish
    {
        public string saal { get; set; }
        public string shop { get; set; }
        public int IdMalek { get; set; }
        public Nullable<int> DateSodor { get; set; }
        public Nullable<decimal> MablaghKolNosazi { get; set; }
        public Nullable<decimal> MablaghAvarezNosazi { get; set; }
        public Nullable<decimal> MablaghKhadamatNosazi { get; set; }
        public string ShenaseGhabzNosazi { get; set; }
        public string ShenasePardakhtNosazi { get; set; }
        public Nullable<decimal> MablaghKolKhadamat { get; set; }
        public Nullable<decimal> MablaghAvarezKhadamat { get; set; }
        public Nullable<decimal> MablaghKhadamatKhadamat { get; set; }
        public string ShenaseGhabzKhadamat { get; set; }
        public string ShenasePardakhtKhadamat { get; set; }
        public Nullable<int> AreaId { get; set; }
        public string codeN { get; set; }
        public Nullable<decimal> mantaghe { get; set; }
        public Nullable<decimal> hoze { get; set; }
        public Nullable<decimal> blok { get; set; }
        public Nullable<decimal> shomelk { get; set; }
        public Nullable<int> code_tree { get; set; }
        public Nullable<int> idparent { get; set; }
        public bool IsCumulative { get; set; }
        public Nullable<decimal> khadamat { get; set; }
        public Nullable<decimal> khoshhesabi { get; set; }
        public Nullable<decimal> Tax { get; set; }
    }
}
