//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_sodorRay
    {
        public Nullable<int> Code_Karbari_Farei_Mojod { get; set; }
        public string Onvan_Karbari_Farei_Mojod { get; set; }
        public Nullable<int> Code_Karbari_Asli_Mojaz { get; set; }
        public string Onvan_Karbari_Asli_Mojaz { get; set; }
        public Nullable<int> Code_Karbari_Farei_Mojaz { get; set; }
        public Nullable<double> tarakom { get; set; }
        public string Onvan_Karbari_Farei_Mojaz { get; set; }
        public Nullable<double> TedadVahed { get; set; }
        public string Tabaghe { get; set; }
        public Nullable<int> Tarikh { get; set; }
        public Nullable<double> Ekhtelaf { get; set; }
        public Nullable<int> typeVote { get; set; }
        public Nullable<System.DateTime> dateVote { get; set; }
        public Nullable<double> mablaghJarime { get; set; }
        public Nullable<double> Zarib { get; set; }
        public Nullable<double> ArzeshSarghofli { get; set; }
        public Nullable<long> VoteInformationId { get; set; }
        public Nullable<int> MasahatkhalafID { get; set; }
        public Nullable<int> Code_Karbari_Asli_Mojod { get; set; }
        public Nullable<double> takhalof { get; set; }
        public Nullable<double> parvaneh { get; set; }
        public string Onvan_Khalaf { get; set; }
        public Nullable<int> Code_Khalaf { get; set; }
        public int Radif { get; set; }
        public int sh_darkhast { get; set; }
        public int shop { get; set; }
        public string Onvan_Karbari_Asli_Mojod { get; set; }
        public int masahat_khalafID { get; set; }
        public Nullable<long> Made100_VoteInformationId { get; set; }
        public string codeVoteText { get; set; }
        public string typeVoteText { get; set; }
        public Nullable<long> Id { get; set; }
        public Nullable<long> MabnayMohasebe { get; set; }
        public Nullable<int> numberVote { get; set; }
        public string formatnumberVote { get; set; }
        public int PishnevisId { get; set; }
        public string Komission_Text { get; set; }
        public Nullable<int> Komission_Code { get; set; }
        public Nullable<bool> Made100 { get; set; }
        public Nullable<double> MazadParvaneh { get; set; }
        public Nullable<int> codeVote { get; set; }
    }
}
