//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_SurveyConfirm
    {
        public decimal shop { get; set; }
        public string vazmelk { get; set; }
        public string codeposti { get; set; }
        public string CodeNg { get; set; }
        public Nullable<decimal> mantaghe { get; set; }
        public Nullable<decimal> hoze { get; set; }
        public Nullable<decimal> blok { get; set; }
        public Nullable<decimal> shomelk { get; set; }
        public Nullable<decimal> sakhteman { get; set; }
        public Nullable<decimal> apar { get; set; }
        public Nullable<decimal> senfi { get; set; }
        public string codeN { get; set; }
        public long IDParHistory { get; set; }
        public Nullable<int> AreaId { get; set; }
        public string UserName { get; set; }
        public bool StatusConfirm { get; set; }
    }
}
