//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_subSign
    {
        public string fullName { get; set; }
        public string subFullName { get; set; }
        public string nameSemat { get; set; }
        public string subNameSemat { get; set; }
        public int Id { get; set; }
        public int userCode { get; set; }
        public int sub_userCode { get; set; }
        public int reportId { get; set; }
        public string reportName { get; set; }
        public System.DateTime startDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public bool Active { get; set; }
    }
}
