//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_SurveyTransferAll
    {
        public decimal shop { get; set; }
        public string vazmelk { get; set; }
        public string codeposti { get; set; }
        public string CodeNg { get; set; }
        public Nullable<int> StatusCalc { get; set; }
        public string ErrorCalc { get; set; }
        public Nullable<System.DateTime> DateTimeCalc { get; set; }
        public Nullable<int> userCode { get; set; }
        public Nullable<decimal> mantaghe { get; set; }
        public Nullable<decimal> hoze { get; set; }
        public Nullable<decimal> blok { get; set; }
        public Nullable<decimal> shomelk { get; set; }
        public Nullable<decimal> sakhteman { get; set; }
        public Nullable<decimal> apar { get; set; }
        public Nullable<decimal> senfi { get; set; }
        public string codeN { get; set; }
        public string shoFish { get; set; }
    }
}
