//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_TakhfifDaramad
    {
        public long ID { get; set; }
        public int sh_Darkhast { get; set; }
        public int Sh_Mohasebe { get; set; }
        public int RadifDf { get; set; }
        public int c_Takhfif { get; set; }
        public string sharhTakhfif { get; set; }
        public Nullable<decimal> MablaghTakhfif { get; set; }
        public string Sharh { get; set; }
        public int UserCode { get; set; }
        public string UserFullName { get; set; }
        public System.DateTime TakhfifDate { get; set; }
        public Nullable<double> baha1 { get; set; }
        public decimal saal { get; set; }
        public string Kod_Daramadi { get; set; }
        public string noemohasebeh { get; set; }
        public Nullable<int> KodasliTakhfif { get; set; }
    }
}
