//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_TaqsitM
    {
        public long CodeMTaqsit { get; set; }
        public decimal Shop { get; set; }
        public int IdMalek { get; set; }
        public decimal YearFish { get; set; }
        public Nullable<decimal> Bed { get; set; }
        public Nullable<decimal> Bes { get; set; }
        public Nullable<System.DateTime> DatetimeTaqsit { get; set; }
        public Nullable<int> CntAqsat { get; set; }
        public Nullable<int> CntPaidAqsat { get; set; }
        public Nullable<int> CntRemainAqsat { get; set; }
        public Nullable<decimal> DiffrenceTaqsit { get; set; }
    }
}
