//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_TaqsitD
    {
        public long CodeMTaqsit { get; set; }
        public long CodeDTaqsit { get; set; }
        public Nullable<decimal> Khadamat { get; set; }
        public Nullable<decimal> Avarez { get; set; }
        public Nullable<decimal> FireStation { get; set; }
        public Nullable<decimal> Education { get; set; }
        public Nullable<decimal> Tax { get; set; }
        public bool IsPaid { get; set; }
        public Nullable<long> RadifAvarezBes { get; set; }
        public Nullable<int> SerialShenase { get; set; }
        public decimal Shop { get; set; }
        public int IdMalek { get; set; }
        public decimal YearFish { get; set; }
        public Nullable<decimal> Bed { get; set; }
        public Nullable<decimal> Bes { get; set; }
        public Nullable<System.DateTime> DatetimeTaqsit { get; set; }
    }
}
