//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_Tozihat_Marahel
    {
        public string Sho_Darkhast { get; set; }
        public int DescID { get; set; }
        public Nullable<double> Shop { get; set; }
        public Nullable<int> C_MarhaleJari { get; set; }
        public string MarhalehJari { get; set; }
        public Nullable<int> C_MarhaleMaghsad { get; set; }
        public string MarhalehMaghsad { get; set; }
        public string Description { get; set; }
        public Nullable<int> UserCode { get; set; }
        public string UserName { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public bool showAlarm { get; set; }
        public byte[] signature { get; set; }
        public bool DastoorShahrdar { get; set; }
    }
}
