//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_TrafficFormula
    {
        public int FolderId { get; set; }
        public Nullable<int> RequestNumber { get; set; }
        public string Caption { get; set; }
        public int Year { get; set; }
        public int TotalAmount { get; set; }
        public string Description { get; set; }
        public int Amount { get; set; }
        public Nullable<int> FormulaId { get; set; }
        public string Expr1 { get; set; }
        public string Expr2 { get; set; }
        public int MasterId { get; set; }
    }
}
