//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_TurnOverNosazi
    {
        public Nullable<decimal> shop { get; set; }
        public string codeN { get; set; }
        public string NameFamily { get; set; }
        public string kodemeli { get; set; }
        public string address { get; set; }
        public string mob { get; set; }
        public Nullable<decimal> sal { get; set; }
        public string fish { get; set; }
        public string NameMoteghazi { get; set; }
        public Nullable<int> tarikhfish { get; set; }
        public Nullable<int> tarikhsabt { get; set; }
        public string serial_fish { get; set; }
        public string ShenaseGhabz { get; set; }
        public string ShenasePardakht { get; set; }
        public string sharh { get; set; }
        public string CodeNg { get; set; }
        public decimal avarez { get; set; }
        public decimal khadamat { get; set; }
        public decimal mafiyat { get; set; }
        public decimal bed { get; set; }
        public decimal badhesabi { get; set; }
        public decimal pelakkobi { get; set; }
        public decimal moavaghe { get; set; }
        public decimal sayer { get; set; }
        public decimal khoshhesabi { get; set; }
        public decimal khoshhesabi_khadamat { get; set; }
        public decimal bes { get; set; }
        public Nullable<decimal> mantaghe { get; set; }
        public Nullable<decimal> hoze { get; set; }
        public Nullable<decimal> blok { get; set; }
        public Nullable<decimal> shomelk { get; set; }
        public Nullable<decimal> sakhteman { get; set; }
        public Nullable<decimal> apar { get; set; }
        public Nullable<decimal> senfi { get; set; }
        public Nullable<decimal> id { get; set; }
        public decimal Education { get; set; }
        public decimal FireStation { get; set; }
        public decimal Tax { get; set; }
        public Nullable<int> AreaId { get; set; }
    }
}
