//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_UpdateDaramadCode_Bodje
    {
        public decimal Radif { get; set; }
        public int sal { get; set; }
        public Nullable<int> AzSal { get; set; }
        public string AzCode { get; set; }
        public string TaCode { get; set; }
        public Nullable<System.DateTime> DateSabt { get; set; }
        public string AzDaramadCode { get; set; }
        public string sharhAzDaramadCode { get; set; }
        public string TaDaramadCode { get; set; }
        public string sharhTaDaramadCode { get; set; }
    }
}
