//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_UserSigners
    {
        public int Id { get; set; }
        public int reportId { get; set; }
        public Nullable<int> userCode { get; set; }
        public Nullable<int> sematId { get; set; }
        public string sematName { get; set; }
        public string userTitle { get; set; }
        public byte[] sign { get; set; }
        public Nullable<bool> Active { get; set; }
    }
}
