//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_userGroup
    {
        public string codeGroh_Dastresi { get; set; }
        public string nameFamily { get; set; }
        public string groupName { get; set; }
        public string code { get; set; }
        public double UserCode { get; set; }
        public string strOrganizationId { get; set; }
        public Nullable<int> code_tree { get; set; }
        public Nullable<int> AreaId { get; set; }
        public string Hash { get; set; }
    }
}
