//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_WorkExperience
    {
        public decimal shop { get; set; }
        public string NameShoghl { get; set; }
        public Nullable<int> c_OnvanShoghl { get; set; }
        public string OnvanShoghl { get; set; }
        public Nullable<int> TarikhShoro { get; set; }
        public Nullable<int> TarikhPayan { get; set; }
        public string name { get; set; }
        public string family { get; set; }
        public string kodemeli { get; set; }
        public string codeN { get; set; }
    }
}
