//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_DarkhsTest
    {
        public double shop { get; set; }
        public int Id { get; set; }
        public long shodarkhast { get; set; }
        public string noedarkhast { get; set; }
        public Nullable<int> c_noedarkhast { get; set; }
        public string noemot { get; set; }
        public Nullable<int> c_noemot { get; set; }
        public string address { get; set; }
        public string mob { get; set; }
        public bool Ebtal { get; set; }
        public System.Data.Spatial.DbGeometry Shape { get; set; }
    }
}
