//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VoteViolationType
    {
        public int Id { get; set; }
        public long ShoP { get; set; }
        public long ShoD { get; set; }
        public byte PishnevisId { get; set; }
        public Nullable<decimal> DestructiveArea { get; set; }
        public Nullable<decimal> PenaltyAmount { get; set; }
        public string CertificateNumber { get; set; }
        public Nullable<System.DateTime> CertificateDate { get; set; }
        public int VoteNumber { get; set; }
        public System.DateTime VoteDate { get; set; }
        public byte CodeRayType { get; set; }
        public Nullable<bool> Urban { get; set; }
        public Nullable<bool> Technical { get; set; }
        public Nullable<bool> Sanitary { get; set; }
        public Nullable<bool> DemolitionEntireBuilding { get; set; }
        public Nullable<bool> PartialDestruction { get; set; }
        public Nullable<bool> BlockTheWindow { get; set; }
        public Nullable<bool> TerraceObstruction { get; set; }
        public Nullable<bool> VoteViolation_A { get; set; }
        public Nullable<bool> VoteViolation_B { get; set; }
        public Nullable<bool> VoteViolation_C { get; set; }
        public Nullable<bool> VoteViolation_Description { get; set; }
        public string Description { get; set; }
    }
}
