//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Voting
    {
        public long Id { get; set; }
        public bool IsDelete { get; set; }
        public int Shop { get; set; }
        public int Shod { get; set; }
        public int DraftId { get; set; }
        public System.DateTime VotingDate { get; set; }
        public int VotingNo { get; set; }
        public string FormatVotingNo { get; set; }
        public Nullable<int> c_VotingType { get; set; }
        public string VotingType { get; set; }
        public string Description { get; set; }
        public string SignificationNo { get; set; }
        public Nullable<System.DateTime> SignificationDate { get; set; }
        public string SignificationDescription { get; set; }
        public Nullable<bool> IsDelivery { get; set; }
        public Nullable<System.DateTime> DelivaryDate { get; set; }
        public int UserId { get; set; }
        public string UserFullName { get; set; }
        public System.DateTime SystemDate { get; set; }
        public Nullable<bool> AutomaticVoting { get; set; }
        public Nullable<bool> VoteStstus { get; set; }
        public Nullable<bool> MeetingStatus { get; set; }
        public bool SystemConfirmation { get; set; }
    }
}
