//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Warnings
    {
        public int Id { get; set; }
        public double Shop { get; set; }
        public double Shod { get; set; }
        public bool IsDelete { get; set; }
        public System.DateTime Date { get; set; }
        public string WarningNumber { get; set; }
        public Nullable<System.DateTime> WarningDate { get; set; }
        public string WarningReason { get; set; }
        public string PresenceHour { get; set; }
        public Nullable<System.DateTime> PresenceDate { get; set; }
        public string DeliveryTime { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public Nullable<bool> Owner { get; set; }
        public Nullable<bool> AffiliateOwner { get; set; }
        public string Relative { get; set; }
        public Nullable<bool> ExecutiveAgent { get; set; }
        public string ExecutiveAgentName { get; set; }
        public Nullable<bool> InstallationOnSite { get; set; }
        public string Province { get; set; }
        public string City { get; set; }
    }
}
