//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class YearZaribTadil
    {
        public YearZaribTadil()
        {
            this.DetailZaribTadil = new HashSet<DetailZaribTadil>();
        }
    
        public int Id { get; set; }
        public int Year { get; set; }
    
        public virtual ICollection<DetailZaribTadil> DetailZaribTadil { get; set; }
    }
}
