//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class YearCoefficientRenovation
    {
        public YearCoefficientRenovation()
        {
            this.RenovationCoefficientArea = new HashSet<RenovationCoefficientArea>();
        }
    
        public int Id { get; set; }
        public int Year { get; set; }
    
        public virtual ICollection<RenovationCoefficientArea> RenovationCoefficientArea { get; set; }
    }
}
