//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zavabet
    {
        public decimal shop { get; set; }
        public decimal shoDarkhast { get; set; }
        public long d_radif { get; set; }
        public long Id { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<int> c_melakamal { get; set; }
        public string melakeamal { get; set; }
        public string karbar { get; set; }
        public Nullable<int> tarikh_z { get; set; }
        public Nullable<int> saat { get; set; }
        public string tozihat { get; set; }
        public string Tozihat2 { get; set; }
        public Nullable<int> c_KarbariTarh { get; set; }
        public string KarbariTarh { get; set; }
        public Nullable<long> C_Khadamat { get; set; }
        public string Khadamat { get; set; }
    }
}
