// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.33/esri/copyright.txt for details.
//>>built
define("esri/dijit/analysis/mixins/browselayers/BrowseLayerMixin","dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/has dojo/query ../../../../kernel ../../../../request ../../../../lang ../../../../layers/CSVLayer ../../../../arcgis/Portal ../../../../SpatialReference ../../ProjectExtent dojo/Deferred ../../ItemTypes ../../utils ./configs/AGOLBrowseItem ./configs/EnterpriseBrowseItem dojo/i18n!../../nls/BrowseLayerMixin".split(" "),function(n,e,x,y,q,t,v,r,z,u,A,B,p,d,w,C,D,E){n=n([],{tableSupportedTools:"JoinFeatures SummarizeAttributes ExtractData GeocodeLocationsfromTable CopyToDataStore AppendData CalculateField MergeLayers DescribeDataset DetectIncidents".split(" "),
allowedItemTypes:[],defaultItemTypes:[d.MS,d.FS],availableItemTypeFilters:["layers","featureLayers"],_createBrowseItems:function(a,b,c){a=a||{};var m=a.browseValue||{};b=b||{};var g=this.defaultItemTypes.concat(this.get("allowedItemTypes"));if(this.useArcGISComponents)this.setUpItemBrowser(a,b,c).then(function(){this.map&&this._chopExtentAtDateLine(this.map.extent).then(this._projectExtentAndDispatch.bind(this))}.bind(this));else{var e=[];g.forEach(function(a){e.push('type:"'+a+'"')});"browse"===
m?(c=this._browsedlg.browseItems.get("query"),c.custom=this._queryTagsForLivingAtlasBrowseItems(b),this._browsedlg.browseItems.set("extent",this.get("map").extent),this._browsedlg.browseItems.set("query",c),this._browsedlg.show()):(this.showGeoAnalyticsParams&&e.push('type:"'+d.BIGDATA+'"'),c=this._browseLyrsdlg.browseItems.get("query"),c.types=e,this._browseLyrsdlg.browseItems.set("query",c),b.geometryTypes?(this._browseLyrsdlg.browseItems.plugIn.checkGeometryType=!0,0<b.geometryTypes.length&&(this._browseLyrsdlg.browseItems.plugIn.geometryTypes=
b.geometryTypes)):this._browseLyrsdlg.browseItems.plugIn.checkGeometryType=!1,b.layerTypes?(this._browseLyrsdlg.browseItems.plugIn.checkLayerType=!0,0<b.layerTypes.length&&(this._browseLyrsdlg.browseItems.plugIn.layerTypes=b.layerTypes)):this._browseLyrsdlg.browseItems.plugIn.checkLayerType=!1,b.customCheck?(this._browseLyrsdlg.browseItems.plugIn.customCheckHandler=b.customCheck.customCheckHandler,this._browseLyrsdlg.browseItems.plugIn.customCheckFailureMessage=b.customCheck.customCheckFailureMessage):
this._browseLyrsdlg.browseItems.plugIn.customCheckHandler=void 0,this._browseLyrsdlg.show())}},setUpItemBrowser:function(a,b,c){var m=new p;window.require(["arcgis-components/wrappers/ItemBrowser","esri/arcgis/Portal"],function(g,k){if(!this.ib){var h=document.createElement("div");!a.isDialog&&document.body.appendChild(h);var f=new k.Portal(this.portalSelf&&this.portalSelf.urlKey&&this.portalSelf.customBaseUrl?location.protocol+"//"+this.portalSelf.urlKey+"."+this.portalSelf.customBaseUrl+"/sharing/rest":
(this.portalSelf&&this.portalSelf.portalHostname?location.protocol+"//"+this.portalSelf.portalHostname:this.portalUrl)+"/sharing/rest"),l=this.defaultItemTypes.concat(this.get("allowedItemTypes")),n=function(){this.ib.dispatch({type:"CLOSE_FULLSCREEN_BROWSER"});a.isDialog&&this._closeDialog();this._resetSelectBox(c);!a.isDialog&&this._removeDOMfromBody(h)},p=function(b){this.ib.dispatch({type:"CLOSE_FULLSCREEN_BROWSER"});a.isDialog&&this._closeDialog();b[0]&&b[0].type===d.RFT?this.onSelectRFTTool.bind(this)(b[0],
f):b[0]&&b[0].type===d.DLPK?this.onSelectDLPKTool.bind(this)(b[0],f):this.onBrowseItemSelect.bind(this)(b[0],f,c);!a.isDialog&&this._removeDOMfromBody(h)},q=function(b){this.ib.dispatch({type:"CLOSE_FULLSCREEN_BROWSER"});a.isDialog&&this._closeDialog();this.onSelectGPTool.bind(this)(b);!a.isDialog&&this._removeDOMfromBody(h)},r=function(b){this.ib.dispatch({type:"CLOSE_FULLSCREEN_BROWSER"});a.isDialog&&this._closeDialog();this.onEditRFTTool.bind(this)(b,f);!a.isDialog&&this._removeDOMfromBody(h)},
t=function(b){this.ib.dispatch({type:"CLOSE_FULLSCREEN_BROWSER"});a.isDialog&&this._closeDialog();this.onBrowseItemSelect.bind(this)(b,f,c);!a.isDialog&&this._removeDOMfromBody(h)},u=function(b){this.ib.dispatch({type:"CLOSE_FULLSCREEN_BROWSER"});a.isDialog&&this._closeDialog();b&&b.type===d.RFT?this.onEditRFTTool.bind(this)(b,f):this.onBrowseItemSelect.bind(this)(b,f,c,!0);!a.isDialog&&this._removeDOMfromBody(h)};-1<this.tableSupportedTools.indexOf(this.helpFileName)&&(l=l.concat([this.showGeoAnalyticsParams?
d.TABLE:d.BTABLE]));f.signIn().then(function(){this._fetchGroupForRFT(f).then(function(c){-1<l.indexOf(d.IS)?this.availableItemTypeFilters=["layers","featureLayers","mapImageLayers","imageryLayers"]:-1===l.indexOf(d.GPSERVICE)&&-1===l.indexOf(d.RFT)&&-1===l.indexOf(d.FILE)&&(this.availableItemTypeFilters=this.availableItemTypeFilters.concat(["layers","featureLayers"]));-1<this.tableSupportedTools.indexOf(this.helpFileName)&&(this.availableItemTypeFilters=this.availableItemTypeFilters.concat(["tables"]));
c={allowedItemTypes:this.showGeoAnalyticsParams?[d.BIGDATA].concat(l):l,availableItemTypeFilters:this.showGeoAnalyticsParams?this.availableItemTypeFilters.concat(["bigDataFileShares"]):this.availableItemTypeFilters,customQueryTags:b,addQueryParameters:a.addQueryParameters,portal:f,isPortal:this.isSingleTenant,onSelectSubLayer:t.bind(this),onActionSubLayer:u.bind(this),onSelectGPTool:q.bind(this),onEditRFT:r.bind(this),rftGroupId:c,disableLAAL:a.disableLAAL,disableBoundary:a.disableBoundary,title:a.title,
disabledSubResources:this._getDisableResources(a.disabledSubResources),showRFTSystemSection:null!=a.showRFTSystemSection?a.showRFTSystemSection:!0,showRFTEditCustomAction:null!=a.showRFTEditCustomAction?a.showRFTEditCustomAction:!0};var k=e.mixin(g.initialState.settings.config,this.isSingleTenant?D.getConfig(c):C.getConfig(c));-1<c.allowedItemTypes.indexOf(d.RFT)&&!this.isSingleTenant&&(k.addQueryParameters=function(a){return"all"===a.parameters.section?"-owner: (esri_*)":""});this.ib=new g.ItemBrowserWrapper(h,
{apiVersion:3,portal:f,request:v,initialState:e.mixin(g.initialState,{settings:e.mixin(g.initialState.settings,{config:e.mixin(k,{onBack:n.bind(this),onSelect:p.bind(this)})}),ui:e.mixin(g.initialState.ui,{expanded:e.mixin(g.initialState.ui.expanded,{filters:!0})})}),parameters:e.mixin(g.initialState.parameters,{section:"myContent",filter:e.mixin(g.initialState.parameters.filter,{searchMapArea:!1})})});a.isDialog&&this._createDialog(h,f);m.resolve()}.bind(this))}.bind(this))}}.bind(this));return m},
_queryTagsForLivingAtlasBrowseItems:function(a){if((a=a&&a.tags)&&0!==a.length){if(1===a.length)return['tags:"'+a[0]+'"'];q=[];a.forEach(function(a){q.push('tags:"'+a+'"')});return q}},onBrowseItemSelect:function(a,b,c,m){b=this._getPortalItem(a,b);var d={selection:b,dialog:this._browseLyrsdlg||this._browsedlg};!a.url||w.isHostedService(a.url)||this.isSingleTenant||b.selectedLayer instanceof z?this._handleBrowseItemsSelect(d,m):this._getProxyServiceInfo(a).then(function(){r.isDefined(a.analysisProxyCheck)&&
"failure"===a.analysisProxyCheck?this._resetSelectBox(c):this._handleBrowseItemsSelect(d,m)}.bind(this),function(){this._resetSelectBox(c)}.bind(this))},onSelectGPTool:function(a){a.resource.url=a.url;this._handleSelectGpTool(a.resource)},onSelectRFTTool:function(a,b){this._handleSelectRFTTool(this._getPortalItem(a,b))},onSelectDLPKTool:function(a,b){this._handleSelectDLPKTool(this._getPortalItem(a,b))},onEditRFTTool:function(a,b){this._handleEditRFTTool(this._getPortalItem(a,b))},_getPortalItem:function(a,
b){a.resource&&a.item?(b=new u.PortalItem(e.mixin(a.item,{portal:b})),b.selectedLayer=a.resource,b.selectedLayer.url=a.url):(b=new u.PortalItem(e.mixin(a,{portal:b})),a.type&&-1<[d.CSV,d.XLS].indexOf(a.type)&&(b.selectedLayer=b));return b},_createDialog:function(a,b){window.require(["dijit/Dialog","esri/dijit/analysis/mixins/browselayers/configs/Common"],function(b,d){this.itemBrowserDialog||(this.itemBrowserDialog=new b({style:"width: 900px; height:900px; overflow: auto",id:"itemBrowserDialog",closable:!1,
title:E.customAnalysisLayerTitle}));this.itemBrowserDialog.set("content",a);this.itemBrowserDialog.show()}.bind(this))},_closeDialog:function(){this.itemBrowserDialog.hide();this.itemBrowserDialog.destroy();delete this.itemBrowserDialog;delete this.ib},_setAllowedItemTypesAttr:function(a){this.allowedItemTypes=a},_setAvailableItemTypeFiltersAttr:function(a){this.availableItemTypeFilters=a},_getDisableResources:function(a){var b={};a&&a.length&&a.forEach(function(a){a&&a.url&&(b[a.url]=!0)},this);
return b},_projectExtentAndDispatch:function(a){this.sr||(this.sr=new A(4326));B(a,this.sr,function(a){this._dispatchExtentToItemBrowser(a[0])}.bind(this),function(a){console.error(a)}.bind(this))},_chopExtentAtDateLine:function(a){var b=new p;window.esri.geometry.normalizeCentralMeridian([a],null,function(c){if(c[0].rings){var d=(new window.esri.geometry.Polygon(a.spatialReference)).addRing(c[0].rings[0]).getExtent();c=(new window.esri.geometry.Polygon(a.spatialReference)).addRing(c[0].rings[1]).getExtent();
b.resolve(d.getWidth()>c.getWidth()?d:c)}else b.resolve(c[0])},function(a){b.reject(a)});return b},_dispatchExtentToItemBrowser:function(a){window.require(["arcgis-components/wrappers/ItemBrowser"],function(b){this.ib.dispatch(b.updateExtent({minx:a.xmin,miny:a.ymin,maxx:a.xmax,maxy:a.ymax}))}.bind(this))},_fetchGroupForRFT:function(a){var b=new p;-1===this.allowedItemTypes.indexOf(d.RFT)&&b.resolve();this._systemRFTsGroup&&b.resolve(this._systemRFTsGroup);w.fetchGroupForRFT(a).then(function(a){this._systemRFTsGroup=
a;b.resolve(a)}.bind(this));return b},_removeDOMfromBody:function(a){setTimeout(function(){document.body.removeChild(a)},300);delete this.ib},_resetSelectBox:function(a){a&&a.reset()},_getProxyServiceInfo:function(a){var b=new p,c,d,e;r.isDefined(a)&&r.isDefined(a.url)||b.reject({error:"mapLayer is not defined"});c=a.url+(-1<a.url.indexOf("?")?"\x26":"?")+"f\x3djson";var k=t.id.findCredential(a.url);d=a.url;this.proxyCheckedServers||(this.proxyCheckedServers=[]);x.some(this.proxyCheckedServers,function(b){e=
d.substring(0,d.indexOf("/",9));if(b.server===e)return a.analysisProxyCheck=b.check,!0},this)?b.resolve({}):(k&&k.token&&(c+="\x26token\x3d"+k.token),b=v({url:c,content:null},{useProxy:!0}),b.then(function(){a.analysisProxyCheck="success";this.proxyCheckedServers.push({server:d.substring(0,d.indexOf("/",9)),check:"success"})}.bind(this),function(){a.analysisProxyCheck="failure";this.proxyCheckedServers.push({server:d.substring(0,d.indexOf("/",9)),check:"failure"})}.bind(this)));return b.promise}});
y("extend-esri")&&e.setObject("dijit.analysis.mixins.browselayers.BrowseLayerMixin",n,t);return n});