// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.33/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/ReportPlayer/core/conversion/portalToEditorUtils/parsers/TableParser","dojo/_base/lang esri/dijit/geoenrichment/utils/JsonXmlConverter esri/dijit/geoenrichment/ReportPlayer/core/supportClasses/templateJsonUtils/fieldInfo/FieldInfoBuilder esri/dijit/geoenrichment/ReportPlayer/core/supportClasses/templateJsonUtils/fieldInfo/RichTextJsonUtil ../../../supportClasses/DocumentOptions ../../ConversionUtil ../../../sections/SectionTypes ./AlignParser ./_HiddenCellsCollector esri/dijit/geoenrichment/utils/ColorUtil".split(" "),
function(y,p,z,A,B,h,l,C,x,D){var u={parseTableCellAttributes:function(a,c,b){b=b.tableDefaultStyles;c=c||{};a.overrideStyle&&(c.overrideStyle=a.overrideStyle);a.pad&&(c.horizontalPadding=h.ptToPx(a.pad));a.vpad&&(c.verticalPadding=h.ptToPx(a.vpad));a.angle&&(c.angle=Number(a.angle)||0);C.parseAlign(a,c);a.width&&(c.width=h.ptToPx(a.width));a.height&&(c.height=h.ptToPx(a.height));y.mixin(c,h.ptToPxObj(h.parseStyleString(a.style)));if(c.overrideStyle&&b){b=b.getStyle(c.overrideStyle);for(var f in b)delete c[f]}u._parseBorderProperties(a,
c);return c},_SIDES:["Top","Right","Bottom","Left"],_parseBorderProperties:function(a,c){u._SIDES.forEach(function(b){if(a["border"+b+"Width"]){a["border"+b+"Color"]&&(c["border"+b+"Color"]=a["border"+b+"Color"]);a["border"+b+"Width"]&&(c["border"+b+"Width"]=h.ptToPx(a["border"+b+"Width"]));a["border"+b+"Style"]&&(c["border"+b+"Style"]=a["border"+b+"Style"]);var f=a["border"+b+"Opacity"];c["border"+b+"Opacity"]=f?Number(f):1}})}},r={getElement:function(a,c,b){var f=r._processTableColumns(a,c.templateJson,
b),k=Number(a.attributes.fixedColumns)||0,w=Number(a.attributes.dynamicColumns)||0,d=r._getTableOuterTags(a,c);b=d.trTags;var g=d.bgTag,e=d.fgTag,m=d.backgroundFloatingPanelsTag,q=d.foregroundFloatingPanelsTag,n=d.filterTag,d=d.sortingTag;if(b){var p=b.map(function(){return{style:{fields:{}},fieldInfos:{}}}),t=x.collectHiddenCells(b,c);b.forEach(function(a,b){var d=p[b];a.attributes&&a.attributes.height&&(d.style.height=h.ptToPx(a.attributes.height));if(a.tags&&a.tags.length){var m=0;if(w){var q=
[],e=[],g=0;a.tags.forEach(function(a){for(;x.isHidden(t,g,b);)g++;g<k?q.push(a):e.push(a);g++});var n=Math.round((f.length-k)/w);a.tags=q;for(var l=0;l<n;l++)a.tags=a.tags.concat(e)}a.tags.forEach(function(a){for(;x.isHidden(t,m,b);)m++;if(f[m]){var q=f[m].field,e=a.attributes||{},g=d.style.fields[q]={};u.parseTableCellAttributes(e,g,c);e.width&&r._parseSpannedCellsDimentions(e,p,f,b,m);var k=Number(e.colspan),e=Number(e.rowspan);k&&(d.columnSpans=d.columnSpans||{},d.columnSpans[q]=k);e&&(d.rowSpans=
d.rowSpans||{},d.rowSpans[q]=e);try{r._parseCellContent(a,d,q,g,c)}catch(E){console.log(E)}m++}})}})}b={id:"table",customName:a.attributes.customName,backgroundSectionJson:g&&r._parseTableBackgroundForeground(g,c,!0),foregroundSectionJson:e&&r._parseTableBackgroundForeground(e,c,!1),backgroundFloatingTablesSectionJson:m&&r._parseFloatingPanels(m,c,!0),foregroundFloatingTablesSectionJson:q&&r._parseFloatingPanels(q,c,!1),data:{columns:f,data:p||[]},style:{width:h.ptToPx(a.attributes.width),left:h.ptToPx(a.attributes.left),
top:h.ptToPx(a.attributes.spaceBefore),spaceAfter:h.ptToPx(a.attributes.spaceAfter),alternatingStyle:a.attributes.alternatingStyle,opacity:a.attributes.opacity?Number(a.attributes.opacity):void 0,fixedCellsOpacity:a.attributes.fixedCellsOpacity?Number(a.attributes.fixedCellsOpacity):void 0},attributes:{},presetFilter:n&&c.parsers.getParser("filter").getFilter(n),noChartView:!!a.attributes.noChartView};var v=d&&c.parsers.getParser("sorting").getSorting(d);if(v){var l;f.some(function(a,b){if(b===v.columnIndex)return l=
a.field,!0});l&&(v.field=l,delete v.columnIndex,b.presetSorting=v)}k&&(b.attributes.fixedColumns=k);w&&(b.attributes.dynamicColumns=w);a.attributes.fixedRows&&(b.attributes.fixedRows=Number(a.attributes.fixedRows)||0);a.attributes.dynamicRows&&(b.attributes.dynamicRows=Number(a.attributes.dynamicRows)||0);b.attributes.inSectionRole=a.attributes.inSectionRole;return b},_processTableColumns:function(a,c,b){if(b&&b.fixTableWidthsForPage&&(c=h.pxToPt(B.getPageBox(c.documentOptions).contentW),a.attributes.widths&&
Number(a.attributes.width)>c)){b=h.splitTrim(a.attributes.widths,";",!0);var f=Number(a.attributes.width)-c,k=Number(b[b.length-1]);k>f&&(b[b.length-1]=k-f,a.attributes.widths=b.join(";"),a.attributes.width=c)}var w=0;return a.attributes.widths?h.splitTrim(a.attributes.widths,";",!0).map(function(a){return{field:"field"+w++,style:{width:h.ptToPx(a)}}}):[]},_getTableOuterTags:function(a,c){var b=[],f,k,h,d,g,e;1.1<=c.revisionVersion?a.tags&&a.tags.forEach(function(a){if("tr"===a.name)b.push(a);else if("filter"===
a.name)g=a;else if("sorting"===a.name)e=a;else switch(a.attributes.type){case l.TABLE_BACKGROUND:f=a;break;case l.TABLE_FOREGROUND:k=a;break;case l.TABLE_BACKGROUND_FLOATING_PANELS:h=a;break;case l.TABLE_FOREGROUND_FLOATING_PANELS:case l.TABLE_FLOATING_PANELS:d=a}}):a.tags&&a.tags.forEach(function(a){"tr"===a.name?b.push(a):"background"===a.name?f=a:"foreground"===a.name?k=a:"floatingElements"===a.name&&(d=a)});return{trTags:b,bgTag:f,fgTag:k,backgroundFloatingPanelsTag:h,foregroundFloatingPanelsTag:d,
filterTag:g,sortingTag:e}},_processTdContent:function(a,c){function b(a){a=a.tags&&1===a.tags.length&&a.tags[0];if(!a||!a.tags)return null;"b"===a.name?c.fontWeight="bold":"i"===a.name?c.fontStyle="italic":"u"===a.name&&(c.textDecoration="underline");return"b"===a.name||"i"===a.name||"u"===a.name?b(a)||{tag:a.tags[0],parentTag:a}:null}var f,k,h,d,g;if(a.tags&&a.tags.length){f=p.queryTopJson(a,"trigger")[0];var e=p.queryTopJson(a,"d")[0];k=(k=e&&p.queryTopJson(e,"dataDrillingPanels")[0]||p.queryTopJson(a,
"dataDrillingPanels")[0])&&p.queryTopJson(k,"dataDrillingPanel")[0];h=e&&p.queryTopJson(e,"tooltip")[0];g=a.tags.filter(function(a){return"br"!==a.name});d=e?e:g[0];if(f&&e)d=e;else{var m=b(a);d=m&&m.tag||e||g[0];a=m&&m.parentTag||a}}return{mainTag:d,triggerTag:f,ddTag:k,tooltipTag:h,parentTag:a,hasMultipleTags:g&&1<g.length}},_parseSpannedCellsDimentions:function(a,c,b,f,k){if(a.spannedWidths||a.spannedHeights){var l=a.spannedWidths?a.spannedWidths.split(";").map(function(a){return h.ptToPx(a)}):
[h.ptToPx(a.width)];a=a.spannedHeights?a.spannedHeights.split(";").map(function(a){return h.ptToPx(a)}):[h.ptToPx(a.height)];for(var d=0;d<l.length;d++)for(var g=0;g<a.length;g++){var e=b[k+d],m=c[f+g],e=m.style.fields[e.field]=m.style.fields[e.field]||{};e.width=l[d];e.height=a[g]}}},_parseCellContent:function(a,c,b,f,k){function l(a){p.isRichText(a)?c.fieldInfos[b]=A.createFieldInfoFromRichText(a):c[b]=p.unrichHTML(a)}var d=r._processTdContent(a,f);a=d.mainTag;var g=d.parentTag,e=d.triggerTag,m=
d.ddTag,q=d.tooltipTag,d=d.hasMultipleTags,n;if(d&&!e&&!m&&!q){var u=k.parsers.getParser("field").parseRichTextTag(g,k);u&&(c.fieldInfos[b]=u,n=!0)}if(a&&!n){k.report.isGraphicReport&&"section"===a.name&&!a.attributes.style&&f.backgroundColor&&!D.isTransparent(f.backgroundColor)&&(a.attributes.style=h.composeStyleString({backgroundColor:f.backgroundColor}),delete f.backgroundColor);var t;try{t=k.parsers.getParser("field").parseField(a,g,k,e,m,q)}catch(v){console.log(v),t=z.createFieldInfoForUnsupportedContent()}if(!1===
t)n=!0;else if("number"===typeof t)c[b]=t+"",n=!0;else if(t)c.fieldInfos[b]=t,n=!0;else if("chart"===a.name)n=!0;else if("img"===a.name)n=!0;else if("mapImage"===a.name)n=!0;else if("text"===a.name)c[b]=a.attributes.name,n=!0;else if("a"===a.name&&a.tags&&a.tags[0].text){if(f=a.attributes.href)c.urls=c.urls||{},c.urls[b]=f,c[b]=a.tags[0].text,n=!0}else a.text&&!d&&(l(a.text),n=!0)}n||l(p.getInnerHTML(g))},_parseTableBackgroundForeground:function(a,c,b){a.attributes=a.attributes||{};a.attributes.type=
b?l.TABLE_BACKGROUND:l.TABLE_FOREGROUND;return c.parsers.getParser("section").parseSection(a,c)},_parseFloatingPanels:function(a,c,b){a.attributes=a.attributes||{};a.attributes.type=b?l.TABLE_BACKGROUND_FLOATING_PANELS:l.TABLE_FOREGROUND_FLOATING_PANELS;return c.parsers.getParser("section").parseSection(a,c)}};r.parseTableCellAttributes=u.parseTableCellAttributes;return r});