// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.33/esri/copyright.txt for details.
//>>built
var __extends=this&&this.__extends||function(){var t=function(h,k){t=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(k,n){k.__proto__=n}||function(k,n){for(var p in n)n.hasOwnProperty(p)&&(k[p]=n[p])};return t(h,k)};return function(h,k){function u(){this.constructor=h}t(h,k);h.prototype=null===k?Object.create(k):(u.prototype=k.prototype,new u)}}();
define("esri/arcade/featureset/sources/FeatureLayerMemory","require exports ../../../graphic ../support/FeatureSet ../support/IdSet ../support/shared ../../polyfill/promiseUtils ../../../geometry/Geometry ../../../geometry/geometryEngineAsync ../../../geometry/jsonUtils ../../../layers/Field".split(" "),function(t,h,k,u,n,p,g,w,r,x,v){return function(h){function b(a){var c=h.call(this,a)||this;c.source=[];a.spatialReference&&(c.spatialReference=a.spatialReference);c.types=a.types;c.geometryType=a.geometryType;
c.typeIdField=a.typeIdField;c.objectIdField=a.objectIdField;c.fields=a.fields.slice(0);c.source=a.source;c._transparent=!0;c._maxProcessing=1E3;c._wset=null;return c}__extends(b,h);b.prototype._maxQueryRate=function(){return p.defaultMaxRecords};b.prototype.load=function(){var a=this;null===this._loadPromise&&(this._loadPromise=g.create(function(c,l){a._initialiseFeatureSet();c(a)}));return this._loadPromise};b.prototype._initialiseFeatureSet=function(){this._databaseType=p.FeatureServiceDatabaseType.Standardised};
b.prototype.optimisePagingFeatureQueries=function(a){};b.prototype.relationshipMetaData=function(){return[]};b.prototype.nativeCapabilities=function(){return{title:"",source:this,canQueryRelated:!1,capabilities:{query:{maxRecordCount:1E3},queryRelated:{supportsOrderBy:!1,supportsPagination:!1}},databaseType:this._databaseType,requestStandardised:!1}};b.prototype._allFeatures=function(){return this.source};b.prototype._isInFeatureSet=function(a){return p.IdState.InFeatureSet};b.prototype.isTable=function(){return null===
this.geometryType||""===this.geometryType};b.prototype._transformSetWithIdChanges=function(a){};b.prototype._candidateIdTransform=function(a){return a};b.prototype._getSet=function(a){var c=this;return null===this._wset?this._ensureLoaded().then(function(){return c._getFilteredSet("",null,null,null,a)}).then(function(a){return c._wset=a}):g.resolve(this._wset)};b.prototype._getFilteredSet=function(a,c,l,d,b){var e=this;try{return this._ensureLoaded().then(function(){if(e.isTable()&&c&&null!==a&&""!==
a)return new n([],[],!0,null);if(null===e._wset){var d=[];e._allFeatures().forEach(function(a){void 0===a.geometry&&(a.geometry=null);var c=a.attributes[e.objectIdField];d.push(c);e._featureCache[c]=a});e._wset=new n([],d,!1,null)}var g=e._wset._known.slice(0);e._checkCancelled(b);return e.fetchAndRefineFeaturesByWhere(g,l,b).then(function(d){e._checkCancelled(b);return null!==c?e.fetchAndRefineFeaturesSpatially(d,c,a,b).then(function(a){return new n([],a,!1,null)}):new n([],d,!1,null)})})}catch(y){return g.reject(y)}};
b.prototype.executeSpatialRelationTest=function(a,c,b,d){if(null===a.geometry)return g.resolve(!1);switch(c){case "esriSpatialRelEnvelopeIntersects":return c=p.shapeExtent(b),a=p.shapeExtent(a.geometry),r.intersects(c,a);case "esriSpatialRelIntersects":return r.intersects(b,a.geometry);case "esriSpatialRelContains":return r.contains(b,a.geometry);case "esriSpatialRelOverlaps":return r.overlaps(b,a.geometry);case "esriSpatialRelWithin":return r.within(b,a.geometry);case "esriSpatialRelTouches":return r.touches(b,
a.geometry);case "esriSpatialRelCrosses":return r.crosses(b,a.geometry);case "esriSpatialRelRelation":return r.relate(b,a.geometry,d)}};b.prototype.executeWhereTest=function(a,c){return c.testFeature(a)};b.prototype.fetchAndRefineFeaturesSpatially=function(a,c,b,d){var e=[];d=[];var l="";0<=b.indexOf("esriSpatialRelRelation")&&(l=b.split(":")[1],b="esriSpatialRelRelation");for(var k=0;k<a.length;k++){var n=this._featureFromCache(a[k]);d.push(this.executeSpatialRelationTest(n,b,c,l))}return 0===d.length?
g.resolve(e):g.all(d).then(function(c){for(var b=0;b<a.length;b++)!0===c[b]&&e.push(a[b]);return e})};b.prototype.fetchAndRefineFeaturesByWhere=function(a,c,b){b=[];if(null===c)return g.resolve(a);for(var d=0;d<a.length;d++){var e=this._featureFromCache(a[d]);this.executeWhereTest(e,c)&&b.push(a[d])}return g.resolve(b)};b.prototype._getFeatures=function(a,b,l,d){d=[];-1!==b&&void 0===this._featureCache[b]&&d.push(b);for(var c=a._lastFetchedIndex;c<a._known.length&&!(a._lastFetchedIndex+=1,void 0===
this._featureCache[a._known[c]]&&(a._known[c]!==b&&d.push(a._known[c]),d.length>l));c++);return 0===d.length?g.resolve("success"):g.reject(Error("Unaccounted for Features. Not in Feature Collection"))};b.prototype._refineSetBlock=function(a,b,l){return g.resolve(a)};b.prototype._stat=function(a,b,l,d,e,k,n){return g.resolve({calculated:!1})};b.prototype._canDoAggregates=function(a,b,l,d,e){return g.resolve(!1)};b._cloneAttr=function(a){var b={},l;for(l in a)b[l]=a[l];return b};b.create=function(a,
c){var l=c.toJson(),d=a.layerDefinition.objectIdField,e=a.layerDefinition.geometryType,g=a.layerDefinition.typeIdField?a.layerDefinition.typeIdField:"",n=[];if(a.layerDefinition.types)for(var h=0,f=a.layerDefinition.types;h<f.length;h++)n.push(f[h]);void 0===e&&(e=a.featureSet.geometryType);void 0===e&&(e="");h=a.featureSet.features;if(""===d||void 0===d){for(var m=!1,q=0,p=a.layerDefinition.fields;q<p.length;q++)if(f=p[q],"oid"===f.type||"esriFieldTypeOID"===f.type){d=f.name;m=!0;break}if(!1===m){d=
"FID";m=!0;for(q=0;m;){for(var p=!0,r=0,t=a.layerDefinition.fields;r<t.length;r++)if(f=t[r],f.name===d){p=!1;break}!0===p?m=!1:(q++,d="FID"+q.toString())}a.layerDefinition.fields.push({type:"esriFieldTypeOID",name:d,alias:d});f=[];for(m=0;m<h.length;m++)f.push({geometry:a.featureSet.features[m].geometry,attributes:a.featureSet.features[m].attributes?this._cloneAttr(a.featureSet.features[m].attributes):{}}),f[m].attributes[d]=m;h=f}}m=[];q=0;for(a=a.layerDefinition.fields;q<a.length;q++)f=a[q],f instanceof
v?m.push(f):m.push(new v(f));a=[];for(q=0;q<h.length;q++)f=h[q],f.geometry&&!1===f.geometry instanceof w&&void 0===f.geometry.spatialReference&&(f.geometry.spatialReference=l),a.push(new k(null===f.geometry||void 0===f.geometry?null:x.fromJson(f.geometry),null,f.attributes));return new b({source:a,types:n,typeIdField:g,fields:m,objectIdField:d,geometryType:e,spatialReference:c})};b.prototype.canBeBigDataFeatureSet=function(){return!1};b.prototype.shouldBeResolvedAsBigData=function(){return!1};b.prototype.queryAttachments=
function(a,b,l,d){return g.resolve([])};b.prototype.getFeatureByObjectId=function(a,b){b=0;for(var c=this.source;b<c.length;b++){var d=c[b];if(d.attributes[this.objectIdField]===a)return g.resolve(d)}return g.resolve(null)};return b}(u)});