// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.33/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/ReportPlayer/core/grid/coreUtils/tooltip/GridCellTooltipBuilder","dojo/_base/declare ../GridDataUtil ../../../supportClasses/conditionalStyling/ConditionalStyleLegendBuilder ../../../supportClasses/templateJsonUtils/fieldInfo/FieldInfoNameUtil ../../../supportClasses/templateJsonUtils/fieldInfo/FieldInfoRenderer ../../../supportClasses/WidgetQueryUtil ../../valueField/supportClasses/TextRenderer ./_ScriptExpressionBuilder esri/dijit/geoenrichment/utils/ObjectUtil esri/dijit/geoenrichment/utils/TooltipUtil esri/dijit/geoenrichment/ReportPlayer/config dojo/i18n!esri/nls/jsapi".split(" "),
function(p,e,q,t,w,x,y,z,n,A,u,l){l=l.geoenrichment.dijit.ReportPlayer.Grid;var B=p(null,{_cell:null,_content:"",constructor:function(a){this._cell=a},getContent:function(){return this._content?"\x3cdiv class\x3d'esriGEAdjustableGridValueField_cellTooltipContent'\x3e"+this._content+"\x3c/div\x3e":null},addValue:function(a){this._content+="\x3cdiv class\x3d'esriGERowHigh esriGEAdjustableGridValueField_cellTooltipContentValue'\x3e"+a+"\x3c/div\x3e"},addImageValue:function(a){var b=e.getNumericCellValue(a);
isNaN(b)||"number"!==typeof b||(a=a.numberFormatFunction?a.numberFormatFunction(b):n.formatNumber(b),this._content+="\x3cdiv class\x3d'esriGERowHigh esriGEAdjustableGridValueField_cellTooltipContentValue'\x3e"+a+"\x3c/div\x3e")},addAlias:function(a){this._content+="\x3cdiv class\x3d'esriGERowHigh'\x3e\x3cb\x3e"+l.variable+"\x3c/b\x3e "+a+"\x3c/div\x3e"},buildRichText:function(a){var b=this._cell.parentGrid.viewModel.dynamicReportInfo;a=w.renderFieldInfoInTableCell(a,{previewValues:!0,fieldData:b&&
b.fieldData,isGraphicReport:!0,currentFeatureIndex:this._cell.parentGrid.currentFeatureIndex});this._content+="\x3cdiv class\x3d'esriGERowHigh'\x3e"+a.formattedValue+"\x3c/div\x3e"},addExpression:function(a,b){if(a=z.buildTooltipExpression(a,b))this._content+="\x3cdiv class\x3d'esriGERowHigh'\x3e"+l.variableIsBasedOnExpression+"\x3c/div\x3e",this._content+="\x3cdiv class\x3d'esriGERowHigh'\x3e"+a+"\x3c/div\x3e"},addConditionalStyleLegend:function(a){var b=e.getNumericCellValue(a),c=e.getConditionalFormatting(a);
a=e.getFieldInfo(a).isImage;this._content+=q.createLegendNode(c,a?"image":"text",b).outerHTML},addTextBlock:function(a){this._content+="\x3cdiv class\x3d'esriGERowHigh'\x3e"+a+"\x3c/div\x3e"},addSeparator:function(){this._content+="\x3cdiv class\x3d'esriGERowHigh esriGEAdjustableGridValueField_cellTooltipContentSeparator'\x3e\x3c/div\x3e"}}),C=/<\w/,D={value:!1,alias:!0,expression:!1,conditional:!1},c={setDynamicTooltipToCell:function(a,b,k){if((a.hasOverflowText()||e.isVariableLikeFieldCell(a)||
e.isImageTriggerCell(a))&&c.isTooltipVisible(a)){var g=c.getTooltipInfo(a),d=c.getSourceFieldInfo(a),d=d&&!(!d.script&&!d.expressionText)&&g.expression,g=!!g.fieldInfo,g=d||g;a.own(A.setTooltipToNode(a.domNode,function(){return c.renderCellTooltip(a,b,k)},{classes:"esriGEAdjustableGridValueField_cellTooltip",notRestricted:d,stayOnHover:g,classes:g?null:["esriGENonInteractable"],style:c.getTooltipStyleFunc(a)}))}},getTooltipInfo:function(a){var b=c.getSourceFieldInfo(a);return b&&b.tooltipInfo?b.tooltipInfo:
(a=x.getReportContainerGrid(a))&&a.tooltipInfo&&a.tooltipInfo.table||D},isTooltipVisible:function(a){var b=c.getSourceFieldInfo(a);if(b&&b.dataDrillingPanelInfo)return!1;a=c.getTooltipInfo(a);return a.value||a.alias||a.expression||a.conditional||a.fieldInfo},getSourceFieldInfo:function(a){var b=e.getFieldInfo(a);a=e.getConditionalFormatting(a);return b&&b.isImage?a&&a.fieldInfo:b},getTooltipStyleFunc:function(a){return function(){return c.getTooltipStyle(a)}},getTooltipStyle:function(a){if(!a.parentGrid)return null;
var b={},e=a.parentGrid.viewModel.getCurrentTheme(a.parentGrid.theme).table.tooltip;n.copyOwnJsonProperties(e,b);n.copyOwnJsonProperties(c.getTooltipInfo(a).style,b);return b},renderCellTooltip:function(a,b,k){k=k||{};var g=k.getExpression||function(a){return u.modules.complexCellTooltips&&a.expressionText},d=y.getFullText(a),m=e.getFieldInfo(a),l=m&&m.isImage,n=e.isVariableLikeFieldCell(m),p=e.getConditionalFormatting(a),v=c.getSourceFieldInfo(a),q=m&&m.isRichText||d&&C.test(d),f=new B(a),h=c.getTooltipInfo(a);
n?(h.value&&d&&f.addValue(d),h.alias&&f.addAlias(t.getFieldInfoAlias(m))):l?(h.value&&f.addImageValue(a),h.alias&&f.addAlias(t.getFieldInfoAlias(v))):d&&!q&&h.value&&d&&f.addValue(d);h.fieldInfo&&f.buildRichText(h.fieldInfo);if(h.expression){var r=g(v);r&&f.addExpression(r,b)}h.conditional&&p&&u.modules.complexCellTooltips&&(r&&f.addSeparator(),k.conditionalLegendDesc&&f.addTextBlock(k.conditionalLegendDesc),f.addConditionalStyleLegend(a));return f.getContent()}};return c});