// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.33/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/ReportPlayer/dataProvider/supportClasses/tasks/parsers/DataXMLParser","esri/units esri/dijit/geoenrichment/utils/FieldUtil esri/dijit/geoenrichment/utils/JsonXmlConverter ../../data/AreaDataUtil ../../../../core/supportClasses/DocumentOptions ./AttrUtil esri/dijit/geoenrichment/ReportPlayer/config esri/dijit/geoenrichment/ReportPlayer/_devConfig".split(" "),function(k,q,h,r,t,u,v,n){function l(b){return b.innerHTML?b.innerHTML:b.tags&&b.tags.length&&b.tags[0].text||
""}function w(b){var g={Title:null,Subtitle:null,country:null,hierarchyId:null,exportSettings:null};b.tags&&b.tags.forEach(function(a){"ReportTitle"===a.name&&(g.Title=l(a));"ReportTitle2"===a.name&&(g.Subtitle=l(a));if("CurrencyFormat"===a.name){a=l(a);var e=a.split(";")[0].replace("0","").trim();g.country={id:null,currencySymbol:e,currencyFormat:a}}else if("ReportLayout"===a.name){var d=g.exportSettings={};a.tags.forEach(function(c){if("Options"===c.name&&c.attributes)d.addHeader=!!c.attributes.header,
d.addDataSource=!!c.attributes.dataSource,d.addFooter=!!c.attributes.footer;else if("Page"===c.name&&c.attributes){d.pageSettings={};var f=c.attributes;if(f.width&&f.height&&f.units){c=Number(f.width);var a=Number(f.height);if(f=f.units===k.MILLIMETERS?"mm":f.units===k.CENTIMETERS?"cm":f.units===k.INCHES?"in":f.units===k.POINTS?"pt":null)d.pageSettings.pagesize=t.combineCustomSizeString(c,a,f)}else f.size&&f.orientation&&(d.pageSettings.pagesize=f.size.toLowerCase(),d.pageSettings.orientation=f.orientation.toLowerCase())}})}});
return g}function x(b){function g(a){e.sites=a.tags.map(function(a){var f={attributes:null,notes:null,images:null};a.tags&&a.tags.forEach(function(a){"Attributes"===a.name&&a.tags&&(f.attributes=a.tags.map(function(a){return{name:a.attributes.Name,alias:a.attributes.Alias,type:a.attributes.Type,value:q.isNumericField(a.attributes.Type)?Number(a.attributes.Value):a.attributes.Value}}));"Notes"===a.name&&a.tags&&(f.notes=a.tags.map(function(a){return{text:a.attributes.Text}}));"Images"===a.name&&a.tags&&
(f.images=a.tags.map(function(a){return{url:a.attributes.Source,thumbnail:a.attributes.Thumbnail,description:a.attributes.Description,imageViewType:null}}))});return f})}function a(a){var c;e.stdLevels=a.tags.map(function(a,e){c=c||a.attributes.Id.substr(0,a.attributes.Id.indexOf("."));return{id:a.attributes.Id,name:a.attributes.Caption,isWholeCountry:a.attributes.IsWholeCountry||0===e}});"US"===c&&(e.countrId="US");"CAN"===c&&(e.countrId="CA")}var e={sites:null,stdLevels:null,countrId:null};b.tags.forEach(function(e){"StudyAreas"===
e.name?g(e):"StandardGeographyLevels"===e.name&&a(e)});return e}function y(b,g){function a(a){if(a=function(a){var e={},b,k,m;a.tags.forEach(function(c){var d=l(c),h=d,p=f[a.name][c.name];"string"===(p&&p.type)?d=String(d):(d=Number(d),isNaN(d)&&(d=h),n.emulateErrors.createReportNaN&&(d=NaN),n.emulateErrors.createReportNull&&(d=null));g&&(d=g(c.name,d,a.name));void 0===e[c.name]&&(e[c.name]=d);"AREA_ID"===c.name&&(b=d);"IDFNDFIELD"===c.name&&(k=d);"STORE_ID"===c.name&&(m=d)});b=b||k;if(!b&&!m)return null;
var h;!b&&m&&(h=Number(m));b&&void 0===d[b]&&(d[b]=c++);u.cleanUpAttrs(e,v.isPlayerOnServer?{STORE_ID:1}:null);return{name:a.name,attrs:e,areaIndex:void 0!==h?h:d[b]}}(a)){var b=e[a.areaIndex]=e[a.areaIndex]||{};b[a.name]?b[a.name].comparisonLevels.push(a.attrs):b[a.name]=r.createCalculator(a.attrs)}}var e=[],d={},c=0,f;b.tags[0].tags.forEach(function(c){"xs:schema"===c.name?f=z.parseSchema(c):a(c)});return{areaData:e,schemaParseResult:f}}var z={parseSchema:function(b){var g={};b.tags.forEach(function(a){"xs:element"===
a.name&&a.attributes&&"ReportData"===a.attributes.name&&h.queryJson(a,"xs:element").filter(function(a){return!!a.tags}).forEach(function(a){var b=g[a.attributes.name]={};h.queryJson(a,"xs:element").forEach(function(a){b[a.attributes.name]={type:"xs:string"===a.attributes.type?"string":"number",alias:a.attributes["msdata:Caption"]||"",vintage:a.attributes["msdata:Vintage"]||"",source:a.attributes["msdata:Source"]||""}})})});return g}};return{parse:function(b,g){return this._parseDataXmlJson(h.parseXml(b,
{saveInnerHTML:!0}),g)},_parseDataXmlJson:function(b,g){if(!b||!b.tags||2>b.tags.length)return[];var a,e,d,c;b.tags.forEach(function(b){"ReportInfo"===b.name?a=w(b):"ReportArea"===b.name?e=x(b):"ReportData"===b.name&&(b=y(b,g),c=b.areaData,d=b.schemaParseResult)});n.logData&&(console.log("DataXMLPareser.js \x3d\x3e areaData:"),console.log(c));e&&(a.country.id=e.countrId,a.sites=e.sites,a.stdLevels=e.stdLevels);a.variables=d;return{reportInfo:a,areaData:c}}}});