// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.33/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/ReportPlayer/core/charts/tooltips/ChartTooltip","dojo/_base/declare dojo/_base/lang dojo/string dojo/dom-construct ./ZoomSupportTooltip ./_BuilderUtil ./_ColumnBarChartTooltipBuilder ./_GaugeChartTooltipBuilder ./_WaffleChartTooltipBuilder ./_LineChartTooltipBuilder ./_PieDonutRingChartTooltipBuilder ../utils/ChartTypes ../../supportClasses/conditionalStyling/ConditionalStyleLegendBuilder ../../dataDrilling/DataDrillingVisualizer ../../supportClasses/WidgetQueryUtil dojo/i18n!esri/nls/jsapi".split(" "),
function(l,n,p,h,q,r,t,u,v,w,x,g,y,z,A,k){function m(a,b,d){a._hide();var e=new z({viewModel:b.viewModel,theme:b.theme,parentWidget:b.chartContainer,getPreviewValueFunction:r.buldPreviewValueFunction(b,{type:"dataDrilling"}),domNode:d,closeZoomedDDWhenClickedOutside:!0,closeZoomedDDOnEsc:!0,onClose:function(){e.play(!1,!0)}});e.play(!0,!0,null,b.dataDrillingPanelInfo.sectionJson)}k=k.geoenrichment.dijit.ReportPlayer.ChartTooltip;var f={lastShownInfo:null,setInfo:function(a){(f.lastShownInfo=a)&&setTimeout(function(){f.lastShownInfo===
a&&(f.lastShownInfo=null)},6E4)}};l=l(q,{tooltipClass:"esriGEChartContainer_chartTooltip_masterTooltip",_chartType:null,constructor:function(){var a=this,b=this.text;this.text=function(d,e){var c;c=d.run&&d.run.data&&d.run.data[d.index];c=c.tooltip&&"object"===typeof c.tooltip?a._renderTooltip(c.tooltip):void 0;return c||b(d,e)}},_needSetRectFromShape:function(){return g.isPictureLike(this._chartType)},setChartType:function(a){this._chartType=a},_renderTooltip:function(a){a=n.mixin({},a,a.getContext());
var b=!a.viewModel.dynamicReportInfo,d=b&&!a.viewModel.isGraphicStyle,e=!A.isDataDrillingView(a.chartContainer);(a.viewModel.enableDataDrilling||b)&&e||delete a.dataDrillingPanelInfo;var c=h.create("div",{"class":"esriGEChartContainer_chartTooltip"},document.body);if(!d)if(a.richTextFieldInfo||a.showTitle||a.showValue||a.showMin||a.showMax||a.showAvg||a.showWeight||a.showConditional||a.dataDrillingPanelInfo)this._buildTooltip(a,c,b,e);else if(b)h.create("div",{"class":"chartTooltip_row esriGERowHigh",
innerHTML:k.noTooltipAvailable},c);else return{node:null};f.setInfo(a.dataDrillingPanelInfo&&a.dataDrillingPanelInfo.showOnClick&&!b?{tooltip:this,info:a,root:c}:null);document.body.removeChild(c);return{node:c,style:a.tooltipStyle}},_buildTooltip:function(a,b,d,e){var c=this;this._chartType===g.PIE||this._chartType===g.DONUT||this._chartType===g.RING?x.buildPieDonutRingChartTooltip(a,b):this._chartType===g.GAUGE?u.buildGaugeChartTooltip(a,b):this._chartType===g.WAFFLE?v.buildWaffleChartTooltip(a,
b):g.isColumnBarLike(this._chartType)?t.buildColumnChartTooltip(a,b):g.isLineLike(this._chartType)&&w.buildLineChartTooltip(a,b);a.conditionalStyling&&a.showConditional&&h.place(y.createLegendNode(a.conditionalStyling,"chart",a.isBenchmarked?a.unbenchmarkedValue:a.value),b);if(a.dataDrillingPanelInfo||d&&e){var f=h.create("div",{"class":"chartTooltip_row esriGERowHigh esriGECenter",style:"margin-top:20px;"},b);(e=d&&!a.dataDrillingPanelInfo)||h.create("div",{"class":"dijitInline esriGESpaceAfterMedium",
innerHTML:p.substitute('\x3csvg xmlns\x3d"http://www.w3.org/2000/svg" width\x3d"16" height\x3d"16" viewBox\x3d"0 0 32 32"\x3e\x3cpath fill\x3d"${fill}" d\x3d"M30 28v1H3V4h1v24h2v-9h6v9h2V6h6v22h2V13h6v15h2z"/\x3e\x3c/svg\x3e',{fill:a.tooltipLinkStyle.color})},f);f=h.create("div",{"class":"dijitInline esriGELink",innerHTML:d?a.dataDrillingPanelInfo?k.drillForMoreDataEdit:k.addDataDrilling:k.drillForMoreData},f);e||(f.style.color=a.tooltipLinkStyle.color);f.addEventListener("click",function(){d?(c._hide(),
a.chartContainer.onShowDataDrillingPreview(a)):m(c,a,b)})}}});l.tryShowDataDrillingForShownTooltip=function(){var a=f.lastShownInfo;a&&m(a.tooltip,a.info,a.root)};return l});