// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.33/esri/copyright.txt for details.
//>>built
define("esri/layers/rasterLib/tile/RasterTileManager","dojo/_base/declare dojo/_base/lang dojo/Deferred dojo/when ../DeferredList2 ../../../geometry/Extent ../../../SpatialReference ../../../geometry/Point ../../PixelBlock ./RasterTileInfo ../raster/rasterProjectionHelper".split(" "),function(E,p,u,C,D,z,F,G,A,J,y){var H=function(a,b){var c;for(c=0;c<a.length;c++)if(b(a[c]))return a[c]},I=function(a,b){var c;for(c=0;c<a.length;c++)if(b(a[c]))return c;return-1};return E(null,{declaredClass:"esri.layers.rasterLib.tile.RasterTileManager",
count:null,fullBoundary:null,tileBoundary:null,tiles:null,resolution:null,virtual:!0,prefetchBufferSize:0,_progressiveGlobal:!1,_MAX_TILES:128,_defaultMatrixResolution:20,constructor:function(a){this.tiles=[];this.tileInfo=a&&a.tileInfo;this.mapSpatialReference=a&&a.mapSR;this.virtual=this.tileInfo.virtual;this.layer=a&&a.layer;this.identifiers=this.layer.raster.rasterFunction?this.layer.raster.getMemberRasters().map(function(a){return a._rasterId}):[this.layer.raster._rasterId];a=!this.virtual&&
!this.mapSpatialReference.equals(this.tileInfo.spatialReference);var b=y.requirePE(this.mapSpatialReference,this.tileInfo.spatialReference);this.xformSetting={requireProjection:a,requirePE:b,meshSize:a?[this._defaultMatrixResolution,this._defaultMatrixResolution]:[1,1]}},setTileInfo:function(a){this.tileInfo=a;this.virtual=a.virtual;this.mapResolution=null;this.tiles.length=0;this.xformSetting.requireProjection=!this.virtual&&!this.mapSpatialReference.equals(this.tileInfo.spatialReference);this.xformSetting.requirePE=
y.requirePE(this.mapSpatialReference,this.tileInfo.spatialReference);this.xformSetting.meshSize=this.xformSetting.requireProjection?[this._defaultMatrixResolution,this._defaultMatrixResolution]:[1,1]},updateResolution:function(a,b){if(!(this.mapResolution&&a&&this._resolutionEqual(this.mapResolution.x,a.x)&&this._resolutionEqual(this.mapResolution.y,a.y))){this.tiles.forEach(p.hitch(this,function(a){a.fetch&&!a.fetch.isCanceled()&&a.fetch.cancel();a.update&&!a.update.isCanceled()&&a.update.cancel()}));
this.tiles.length=0;var c=this.xformSetting.requireProjection;this.mapResolution=this.resolution=a;c&&(this.resolution=y.projectResolution(a,this.tileInfo.spatialReference,this.layer.projectedFullExtent||b));var d=this._resolution=this.resolution;if(!this.tileInfo.virtual){b=H(this.tileInfo.lods,function(a){return Math.abs(a.resolution-d.x)<.01*d.x});if(!b)if(d.x>this.tileInfo.lods[0].resolution)b=this.tileInfo.lods[0],this.ooe=!0;else{if(d.x<this.tileInfo.lods[this.tileInfo.lods.length-1].resolution)b=
this.tileInfo.lods[this.tileInfo.lods.length-1];else for(a=0;a<this.tileInfo.lods.length-1;a++)if(b=this.tileInfo.lods[a],c=this.tileInfo.lods[a+1],b.resolution>d.x&&c.resolution<d.x){d.x/b.resolution>c.resolution/d.x&&(b=c);break}this.ooe=!1}this.level=b&&b.level;d=this.resolution=new G({x:b.resolution,y:b.resolution,spatialReference:this.tileInfo.spatialReference})}b=this.layer.raster.rasterInfo.extent;c=this.tileInfo.origin;a=this.tileInfo.cols;var e=this.tileInfo.rows;this.fullBoundary={rowStart:Math.floor((c.y-
b.ymax)/d.y/e),rowEnd:Math.ceil((c.y-b.ymin-d.y)/d.y/e),colStart:Math.floor((b.xmin-c.x)/d.x/a),colEnd:Math.ceil((b.xmax-c.x-d.x)/d.x/a)};if(b=b.spatialReference._getInfo())this.fullBoundary.colRange=Math.round((b.valid[1]-b.valid[0])/d.x/a);this.hasNewData=!0}},getXformGrid:function(){var a=this.mapExtent,b=this.layer._hasTilingEffects?this.extent:this.fullExtent,c=this.layer.getCurrentResolution(),d=JSON.stringify(a.toJson())+JSON.stringify(b.toJson());this._cachedExtentString&&this._cachedExtentString===
d||(this._cachedExtentString=d,this._xformGrid=a=y.getProjectionOffsetGrid(a,b,c));a=this._xformGrid;this.xformSetting.meshSize=a&&a.size;return a},updateExtent:function(a,b){this.mapExtent=this.extent=a;var c=this.xformSetting.requireProjection;if(c){this.extent=y.project(a,this.tileInfo.spatialReference);if(!this.extent)return;this.extent.spatialReference=new F(this.extent.spatialReference.toJson())}this.updateResolution(b,a);a=this.extent;var d=this.tileInfo,e=d.cols,f=d.rows;b=this.resolution;
var g=a,c=c?this.layer.raster.rasterInfo.extent:this.layer.raster.projectedFullExtent;this.ooe&&(g=this._getIntersect(a,c));var l=g.xmin,c=g.xmax;if(c<l){var k=a.spatialReference._getInfo();k&&(c+=Math.ceil((l-c)/(k.valid[1]-k.valid[0]))*(k.valid[1]-k.valid[0]));g.xmax=c}var l=Math.floor((l-d.origin.x)/b.x/e)-this.prefetchBufferSize,k=Math.floor((c-d.origin.x)/b.x/e)+this.prefetchBufferSize,n=Math.floor((d.origin.y-g.ymax)/b.y/f)-this.prefetchBufferSize,B=Math.floor((d.origin.y-g.ymin)/b.y/f)+this.prefetchBufferSize;
this.tileBoundary={rowStart:n,rowEnd:B,colStart:l,colEnd:k};var h,m,q;if((B-n+1)*(k-l+1)>this._MAX_TILES||!this.virtual&&this._resolution.x>8*this.tileInfo.lods[0].resolution)this.tiles.forEach(p.hitch(this,function(a){a.fetch&&!a.fetch.isCanceled()&&a.fetch.cancel();a.update&&!a.update.isCanceled()&&a.update.cancel()})),this.tiles.length=0;else{var c=this.tiles,g=!1,r=this.fullBoundary&&this.fullBoundary.colRange,v=0;r&&(0>l||k>r)&&(this.wrapTimes=v=0>l?-1-Math.floor(-l/r):Math.floor(k/r));for(h=
c.length-1;0<=h;h--)if(m=c[h].row,q=c[h].col,v&&r&&(0>l||k>r)&&(q=q>k?v*r+q:q<l?v*r+q:q),m<n||m>B||q<l||q>k)c[h].fetch&&!c[h].fetch.isCanceled()&&c[h].fetch.cancel(),c[h].update&&!c[h].update.isCanceled()&&c[h].update.cancel(),c.splice(h,1),g=!0;var w;for(h=n;h<=B;h++)for(n=l;n<=k;n++)m=new z(d.origin.x+b.x*e*n,d.origin.y-b.y*f*(h+1),d.origin.x+b.x*e*(n+1),d.origin.y-b.y*f*h,a.spatialReference),w=r?0<=n?n%r:r- -n%r:n,q=I(c,function(a){return a.row===h&&a.col===w}),-1===q&&(c.push({row:h,col:w,cellsizeX:b.x,
cellsizeY:b.y,width:e,height:f,extent:m,normalizedExtent:this._wrapExtent(m),pixelBlock:null,virtual:this.virtual,level:this.level,tileType:this.tileInfo.tileType||"Raster"}),g=!0);g&&this._sortTiles();b=this.tileInfo.rows*(this.tileBoundary.rowEnd-this.tileBoundary.rowStart+1);this.width=this.tileInfo.cols*(this.tileBoundary.colEnd-this.tileBoundary.colStart+1);this.height=b;this.count=c.length;b=Math.min.apply(null,c.map(function(a){return a.extent.xmin}));d=Math.max.apply(null,c.map(function(a){return a.extent.xmax}));
e=Math.min.apply(null,c.map(function(a){return a.extent.ymin}));f=Math.max.apply(null,c.map(function(a){return a.extent.ymax}));b=this.fullExtent=new z(b,e,d,f,a.spatialReference);if(this.layer.roaming||this.layer.useWebGL)this.layer._hasTilingEffects?(this.xformSetting.offset=[0,0],this.xformSetting.scale=[1,1]):(g&&(this._tilesChanged=!0),this.xformSetting.offset=[(a.xmin-b.xmin)/(b.xmax-b.xmin),-(b.ymin-a.ymin)/(b.ymax-b.ymin)],this.xformSetting.scale=[(a.xmax-a.xmin)/(b.xmax-b.xmin),(a.ymax-a.ymin)/
(b.ymax-b.ymin)])}},fetchTiles:function(a){(this._tilesChanged||a)&&this._fetchTiles(a)},_fetchTiles:function(a){this._fetchCounter=0;var b=this.extent;this.fetchAllCompleted=a?new u:null;(this._tilesChanged||a&&this.layer._hasTilingEffects)&&this.tiles.forEach(p.hitch(this,function(a){a.updateCompleted=!1}));var c={};!this.layer.roaming&&this.layer._hasTilingEffects&&a?(this.identifiers.forEach(function(a,b){c[a]={extent:this.extent,pixelBlock:new A({width:this.layer._map.width,height:this.layer._map.height,
pixels:[],pixelType:"",mask:null,statistics:[]})}}.bind(this)),this.originalPixelData={extent:this.extent,src:c,isEmpty:!0}):this._tilesChanged&&(this.identifiers.forEach(function(a,b){c[a]={extent:this.fullExtent,pixelBlock:new A({width:128,height:128,pixels:[],pixelType:"",mask:null,statistics:[]})}}.bind(this)),this.originalPixelData={extent:this.fullExtent,src:c,isEmpty:!0});this.tiles.forEach(p.hitch(this,function(c){if(c.fetch)c.update||(c.update=this.updateTile(c));else{if(this._isTileOutSide(c,
b)){c.updateCompleted=!0;return}this._requestTile(c)}this.layer.roaming&&this.layer.useWebGL?this._fillPixelData(c):c.src&&a&&(this.layer._hasTilingEffects||this.layer.useWebGL)&&(this._fillPixelData(c),this.layer._hasTilingEffects&&(c.updateCompleted=!0),c.processedPixelBlock=null,c.renderedPixelBlock=null)}));0===this._fetchCounter&&(this._fetched=!0);this._tilesChanged=!1;a&&this._updateFetchStatus()},updateTile:function(a,b){var c=new u;if(!a.src&&!a.fetch)return c.resolve(a),c.promise;C(a.src||
a._fetched||a.fetch,p.hitch(this,function(){var d=this.layer.tileMode&&this.layer._rasterHandler&&!(this.layer._hasTilingEffects||this.layer.useWebGL),e=this.layer._drawTile,f=this._validateRawPixelBlocks(a);this.layer._hasTilingEffects&&!this.layer.useWebGL&&(e=e&&(this._progressiveGlobal||b));if((b||!b&&f)&&(d||e||this.layer.roaming)){if(this.xformSetting.requireProjection&&this.layer.useWebGL&&(this.xformSetting.gridConfig=this.getXformGrid(),null==this.xformSetting.gridConfig))return c.cancel(),
c.promise;this._processTile(a,b).then(p.hitch(this,function(a){c.isCanceled()||this._renderTile(a,b).then(p.hitch(this,function(a){this.hasNewData=!1;c.isCanceled()||c.resolve(a)}))}))}else b||f||(a.updateCompleted=!0),this.layer.useWebGL||this.layer._hasTilingEffects?c.resolve(this.originalPixelData):c.resolve()}));return c.promise},setLayer:function(a){this.layer=a},fillupTiles:function(){this.tiles.forEach(p.hitch(this,function(a){a.update&&a.updateCompleted&&!a.filled&&(a.updateCompleted=!1,this._fillPixelData(a),
a.updateCompleted=!0)}))},_validateRawPixelBlocks:function(a){return a&&a.src&&!this.identifiers.some(function(b){return!(a.src[b].pixelBlock&&0!==a.src[b].pixelBlock.validPixelCount&&a.src[b].pixelBlock.pixels&&0<a.src[b].pixelBlock.pixels.length)})},_wrapExtent:function(a){var b=a.spatialReference._getInfo(),c;if(b){var d=b.valid[0],b=b.valid[1];if(a.xmin<d-this.resolution.x||a.xmax>b+this.resolution.y)c=new z((a.xmin-d)%(b-d),a.ymin,(a.xmax-b)%(b-d),a.ymax,a.spatialReference),c.xmax<c.xmin&&(c=
null)}return c||a},_getIntersect:function(a,b){return new z(Math.max(a.xmin,b.xmin),Math.max(a.ymin,b.ymin),Math.min(a.xmax,b.xmax),Math.min(a.ymax,b.ymax),a.spatialReference)},_isTileOutSide:function(a,b){var c=!1,d,e;a.virtual?(e=a.normalizedExtent,(b=b||(this.xformSetting.requireProjection?this.layer.raster.rasterInfo.extent:this.layer.raster.projectedFullExtent))?(a=e.xmin-this.prefetchBufferSize*this.tileInfo.cols*this.resolution.x,c=e.ymin-this.prefetchBufferSize*this.tileInfo.rows*this.resolution.y,
d=e.xmax+this.prefetchBufferSize*this.tileInfo.cols*this.resolution.x,e=e.ymax+this.prefetchBufferSize*this.tileInfo.rows*this.resolution.y,c=d<=b.xmin||a>=b.xmax||e<=b.ymin||c>=b.ymax):c=!1):c=0>a.level||a.row<this.fullBoundary.rowStart||a.row>this.fullBoundary.rowEnd||a.col<this.fullBoundary.colStart||a.col>this.fullBoundary.colEnd;return c},_resolutionEqual:function(a,b){return a===b||a&&b&&Math.abs(a-b)<Math.abs(b/1E4)?!0:!1},_requestTile:function(a){var b,c=this.identifiers,d;this._isTileOutSide(a)?
(b=new u,a.updateCompleted=!0,b.resolve(null),b=b.promise):b=this.layer.raster.rasterFunction?new D(this.layer.raster.getMemberRasters().map(function(b){return b.read(a)})):new D([this.layer.raster.read(a)]);a.fetch=b;this._fetchCounter++;C(a.src||a._fetched||b,p.hitch(this,function(b){if(d=b&&b.some(function(a){return a[0]})){var e={};b.forEach(function(a,b){e[c[b]]=a[0]&&a[1]?{extent:a[1].extent,pixelBlock:a[1].pixelBlock,width:a[1].width,height:a[1].height}:null});a.src=e}else a.src=null;this._fetchCounter--;
0===this._fetchCounter&&(this._fetched=!0);a._fetched=!0;this._updateFetchStatus()}),p.hitch(this,function(){this._fetchCounter--;0===this._fetchCounter&&(this._fetched=!0);a._fetched=!0;this._updateFetchStatus()}));a.update=this.updateTile(a)},_updateFetchStatus:function(){this.layer._drawTile&&this.fetchAllCompleted&&!this.fetchAllCompleted.isResolved()&&!this.tiles.some(function(a){return!a._fetched})&&(this.tiles.forEach(p.hitch(this,function(a){this._fillPixelData(a)})),this.fetchAllCompleted.resolve())},
_fillPixelData:function(a,b){if(a&&!a.updateCompleted)if(Math.abs(a.cellsizeX-this.resolution.x)>a.cellsizeX/10)a.updateCompleted=!0;else if(!1===this._validateRawPixelBlocks(a))a.updateCompleted=!0;else{var c=a.extent,d,e,f;this.layer.roaming||this.layer.useWebGL&&!this.layer._hasTilingEffects?(d=this.fullExtent,e=this.tileInfo.cols*(this.tileBoundary.colEnd-this.tileBoundary.colStart+1),f=this.tileInfo.rows*(this.tileBoundary.rowEnd-this.tileBoundary.rowStart+1),b?this.originalPixelData.renderedPixelBlock||
(this.originalPixelData.renderedPixelBlock=new A({width:e,height:f,pixels:[],pixelType:"",mask:null,statistics:[]})):this.identifiers.forEach(p.hitch(this,function(a){this.originalPixelData.src[a].pixelBlock.width=e;this.originalPixelData.src[a].pixelBlock.height=f}))):(d=this.extent,e=this.layer._map.width,f=this.layer._map.height,b?this.originalPixelData.renderedPixelBlock||(this.originalPixelData.renderedPixelBlock=new A({width:e,height:f,pixels:[],pixelType:"",mask:null,statistics:[]})):this.identifiers.forEach(p.hitch(this,
function(a){this.originalPixelData.src[a].pixelBlock.width=e;this.originalPixelData.src[a].pixelBlock.height=f})));if(d.xmax<=c.xmin||d.xmin>=c.xmax||d.ymax<=c.ymin||d.ymin>=c.ymax)return null;var g=this.originalPixelData.isEmpty=!1;this.identifiers.forEach(p.hitch(this,function(b){a.src&&(this._fillPixelBlock(a.src[b],this.originalPixelData.src[b],{extent:d,width:e,height:f},!1),g=!0)}));a.filled=g;this.hasNewData=!0}},_fillPixelBlock:function(a,b,c,d){var e=a.extent,f=c.extent;d=c.width;c=c.height;
if(a.pixelBlock&&a.pixelBlock.pixels&&a.pixelBlock.pixels[0]){var g=(e.xmax-e.xmin)/a.width,l=Math.max(e.xmin,f.xmin),k=Math.min(e.ymax,f.ymax),n=Math.round((l-e.xmin)/g),p=a.width-Math.round(Math.abs(e.xmax-Math.min(e.xmax,f.xmax))/g),h=Math.round(Math.abs(e.ymax-k)/g),e=a.height-Math.round((Math.max(e.ymin,f.ymin)-e.ymin)/g),l=Math.round((l-f.xmin)/g),f=Math.round(Math.abs(f.ymax-k)/g),m,q,r,v,g=a.pixelBlock.pixels.length;b=b.pixelBlock;var k=a.width,w=b.mask||new Uint8Array(d*c),t=a.pixelBlock,
u=t.mask,x=0;for(q=0;q<g;q++){r=t.pixels[q];v=b.pixels[q]||new r.constructor(d*c);for(a=h;a<e;a++)for(x=(f+a-h)*d+l,m=n;m<p;m++)v[x+m-n]=r[a*k+m];b.pixels[q]=v}if(u)for(a=h;a<e;a++)for(x=(f+a-h)*d+l,m=n;m<p;m++)w[x+m-n]=u[a*k+m];else for(a=h;a<e;a++)for(x=(f+a-h)*d+l,m=n;m<p;m++)w[x+m-n]=1;b.pixelType=b.pixelType||t.pixelType;b.mask=w;if(!(b.statistics&&0<b.statistics.length))for(b.statistics=[],a=0;a<t.statistics.length;a++)b.statistics[a]={minValue:t.statistics[a].minValue,maxValue:t.statistics[a].maxValue};
else if(t.statistics&&b.statistics)for(a=0;a<b.statistics.length;a++)b.statistics[a].minValue=Math.min(t.statistics[a].minValue,b.statistics[a].minValue),b.statistics[a].maxValue=Math.max(t.statistics[a].maxValue,b.statistics[a].maxValue)}},_processTile:function(a,b){var c=new u,d,e=this.layer._hasTilingEffects,f=this.layer.useWebGL,g=e||f,l=this.layer.raster.rasterFunction&&a&&(e||f||!a.processedPixelBlock);b?d=a:(this._fillPixelData(a),d=g?this.originalPixelData:a);this.xformSetting.hasNewTexture=
this.hasNewData;var k;l?(this.identifiers.forEach(function(a){if(0===d.src[a].pixelBlock.pixels.length||0===d.src[a].pixelBlock.pixels[0].length)k=!0}),k?c.resolve({extent:d.extent,processedPixelBlock:d.src[this.identifiers[0]],pixelBlock:d.src[this.identifiers[0]]}):f?(this.processedPixelData=this.layer.raster.rasterFunction.read(d),c.resolve(this.processedPixelData)):this.layer._rasterHandler?this.layer._rasterHandler.process({extent:d.extent,src:d.src}).then(function(b){e?(this.processedPixelData=
b,c.resolve(this.processedPixelData)):(a.processedPixelBlock=b.pixelBlock,c.resolve(a))}):(b=this.layer.raster.rasterFunction.read(a),a.processedPixelBlock=b.pixelBlock,c.resolve(a))):g?c.resolve(d.src[this.identifiers[0]]):(a.pixelBlock=d.src[this.identifiers[0]]&&d.src[this.identifiers[0]].pixelBlock,c.resolve(a));return c.promise},_renderTile:function(a){var b=new u,c=this.layer._hasTilingEffects,d=this.layer.useWebGL,e=Math.abs((a.extent.xmax-a.extent.xmin)/a.width-this.layer.getCurrentResolution().x)>
this.resolution.x/10,e=this.layer.useWebGL&&(e||this._isTileOutSide(a,this.layer._map.extent));this.xformSetting.hasNewTexture=this.hasNewData;this.layer._rasterRenderer&&a&&(a.texture||a.src||a.pixelBlock||a.processedPixelBlock)?d&&!e?(this.layer.raster.rasterFunction&&this.layer.raster.rasterFunction.renderTexture||this.layer._rasterRenderer.draw(a),b.resolve(a)):this.layer._rasterHandler?this.layer._rasterHandler.render({extent:a.extent,pixelBlock:a.processedPixelBlock||a.pixelBlock}).then(function(d){c?
(d.renderedPixelBlock=d.pixelBlock,b.resolve(d)):(a.renderedPixelBlock=d.pixelBlock,b.resolve(a))}.bind(this)):(a.renderedPixelBlock=this.layer._rasterRenderer.draw(a).pixelBlock,b.resolve(a)):(a.renderedPixelBlock=a.processedPixelBlock||a.pixelBlock,b.resolve(a));return b.promise},_sortTiles:function(){this.tiles.sort(function(a,b){return a.row<b.row||a.row==b.row&&a.col<b.col?-1:1})}})});