// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.33/esri/copyright.txt for details.
//>>built
var __extends=this&&this.__extends||function(){var v=function(k,l){v=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(k,l){k.__proto__=l}||function(k,l){for(var p in l)l.hasOwnProperty(p)&&(k[p]=l[p])};return v(k,l)};return function(k,l){function p(){this.constructor=k}v(k,l);k.prototype=null===l?Object.create(l):(p.prototype=l.prototype,new p)}}();
define("esri/arcade/featureSetUtils","require exports ../request ./featureSetCollection ./featureset/sources/FeatureLayerDynamic ./featureset/sources/FeatureLayerDynamicMap ./featureset/sources/FeatureLayerMemoryMap ./featureset/sources/FeatureSetRelated ./featureset/support/cache ./featureset/support/shared ./polyfill/promiseUtils ./polyfill/sql/WhereClause ../arcgis/Portal ../layers/FeatureLayer ./featureset/actions/GroupBy".split(" "),function(v,k,l,p,A,B,C,D,h,y,q,E,F,r){function z(c){if(null!==
h.applicationCache){var b=h.applicationCache.getLayerInfo(c);if(null!==b)return b}b=l({url:c,content:{f:"json"},callbackParamName:"callback",handleAs:"json"}).then(function(d){return d?(d.layers||(d.layers=[]),d.tables||(d.tables=[]),q.resolve(d)):q.resolve({layers:[],tables:[]})});null!==h.applicationCache&&(h.applicationCache.setLayerInfo(c,b),b=b.catch(function(d){h.applicationCache.clearLayerInfo(c);throw d;}));return b}function G(c){if(null!==h.applicationCache){var b=h.applicationCache.getLayerInfo(c);
if(null!==b)return b}b=l({url:c,content:{f:"json"},callbackParamName:"callback",handleAs:"json"}).then(function(d){return d?q.resolve(d):q.resolve(null)});null!==h.applicationCache&&(h.applicationCache.setLayerInfo(c,b),b=b.catch(function(d){h.applicationCache.clearLayerInfo(c);throw d;}));return b}function H(c,b){var d="QUERYDATAELEMTS:"+b.toString()+":"+c;if(null!==h.applicationCache){var e=h.applicationCache.getLayerInfo(d);if(null!==e)return e}c=l({url:c+"/queryDataElements",usePost:!0,handleAs:"json",
content:{layers:JSON.stringify([b.toString()]),f:"json"}}).then(function(a){if(a&&a.layerDataElements&&a.layerDataElements[0])return a.layerDataElements[0];throw Error("Not Found");});null!==h.applicationCache&&(h.applicationCache.setLayerInfo(d,c),c=c.catch(function(a){h.applicationCache.clearLayerInfo(d);throw a;}));return c}function t(c,b,d,e,a){void 0===d&&(d=null);void 0===e&&(e=!0);void 0===a&&(a=null);null===d&&(d=["*"]);return new A({url:c,outFields:d,spatialReference:b,includeGeometry:e,
lrucache:a})}function u(c,b,d,e,a){void 0===d&&(d=null);void 0===e&&(e=!0);void 0===a&&(a=null);return q.resolve(t(c,b,d,e,a))}function w(c,b,d,e,a){void 0===b&&(b=null);void 0===d&&(d=null);void 0===e&&(e=!0);void 0===a&&(a=null);if(!c.getMap()){if(c.url)return t(c.url,b,d,e,a);throw Error("FeatureSets can only be used once the layer is added to a Map");}if(c.mode===r.MODE_SNAPSHOT&&!c.url)return new C({layer:c,spatialReference:b,outFields:d,includeGeometry:e});if(c.mode===r.MODE_SNAPSHOT||c.mode===
r.MODE_ONDEMAND||c.mode===r.MODE_AUTO)return new B({layer:c,spatialReference:b,outFields:d,includeGeometry:e,lrucache:a});throw Error("FeatureSets only support for Snapshot or OnDemand FeatureSet");}function I(c,b){var d=b.portalUrl+(b.portalUrl.match(/\/$/)?"":"/")+"content/items/"+c;return q.create(function(e,a){return l({url:d,content:{f:"json"},callbackParamName:"callback",load:function(a){e({item:a})},error:function(d){a(d)}})})}Object.defineProperty(k,"__esModule",{value:!0});k.initialiseMetaDataCache=
function(){null===h.applicationCache&&(h.applicationCache=new h)};k.constructFeatureSetFromUrlRaw=t;k.constructFeatureSetFromUrl=u;k.constructFeatureSet=w;var J=function(c){function b(d,e,a){void 0===e&&(e=null);void 0===a&&(a=null);var g=c.call(this)||this;g._map=d;g._overridespref=e;g.lrucache=a;g._instantLayers=[];return g}__extends(b,c);b.prototype.makeAndAddFeatureSet=function(d,e,a){void 0===e&&(e=!0);void 0===a&&(a=null);var g=w(d,this._overridespref,null===a?["*"]:a,e,this.lrucache);this._instantLayers.push({featureset:g,
opitem:d,includeGeometry:e,outFields:JSON.stringify(a)});return g};b.prototype.makeAndAddFeatureSetTable=function(d,e,a){void 0===e&&(e=!0);void 0===a&&(a=null);var g=t(d.url,this._overridespref,a,e,this.lrucache);this._instantLayers.push({featureset:g,opitem:{name:d.title,id:d.id},includeGeometry:e,outFields:JSON.stringify(a)});return g};b.prototype.featureSetByName=function(d,e,a){void 0===e&&(e=!0);void 0===a&&(a=null);null===a&&(a=["*"]);a=a.slice(0);a=a.sort();for(var g=JSON.stringify(a),b=0;b<
this._instantLayers.length;b++){var c=this._instantLayers[b];if(c.opitem.name===d&&c.includeGeometry===e&&c.outFields===g)return this.resolvePromise(this._instantLayers[b].featureset)}g=null;b=0;for(c=this._map.graphicsLayerIds;b<c.length;b++){var m=this._map.getLayer(c[b]);if(m instanceof r&&m.name===d){g=m;break}}return g?this.resolvePromise(this.makeAndAddFeatureSet(g,e,a)):this._map.tables&&(g=this._map.tables.find(function(a){return a.title&&a.title===d||a.title&&a.title===d?!0:!1}))?this.resolvePromise(this.makeAndAddFeatureSetTable(g,
e,a)):this.resolvePromise(null)};b.prototype.featureSetById=function(d,e,a){void 0===e&&(e=!0);void 0===a&&(a=["*"]);null===a&&(a=["*"]);a=a.slice(0);a=a.sort();for(var b=JSON.stringify(a),c=0;c<this._instantLayers.length;c++){var f=this._instantLayers[c];if(f.opitem.id===d&&f.includeGeometry===e&&f.outFields===b)return this.resolvePromise(this._instantLayers[c].featureset)}b=null;c=0;for(f=this._map.graphicsLayerIds;c<f.length;c++){var m=this._map.getLayer(f[c]);if(m instanceof r&&m.id===d){b=m;
break}}return b?this.resolvePromise(this.makeAndAddFeatureSet(b,e,a)):this._map.tables&&(b=this._map.tables.find(function(a){return a.id&&a.id===d||a.id&&a.id===d?!0:!1}))?this.resolvePromise(this.makeAndAddFeatureSetTable(b,e,a)):this.resolvePromise(null)};return b}(p);k.createFeatureSetCollectionFromMap=function(c,b,d){void 0===d&&(d=null);return new J(c,b,d)};var K=function(c){function b(d,b,a){void 0===b&&(b=null);void 0===a&&(a=null);var e=c.call(this)||this;e._url=d;e._overridespref=b;e.lrucache=
a;e.metadata=null;e._instantLayers=[];return e}__extends(b,c);Object.defineProperty(b.prototype,"url",{get:function(){return this._url},enumerable:!0,configurable:!0});b.prototype._loadMetaData=function(){var d=this;return z(this._url).then(function(b){return d.metadata=b})};b.prototype.makeAndAddFeatureSet=function(d,b,a){void 0===b&&(b=!0);void 0===a&&(a=null);var e=w(d,this._overridespref,null===a?["*"]:a,b,this.lrucache);this._instantLayers.push({featureset:e,opitem:d,includeGeometry:b,outFields:JSON.stringify(a)});
return e};b.prototype.load=function(){return this._loadMetaData()};b.prototype.clone=function(){return new b(this._url,this._overridespref,this.lrucache)};b.prototype.featureSetByName=function(b,e,a){var d=this;void 0===e&&(e=!0);void 0===a&&(a=null);null===a&&(a=["*"]);a=a.slice(0);a=a.sort();for(var c=JSON.stringify(a),f=0;f<this._instantLayers.length;f++){var m=this._instantLayers[f];if(m.opitem.name===b&&m.includeGeometry===e&&m.outFields===c)return this.resolvePromise(this._instantLayers[f].featureset)}return this._loadMetaData().then(function(c){for(var g=
null,f=0,m=c.layers?c.layers:[];f<m.length;f++){var h=m[f];h.name===b&&(g=h)}if(!g)for(f=0,c=c.tables?c.tables:[];f<c.length;f++)h=c[f],h.name===b&&(g=h);return g?d.resolvePromise(t(d._url+"/"+g.id,d._overridespref,a,e,d.lrucache)):d.resolvePromise(null)})};b.prototype.featureSetById=function(b,c,a){var d=this;void 0===c&&(c=!0);void 0===a&&(a=["*"]);null===a&&(a=["*"]);a=a.slice(0);a=a.sort();var e=JSON.stringify(a);b=null!==b&&void 0!==b?b.toString():"";for(var f=0;f<this._instantLayers.length;f++){var m=
this._instantLayers[f];if(m.opitem.id===b&&m.includeGeometry===c&&m.outFields===e)return this.resolvePromise(this._instantLayers[f].featureset)}return this._loadMetaData().then(function(e){for(var f=null,g=0,m=e.layers?e.layers:[];g<m.length;g++){var h=m[g];null!==h.id&&void 0!==h.id&&h.id.toString()===b&&(f=h)}if(!f)for(g=0,e=e.tables?e.tables:[];g<e.length;g++)h=e[g],null!==h.id&&void 0!==h.id&&h.id.toString()===b&&(f=h);return f?d.resolvePromise(t(d._url+"/"+f.id,d._overridespref,a,c,d.lrucache)):
d.resolvePromise(null)})};return b}(p);k.createFeatureSetCollectionFromService=function(c,b,d){void 0===d&&(d=null);return new K(c,b,d)};k.getPortal=function(c,b){return null===c?b:new F.Portal(c.field("url"))};k.constructFeatureSetFromPortalItem=function(c,b,d,e,a,g,k){return q.create(function(f,m){if(h.applicationCache){var l=h.applicationCache.getLayerInfo(c+":"+g.url);if(l){l.then(function(c){try{var g=u(y.extractServiceUrl(c.item.url)+"/"+b,d,e,a,k);f(g)}catch(x){m(x)}},function(a){m(a)});return}}l=
I(c,g);h.applicationCache&&h.applicationCache.setLayerInfo(c+":"+g.url,l);l.then(function(c){try{var g=u(y.extractServiceUrl(c.item.url)+"/"+b,d,e,a,k);f(g)}catch(x){m(x)}},function(a){h.applicationCache&&h.applicationCache.clearLayerInfo(c+":"+g.url);m(a)})})};k.constructFeatureSetFromRelationship=function(c,b,d,e,a,g,h){void 0===e&&(e=null);void 0===a&&(a=null);void 0===g&&(g=!0);void 0===h&&(h=null);var f=c.serviceUrl();if(!f)return null;f="/"===f.charAt(f.length-1)?f+b.relatedTableId.toString():
f+"/"+b.relatedTableId.toString();return u(f,e,a,g,h).then(function(f){return new D({layer:c,relatedLayer:f,relationship:b,objectId:d,spatialReference:e,outFields:a,includeGeometry:g,lrucache:h})})};k.constructAssociationMetaDataFeatureSetFromUrl=function(c,b){var d=[],e=3,a=null,g={},h=null;return z(c).then(function(f){if(f.controllerDatasetLayers&&void 0!==f.controllerDatasetLayers.utilityNetworkLayerId&&null!==f.controllerDatasetLayers.utilityNetworkLayerId){if(f.layers)for(var m=0,k=f.layers;m<
k.length;m++){var l=k[m];g[l.id]=l.name}if(f.tables)for(m=0,k=f.tables;m<k.length;m++)l=k[m],g[l.id]=l.name;var p=f.controllerDatasetLayers.utilityNetworkLayerId;return H(c,p).then(function(f){if(f){(a=f)&&a.dataElement&&void 0!==a.dataElement.schemaGeneration&&(e=a.dataElement.schemaGeneration);h={};a.dataElement.domainNetworks||(a.dataElement.domainNetworks=[]);f=0;for(var m=a.dataElement.domainNetworks;f<m.length;f++){for(var k=m[f],l=0,q=k.edgeSources?k.edgeSources:[];l<q.length;l++){var n=q[l],
n={layerId:n.layerId,sourceId:n.sourceId,className:g[n.layerId]?g[n.layerId]:null};n.className&&(h[n.className]=n)}l=0;for(k=k.junctionSources?k.junctionSources:[];l<k.length;l++)n=k[l],n={layerId:n.layerId,sourceId:n.sourceId,className:g[n.layerId]?g[n.layerId]:null},n.className&&(h[n.className]=n)}if(a.dataElement.terminalConfigurations)for(f=0,m=a.dataElement.terminalConfigurations;f<m.length;f++)for(k=0,n=m[f].terminals;k<n.length;k++)l=n[k],d.push({terminalId:l.terminalId,terminalName:l.terminalName});
return G(c+"/"+p).then(function(a){if(a.systemLayers&&void 0!==a.systemLayers.associationsTableId&&null!==a.systemLayers.associationsTableId){var f=[];4<=e&&(f.push("STATUS"),f.push("PERCENTALONG"));return u(c+"/"+a.systemLayers.associationsTableId.toString(),b,"OBJECTID FROMNETWORKSOURCEID TONETWORKSOURCEID FROMGLOBALID TOGLOBALID TOTERMINALID FROMTERMINALID ASSOCIATIONTYPE ISCONTENTVISIBLE GLOBALID".split(" ").concat(f),!1,null).then(function(a){return a.load()}).then(function(a){return 4<=e?(a=
a.filter(E.WhereClause.create("STATUS NOT IN (1, 2, 3, 4, 5, 6, 7, 9, 10, 11, 12, 13, 14, 15, 17, 18, 19, 20, 21, 22, 23, 25, 26, 27, 28, 29, 30, 31, 33, 34, 35, 36, 37, 38, 39, 41, 42, 43, 44, 45, 46, 47, 49, 50, 51, 52, 53, 54, 55, 57, 58, 59, 60, 61, 62,63)",a.getFieldsIndex())),a.load()):a}).then(function(a){return{lkp:h,associations:a,unVersion:e,terminals:d}})}return{associations:null,unVersion:e,lkp:null,terminals:[]}})}return{associations:null,unVersion:e,lkp:null,terminals:[]}})}return{associations:null,
unVersion:e,lkp:null,terminals:[]}})}});