// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.33/esri/copyright.txt for details.
//>>built
require({cache:{"dojox/xml/parser":function(){define(["dojo/_base/kernel","dojo/_base/lang","dojo/_base/array","dojo/_base/window","dojo/_base/sniff"],function(c){c.getObject("xml.parser",!0,dojox);dojox.xml.parser.parse=function(d,g){var f=c.doc,k;g=g||"text/xml";if(d&&c.trim(d)&&"DOMParser"in c.global){k=(new DOMParser).parseFromString(d,g);d=k.documentElement;if("parsererror"==d.nodeName&&"http://www.mozilla.org/newlayout/xml/parsererror.xml"==d.namespaceURI){if(f=d.getElementsByTagNameNS("http://www.mozilla.org/newlayout/xml/parsererror.xml",
"sourcetext")[0])f=f.firstChild.data;throw Error("Error parsing text "+d.firstChild.data+" \n"+f);}return k}if("ActiveXObject"in c.global){f=function(c){return"MSXML"+c+".DOMDocument"};f=["Microsoft.XMLDOM",f(6),f(4),f(3),f(2)];c.some(f,function(c){try{k=new ActiveXObject(c)}catch(y){return!1}return!0});if(d&&k&&(k.async=!1,k.loadXML(d),d=k.parseError,0!==d.errorCode))throw Error("Line: "+d.line+"\nCol: "+d.linepos+"\nReason: "+d.reason+"\nError Code: "+d.errorCode+"\nSource: "+d.srcText);if(k)return k}else if(f.implementation&&
f.implementation.createDocument){if(d&&c.trim(d)&&f.createElement){g=f.createElement("xml");g.innerHTML=d;var z=f.implementation.createDocument("foo","",null);c.forEach(g.childNodes,function(c){z.importNode(c,!0)});return z}return f.implementation.createDocument("","",null)}return null};dojox.xml.parser.textContent=function(d,g){if(1<arguments.length)return dojox.xml.parser.replaceChildren(d,(d.ownerDocument||c.doc).createTextNode(g)),g;if(void 0!==d.textContent)return d.textContent;var f="";d&&c.forEach(d.childNodes,
function(c){switch(c.nodeType){case 1:case 5:f+=dojox.xml.parser.textContent(c);break;case 3:case 2:case 4:f+=c.nodeValue}});return f};dojox.xml.parser.replaceChildren=function(d,g){var f=[];c.isIE&&c.forEach(d.childNodes,function(c){f.push(c)});dojox.xml.parser.removeChildren(d);c.forEach(f,c.destroy);c.isArray(g)?c.forEach(g,function(c){d.appendChild(c)}):d.appendChild(g)};dojox.xml.parser.removeChildren=function(c){for(var d=c.childNodes.length;c.hasChildNodes();)c.removeChild(c.firstChild);return d};
dojox.xml.parser.innerXML=function(c){return c.innerXML?c.innerXML:c.xml?c.xml:"undefined"!=typeof XMLSerializer?(new XMLSerializer).serializeToString(c):null};return dojox.xml.parser})},"esri/layers/WMTSLayerInfo":function(){define(["dojo/_base/declare","dojo/_base/lang","dojo/has","../kernel"],function(c,d,g,f){c=c(null,{declaredClass:"esri.layers.WMTSLayerInfo",identifier:null,tileMatrixSet:null,format:null,style:null,tileInfo:null,title:null,fullExtent:null,initialExtent:null,description:null,
dimension:null,constructor:function(c){c&&(this.title=c.title,this.tileMatrixSet=c.tileMatrixSet,this.format=c.format,this.style=c.style,this.tileInfo=c.tileInfo,this.fullExtent=c.fullExtent,this.initialExtent=c.initialExtent,this.identifier=c.identifier,this.description=c.description,this.dimension=c.dimension)}});g("extend-esri")&&d.setObject("layers.WMTSLayerInfo",c,f);return c})},"*noref":1}});
define("esri/layers/WMTSLayer","dojo/_base/kernel dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/sniff dojox/xml/parser ../kernel ../lang ../request ../urlUtils ../WKIDUnitConversion ../SpatialReference ../geometry/Point ../geometry/Extent ../geometry/webMercatorUtils ./TiledMapServiceLayer ./TileInfo ./WMTSLayerInfo dojo/query".split(" "),function(c,d,g,f,k,z,E,y,F,G,A,B,C,D,H,I,J,K){d=d([I],{declaredClass:"esri.layers.WMTSLayer",copyright:null,extent:null,tileUrl:null,spatialReference:null,
tileInfo:null,constructor:function(a,b){this.version="1.0.0";this.tileUrl=this._url=a;this.serviceMode="RESTful";this._parseCapabilities=g.hitch(this,this._parseCapabilities);this._getCapabilitiesError=g.hitch(this,this._getCapabilitiesError);this._formatDictionary={"image/png":".png","image/png8":".png","image/png24":".png","image/png32":".png","image/jpg":".jpg","image/jpeg":".jpeg","image/gif":".gif","image/bmp":".bmp","image/tiff":".tif","image/jpgpng":"","image/jpegpng":"","image/unknown":""};
b||(b={});if(b.serviceMode)if("KVP"===b.serviceMode||"RESTful"===b.serviceMode)this.serviceMode=b.serviceMode;else{console.error("WMTS mode could only be 'KVP' or 'RESTful'");return}this.customParameters=b.customParameters;this.customLayerParameters=b.customLayerParameters;this.layerInfo=new K;b.layerInfo&&(this.layerInfo=b.layerInfo,this._identifier=b.layerInfo.identifier,this._tileMatrixSetId=b.layerInfo.tileMatrixSet,b.layerInfo.format&&(this.format="image/"+b.layerInfo.format),this._style=b.layerInfo.style,
this.title=b.layerInfo.title,this._dimension=b.layerInfo.dimension,this._dimension2=b.layerInfo.dimension2);b.resourceInfo?(this.version=b.resourceInfo.version,b.resourceInfo.getTileUrl&&(this._url=this.tileUrl=b.resourceInfo.getTileUrl),this.copyright=b.resourceInfo.copyright,this.layerInfos=b.resourceInfo.layerInfos,this.customParameters=b.resourceInfo.customParameters||this.customParameters,this.customLayerParameters=b.resourceInfo.customLayerParameters||this.customLayerParameters,this._parseResourceInfo(),
this.loaded=!0,this.onLoad(this)):this._getCapabilities()},setActiveLayer:function(a){this.setVisibleLayer(a)},setVisibleLayer:function(a){this._setActiveLayer(a);this.refresh(!0)},setCustomParameters:function(a,b){this.customParameters=a;this.customLayerParameters=b;this.refresh(!0)},getTileUrl:function(a,b,e){a=this._levelToLevelValue[a];a=this.resourceUrls&&0<this.resourceUrls.length?this.resourceUrls[b%this.resourceUrls.length].template.replace(/\{Style\}/gi,this._style).replace(/\{TileMatrixSet\}/gi,
this._tileMatrixSetId).replace(/\{TileMatrix\}/gi,a).replace(/\{TileRow\}/gi,b).replace(/\{TileCol\}/gi,e).replace(/\{dimensionValue\}/gi,this._dimension).replace(/\{dimensionValue2\}/gi,this._dimension2):this.UrlTemplate.replace(/\{level\}/gi,a).replace(/\{row\}/gi,b).replace(/\{col\}/gi,e);a=this._appendCustomLayerParameters(a);a=this.addTimestampToURL(a);return G.addProxy(a)},getTileUrlTemplate:function(a){var b=a.identifier,e=a.tileMatrixSet,c=a.format,m=a.style,d=a.dimension,u=a.dimension2;b?
a=f.filter(this.layers,function(a){return a.identifier===b})[0]:(a=this.layers[0],b=this.layers[0].identifier);if(a){if(!c)c=a.formats[0];else if(!(-1===c.indexOf("image/")&&-1<f.indexOf(a.formats,c))&&(-1===c.indexOf("image/")&&(c="image/"+c),-1===f.indexOf(a.formats,c))){console.error("The layer doesn't support the format of "+c);this.onError(Error("The layer doesn't support the format of "+c));return}if(!m)m=a.styles[0];else if(-1===f.indexOf(a.styles,m)){console.error("The layer doesn't support the style of "+
m);this.onError(Error("The layer doesn't support the style of "+m));return}if(!d&&a.dimensions)d=a.dimensions[0];else if(-1===f.indexOf(a.dimensions,d)){console.error("The layer doesn't support the dimension of "+d);this.onError(Error("The layer doesn't support the dimension of "+d));return}if(!u&&a.dimensions2)u=a.dimensions2[0];else if(-1===f.indexOf(a.dimensions2,u)){console.error("The layer doesn't support the dimension of "+u);this.onError(Error("The layer doesn't support the dimension of "+
u));return}var g;if(e){if(g=f.filter(a.tileMatrixSetInfos,function(a){return a.tileMatrixSet===e})[0],!g){console.error("The tileMatrixSetId "+e+" is not supported by the layer of "+b);this.onError(Error("The tileMatrixSetId "+e+" is not supported by the layer of "+b));return}}else(g=f.filter(a.tileMatrixSetInfos,function(a){return"GoogleMapsCompatible"===a.tileMatrixSet})[0])||(g=a.tileMatrixSetInfos[0]),e=g.tileMatrixSet;return this._getTileUrlTemplate(b,e,c,m,d,u)}console.error("couldn't find the layer "+
b);this.onError(Error("couldn't find the layer "+b))},_getTileUrlTemplate:function(a,b,c,h,m,f){var e;a||(a=this._identifier);b||(b=this._tileMatrixSetId);c||(c=this.format);h||""===h||(h=this._style);if(this.resourceUrls&&0<this.resourceUrls.length)return e=this.resourceUrls[0].template,e.indexOf(".xxx")===e.length-4&&(e=e.slice(0,e.length-4)),e=e.replace(/\{Style\}/gi,h),e=e.replace(/\{TileMatrixSet\}/gi,b),e=e.replace(/\{TileMatrix\}/gi,"{level}"),e=e.replace(/\{TileRow\}/gi,"{row}"),e=e.replace(/\{TileCol\}/gi,
"{col}"),e=e.replace(/\{dimensionValue\}/gi,m),e=e.replace(/\{dimensionValue2\}/gi,f);"KVP"===this.serviceMode?e=this._url+"SERVICE\x3dWMTS\x26VERSION\x3d"+this.version+"\x26REQUEST\x3dGetTile\x26LAYER\x3d"+a+"\x26STYLE\x3d"+h+"\x26FORMAT\x3d"+c+"\x26TILEMATRIXSET\x3d"+b+"\x26TILEMATRIX\x3d{level}\x26TILEROW\x3d{row}\x26TILECOL\x3d{col}":"RESTful"===this.serviceMode&&(m="",this._formatDictionary[c.toLowerCase()]&&(m=this._formatDictionary[c.toLowerCase()]),e=this._url+a+"/"+h+"/"+b+"/{level}/{row}/{col}"+
m);return e},_parseResourceInfo:function(){var a=this.layerInfos,b,e;"KVP"===this.serviceMode&&(this._url+=-1<this._url.indexOf("?")?"":"?");for(e=0;e<a.length;e++)if(!(this._identifier&&a[e].identifier!==this._identifier||this.title&&a[e].title!==this.title||this._tileMatrixSetId&&a[e].tileMatrixSet!==this._tileMatrixSetId||this.format&&"image/"+a[e].format!==this.format||this._style&&a[e].style!==this._style)){g.mixin(this,{description:a[e].description,tileInfo:a[e].tileInfo,spatialReference:a[e].tileInfo.spatialReference,
fullExtent:a[e].fullExtent,initialExtent:a[e].initialExtent,_identifier:a[e].identifier,_tileMatrixSetId:a[e].tileMatrixSet,format:"image/"+a[e].format,_style:a[e].style});break}for(e=0;e<a.length;e++)b=a[e].tileInfo,96!==b.dpi&&(f.forEach(b.lods,function(a){a.scale=96*a.scale/b.dpi}),b.dpi=96),f.forEach(b.lods,function(c){c.resolution=this._getResolution(b.spatialReference.wkid,90.71428571428571*c.scale/96,a[e].tileMatrixSet)},this);this._setActiveLayer();this.UrlTemplate=this._getTileUrlTemplate();
this._levelToLevelValue=[];f.forEach(this.tileInfo.lods,function(a){this._levelToLevelValue[a.level]=a.levelValue?a.levelValue:a.level},this)},_getCapabilities:function(){var a;"KVP"===this.serviceMode?a=-1<this._url.indexOf("?")?this._url+"\x26request\x3dGetCapabilities\x26service\x3dWMTS\x26version\x3d"+this.version:this._url+"?request\x3dGetCapabilities\x26service\x3dWMTS\x26version\x3d"+this.version:"RESTful"===this.serviceMode&&(a=this._url+"/"+this.version+"/WMTSCapabilities.xml");a=this._appendCustomParameters(a);
F({url:a,handleAs:"text",load:this._parseCapabilities,error:this._getCapabilitiesError})},_parseCapabilities:function(a){a=a.replace(/ows:/gi,"");a=z.parse(a);var b=c.query("Contents",a)[0];if(b){var e=c.query("OperationsMetadata",a)[0],h=c.query("[name\x3d'GetTile']",e)[0],e=this._url,h=c.query("Get",h),m,d=!1,u,g;for(m=0;m<h.length;m++){var p=c.query("Constraint",h[m])[0];if(!p||this._getTagWithChildTagValue("AllowedValues","Value",this.serviceMode,p)){e=h[m].attributes[0].nodeValue;d=!0;break}else if(!p||
this._getTagWithChildTagValue("AllowedValues","Value","RESTful",p))u=h[m].attributes[0].nodeValue;else if(!p||this._getTagWithChildTagValue("AllowedValues","Value","KVP",p))g=h[m].attributes[0].nodeValue}d||("KVP"===this.serviceMode&&u?(e=u,this.serviceMode="RESTful"):"RESTful"===this.serviceMode&&g&&(e=g,this.serviceMode="KVP"));-1===e.indexOf("/1.0.0/")&&"RESTful"===this.serviceMode&&(e+="/");"KVP"===this.serviceMode&&(e+=-1<e.indexOf("?")?"":"?");this._url=e;this.copyright=this._getTagValues("Capabilities\x3eServiceIdentification\x3eAccessConstraints",
a)[0];u=c.query("Layer",b);var n,q=[];this.layers=[];f.forEach(u,function(a){n=this._getTagValues("Identifier",a)[0];q.push(n);this.layers.push(this._getWMTSLayerInfo(n,a,b))},this);this._setActiveLayer();this.loaded=!0;this.onLoad(this)}else console.error("The WMTS capabilities XML is not valid"),this.onError(Error("The WMTS capabilities XML is not valid"))},_setActiveLayer:function(a){a||(a={});a.identifier&&(this._identifier=a.identifier);a.tileMatrixSet&&(this._tileMatrixSetId=a.tileMatrixSet);
a.format&&(this.format=a.format);a.style&&(this._style=a.style);a.dimension&&(this._dimension=a.dimension);a.dimension2&&(this._dimension2=a.dimension2);if(this.layers)if(this._identifier?a=f.filter(this.layers,function(a){return a.identifier===this._identifier},this)[0]:(a=this.layers[0],this._identifier=this.layers[0].identifier),a){if(this.format){if(-1===this.format.indexOf("image/")&&(this.format="image/"+this.format),-1===f.indexOf(a.formats,this.format)){console.error("The layer doesn't support the format of "+
this.format);this.onError(Error("The layer doesn't support the format of "+this.format));return}}else this.format=a.formats[0],-1===this.format.indexOf("image/")&&(this.format="image/"+this.format);if(!this._style)this._style=a.styles[0];else if(-1===f.indexOf(a.styles,this._style)){console.error("The layer doesn't support the style of "+this._style);this.onError(Error("The layer doesn't support the style of "+this._style));return}if(!this._dimension&&a.dimensions)this._dimension=a.dimensions[0];
else if(-1===f.indexOf(a.dimensions,this._dimension)){console.error("The layer doesn't support the dimension of "+this._dimension);this.onError(Error("The layer doesn't support the dimension of "+this._dimension));return}if(!this._dimension2&&a.dimensions2)this._dimension2=a.dimensions2[0];else if(-1===f.indexOf(a.dimensions2,this._dimension2)){console.error("The layer doesn't support the dimension of "+this._dimension2);this.onError(Error("The layer doesn't support the dimension of "+this._dimension2));
return}var b;if(this._tileMatrixSetId){if(b=f.filter(a.tileMatrixSetInfos,function(a){return a.tileMatrixSet===this._tileMatrixSetId},this)[0],!b){console.error("The tileMatrixSetId "+this._tileMatrixSetId+" is not supported by the layer of "+this._identifier);this.onError(Error("The tileMatrixSetId "+this._tileMatrixSetId+" is not supported by the layer of "+this._identifier));return}}else(b=f.filter(a.tileMatrixSetInfos,function(a){return"GoogleMapsCompatible"===a.tileMatrixSet})[0])||(b=a.tileMatrixSetInfos[0]),
this._tileMatrixSetId=b.tileMatrixSet;this.description=a.description;this.title=a.title;this.spatialReference=b.tileInfo.spatialReference;this.tileInfo=b.tileInfo;this._levelToLevelValue=[];f.forEach(this.tileInfo.lods,function(a){this._levelToLevelValue[a.level]=a.levelValue?a.levelValue:a.level},this);102100===this.spatialReference.wkid||102113===this.spatialReference.wkid?this.fullExtent=this.initialExtent=H.geographicToWebMercator(a.gcsExtent):4326===this.spatialReference.wkid?this.fullExtent=
this.initialExtent=a.gcsExtent:(this.fullExtent=b.fullExtent,this.initialExtent=b.initialExtent);this.resourceUrls=a.resourceUrls;this.UrlTemplate=this._getTileUrlTemplate();this.layerInfo={identifier:this._identifier,tileMatrixSet:this._tileMatrixSetId,format:this.format,style:this._style,fullExtent:this.fullExtent,initialExtent:this.initialExtent,tileInfo:this.tileInfo,title:this.title,description:this.description}}else console.error("couldn't find the layer "+this._identifier),this.onError(Error("couldn't find the layer "+
this._identifier))},_getWMTSLayerInfo:function(a,b,e){var h=this._getTagValues("Abstract",b)[0],m=this._getTagValues("Title",b)[0],d=c.query("WGS84BoundingBox",b)[0],g=d?this._getTagValues("LowerCorner",d)[0].split(" "):["-180","-90"],k=d?this._getTagValues("UpperCorner",d)[0].split(" "):["180","90"],d=parseFloat(g[0]),g=parseFloat(g[1]),p=parseFloat(k[0]),k=parseFloat(k[1]),d=new D(d,g,p,k,new B({wkid:4326})),k=this._getTagValues("Identifier",c.query("Style",b)[0]),n=this._getTagValues("Identifier",
c.query("Dimension",b)[0]),q=this._getTagValues("Default",c.query("Dimension",b)[0])||this._getTagValues("Value",c.query("Dimension",b)[0]),w=1<c.query("Dimension",b).length?this._getTagValues("Identifier",c.query("Dimension",b)[1]):[],t=1<c.query("Dimension",b).length?this._getTagValues("Default",c.query("Dimension",b)[1])||this._getTagValues("Value",c.query("Dimension",b)[1]):[],g=this._getTagValues("Format",b);e=this._getLayerMatrixInfos(b,e);a={identifier:a,tileMatrixSetInfos:e,formats:g,styles:k,
title:m,description:h,gcsExtent:d,dimensions:q,dimensions2:t};b=c.query("ResourceURL",b);var r=[],l;f.forEach(b,function(a){l=a.getAttribute("template");if(n&&q&&n[0]&&q[0])if(-1<l.indexOf("{"+n+"}"))l=l.replace("{"+n+"}","{dimensionValue}");else{var b=l.toLowerCase().indexOf("{"+n[0].toLowerCase()+"}");-1<b&&(l=l.substring(0,b)+"{dimensionValue}"+l.substring(b+n[0].length+2))}w&&t&&w[0]&&t[0]&&(-1<l.indexOf("{"+w+"}")?l=l.replace("{"+w+"}","{dimensionValue2}"):(b=l.toLowerCase().indexOf("{"+w[0].toLowerCase()+
"}"),-1<b&&(l=l.substring(0,b)+"{dimensionValue2}"+l.substring(b+w[0].length+2))));r.push({template:l,format:a.getAttribute("format"),resourceType:a.getAttribute("resourceType")})});r&&0<r.length&&(a.resourceUrls=r);return a},_getLayerMatrixInfos:function(a,b){var c=[],h=this._getTagValues("TileMatrixSet",a);if(h&&0!==h.length)return f.forEach(h,function(e){e=this._getLayerMatrixInfo(e,a,b);c.push(e)},this),c},_getLayerMatrixInfo:function(a,b,e){var h,d,f,g,k=[];b=this._getTagWithChildTagValue("TileMatrixSetLink",
"TileMatrixSet",a,b);var p=this._getTagValues("TileMatrix",b),n=this._getTagWithChildTagValue("TileMatrixSet","Identifier",a,e),q=this._getTagValues("SupportedCRS",n)[0];h=parseInt(q.split(":").pop(),10);if(900913==h||3857==h)h=102100;if(-1<q.toLowerCase().indexOf("crs84")||-1<q.toLowerCase().indexOf("crs:84"))h=4326,g=!0;else if(-1<q.toLowerCase().indexOf("crs83")||-1<q.toLowerCase().indexOf("crs:83"))h=4269,g=!0;else if(-1<q.toLowerCase().indexOf("crs27")||-1<q.toLowerCase().indexOf("crs:27"))h=
4267,g=!0;var w=new B({wkid:h}),t=c.query("TileMatrix",n)[0];e=parseInt(this._getTagValues("TileWidth",t)[0],10);b=parseInt(this._getTagValues("TileHeight",t)[0],10);d=this._getTagValues("TopLeftCorner",t)[0].split(" ");var r=d[0],l=d[1];1<r.split("E").length&&(d=r.split("E"),r=d[0]*Math.pow(10,d[1]));1<l.split("E").length&&(d=l.split("E"),l=d[0]*Math.pow(10,d[1]));var r=parseFloat(r),l=parseFloat(l),y=g&&4326===h&&90===r&&-180===l;for(d=0;d<this._flippingAxisForWkids.length;d++)if(q.split(":").pop()>=
this._flippingAxisForWkids[d][0]&&q.split(":").pop()<=this._flippingAxisForWkids[d][1]||4326===h&&(!g||y)){4326===h&&90<r&&(r="90");f=new C(l,r,w);break}d===this._flippingAxisForWkids.length&&(f=new C(r,l,w));if(0===p.length)for(p=c.query("TileMatrix",n),d=0;d<p.length;d++)g=this._getLodFromTileMatrix(p[d],h,d,a),k.push(g);else for(d=0;d<p.length;d++)g=this._getTagWithChildTagValue("TileMatrix","Identifier",p[d],n),g=this._getLodFromTileMatrix(g,h,d,a),k.push(g);h=c.query("BoundingBox",n)[0];var v,
x;h&&(v=this._getTagValues("LowerCorner",h)[0].split(" "),x=this._getTagValues("UpperCorner",h)[0].split(" "));v&&1<v.length&&x&&1<x.length?(t=parseFloat(v[0]),h=parseFloat(v[1]),v=parseFloat(x[0]),x=parseFloat(x[1])):(v=this._getTagValues("MatrixWidth",t)[0],h=this._getTagValues("MatrixHeight",t)[0],t=f.x,x=f.y,v=t+v*b*k[0].resolution,h=x-h*e*k[0].resolution);x=v=new D(t,h,v,x,w);f=new J({dpi:96,spatialReference:w,format:this.format,rows:e,cols:b,origin:f,lods:k});return{tileMatrixSet:a,fullExtent:x,
initialExtent:v,tileInfo:f}},_getCapabilitiesError:function(a){console.error("Failed to get capabilities xml");this.onError(a)},_getLodFromTileMatrix:function(a,b,c,d){var e=this._getTagValues("Identifier",a)[0];a=this._getTagValues("ScaleDenominator",a)[0];1<a.split("E").length?(a=a.split("E"),a=a[0]*Math.pow(10,a[1])):a=parseFloat(a);b=this._getResolution(b,a,d);return{level:c,levelValue:e,scale:1.058267716535433*a,resolution:b}},_getResolution:function(a,b,c){a=y.isDefined(A[a])?A.values[A[a]]:
"default028mm"===c?6370997*Math.PI/180:6378137*Math.PI/180;return 7*b/25E3/a},_getTag:function(a,b){return(a=c.query(a,b))&&0<a.length?a[0]:null},_getTagValues:function(a,b){var e=[];a=a.split("\x3e");var d;d=c.query(a[0],b)[0];if(1<a.length){for(b=1;b<a.length-1;b++)d=c.query(a[b],d)[0];b=c.query(a[a.length-1],d)}else b=c.query(a[0],b);b&&0<b.length&&f.forEach(b,function(a){9>k("ie")?e.push(a.childNodes.length?a.childNodes[0].nodeValue:""):e.push(a.textContent)});return e},_getAttributeValues:function(a,
b,e){a=c.query(a,e);var d=[];a&&0<a.length&&f.forEach(a,function(a){d.push(a.getAttribute(b))});return d},_getTagWithChildTagValue:function(a,b,e,d){d=d.childNodes;var f,g;for(g=0;g<d.length;g++)if(-1<d[g].nodeName.indexOf(a)&&(9>k("ie")?y.isDefined(c.query(b,d[g])[0])&&(f=c.query(b,d[g])[0].childNodes[0].nodeValue):y.isDefined(c.query(b,d[g])[0])&&(f=c.query(b,d[g])[0].textContent),f===e||e.split(":")&&f===e.split(":")[1]))return d[g]},_appendCustomParameters:function(a){var b;if(this.customParameters)for(b in this.customParameters)a+=
(-1===a.indexOf("?")?"?":"\x26")+b+"\x3d"+encodeURIComponent(this.customParameters[b]);return a},_appendCustomLayerParameters:function(a){var b,c;if(this.customLayerParameters||this.customParameters)for(b in c=g.clone(this.customParameters||{}),g.mixin(c,this.customLayerParameters||{}),c)a+=(-1===a.indexOf("?")?"?":"\x26")+b+"\x3d"+encodeURIComponent(c[b]);return a},_flippingAxisForWkids:[[3819,3819],[3821,3824],[3889,3889],[3906,3906],[4001,4025],[4027,4036],[4039,4047],[4052,4055],[4074,4075],[4080,
4081],[4120,4176],[4178,4185],[4188,4216],[4218,4289],[4291,4304],[4306,4319],[4322,4326],[4463,4463],[4470,4470],[4475,4475],[4483,4483],[4490,4490],[4555,4558],[4600,4646],[4657,4765],[4801,4811],[4813,4821],[4823,4824],[4901,4904],[5013,5013],[5132,5132],[5228,5229],[5233,5233],[5246,5246],[5252,5252],[5264,5264],[5324,5340],[5354,5354],[5360,5360],[5365,5365],[5370,5373],[5381,5381],[5393,5393],[5451,5451],[5464,5464],[5467,5467],[5489,5489],[5524,5524],[5527,5527],[5546,5546],[2044,2045],[2081,
2083],[2085,2086],[2093,2093],[2096,2098],[2105,2132],[2169,2170],[2176,2180],[2193,2193],[2200,2200],[2206,2212],[2319,2319],[2320,2462],[2523,2549],[2551,2735],[2738,2758],[2935,2941],[2953,2953],[3006,3030],[3034,3035],[3038,3051],[3058,3059],[3068,3068],[3114,3118],[3126,3138],[3150,3151],[3300,3301],[3328,3335],[3346,3346],[3350,3352],[3366,3366],[3389,3390],[3416,3417],[3833,3841],[3844,3850],[3854,3854],[3873,3885],[3907,3910],[4026,4026],[4037,4038],[4417,4417],[4434,4434],[4491,4554],[4839,
4839],[5048,5048],[5105,5130],[5253,5259],[5269,5275],[5343,5349],[5479,5482],[5518,5519],[5520,5520],[20004,20032],[20064,20092],[21413,21423],[21473,21483],[21896,21899],[22171,22177],[22181,22187],[22191,22197],[25884,25884],[27205,27232],[27391,27398],[27492,27492],[28402,28432],[28462,28492],[30161,30179],[30800,30800],[31251,31259],[31275,31279],[31281,31290],[31466,31700]]});k("extend-esri")&&g.setObject("layers.WMTSLayer",d,E);return d});