// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.33/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/ReportPlayer/playerSupports/_CommandSupport","dojo/_base/declare dojo/_base/lang esri/dijit/geoenrichment/Deferred esri/dijit/geoenrichment/when esri/dijit/geoenrichment/ReportPlayer/PlayerCommands esri/dijit/geoenrichment/ReportPlayer/config esri/dijit/geoenrichment/utils/DeviceUtil".split(" "),function(n,m,k,e,f,p,q){return n(null,{_initCommands:function(){q.isMobileDevice()||!p.modules.exportCommands?this.playerToolbar.notifyCommandButtonsAdded():e(this.dataProvider.getCommands&&
this.dataProvider.getCommands(),function(a){this._createCommandButtons(a);this.playerToolbar&&this.playerToolbar.notifyCommandButtonsAdded()}.bind(this))},_lastNonPrintCommandId:null,_executeExportCallback:null,_executePrintCallback:null,_createCommandButtons:function(a){function b(a){var b=new k,c=new k;d.onCommandSettingsShown(b.promise);d._saveVisualState();e(d._getPrintableContainer({commandId:a,showDialog:!0}),function(a){if(a){var b=a.getSelectedCommandId();b&&b!==f.PRINT&&(d._lastNonPrintCommandId=
b);e(d._executeCommand(b,{printableContainer:a}),c.resolve,c.reject)}else e(d._applySavedVisualState(),function(){d.onCommandCanceled();c.resolve()})}).always(b.resolve);return c.promise}var d=this;if(a&&a.length){var c,g=a.filter(function(a){return a.id===f.PRINT?(c=a,!1):!0});g.length&&(this._executeExportCallback=function(){return b(d._lastNonPrintCommandId||g[0].id)},this._createCommandButton(g[0],this._executeExportCallback));c&&(this._executePrintCallback=function(){return b(c.id)},this._createCommandButton(c,
this._executePrintCallback))}},executeExport:function(){return this._executeExportCallback&&this._executeExportCallback()},executePrint:function(){return this._executePrintCallback&&this._executePrintCallback()},_createCommandButton:function(a,b){return this.playerToolbar&&this.playerToolbar.createCommandButton(a,b)},getCommandExportDialogSettings:function(){return this._getPrintDialogSettings()},executeCommand:function(a,b){b=b||{};this._saveVisualState();var d=this._viewModel.dynamicReportInfo.fieldData;
!this.isPlayerOnServer||a!==f.PDF&&a!==f.IMAGE||(b.exportSettings=m.mixin({},d.reportInfo&&d.reportInfo.exportSettings,b.exportSettings));var c=this;return e(this._getPrintableContainer({commandId:a,showDialog:!1,exportSettings:b.exportSettings}),function(d){return c._executeCommand(a,m.mixin({printableContainer:d},b))})},_executeCommand:function(a,b){function d(){e(c.dataProvider.executeCommand&&c.dataProvider.executeCommand(a,c,b,function(a){c.onCommandProgress(a)}),l.resolve,l.reject)}var c=this,
g=this._viewModel.dynamicReportInfo.fieldData;a!==f.PDF&&a!==f.DYNAMIC_HTML||!g.runReportTaskIDs||(b.creditsTaskIDs=g.runReportTaskIDs);var l=new k;this.isPlayerOnServer?d():setTimeout(d);var h=l.promise.then(function(a){return e(c._applySavedVisualState(),function(){return a})});this.onCommandStart(h,a);this._showWaiting(h,"executeCommand");h.always(function(){c.onCommandEnd(h)});return h},_visualStateMemo:null,_saveVisualState:function(){this._visualStateMemo=this.getVisualState()},_applySavedVisualState:function(){var a=
this;return this.setVisualState(this._visualStateMemo).then(function(){a._visualStateMemo=null})},onCommandSettingsShown:function(a){},onCommandCanceled:function(){},onCommandStart:function(a,b){},onCommandProgress:function(a){},onCommandEnd:function(a){}})});