// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.33/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/ReportPlayer/dataProvider/_SerializationSupport","require dojo/_base/declare dojo/_base/lang esri/dijit/geoenrichment/Deferred esri/dijit/geoenrichment/when esri/dijit/geoenrichment/promise/all ./supportClasses/areas/AnalysisAreaJsonUtil ./supportClasses/areas/AnalysisAreaUtil ./supportClasses/PortalManager ../core/infographics/InfographicTypes ../core/supportClasses/templateJsonUtils/query/TemplateJsonQueryUtil esri/dijit/geoenrichment/ReportPlayer/countryConfig esri/dijit/geoenrichment/ReportPlayer/_devConfig".split(" "),
function(x,y,z,h,e,A,g,B,C,l,D,q,E){function r(){var a=new h;x("./supportClasses/attachments/AttachmentsStoreSerializer ./supportClasses/GEUtil ../core/supportClasses/templateJsonUtils/TemplateJsonSerializer ../core/supportClasses/templateJsonUtils/TemplateJsonAnalyzer ../core/infographics/utils/InfographicJsonUtil ../core/conversion/portalToEditorUtils/variables/PlayerVariableProvider ../core/infographics/InfographicTypes ./commands/mapToImage/MapToURLUtil esri/dijit/geoenrichment/utils/ProjectionUtil".split(" "),
function(c,b,d,F,k,f,e,g,h){m=c;t=b;n=d;p=k;u=f;l=e;v=g;w=h;a.resolve()});return a.promise}var m,t,n,p,u,v,w;return y(null,{reportDataToJson:function(a,c){var b=this;c=c||{};var d=!1;D.processTemplateFieldInfos(a.templateJson,function(a){a.isInfographic&&a.infographicJson.type===l.ATTACHMENTS&&(d=!0)});return r().then(function(){return e(null,function(){return e(a.attachmentsStore&&m.getAttachmentsStoreJson(a.attachmentsStore,{numAreas:a.analysisAreas.length,saveImages:d}),function(d){var k=z.mixin({},
a.config);!1!==c.forceFixedDataMode&&delete k.geoenrichmentUrl;d={isMultiFeature:a.isMultiFeature,reportTitle:a.reportTitle,templateJson:n.serialize(a.templateJson),reportObject:b._prepareReportObjectJson(a.reportObject),fieldData:a.fieldData,analysisAreas:g.areasToJson(a.analysisAreas),combinedAreasInfo:a.combinedAreasInfo&&g.combinedAreasInfoToJson(a.combinedAreasInfo),reverseAnalysisAreasOnMap:a.reverseAnalysisAreasOnMap,infographicOptions:a.infographicOptions&&a.infographicOptions.toJson(),attachmentsStore:d,
templateVariableProvider:a.templateVariableProvider&&a.templateVariableProvider.toJson(),config:k,countryConfig:q.toJson(),mapImageInfos:c.mapImageInfos,customLogo:a.customLogo};E.logData&&(console.log("_SerializationSupport.js \x3d\x3e reportDataJson"),console.log(d));return d})})})},_prepareReportObjectJson:function(a){var c={},b;for(b in a)a[b]&&"object"!==typeof a[b]&&(c[b]=a[b]);return c},_enrichInfographicVariables:function(a,c){var b=a.infographicOptions;return e(b.getOptions().getItems(b.countryID),
function(){var d=[];c.forEach(function(c){c.isInfographic&&c.variables&&a.analysisAreas.forEach(function(a,f){b.setCurrentAnalysisAreaIndex(f);var e=new h;a=b.createGeoenrichment({currentFeatureIndex:f});a.onDone=function(){e.resolve()};a.country=b.countryID;f=l.supportsComparison(c.type);a.setGeoLevels(f?p.getSubLevels(c):null,f?p.getHighestLevel(c):null);a.setVariables(c.variables);a.setStudyArea(b.studyArea);d.push(e.promise)})});return A(d)})},reportDataFromJson:function(a){var c=this;return r().then(function(){var b=
a.fieldData;b.featureData&&(b.areaData=b.featureData.map(function(a){return{mainCalculator:{data:a}}}),delete b.featureData);var d={isMultiFeature:a.isMultiFeature,reportTitle:a.reportTitle,templateJson:n.deserialize(a.templateJson),reportObject:a.reportObject,fieldData:b,analysisAreas:g.areasFromJson(a.analysisAreas),combinedAreasInfo:a.combinedAreasInfo&&g.combinedAreasInfoFromJson(a.combinedAreasInfo)||{},reverseAnalysisAreasOnMap:a.reverseAnalysisAreasOnMap,infographicOptions:a.infographicOptions&&
c._infographicOptionsProvider.getInfographicOptionsFromJson(a.infographicOptions),attachmentsStore:a.attachmentsStore&&m.getAttachmentsStoreFromJson(a.attachmentsStore),templateVariableProvider:a.templateVariableProvider&&new u(a.templateVariableProvider),config:a.config||{},mapImageInfos:a.mapImageInfos,customLogo:a.customLogo};B.populateCombinedAreasInfo(d.combinedAreasInfo,d.analysisAreas);t.setGeoenrichmentUrl(null);b=!1;d.config.geometryServiceUrl?w.setGeometryServiceUrl(d.config.geometryServiceUrl):
b=!0;d.config.printMapTaskUrl?v.setPrintMapTaskUrl(d.config.printMapTaskUrl):b=!0;q.fromJson(a.countryConfig);return e(b&&C.tryConfigureServicesFromAGOLPublic()).then(function(){return d})})}})});