// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.33/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/ReportPlayer/dataProvider/_ServerSerializationSupport","dojo/_base/declare dojo/_base/lang esri/dijit/geoenrichment/when esri/dijit/geoenrichment/utils/ImageUtil ./supportClasses/ReportDataProcessor ./supportClasses/tasks/parsers/DataXMLParser ./supportClasses/areas/AnalysisAreaUtil ./supportClasses/areas/AnalysisAreaJsonUtil ./supportClasses/areas/AreasPreprocessor ./supportClasses/GEUtil ../core/supportClasses/ReportTemplateTypes ../core/conversion/PortalToEditorConverter ../core/supportClasses/templateJsonUtils/query/TemplateJsonQueryUtil ./supportClasses/attachments/AttachmentsStoreSerializer ../core/supportClasses/templateJsonUtils/TemplateJsonSerializer ../core/conversion/portalToEditorUtils/variables/PlayerVariableProvider ../core/conversion/portalToEditorUtils/metadata/MetadataFromDataBuilder ../countryConfig".split(" "),
function(h,p,k,q,z,A,r,t,B,l,C,D,E,F,G,H,I,J){return h(null,{reportDataToServerData:function(c){return null},reportDataFromServerData:function(c,u){function h(b,c){d.some(function(b){return"metadata.xml"===b.name})||d.push({name:"metadata.xml",data:I.recoverMetadataFromAreaData(b.areaData,c)})}function K(b,d){c.sites=[];var e={};b.areaData.forEach(function(b){var a=b.headers&&b.headers.data||{};b={name:a.SITE_NAME||a.STORE_NAME||a.AREA_DESC,shortName:a.AREA_DESC,address:a.STORE_ADDR,description:a.AREA_DESC2,
latitude:a.STORE_LAT,longitude:a.STORE_LONG};a=a.STORE_ID||"default";"number"!==typeof e[a]&&(e[a]=c.sites.length,c.sites.push(p.mixin({areas:[]},b)));c.sites[e[a]].areas.push(p.mixin({feature:{attributes:{}}},b))});b.reportInfo.sites&&b.reportInfo.sites.forEach(function(b,a){a=c.sites[a];a.attributes=b.attributes;a.notes=b.notes;a.images=b.images;a.images&&a.images.forEach(function(b){function a(b){return(b=d[b])&&q.base64DataToDataURL(b,"image/png")}b.url=a(b.url);b.thumbnail=a(b.thumbnail)})})}
var L=this;J.reset();var d=c.reportItem.resources,w;if(!Array.isArray(d)){var x=d,d=[],m;for(m in x)d.push({name:m,data:x[m]})}d.forEach(function(b){"theme.css"===b.name&&(b.name="theme.css.txt")});var n=d.filter(function(b){return"report.xml"===b.name})[0],M=d.filter(function(b){return"data.xml"===b.name})[0],N=function(){var b=/.*\.(png|jpg|jpeg)$/i,c=/.*\.(json)$/i,e={},g={};d.forEach(function(a){b.test(a.name)&&(e[a.name]=a.data,"logo.png"===a.name&&(w=q.base64DataToDataURL(a.data,"image/png")));
if(c.test(a.name)){if(-1!==a.data.indexOf("mapOptions")&&-1!==a.data.indexOf("ComparisonResultsLayer.")){var d=JSON.parse(a.data);d.operationalLayers.filter(function(a){a.featureCollection&&a.featureCollection.layers&&(a.featureCollection.layers=a.featureCollection.layers.filter(function(a){return a.id&&0===a.id.indexOf("ComparisonResultsLayer.")?!1:!0}));return!0});a.data=JSON.stringify(d)}g[a.name]=a.data}});var a={},f=n.data.match(/<section[^<>]*query=".+?".*?>/g);f&&f.forEach(function(b){b=b.replace(/.*?query="/,
"");b=b.replace(/".*/,"");a[b]=1});var v={},f=A.parse(M.data,function(a,b,c){return(a=g[b])?(v[c]=1,a):e[b]||b});h(f,{map:v,locator:a});K(f,e);return f}(),y=new H;return k(function(b){var c=n.data.indexOf("\x3csection"),e={isGraphicReport:n.data.indexOf("\x3ctable")<c,isMultiFeature:!1,defaultComparisonZoom:null,type:C.STANDARD,portalJson:{files:d}};return k(D.provideEditorJson(e,{variableProvider:b}),function(){e.templateJson=G.deserialize(e.templateJson);e.isMultiFeature=E.hasMultiFeatureSections(e.templateJson);
delete e.portalJson;return e})}(y),function(b){r.parseSites(c);var d=t.areasFromJson(c.analysisAreas),e=c.combinedAreasInfo&&t.combinedAreasInfoFromJson(c.combinedAreasInfo)||{},g=c.attachmentsProvider&&F.getAttachmentsStoreFromJson(c.attachmentsProvider),a=L._infographicOptionsProvider.getInfographicOptions({analysisAreas:d}),f={isMultiFeature:b.isMultiFeature&&1<d.length,reportTitle:null,templateJson:b.templateJson,reportObject:b,fieldData:{specialTradeAreaCalculatorName:null,runReportTaskIDs:null,
metadata:{},areaData:[],errors:[],reportInfo:null},analysisAreas:d,combinedAreasInfo:e,reverseAnalysisAreasOnMap:!0,infographicOptions:a,attachmentsStore:g,templateVariableProvider:y,customLogo:w,config:{}};r.populateCombinedAreasInfo(f.combinedAreasInfo,f.analysisAreas);B.provideAreasIndexes(f);l.setGeoenrichmentUrl(null);u&&u.forEach(function(a){switch(a){case "Maps":l.addCapability("FormatInfographicsMaps");break;case "ImageUrls":l.addCapability("FormatInfographicsImageUrls")}});return k(z.applyRunReportAndGetDataResults(N,
f)).then(function(){return f})})}})});