// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.33/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/ReportPlayer/core/charts/utils/builder/columnBarLine/_ColumnBarChartSeriesCalculator","dojo/_base/lang ../../ThemeCalculator ../../ChartSorting ../../ChartLineStyles ../../../../supportClasses/conditionalStyling/ConditionalStyleUtil ../utils/TooltipInfoBuilder ./_ComparisonUtil ./_AxisBuilder ./_PointLabelUtil ./_StatsBuilder esri/dijit/geoenrichment/utils/ColorUtil".split(" "),function(I,A,v,w,J,K,L,x,B,M,G){var N={calcLineStyle:function(a,d){return{color:G.getColorWithAlpha(d.outlineColor||
a,d.outlineOpacity),width:d.outlineThickness,style:w.toGFXValue(d.outlineStyle||w.SOLID)}}};return{calcSeriesColumnBar:function(a){var d=a.chart,e=a.visualProperties,g=a.seriesItems,w=1===g.length,p=a.seriesItemsWithComparison||g,m=a.chartType,E=a.comparisonInfo,C=a.themeSettings,q=a.viewModel,r=1===p.length&&a.sorting,O=1<p.length&&e.renderColumnBarsInOppositeDirections,t=[],H=new M({visualProperties:e,seriesItems:p,viewModel:q,currentFeatureIndex:a.currentFeatureIndex,isMultiFeatureChart:a.isMultiFeatureChart,
excludedSeriesHash:a.excludedSeriesHash,comparisonFeatureAttributes:a.comparisonFeatureAttributes,chartType:m});B.createPointToLabelMap(d);var F={};p.forEach(function(f,g){if(f.points.length){var y={name:f.label,data:[],isComparisonSeries:f.isComparisonSeries,params:{plot:f.isComparisonSeries&&L.getComparisonPlotName(m,E)||void 0}},b=H.getStatisticsForSeriesAt(g);A.provideMissingIconsForPoints(f.points,m);var x=[];f.points.forEach(function(c,l){var d=b.values[l],D=d.value,h=D||0,k;if(e.conditionalStyling){var u=
J.getConditionalStyle(d.isBenchmarked?d.ownValue:h,e.conditionalStyling);k=u&&u.backgroundColor}k=k||A.calcColorForPoint({point:c,seriesItem:f,pointIndex:l,seriesIndex:g,numSeries:w?1:p.length,chartType:m,themeSettings:C,isComparisonSeries:f.isComparisonSeries,comparisonInfo:E,isMultiFeature:a.isMultiFeatureChart});var z=N.calcLineStyle(k,e),r=k;k=1>e.columnBarOpacity?G.getColorWithAlpha(k,e.columnBarOpacity):k;var n;c.hidden&&(n=k,k=r="transparent");var t;c.hidden&&(t=z.color,z.color="transparent");
u=l+1;h={x:u,y:h*(O&&g>=p.length/2?-1:1),originalValue:D,isUnavailableData:isNaN(D),valueProp:"y",unsortedIndex:l,originalIndex:c.originalIndex||l,seriesIndex:g,name:B.getPointLabel(c,q),valuesSumsInSeries:b.absSumInSeries,point:c,fill:k,icon:A.calcIconForPoint(c,r,m),bgIcon:A.calcBackgroundIconForPoint(c,m,C,e),stroke:{color:z.color,width:z.width,style:z.style},unhiddenFillColor:n,unhiddenLineColor:t,isBenchmarked:d.isBenchmarked,unbenchmarkedValue:d.ownValue};e.isStacked&&(n=e.showValuesAsWeightInStack?
b.stackValuesAsWeighedPercents:b.stackValues,h.stackValues=n&&n[l]);e.showValuesAsWeightInStack?h.y=b.weightsInStack?100*b.weightsInStack[l]:0:e.yAxis.showValuesAsWeightsInSeries&&(h.y/=b.absSumInSeries/100);n=B.getPointLabel(p[0].points[l]||c,q);c=K.getTooltipInfo({yValue:D,pointLabel:n,seriesLabel:f.label,isSinglePointInSeries:1===f.points.length,minInSeriesValue:b.minInSeries,maxInSeriesValue:b.maxInSeries,sumInSeriesValue:b.sumInSeries,absSumInSeriesValue:b.absSumInSeries,avgInSeriesValue:b.avgInSeries,
weightInStack:b.weightsInStack&&b.weightsInStack[l],minInAreasValue:b.minInSeries,maxInAreasValue:b.maxInSeries,sumInAreasValue:b.sumInSeries,absSumInAreasValue:b.absSumInSeries,avgInAreasValue:b.avgInSeries,visualProperties:e,chartType:m,isMultiFeature:a.isMultiFeatureChart,conditionalStyling:e.conditionalStyling,fieldInfo:c.fieldInfo,isThisAreaSpecific:E&&!a.isMultiFeatureChart?!f.isComparisonSeries:void 0,isThisAreaSingleSeries:w,decimals:c.value&&c.value.decimals,fill:h.fill,stroke:0<h.stroke.width?
h.stroke.color:void 0,isBenchmarked:d.isBenchmarked,unbenchmarkedValue:d.ownValue,chartContainer:a.chartContainer,viewModel:q,theme:a.theme,themeSettings:C,dataDrillingPanelInfo:a.dataDrillingPanelInfo,pointName:a.isMultiFeatureChart?f.label:n,seriesName:c.originalSeriesName||f.label,areaName:c.areaName,featureIndex:d.featureIndex,isComparisonPoint:c.isComparisonPoint,comparisonFeatureAttribute:c.comparisonFeatureAttribute});var v=F[u]=F[u]||[];a.excludedSeriesHash[f.label]||(v.push(c),x.push(c));
c.getGroup=function(){return a.isMultiFeatureChart?x:v};h.tooltip=c;y.data.push(h)});r&&r!==v.NONE&&(y.data.sort(function(a,b){return(a.y-b.y)*(r===v.DESC?-1:1)}),y.data.forEach(function(a,b){a.x=b+1}));y.data.forEach(function(a){B.updatePointIndexToLabelMap(d,a.x,g,a.point,q)});t.push(y)}},this);g=H.getTotalStats();x.prettifyYAxis(g.minYValue,g.maxYValue,d,e,m,C,q,t);a.plotStats&&(I.mixin(a.plotStats,g),a.plotStats.pointIndexToTooltipsHash=F);return t},prettifyColumnBarYAxis:function(a){x.prettifyYAxis(a.totalStat.minYValue,
a.totalStat.maxYValue,a.chart,a.visualProperties,a.chartType,a.themeSettings,a.viewModel,a.chartSeries,!0,a.chartSize);a.chart.dirty=!0}}});