// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.33/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/ReportPlayer/core/charts/utils/builder/columnBarLine/_LineChartSeriesCalculator","dojo/_base/lang ../../ThemeCalculator ../../ChartTypes ../../ChartLineStyles ../../ChartLineMarkers ../../AxisUtil ../utils/TooltipInfoBuilder ../ChartPlots esri/dijit/geoenrichment/utils/ColorUtil ./_AxisBuilder ./_PointLabelUtil ./_StatsBuilder".split(" "),function(K,q,I,y,v,L,M,N,w,O,H,P){var Q={calcLineStyle:function(a,z,h,f){var b=f.comparisonInfo,F=f.themeSettings,c=f.visualProperties,
r=a.lineThickness||c.lineThickness||1,k=1,G=1,C=1;c.fillLineArea?(k="number"===typeof c.lineOpacity?c.lineOpacity:c.lineAreaOpacity,G=c.lineAreaOpacity):"number"===typeof c.lineOpacity&&(k=c.lineOpacity);h=q.calcColorForPoint({point:null,seriesItem:a,pointIndex:0,seriesIndex:z,numSeries:h.length,chartType:I.LINE,themeSettings:F,isComparisonSeries:a.isComparisonSeries,comparisonInfo:b,isMultiFeature:f.isMultiFeatureChart});1>k&&h&&(h=w.toColor(h),h.a=k);var F=a.lineStyle||y.SOLID,l,d,g,x=a.lineMarkerSize,
u=w.toColor(a.fillColor||h);u.a=G;g=w.toColor(a.lineMarkerColor||h);g.a=k;C="number"===typeof c.lineMarkersFillOpacity?c.lineMarkersFillOpacity:G;c=w.toColor(a.lineMarkerFillColor||u);c.a=C;a.isComparisonSeries&&b?(b.lineThickness&&(r=b.lineThickness),b.lineStyle&&(F=b.lineStyle),b.lineMarkerSize&&(x=b.lineMarkerSize),b.lineMarker?(d=v.getMarkerPath(b.lineMarker),l=v.getMarkerPath(b.lineMarker,x)):(d=q.getComparisonSymbol(),l=q.getComparisonSymbol(x)),b.lineMarkerColor&&(g=w.toColor(b.lineMarkerColor),
g.a=k),b.lineMarkerFillColor&&(c=w.toColor(b.lineMarkerFillColor),c.a=G)):f.viewModel.isGraphicStyle&&(d=a.lineMarker&&v.getMarkerPath(a.lineMarker)||v.getMarkerPathAt(z),l=a.lineMarker&&v.getMarkerPath(a.lineMarker,x)||v.getMarkerPathAt(z,x));return{lineColor:h,width:r,style:y.toGFXValue(F),marker:l,unscaledMarker:d,markerColor:g,markerFillColor:c,fillColor:u}}};return{calcSeriesLine:function(a){var z=a.chart,h=a.chartType,f=a.visualProperties,b=a.seriesItems,v=1===b.length,c=a.seriesItemsWithComparison||
b,r=a.isSecondaryPlot,k=a.reverseXY||h===I.VERTICAL_LINE,w=a.comparisonInfo,C=a.themeSettings,l=a.viewModel,d=[],g=new P({visualProperties:f,seriesItems:c,viewModel:l,currentFeatureIndex:a.currentFeatureIndex,isMultiFeatureChart:a.isMultiFeatureChart,comparisonFeatureAttributes:a.comparisonFeatureAttributes,chartType:h,isSecondaryPlot:r,oppositeDirections:a.oppositeDirections,excludedSeriesHash:a.excludedSeriesHash}),x=a.primaryPlotStat&&a.primaryPlotStat.pointIndexToTooltipsHash||{},u=g.getTotalStats();
c.forEach(function(b,A){if(b.points.length){var m=Q.calcLineStyle(b,A,c,a),B={name:b.label,data:[],isComparisonSeries:b.isComparisonSeries,params:{plot:r?N.SECONDARY:void 0,fill:f.fillLineArea?m.fillColor:"transparent",stroke:{color:m.lineColor,width:m.width,style:m.style},marker:m.marker,unscaledMarker:m.unscaledMarker,markerStroke:{color:m.markerColor,width:m.width,style:y.toGFXValue(y.SOLID)},markerFill:f.fillLineMarkers?m.markerFillColor:"transparent",outline:!1}},n=g.getStatisticsForSeriesAt(A);
b.points.forEach(function(e,d){function m(){return r&&!a.oppositeDirections&&2===a.primarySeries.length?0===A?-.15:.15:0}if(!e.hidden){var g=n.values[d],q=g.value,D=q||0,E=d+1;r||H.updatePointIndexToLabelMap(z,E,A,e,l);var t=a.isMultiFeatureChart&&u.crossSeriesStats[d],p={originalValue:q,isUnavailableData:isNaN(q),unsortedIndex:d,originalIndex:e.originalIndex||d,name:H.getPointLabel(e,l),valuesSumsInSeries:n.absSumInSeries,seriesItem:b,seriesIndex:A,point:e,isBenchmarked:g.isBenchmarked,unbenchmarkedValue:g.ownValue};
k?(p.x=D*(r&&a.oppositeDirections&&1===A?-1:1),p.y=E+m(),p.valueProp="x"):(p.x=E+m(),p.y=D*(r&&a.oppositeDirections&&1===A?-1:1),p.valueProp="y");f.showValuesAsWeightInStack?p[k?"x":"y"]=n.weightsInStack?100*n.weightsInStack[d]:0:f.yAxis.showValuesAsWeightsInSeries&&(p[k?"x":"y"]/=n.absSumInSeries/100);D=H.getPointLabel(c[0].points[d]||e,l);e=M.getTooltipInfo({yValue:q,pointLabel:D,seriesLabel:b.label,minInSeriesValue:n.minInSeries,maxInSeriesValue:n.maxInSeries,sumInSeriesValue:n.sumInSeries,absSumInSeriesValue:n.absSumInSeries,
avgInSeriesValue:n.avgInSeries,weightInStack:n.weightsInStack&&n.weightsInStack[d],minInAreasValue:t&&t.min,maxInAreasValue:t&&t.max,sumInAreasValue:t&&t.sum,absSumInAreasValue:t&&t.absSum,avgInAreasValue:t&&t.avg,visualProperties:f,chartType:h,isMultiFeature:a.isMultiFeatureChart,conditionalStyling:null,fieldInfo:e.fieldInfo,isThisAreaSpecific:w&&!a.isMultiFeatureChart?!b.isComparisonSeries:void 0,isThisAreaSingleSeries:v,decimals:e.value&&e.value.decimals,fill:B.params.markerFill,stroke:B.params.markerStroke.color,
marker:B.params.unscaledMarker||B.params.marker,isBenchmarked:g.isBenchmarked,unbenchmarkedValue:g.ownValue,chartContainer:a.chartContainer,viewModel:l,theme:a.theme,themeSettings:C,dataDrillingPanelInfo:a.dataDrillingPanelInfo,pointName:D,seriesName:e.originalSeriesName||b.label,areaName:e.areaName,featureIndex:g.featureIndex,isComparisonPoint:e.isComparisonPoint,comparisonFeatureAttribute:e.comparisonFeatureAttribute});var y=x[E]=x[E]||[];y.push(e);e.getGroup=function(){return y};p.tooltip=e;B.data.push(p)}});
d.push(B)}},this);if(r){if(a.primaryPlotStat&&(a.primaryPlotStat.minYValue=Math.min(u.minYValue,a.primaryPlotStat.minYValue),a.primaryPlotStat.maxYValue=Math.max(u.maxYValue,a.primaryPlotStat.maxYValue),b=L.getPrettifyYAxisParameters(a.primaryPlotStat.minYValue,a.primaryPlotStat.maxYValue,{baseLineValue:f.yAxis.baseLineValue,renderColumnBarsInOppositeDirections:a.oppositeDirections,previewBelowZero:!l.dynamicReportInfo,nonZeroInclusive:f.yAxis.nonZeroInclusive}),K.mixin(z.axes.y.opt,{majorTickStep:b.majorTickStep,
minorTickStep:b.minorTickStep,min:b.min,max:b.max})),1===a.primarySeries.length){var q=k?"y":"x",J=[];a.primarySeries[0].data.forEach(function(a){var b=d[0].data[a.unsortedIndex];b[q]=a.x;J.push(b)});d[0].data=J}}else O.prettifyYAxis(u.minYValue,u.maxYValue,z,f,h,C,l);return d}}});