// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.33/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/utils/TooltipUtil","dojo/_base/declare dojo/_base/lang dojo/dom-class dojo/dom-construct dojo/dom-geometry dojo/dom-style dojo/on dojo/mouse dojo/sniff dijit/Tooltip dijit/place dojox/gfx ./DeviceUtil ./DnDUtil ./DomUtil ./MouseUtil dojo/domReady!".split(" "),function(C,D,q,k,r,E,n,w,y,z,F,G,x,H,u,p){function A(){}var f={},I=C(z._MasterTooltip,{_customClasses:null,_customStyle:null,_orientKey:null,addCustomClasses:function(a){a&&(q.add(this.domNode,a),this._customClasses=
a)},setCustomStyle:function(a){this._customStyle=a},show:function(a,e,c,d,b,f,g){if(!this.aroundNode||this.aroundNode!==e||this.containerNode.innerHTML!=a)if("playing"==this.fadeOut.status())this._onDeck=arguments;else{"string"===typeof a?this.containerNode.innerHTML=a:(this.containerNode.innerHTML="",k.place(a.domNode||a,this.containerNode));b&&this.set("textDir",b);this.containerNode.align=d?"right":"left";var h=F.around(this.domNode,e,c&&c.length?c:z.defaultPosition,!d,D.hitch(this,"orient")),
t=h.aroundNodePos;"M"==h.corner.charAt(0)&&"M"==h.aroundCorner.charAt(0)?(this.connectorNode.style.top=t.y+(t.h-this.connectorNode.offsetHeight>>1)-h.y+"px",this.connectorNode.style.left=""):"M"==h.corner.charAt(1)&&"M"==h.aroundCorner.charAt(1)?this.connectorNode.style.left=t.x+(t.w-this.connectorNode.offsetWidth>>1)-h.x+"px":(this.connectorNode.style.left="",this.connectorNode.style.top="");this._drawBackground();this.domNode.style.opacity="0";this.fadeIn.play();this.isShowingNow=!0;this.aroundNode=
e;this.onMouseEnter=f||A;this.onMouseLeave=g||A}},orient:function(a,e,c,d,b){this.connectorNode.style.top="";var f=d.h;d=d.w;a.className="dijitTooltip "+{"MR-ML":"dijitTooltipRight","ML-MR":"dijitTooltipLeft","TM-BM":"dijitTooltipAbove","BM-TM":"dijitTooltipBelow","BL-TL":"dijitTooltipBelow dijitTooltipABLeft","TL-BL":"dijitTooltipAbove dijitTooltipABLeft","BR-TR":"dijitTooltipBelow dijitTooltipABRight","TR-BR":"dijitTooltipAbove dijitTooltipABRight","BR-BL":"dijitTooltipRight","BL-BR":"dijitTooltipLeft"}[this._orientKey=
e+"-"+c];this.addCustomClasses(this._customClasses);this.domNode.style.width="auto";var g=r.position(this.domNode);if(y("ie")||y("trident"))g.w+=2;r.setMarginBox(this.domNode,{w:Math.min(Math.max(d,1),g.w)});"B"==c.charAt(0)&&"B"==e.charAt(0)?(a=r.position(a),e=this.connectorNode.offsetHeight,a.h>f?(this.connectorNode.style.top=f-(b.h+e>>1)+"px",this.connectorNode.style.bottom=""):(this.connectorNode.style.bottom=Math.min(Math.max(b.h/2-e/2,0),a.h-e)+"px",this.connectorNode.style.top="")):(this.connectorNode.style.top=
"",this.connectorNode.style.bottom="");this._drawBackground();return Math.max(0,g.w-d)},_surface:null,_surfaceContainer:null,_drawBackground:function(){if(this._orientKey){var a=this.domNode.clientWidth,e=this.domNode.clientHeight,c=r.position(this.domNode),d=r.position(this.connectorNode),b=r.position(this.containerNode);d.x-=c.x;d.y-=c.y;b.x-=c.x;b.y-=c.y;b.x+=1;b.y+=1;b.w-=2;b.h-=2;this._surface&&this._surface.destroy();this._surfaceContainer&&k.destroy(this._surfaceContainer);c=this._surfaceContainer=
k.create("div",{"class":"esriGEAbsoluteStretched"},this.domNode,"first");c.style.pointerEvents="none";a=this._surface=G.createSurface(c,a,e);e=[{x:b.x,y:b.y},{x:b.x+b.w,y:b.y},{x:b.x+b.w,y:b.y+b.h},{x:b.x,y:b.y+b.h},{x:b.x,y:b.y}];c=d.x+d.w/2;d=d.y+d.h/2;switch(this._orientKey){case "BL-TL":case "BM-TM":case "BR-TR":b=[{x:c-5,y:b.y},{x:c,y:d},{x:c+5,y:b.y}];e.splice.apply(e,[1,0].concat(b));break;case "ML-MR":case "BL-BR":b=[{x:b.x+b.w,y:d-5},{x:c,y:d},{x:b.x+b.w,y:d+5}];e.splice.apply(e,[2,0].concat(b));
break;case "TM-BM":case "TL-BL":case "TR-BR":b=[{x:c+5,y:b.y+b.h},{x:c,y:d},{x:c-5,y:b.y+b.h}];e.splice.apply(e,[3,0].concat(b));break;case "MR-ML":case "BR-BL":b=[{x:b.x,y:d+5},{x:c,y:d},{x:b.x,y:d-5}],e.splice.apply(e,[4,0].concat(b))}b=a.createPolyline(e);d="function"===typeof this._customStyle?this._customStyle():this._customStyle;b.setFill(d&&d.backgroundColor||"white").setStroke({color:"#d3d3d3",width:1,join:"round"});d&&d.color&&(this.containerNode.style.color=d.color)}}}),B={show:function(a,
e,c,d,b){"string"===typeof c&&(c=[c]);c=c&&c.map(function(a){return{after:"after-centered",before:"before-centered"}[a]||a});var f=new I;b&&f.setCustomStyle(b);f.addCustomClasses(d);f.show(a,e,c);return f}};f.setTooltipToNode=function(a,e,c){function d(){!b&&f.showTooltipForNode(a,e,c)}c=c||{};if(a&&(f.hideTooltipForNode(a),a.__setTooltipToNodeMouseEnterHandle&&a.__setTooltipToNodeMouseEnterHandle.remove(),e)){var b=!1;x.isMobileDevice()?a.__setTooltipToNodeMouseEnterHandle=H.addNoDragClickHandler(a,
d):a.__setTooltipToNodeMouseEnterHandle=n(a,w.enter,d);c.showTooltip&&d();return{remove:function(){e=null;f.hideTooltipForNode(a)},suspend:function(){f.hideTooltipForNode(a);b=!0},resume:function(){b=!1},refresh:function(){a._shownTooltip&&d()}}}};f.showTooltipForNode=function(a,e,c){function d(){f.hideTooltipForNode(a);var d=Array.isArray(c.classes)?c.classes.join(" "):c.classes,d=(d||"")+" esriGETooltip";c.notRestricted&&(d+=" notRestricted");a._shownTooltip=t=B.show(b,a,c.position||["after","before"],
d,c.style)}if(a){f.hideTooltipForNode(a);var b="function"==typeof e?e():e;if(b){c.textAlign&&(b="\x3cdiv class\x3d'"+("start"===c.textAlign?"esriGEStart":"end"===c.textAlign?"esriGEEnd":"")+"'\x3e"+b+"\x3c/div\x3e");q.add(a,"esriGESimpleTextTooltip");var t;d();var g=f.hideTooltipForNode.bind(f,a);x.isMobileDevice()?a.__setTooltipToNodeMouseLeaveHandle=n(document.body,"touchstart",function(b){p.isMouseOver(a,{event:b})||g()}):a.__setTooltipToNodeMouseLeaveHandle=n.once(a,w.leave,function(){!c.stayOnHover&&
g()});c.ignoreNodeRemoval||(a.__setTooltipToNodeInLayoutHandle=setInterval(function(){!u.isNodeInLayout(a)&&g()},300));x.isMobileDevice()||(a.__setTooltipToNodeMouseOverHandle=setInterval(function(){c.stayOnHover&&p.isMouseOver(t.domNode)||p.isMouseOver(a)||g()},300),a.__setTooltipToNodeClickHandle=n(a,"click",function(b){c.hideOnClick?g():!a._shownTooltip&&d()}),c.stayOnHover&&(a.__setTooltipToNodeMouseLeaveMasterHandle=n(t.domNode,w.leave,g)));return a._shownTooltip}}};f.isShown=function(a){return!(!a||
!a._shownTooltip)};f.hideTooltipForNode=function(a){a&&(a.title="",q.remove(a,"esriGESimpleTextTooltip"),a._shownTooltip&&a._shownTooltip.destroy(),delete a._shownTooltip,a.__setTooltipToNodeMouseLeaveHandle&&a.__setTooltipToNodeMouseLeaveHandle.remove(),clearInterval(a.__setTooltipToNodeInLayoutHandle),clearInterval(a.__setTooltipToNodeMouseOverHandle),a.__setTooltipToNodeClickHandle&&a.__setTooltipToNodeClickHandle.remove(),a.__setTooltipToNodeMouseLeaveMasterHandle&&a.__setTooltipToNodeMouseLeaveMasterHandle.remove())};
var l,m;f.autoTooltip=function(a){n(a,".TrimWithEllipses:mouseover",function(){if(this!==l&&this.offsetWidth<this.scrollWidth){var a=function(){l=null;m&&(m.tooltip.destroy(),m.mouseOutH.remove(),m.mouseMoveH.remove(),m=null)};a();l=this;m={tooltip:B.show(l.textContent,l,["above","below"]),mouseOutH:n.once(l,"mouseout, mousedown, touchstart",a),mouseMoveH:n(document.body,"mousemove",function(){p.isMouseOver(l)||a()})}}})};f.showClosableTooltip=function(a){var e=f._createClosableTooltip(a.message,
a.tooltipClass,a.position);return f._placeClosableTooltip(e,a.node,a.timeout,a.position,a.onClosed)};f.removeClosableTooltip=function(a){a&&a._removeFunc&&a._removeFunc()};f._createClosableTooltip=function(a,e,c){function d(){var a=k.create("div",{"class":"esriGEClosableTooltipTip"},f);q.add(a,"right"===c?"esriGEClosableTooltipTipRight":"esriGEClosableTooltipTipLeft")}function b(){g=k.create("div",{"class":"esriGEClosableTooltipBody"},f);k.create("div",{innerHTML:a,"class":"esriGEClosableTooltipLabel"},
g);h=k.create("div",{"class":"esriGEClosableTooltipCloseButton"},g)}var f=k.create("div",{"class":"esriGEClosableTooltip esriGENonSelectable "+(e||"")},document.body),g,h;"right"!==c?(b(),d()):(d(),b());f.style.position="fixed";return{tooltip:f,body:g,closeButton:h}};f._placeClosableTooltip=function(a,e,c,d,b){function f(){var b=r.position(e),c=b.x+";"+b.y+";"+b.w+";"+b.h;c!==h&&(h=c,c=r.getMarginBox(a.tooltip),E.set(a.tooltip,{left:(g?b.x+b.w:b.x-c.w)+"px",top:b.y+b.h/2-c.h/2+"px"}))}var g="rtl"===
document.dir&&"right"!==d||"rtl"!==document.dir&&"right"===d,h;f();var k,l,m,q,p,v=function(){k&&clearTimeout(k);l&&clearInterval(l);m&&clearInterval(m);q&&q.remove();a.tooltip.parentNode&&a.tooltip.parentNode.removeChild(a.tooltip)};l=setInterval(function(){u.isNodeInLayout(e)&&e.parentNode||(p=!1,v());u.isNodeVisible(e)&&u.isNodeOnscreen(e)?(p=!0,u.show(a.tooltip)):(p=!1,u.hide(a.tooltip))},0);m=setInterval(function(){p&&f()},0);c&&(k=setTimeout(v,c));q=n(a.closeButton,"click",function(){v();b&&
b()});a.tooltip._removeFunc=v;return a.tooltip};f.showTooltipForNode(document.body,"Normal \x3cb\x3eBold\x3c/b\x3e \x3ci\x3eItalic\x3c/i\x3e",{});f.hideTooltipForNode(document.body);return f});