// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.33/esri/copyright.txt for details.
//>>built
require({cache:{"url:esri/dijit/geoenrichment/ReportPlayer/core/templates/DynamicInfographic.html":'\x3cdiv data-dojo-attach-point\x3d"viewDiv" class\x3d"esriGE_dynamicInfographic"\x3e\r\n    \x3cdiv data-dojo-attach-point\x3d"noDataPlaceHolder" class\x3d"esriGENoDataPlaceHolder"\x3e\r\n        \x3cdiv class\x3d"esriGENoDataPlaceHolderLabel"\x3e${nls.noInfographicData}\x3c/div\x3e\r\n    \x3c/div\x3e\r\n    \x3cdiv data-dojo-attach-point\x3d"infographicDiv"\x3e\x3c/div\x3e\r\n    \x3cdiv data-dojo-attach-point\x3d"errorDiv" class\x3d"esriGEReportPlayerPanelErrorMessage"\x3e${nls.dynamicInfographicError}\x3c/div\x3e\r\n\x3c/div\x3e'}});
define("esri/dijit/geoenrichment/ReportPlayer/core/infographics/dynamic/DynamicInfographic","dojo/_base/declare dojo/_base/lang esri/dijit/geoenrichment/Deferred esri/dijit/geoenrichment/when dojo/dom-style dojo/query dojo/on dijit/_WidgetBase dijit/_TemplatedMixin esri/dijit/geoenrichment/infographicUtils/theme ./_Infographic ../InfographicTypes esri/dijit/geoenrichment/utils/DelayUtil esri/dijit/geoenrichment/utils/DomUtil esri/dijit/geoenrichment/utils/InvokeUtil esri/dijit/geoenrichment/utils/MouseUtil ../utils/InfographicJsonUtil ../extentions/BaseSelectComparisonExt dojo/text!../../templates/DynamicInfographic.html dojo/i18n!esri/nls/jsapi ../../../_devConfig".split(" "),
function(l,r,t,h,c,p,m,v,w,x,u,d,y,k,z,A,n,B,C,q,D){q=q.geoenrichment.dijit.ReportPlayer.Infographics;var g={};g[d.ONE_VAR]=230;g[d.AGE_PYRAMID]=0;g[d.RELATED_VARS]=320;g[d.TAPESTRY]=300;g[d.PRIZM5]=300;l=l([v,w],{templateString:C,nls:q,viewModel:null,theme:null,currentFeatureIndex:null,_infographic:null,_stdPolygonsController:null,_thisAreasHighlightController:null,_initPromise:null,buildRendering:function(){B.init();this.inherited(arguments)},postCreate:function(){this.inherited(arguments);this._showError(!1);
this._showEmptyView(!1)},_currentInfographicJson:null,updateInfographic:function(a){if(this.viewDiv)return this._destroyCurrentInfographic(),this._currentInfographicJson=a,this.viewModel.dynamicReportInfo&&this._currentInfographicJson.calcData&&d.supportsComparison(this._currentInfographicJson.type)&&(this._stdPolygonsController=this.viewModel.getStdPolygonsController(this._currentInfographicJson.calcData.calculatorName,this.currentFeatureIndex),this._currentInfographicJson.type===d.ONE_VAR&&(this._thisAreasHighlightController=
this.viewModel.getThisAreasHighlightController())),this._enrichInfographicJsonWithProps(a),this.domNode.style.opacity="0.001",this._initPromise=h(this._createInfographicWidgetFromJson(a),function(){this.domNode&&(this._applyTheme(a),this.domNode.style.opacity="")}.bind(this))},_enrichInfographicJsonWithProps:function(a){n.setLevels(a,a.levels)},_createInfographicWidgetFromJson:function(a){var b=this,f=new t,c=this.viewModel.getInfographicDefaultStyles(this.theme);x.set(this.viewDiv,c&&c.agePyramid&&
c.agePyramid.theme||"light");if(this.viewModel.dynamicReportInfo&&this.viewModel.dynamicReportInfo.infographicOptions){var e=this.viewModel.dynamicReportInfo.infographicOptions;this.viewModel.dynamicReportInfo.isFixedDataMode||this.viewModel.dynamicReportInfo.geClient.hasCapability("ComparisonLevelsInCalculators")||(a.calcData=null);this._infographic=(new u({documentStyleProvider:this.viewModel.getDocumentDefaultStyles(this.theme),infographicStyleProvider:c,widgetParams:this._getWidgetCreationParams(a),
returnGeometry:!1,autoTitle:!1,subtitle:!1,levels:n.getSubLevels(a),highestLevel:n.getHighestLevel(a),onDataRequest:function(){b._showProgress(!0,"data")},onDataReady:function(){h(b.resize(),function(){b._showProgress(!1,"data");b._syncWithShownFeatures();f.resolve()})},onDataError:function(){b._showProgress(!1,"data");b._showError(!0)},onExpandedStateChanged:function(){b._doResize()},onSelectedFeatureChanged:function(){b._syncWithShownFeatures()}})).placeAt(this.infographicDiv);this._showProgress(!0,
"item");return h(function(){return a.calcData?{title:a.title,type:a.type,variables:a.variables||a.calcData.variables}:h(e.getOptions().getItems(e.countryID),function(b){var f;b.some(function(b){if(b.variables&&b.variables.length){var e=n.analyzeVariables(a),d=b.variables[0];if(e.variableID&&-1!==d.indexOf(e.variableID)||e.dataCollectionID&&0===d.indexOf(e.dataCollectionID))return f=b,!0}});return f})}(),function(c){b._showProgress(!1,"item");if(c){var g=e.createGeoenrichment({infographicJson:a,areaData:b.viewModel.dynamicReportInfo.fieldData.areaData,
isMultiFeature:!1,currentFeatureIndex:b.currentFeatureIndex});b._infographic.setGeoenrichment(g);b._infographic.set("expanded",a.type===d.TAPESTRY||1<g.getData().features.length);b._infographic.set("studyArea",e.studyArea);b._infographic.set("countryID",e.countryID);b._infographic.set("type",a.type);b._infographic.set("variables",c.variables);b._infographic.set("title",c.title);b._infographic.startup();var k=!g.isBusy();a.title=a.title||c.title;return h(b.resize(),function(){k&&(b._showProgress(!1,
"data"),b._syncWithShownFeatures(),f.resolve());return f.promise})}b._showError(!0)})}try{return this._createDummyInfographic(a)}catch(E){console.log(E),this._showError(!0)}},_getWidgetCreationParams:function(a){var b={};switch(a.type){case d.AGE_PYRAMID:b.showVerticalAxis=a.showVerticalAxis;break;case d.ONE_VAR:b.isMultiFeature=!1;break;case d.TAPESTRY:case d.PRIZM5:b.titleStyle=a.style.titleStyle,b.backgroundColor=a.style.backgroundColor,b.tableBackgroundColor=a.style.tableBackgroundColor,b.tableBorderColor=
a.style.tableBorderColor,b.textStyle=a.style.textStyle,b.subtextStyle=a.style.subtextStyle,b.hyperlinkTextStyle=a.style.hyperlinkTextStyle,b.detailsValueBorderColor=a.style.detailsValueBorderColor}return b},_createDummyInfographic:function(a){},_syncWithShownFeatures:function(){if(this._stdPolygonsController&&this._infographic&&this._infographic._widget){this._stdPolygonsController.setAttributeFields(this._infographic.dataProvider.getAttributeFields());var a=this._infographic.dataProvider.getAllGeographyAttributes({ignoreFilters:!0}),
b;if(this._currentInfographicJson.type===d.ONE_VAR)b=this._infographic.dataProvider.getAllGeographyAttributes();else{b=[];var f=this._infographic._widget.select&&this._infographic._widget.select.getSelectedAttributes();f&&b.push(f)}this._stdPolygonsController.setShownFeatureAttributes(b);this._stdPolygonsController.setAllFeatureAttributes(a);this._currentInfographicJson.type===d.ONE_VAR&&(this._registerStdPolygonsHighlight(a),this._registerThisAreaHighlight())}},_registerStdPolygonsHighlight:function(a){var b=
this;this._stdPolygonsController.registerInfographic({highlightInfographicForAttributes:function(a){b._isCreated()&&(a=b._infographic._widget.setTableRowHighlighted(a))&&(b.viewDiv.scrollTop=a.offsetTop+200-b.viewDiv.clientHeight)}}).then(function(){if(b._isCreated()){var d;m(b._infographic._widget.table,"mouseover, mousemove",function(){var c=b._infographic._widget.getOverRow();if(c&&c!==d){var e=(d=c)&&c.cells[0].innerHTML,f;e&&a.some(function(a){if(a.StdGeographyName===e)return f=a,!0});f&&(b._stdPolygonsController.highlightGraphicForAttributes(f),
b._infographic._widget.setTableRowHighlighted(f))}});m(b._infographic._widget.table,"mouseout",function(){b._stdPolygonsController.highlightGraphicForAttributes(null);b._infographic._widget.setTableRowHighlighted(null);d=null})}})},_registerThisAreaHighlight:function(){var a=this;this._thisAreasHighlightController.registerTable({highlightTableForAreaIndex:function(b){if(a._isCreated())if(a.currentFeatureIndex===b){if(b=a._infographic._widget.setThisAreaTableRowHighlighted())a.viewDiv.scrollTop=b.offsetTop+
200-a.viewDiv.clientHeight}else a._infographic._widget.setTableRowHighlighted(null)}}).then(function(){if(a._isCreated()){var b;m(a._infographic._widget.table,"mouseover, mousemove",function(){var c=a._infographic._widget.getOverRow();c&&c!==b&&(b=c,a._infographic._widget.isThisAreaRow(b)&&(a._thisAreasHighlightController.highlightGraphicForAreaIndex(a.currentFeatureIndex),a._infographic._widget.setThisAreaTableRowHighlighted()))});m(a._infographic._widget.table,"mouseout",function(){a._thisAreasHighlightController.highlightGraphicForAreaIndex(null);
a._infographic._widget.setTableRowHighlighted(null);b=null})}})},_applyTheme:function(a){this._infographic&&(c.set(this._infographic.domNode,"backgroundColor",a.style&&a.style.backgroundColor||"transparent"),c.set(this._infographic.domNode,"fontFamily","inherit"))},_destroyCurrentInfographic:function(){this._showError(!1);this._showProgress(!1);this._infographic&&this._infographic.destroy();this._infographic=null},_itemLoadingState:0,_dataLoadingState:0,_contentLoadingState:0,_waitingDfd:null,_showProgress:function(a,
b){a?this._waitingDfd||(this._waitingDfd=new t,this.onShowWaiting(this._waitingDfd.promise)):this._waitingDfd&&(this._waitingDfd.resolve(),this._waitingDfd=null);"item"===b?this._itemLoadingState=a?1:2:"data"===b&&(this._dataLoadingState=a?1:2);1!==this._itemLoadingState&&1!==this._dataLoadingState||0!==this._contentLoadingState||(this._contentLoadingState=1,this.onContentLoadingStart());2===this._itemLoadingState&&2===this._dataLoadingState&&1===this._contentLoadingState&&(this._contentLoadingState=
2,this.onContentLoadingEnd())},_filterRangesStats:null,_filterRanges:null,getFilterRanges:function(){return h(this._initPromise,function(){return(this._filterRangesStats=this._infographic.dataProvider.collectFilterRangesStats({excludeThisAreas:!0}))&&this._filterRangesStats.filterRanges}.bind(this))},setFilterRanges:function(a){this._filterRanges=a;return h(this._initPromise,function(){this._infographic.dataProvider.setFilterRanges(a,{ignoreThisAreas:this._currentInfographicJson.type===d.ONE_VAR});
this._infographic._widget.select?(this._infographic._widget.select.setFeatures(this._infographic.dataProvider.getData().features),this._infographic._widget.select.setDefaultValue({emitEvent:!0})):(this._infographic._widget.setDataProvider(this._infographic.dataProvider),this._doResize());this._syncWithShownFeatures();this._showEmptyView(!this.getNumAreasShown());this.onContentUpdated()}.bind(this))},getNumAreasTotal:function(){return this._filterRangesStats&&this._filterRangesStats.numAreasTotal||
0},getNumAreasShown:function(){if(this._currentInfographicJson.type===d.ONE_VAR)return this._infographic.dataProvider.getAllGeographyAttributes().length;if(this._infographic._widget.select)return this._infographic._widget.select.getNumFeatures&&this._infographic._widget.select.getNumFeatures()||0},_showEmptyView:function(a){k[a?"hide":"show"](this.infographicDiv);k[a?"show":"hide"](this.noDataPlaceHolder);a&&this._syncEmptyViewPlaceholder()},_syncEmptyViewPlaceholder:function(){this.noDataPlaceHolder&&
c.set(this.noDataPlaceHolder,"paddingTop",(this.height-c.get(this.noDataPlaceHolder,"height"))/2+"px")},notifyShown:function(){},width:null,height:null,_infographicResizedAtLeastOnce:!1,_hasScroll:!1,resize:function(a,b){void 0!==a&&(this.width=a,this.height=b);return z.invoke(this,"_doResize",50)},_doResize:function(){var a=this;if(this._infographic&&this._infographic.domNode&&k.isNodeInLayout(this.domNode)&&this._currentInfographicJson){this._syncJsonDimensions();var b=this._currentInfographicJson.type,
f=Math.max(function(){if(b===d.ONE_VAR){var e=p(".OneVarMultiComparison_Table",a.domNode)[0],e=e?c.get(e,"height")+120:0;return Math.max(e,g[b])}return b===d.TAPESTRY?(e=(e=p(".Tapestry_Main_Table",a.domNode)[0])?c.get(e,"height")+60:0,Math.max(e,g[b])):b===d.PRIZM5?(e=(e=p(".Prizm5_Main_Table",a.domNode)[0])?c.get(e,"height")+60:0,Math.max(e,g[b])):b!==d.RELATED_VARS||a._infographic.expanded?g[b]:200}(),this.height);this._hasScroll=f>this.height;var h=this.width-(this._hasScroll?k.getScrollbarSize().w+
3:0);c.set(this._infographic.domNode,{width:h+"px",height:f+"px"});c.set(this.viewDiv,{height:this.height+"px",overflowY:"auto"});this._infographic.resize();this._adjustErrorMessage();return y.delay()}},hasScroll:function(){return this._hasScroll},changeScroll:function(a,b){this.domNode.scrollLeft+=a;this.domNode.scrollTop+=b},_syncJsonDimensions:function(){this._currentInfographicJson.style=this._currentInfographicJson.style||{};this._currentInfographicJson.style.width=this.width;this._currentInfographicJson.style.height=
this.height},getPreferredHeight:function(){return this._infographic&&c.get(this._infographic.domNode,"height")},collapseContent:function(){this._infographic&&this._infographic.collapseContent()},getVisualState:function(){return{type:this._currentInfographicJson.type,selectedFeatureId:this._infographic&&this._infographic.getSelectedFeatureID(),filterRanges:this._filterRanges?r.clone(this._filterRanges):null}},setVisualState:function(a){if(a){var b=this;return h(this._initPromise,function(){if(b._infographic)return h(a.filterRanges&&
b.setFilterRanges(a.filterRanges),function(){return a.selectedFeatureId&&b._infographic.setSelectedFeatureID(a.selectedFeatureId)})})}},isMouseOver:function(){return A.isMouseOver(this.domNode)||this._infographic&&this._infographic._widget&&this._infographic._widget.select&&this._infographic._widget.select.isMouseOver()},_showError:function(a){D.emulateErrors.contentErrors&&(a=!0);k[a?"show":"hide"](this.errorDiv);k[a?"hide":"show"](this.infographicDiv)},_adjustErrorMessage:function(){c.set(this.errorDiv,
"paddingTop",c.get(this.domNode,"height")/2-20+"px")},toJson:function(){return r.clone(this._currentInfographicJson)},onContentLoadingStart:function(){},onContentLoadingEnd:function(){},onContentUpdated:function(){},onShowWaiting:function(a){},_isCreated:function(){return this.domNode&&this._infographic&&this._infographic.domNode},destroy:function(){this._stdPolygonsController&&this._stdPolygonsController.setShownFeatureAttributes([]);this._destroyCurrentInfographic();this.inherited(arguments)}});
l.Infographic=u;return l});