// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.33/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/ReportPlayer/core/charts/utils/builder/round/_RoundChartSeriesCalculator","../../ThemeCalculator ../../ChartTypes ../../ChartSorting ../../ChartLineStyles ../../../../supportClasses/conditionalStyling/ConditionalStyleUtil ../../../../sections/dynamicSettings/supportClasses/FilterUtil ../utils/ChartDataUtil ../utils/TooltipInfoBuilder esri/dijit/geoenrichment/utils/ColorUtil".split(" "),function(A,t,u,x,y,B,v,C,z){var D={calcLineStyle:function(a,f){return{color:z.getColorWithAlpha(f.outlineColor||
a,f.outlineOpacity),width:f.outlineThickness||0,style:x.toGFXValue(f.outlineStyle||x.SOLID)}}};return{calcSeries:function(a){var f=a.seriesItems,l=a.chartType,k=a.themeSettings,m=a.visualProperties,n=a.sorting;if(!f.length)return[];var p=f[0],q=[],r={name:"data",data:[]};q.push(r);if(!p.points.length)return q;var g=this._calcStats(a);p.points.forEach(function(c,d){if(!c.hidden){var e=g.values[d],h=e.value,n=h||0,b;t.isConditionalStylingSupported(l)&&m.conditionalStyling&&(b=(b=y.getConditionalStyle(e.isBenchmarked?
e.ownValue:n,m.conditionalStyling))&&b.backgroundColor);b=b||A.calcColorForPoint({point:c,seriesItem:p,pointIndex:d,seriesIndex:0,numSeries:f.length,chartType:l,themeSettings:k});var w=D.calcLineStyle(b,m);b=1>m.fillOpacity?z.getColorWithAlpha(b,m.fillOpacity):b;d={originalValue:h,x:1,y:t.supportsNegativeValues(l)?n:Math.max(1E-4,n),isUnavailableData:isNaN(h),valueProp:"y",unsortedIndex:d,name:c.label,point:c,fill:b,valuesSumsInSeries:g.absValuesSum,seriesIndex:0,stroke:{color:w.color,width:w.width,
style:w.style},isBenchmarked:e.isBenchmarked,unbenchmarkedValue:e.ownValue,unbenchmarkedValuesSumsInSeries:g.unbenchmarkedAbsValuesSum};c=C.getTooltipInfo({yValue:h,pointLabel:c.label,seriesLabel:null,minInSeriesValue:g.minValue,maxInSeriesValue:g.maxValue,sumInSeriesValue:g.valuesSum,absSumInSeriesValue:g.absValuesSum,avgInSeriesValue:g.avgValue,visualProperties:m,chartType:l,conditionalStyling:m.conditionalStyling,fieldInfo:c.fieldInfo,decimals:c.value&&c.value.decimals,fill:d.fill,stroke:0<d.stroke.width?
d.stroke.color:void 0,isBenchmarked:e.isBenchmarked,unbenchmarkedValue:e.ownValue,chartContainer:a.chartContainer,viewModel:a.viewModel,theme:a.theme,themeSettings:k,dataDrillingPanelInfo:a.dataDrillingPanelInfo,pointName:c.label,seriesName:p.label,areaName:null,featureIndex:a.currentFeatureIndex,isComparisonPoint:!1,comparisonFeatureAttribute:null});d.tooltip=c;r.data.push(d)}});t.isSortingSupported(l)&&n&&n!==u.NONE&&r.data.sort(function(a,d){return(a.y-d.y)*(n===u.DESC?-1:1)});return q},_calcStats:function(a){var f=
a.chartType,l=a.viewModel,k=a.visualProperties,m=a.currentFeatureIndex,n=[],p=0,q=0,r=0,g=1E6,c=-1E6;a=a.seriesItems[0].points;var d,e=k.filter&&k.filter.ranges&&B.getRangeStatistics(k.filter.ranges),h=t.isConditionalStylingSupported(f)&&k.conditionalStyling&&y.getStatistics(k.conditionalStyling);if(e||h)d=v.getChartData({filterRangesStats:e,conditionalStats:h,numPoints:a.length,visualProperties:k});var u=0;a.forEach(function(a,e){var b=function(){if(a.hidden)return{value:void 0};var c=v.getPointValue({point:a,
index:e,seriesIndex:0,maxValue:!1,chartType:f,visualProperties:k,viewModel:l,currentFeatureIndex:m,chartData:d}),b=l.getBenchmarkController&&l.getBenchmarkController();return t.isBenchmarkSupported(f)&&b&&0<=b.getAreaIndex()&&b.getAreaIndex()!==m?(b=v.getPointValue({point:a,index:e,seriesIndex:0,maxValue:!1,chartType:f,visualProperties:k,viewModel:l,currentFeatureIndex:b.getAreaIndex(),chartData:d}),{value:c-b,isBenchmarked:!0,ownValue:c}):{value:c}}();n[e]=b;var h=b.value||0;a.hidden||(u++,p+=h,
q+=Math.abs(h),r+=Math.abs(b.ownValue||0),g=Math.min(g,h),c=Math.max(c,h))});return{values:n,valuesSum:p,absValuesSum:q,unbenchmarkedAbsValuesSum:r,minValue:g,maxValue:c,avgValue:p/u}}}});