// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.33/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/ReportPlayer/dataProvider/supportClasses/tasks/EnrichAreasTask","dojo/_base/declare dojo/_base/lang esri/dijit/geoenrichment/when esri/dijit/geoenrichment/promise/all esri/kernel esri/SpatialReference esri/tasks/FeatureSet esri/geometry/Point ../GEUtil ../areas/AnalysisAreaUtil ../attachments/AttributesUtil ../../../core/supportClasses/map/Projector ../../../countryConfig esri/dijit/geoenrichment/utils/CoordinateUtil".split(" "),function(v,h,l,m,q,n,w,r,x,t,y,z,A,
p){function u(a){return(a=a&&q.id.findCredential(a)||q.id.credentials[0])&&a.token}return v(null,{enrichAreas:function(a){var b={};return l(this._analysisAreasToStudyAreas(a.analysisAreas,a.countryID,a.comparisonLevels),function(c){b.studyAreas=c;a.report?b.analysisVariables=[{itemid:a.report.reportID,url:a.report.portalUrl,token:u(a.portalUrl),outFields:["*"]}]:a.fields&&(b.analysisVariables=a.fields);return this._doRunTask(b,a,"enrich")}.bind(this)).then(this._handleFeatureSetsRequest.bind(this))},
createReport:function(a){var b={f:"bin",format:"xml",reportfields:{}};b.report={itemid:a.report.reportID,url:a.report.portalUrl,token:u(a.portalUrl)};return l(this._analysisAreasToStudyAreas(a.analysisAreas,a.countryID,null,a.getAttributes),function(c){b.studyAreas=c;return this._doRunTask(b,a,"createReport")}.bind(this))},_analysisAreasToStudyAreas:function(a,b,c,g){var f=this;c=c&&c.map(function(a){return{layer:a}});return m(a.map(function(a,e){var d;a.geographies&&a.geographies.length?(d=f._studyAreaFromGeographies(a.geographies,
b,!0),a.feature&&a.feature.attributes&&(d.attributes=h.mixin({},d.attributes,a.feature.attributes))):d={attributes:h.mixin({},a.feature.attributes),geometry:a.feature.geometry.toJson()};c&&(d.comparisonLevels=c);return m([f._getStorePointForArea(a),g&&g(a)]).then(function(a){var b=a[0];a=a[1];d.attributes=d.attributes||{};b&&(d.attributes.STORE_LAT=d.attributes.STORE_LAT||b.STORE_LAT,d.attributes.STORE_LONG=d.attributes.STORE_LONG||b.STORE_LONG);d.attributes.STORE_ID=e+"";a&&a.forEach(function(a){d.attributes[a.name]=
y.formatAttributeValueForStudyArea(a)});return d})}))},_getStorePointForArea:function(a){if(a=a.location&&a.location.geometry||a.buffer&&a.buffer.point){a=a instanceof r?a:new r(a);var b=t.geometryToLatLong(a);return b?b:l(z.projectGeometries(a,new n(p.WGS_84_WKID)),function(a){return t.geometryToLatLong(a)})}},createFeatureForGeographies:function(a,b){return this._createFeaturesForGeographies(a,b,!0).then(function(a){return a[0]})},createFeaturesForGeographies:function(a,b){return this._createFeaturesForGeographies(a,
b,!1)},_createFeaturesForGeographies:function(a,b,c){a={returnGeometry:!0,outSR:b.outSR||new n(p.WEB_MERCATOR_WKID),studyAreas:c?[this._studyAreaFromGeographies(a,b.countryID,!0,b.generalizationLevel)]:a.map(function(a){return this._studyAreaFromGeographies([a],b.countryID,!1,b.generalizationLevel)},this),dataCollections:["GlobalIntersect"]};return this._doRunTask(a,b,"enrich").then(this._handleFeatureSetsRequest.bind(this))},_studyAreaFromGeographies:function(a,b,c,g){var f={sourceCountry:b,layer:null,
ids:null},k=null,e=[],d;a.forEach(function(a){if(!a||!a.id)throw Error("Wrong geography.");var b=a.levelId;if(b)if(!k)k=b;else if(c&&k!==b)throw Error("Geographies have different level IDs.");e.push(a.id);a.sourceCountry&&(f.sourceCountry=a.sourceCountry);a.hierarchy&&(f.hierarchy=a.hierarchy);a.attributes&&(d=h.mixin(d||{},a.attributes))});f.layer=k;f.ids=c?[e.join(",")]:e;f.attributes=d;f.generalizationlevel=g;return f},createFeaturesForBuffer:function(a,b){b=b||{};var c={bufferUnits:a.units,bufferRadii:a.radii||
[a.radius],areaType:a.areaType||"RingBuffer"};"NetworkServiceArea"===c.areaType&&(c.travelMode=a.travelMode,c.networkOptions=a.networkOptions);a=a.point||a.polyline;c={returnGeometry:!0,outSR:b.outSR||a.spatialReference||new n(p.WEB_MERCATOR_WKID),dataCollections:["GlobalIntersect"],studyAreasOptions:c,studyAreas:[{geometry:a.toJson?a.toJson():a}]};return this._doRunTask(c,b,"enrich").then(this._handleFeatureSetsRequest.bind(this))},createFeaturesForBuffers:function(a,b){var c={},g=[];a.forEach(function(a){var b;
b=a.point||a.polyline;b=JSON.stringify(b.toJson?b.toJson():b)+";"+a.units+";"+a.areaType+";"+a.travelMode+";"+JSON.stringify(a.networkOptions);var e=c[b];e||(e=c[b]=h.clone(a),delete e.radius,e.radii=[],g.push(e));a.radii?e.radii=e.radii.concat(a.radii):e.radii.push(a.radius)});return m(g.map(function(a){return this.createFeaturesForBuffer(a,b)},this)).then(function(a){var b=[];a.forEach(function(a){b=b.concat(a)});return b})},_doRunTask:function(a,b,c){a=h.mixin({useData:{sourceCountry:b.countryID,
hierarchy:b.hierarchy||A.getHierarchyID()},forStorage:!1},a);return x[c](a)},_handleFeatureSetsRequest:function(a){return(new w(a[0])).features}})});