// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.33/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/ReportPlayer/core/supportClasses/templateJsonUtils/fieldInfo/_FieldInfoPreviewRenderer","dojo/string ./utils ./FieldInfoPreviewSampleUtil ./FieldInfoPreviewAttributeUtil ../../conditionalStyling/ConditionalStyleUtil esri/dijit/geoenrichment/utils/ObjectUtil esri/dijit/geoenrichment/utils/DateUtil ../../../grid/coreUtils/sorting/GridSortUtil ../../../grid/coreUtils/GridDataUtil esri/dijit/geoenrichment/ReportPlayer/countryConfig ../../../sections/dynamicSettings/supportClasses/FilterUtil dojo/i18n!esri/nls/jsapi ../../../../_devConfig".split(" "),
function(l,r,t,u,m,v,w,x,y,g,n,h,z){h=h.geoenrichment.dijit.ReportPlayer.FieldInfoPreview;var A={percent:[10,15,20,25,33,46,72,90,95],percentSmall:[2,3,4,5,6,7],index:[80,99,105,111,113,118,121,130],number:[1150,2013,5006,10135,20456,36813],numberSep:[1150,2013,5006,10135,20456,36813],numberSmall:[10,5,3,7,15]},B=/^MEDAGE|^AVGHHSZ|^UNEMPRT|ECYHSZAVG|ECYPTAMED/,p={percent:{MP19013a_B:72,MP19014a_B:70,EMP_TO_POP:25,NOHS:10,HSG:20,SC:30,BGPD:40,X9074_A:326},percentSmall:{UNEMPRT_CY:5},index:{},number:{MEDHINC_CY:55650,
TOTPOP_CY:20456,TOTHH_CY:8546,MEDDI_CY:38290,S01_BUS:11256,S01_EMP:60382,PCI_CY:30382,MEDNW_CY:88548,MEDVAL_CY:352430,X3004_A:5682,ACSMEDCRNT:1227,X5001_A:1762,X1003_A:4073,X4100_A:543,X8001_A:4538,X1130_A:3465,X7001_A:1568,X9008_A:246,X9073_A:158,X9045_A:42,POPGRWCYCY:1.05,POPGRWCYFY:1.12,ECYPTAPOP:20456,ECYHNIMED:55650},numberSep:{MEDHINC_CY:55650,TOTPOP_CY:20456,TOTHH_CY:8546,MEDDI_CY:38290,S01_BUS:11256,S01_EMP:60382,PCI_CY:30382,MEDNW_CY:88548,MEDVAL_CY:352430,X3004_A:5682,ACSMEDCRNT:1227,X5001_A:1762,
X1003_A:4073,X4100_A:543,X8001_A:4538,X1130_A:3465,X7001_A:1568,X9008_A:246,X9073_A:158,X9045_A:42,ECYPTAPOP:20456,ECYHNIMED:55650},numberSmall:{AVGHHSZ_CY:2,MEDAGE_CY:36,ECYHSZAVG:2,ECYPTAMED:36},string:{TSEGNAME:"Bright Young Professionals",TLIFECODE:"L8",TLIFENAME:"Middle Ground",TSEGCODE:"8A",CONAME:"Coffee",NAICS:"1234",SIC:"5678",ADDR:"380 New York St, Redlands, CA",STATE:"CA",STATE_NAME:"California",ZIP:"92373",ZIP4:"92373",CITY:"Redlands",STREET:"New York st.",DIRECTION:"SW",FRNCOD:"24"}},
C={"Employee/ Population Ratio":"EMP_TO_POP","No High School Diploma":"NOHS","High School Graduate":"HSG","Some College":"SC","Bachelors/Grad/Prof Degree":"BGPD","Tickets to Movies/Museums/Parks: Average":"X9074_A"},q={};return{getValuePreview:function(b,a){return y.isVariableLikeFieldCell(b)?this._getVariableOrScriptPreview(b,a):this._getNonVariablePreview(b,a)},_getVariableOrScriptPreview:function(b,a){function c(b){return{formattedValue:b,value:b,formatFunction:null,isUnavailableData:!1}}function d(a,
c){function d(a){a=0<b.decimals?a+.5432123456789:Math.round(a);return v.formatNumber(a,{places:b.decimals||0,noSeparator:!b.useThousandsSeparator,preserveTrailingZeroes:!0})}c=a;c=0<b.decimals?Number((c+.5432123456789).toFixed(b.decimals)):Math.round(c);return{formattedValue:d(a),value:c,formatFunction:function(a){return d(a)},isUnavailableData:!1}}var e=this._getSampleCacheType(b);if(z.preview.bigValues&&("number"===e||"numberSep"===e))return d(1E12,e);if(a=this._getValueFromPreviewFunction(b,a))return d(a.value,
a.propName);a=t.findNonEmptySample(b);if("string"===typeof a)return c(a);if("number"===typeof a)return d(a,e);var k=b.type||b.isSiteAttribute&&b.attribute.type;a=b.isSiteAttribute&&u.getAttributePreviewValue(b.attribute);if("esriFieldTypeDate"===k)return e=new Date,a&&e.setTime(a),c(w.formatDateShort(e));if("esriFieldTypeString"===k)return c(p.string[b.isDataLayerAttribute?b.attribute.name:b.variableID]||a||h.sampleTextValue);if("number"===typeof a)return d(a,e);a=q[e]=q[e]||{};var k=b.name+";"+b.decimals,
f=a[k];if(!f){var f=p[e],g;g=b.variableID?b.variableID:b.script&&C[b.script.alias];f=f[g];f||(f=A[e],f=f[Math.round((f.length-1)*Math.random())]);f=a[k]=f}return d(f,e)},_getSampleCacheType:function(b){var a=b.statefulName?"p"===b.statefulName.charAt(0):b.showPercent,c=b.statefulName&&"i"===b.statefulName.charAt(0),d=b.hasVariable&&B.test(b.variableID);return a?d?"percentSmall":"percent":c?"index":d?"numberSmall":b.useThousandsSeparator?"numberSep":"number"},_getValueFromPreviewFunction:function(b,
a){if(a=a.getPreviewValueFunction&&a.getPreviewValueFunction({fieldInfo:b})){var c=this._getSampleCacheType(b),c=0===c.indexOf("percent")?"percent":"number";a=a.fields&&a.fields[b.name]||a;return{value:a[c]||a.value,propName:c}}return null},_getNonVariablePreview:function(b,a){var c=void 0;if(a.getPreviewValueFunction){var d=a.getPreviewValueFunction({fieldInfo:b});d&&(d=d.fields&&d.fields[b.name]||d,c=d.formattedValue||d.value)}void 0===c&&("headers.AREA_DESC"===b.name&&-1<a.currentFeatureIndex?
(b=1+2*a.currentFeatureIndex,c=1===b?g.getSingleUnits()?"1 "+g.getSingleUnits():l.substitute(h.fieldPreviewAreaDescWithRadiusSingular,{radius:b}):g.getPluralUnits()?b+" "+g.getPluralUnits():l.substitute(h.fieldPreviewAreaDescWithRadiusPlural,{radius:b})):c=r.fields.getPreview(b.name,a.isGraphicReport,a.isMultiFeature)||b.alias);return{formattedValue:c,value:c,formatFunction:null,isUnavailableData:!1}},getConditionalStylePreview:function(b,a){if(b.triggerJson&&void 0!==a.rowIndex){var c=this._getValueFromPreviewFunction(b,
a);if(c)return{style:m.getConditionalStyle(c.value,b.triggerJson),value:c.value};if(a=b.triggerJson.cases[a.rowIndex%b.triggerJson.cases.length]){b=m.styleFromSetters(a.setters);var d;1===a.compareInfos.length?(d=Number(a.compareInfos[0].value),a=a.compareInfos[0].operator,"\x3e"===a?d++:"\x3c"===a&&d--):2===a.compareInfos.length&&(d=(Number(a.compareInfos[1].value)+Number(a.compareInfos[0].value))/2);return{style:b,value:d}}}return null},getRangeFilterPreview:function(b){if(b.presetFilter&&n.isRangeType(b.presetFilter.method)){if(b.presetFilter.columnIndex!==
b.columnIndex)return null;var a=n.getRangeStatistics(b.presetFilter.ranges),c=a.min,a=a.max;isFinite(c)||isFinite(a)?isFinite(a)?isFinite(c)||(c=0===a?0:0<a?a/2:2*a):a=0!==c?Math.abs(2*c):100:(c=0,a=100);var d=(a-c)/b.numRows;return{value:c+d*b.rowIndex,_min:c,_max:a,_step:d}}},getSortingPreview:function(b){var a=b.presetFilter&&this.getRangeFilterPreview(b);if(!b.presetSorting.order||b.presetSorting.field!==b.columnField)return a;var c=100,d=0,e=d+b.numRows*c;a&&(d=a._min,e=a._max,c=a._step);return{value:b.presetSorting.order===
x.ORDER_ASC?d+b.rowIndex*c:e-b.rowIndex*c}}}});