// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.33/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/ReportPlayer/core/supportClasses/templateJsonUtils/fieldInfo/FieldInfoRenderer",["../../../grid/coreUtils/GridDataUtil","./utils","./_FieldInfoPreviewRenderer","./_FieldInfoDataRenderer","dojo/i18n!esri/nls/jsapi"],function(p,h,k,l,d){function f(a,b){b=b||15;return!a||a.length<=b?a:a.substr(0,b-3)+"..."}var q=d.geoenrichment.dijit.ReportPlayer.ReportPlayer.missingVariable,r=d.geoenrichment.dijit.ReportPlayer.ReportPlayer.unsupportedContent;d=d.geoenrichment.dijit.ReportPlayer.VariableStates;
var e={},g={renderPreview:function(a,b){return b.fieldData?l.getValueFromFieldData(a,b):k.getValuePreview(a,b)},tryProvideConditionalStylePreview:function(a,b,c){a.isUnavailableData||a.conditionalStyle||c.fieldData||!(b=k.getConditionalStylePreview(b,c))||(a.conditionalStyle=c.previewConditionalStyle?b:!1)},tryProvideRangeFilterPreview:function(a,b){a.isUnavailableData||a.modifiedValue||b.fieldData||!b.presetFilter||(a.modifiedValue=k.getRangeFilterPreview(b))},tryProvideSortingPreview:function(a,
b){a.isUnavailableData||b.fieldData||!b.presetSorting||(a.modifiedValue=k.getSortingPreview(b))}},m={buildVariableLabel:function(a){var b;if(a.isWebMap)b=f(a.webMapFieldName)+"(WebMap)";else if(a.isSiteAttribute)b=f(a.alias)+"(SiteAttribute)";else if(a.isDataLayerAttribute)b=f(a.alias)+"(NearbyLocations)";else if(a.isCustomDataCollection)b=f(a.alias)+"(CustomData)";else a:{b=a.variableID;switch(a.statefulName&&a.statefulName.charAt(0).toLowerCase()){case "p":a=d.statePercent_short;break;case "a":a=
d.stateAverage_short;break;case "i":a=d.stateIndex_short;break;case "r":a=d.stateReliability_short;break;default:break a}b=b+" ("+a+")"}return"["+b+"]"},_SCRIPT_ALIAS_RE:/\s/g,buildScriptLabel:function(a){a=a.alias?a.alias.replace(m._SCRIPT_ALIAS_RE,""):h.name.renderScriptName(a.name);return"["+f(a,40)+"]"}},n={renderRichTextFieldInfoInTableCell:function(a,b){return h.richText.createRichTextFromFieldInfo(a,function(a){var c=e.renderFieldInfoInTableCell(a,b),d=c.formattedValue;b&&b.isBenchmarked&&
(a=b.getBenchmarkInfo(c.value,a))&&a.formattedValue&&(d+=" ("+(a.isGreater?"+":"-")+a.formattedValue+")");return d})}};e.renderFieldInfoInTableCell=function(a,b){b=b||{};var c={formattedValue:null,value:null,formatFunction:null,isUnavailableData:!1,conditionalStyle:null,modifiedValue:null};if(a.isRichText)return c.formattedValue=n.renderRichTextFieldInfoInTableCell(a,b),c;if(a.isMissing)return c.formattedValue=q,c.isUnavailableData=!0,c;if(a.isUnsupportedContent)return c.formattedValue=r,c.isUnavailableData=
!0,c;if(b.previewValues){if(c=g.renderPreview(a,b),c.isUnavailableData)return c}else c.formattedValue=a.hasVariable?m.buildVariableLabel(a):a.script?m.buildScriptLabel(a.script):"["+a.alias+"]";if(p.isVariableLikeFieldCell(a)&&(g.tryProvideConditionalStylePreview(c,a,b),g.tryProvideRangeFilterPreview(c,b),g.tryProvideSortingPreview(c,b),c.formattedValue=h.format.providePercentCurrencySymbols(c.formattedValue,a,{placePercentCurrencyInFront:!b.previewValues}),c.formatFunction)){var d=c.formatFunction;
c.formatFunction=function(c){return h.format.providePercentCurrencySymbols(d(c),a,{placePercentCurrencyInFront:!b.previewValues})};c.conditionalStyle&&void 0===c.conditionalStyle.formattedValue&&(c.conditionalStyle.formattedValue=c.formatFunction(c.conditionalStyle.value));c.modifiedValue&&void 0===c.modifiedValue.formattedValue&&(c.modifiedValue.formattedValue=c.formatFunction(c.modifiedValue.value))}return c};e.getConditionalStylePreview=function(a,b){var c={};g.tryProvideConditionalStylePreview(c,
a,{rowIndex:b,previewConditionalStyle:!0});return c.conditionalStyle};e.renderRichTextFieldInfoInTableCell=n.renderRichTextFieldInfoInTableCell;e.getValueFromFieldData=l.getValueFromFieldData;e.getFieldDataValue=l.getFieldDataValue;return e});