// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.33/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/ReportPlayer/core/conversion/portalToEditorUtils/parsers/infographic/SimpleInfographicParser","dojo/_base/lang esri/dijit/geoenrichment/utils/JsonXmlConverter ../../../ConversionUtil esri/dijit/geoenrichment/ReportPlayer/core/infographics/utils/InfographicJsonUtil esri/dijit/geoenrichment/ReportPlayer/core/sections/SectionTypes esri/dijit/geoenrichment/ReportPlayer/core/supportClasses/templateJsonUtils/fieldInfo/FieldInfoBuilder ../../../../supportClasses/tableJson/TableJsonResizeUtil dojo/i18n!esri/nls/jsapi".split(" "),
function(w,t,k,x,f,y,u,l){l=l.geoenrichment.dijit.ReportPlayer.ReportPlayer;return{portalToEditor:function(c,e){function m(a){return e.parsers.getParser("section").parseTable(a,e)}var v=c.tags.slice(),d,n=[],p,q;(function(){1.1<=e.revisionVersion?v.forEach(function(a){switch(a.attributes.type){case f.INFOGRAPHIC_HEADER:d=a.tags[0];break;case f.INFOGRAPHIC_VARIABLE:n.push(a);break;case f.INFOGRAPHIC_BACKGROUND:p=a.tags;break;case f.INFOGRAPHIC_FOREGROUND:q=a.tags}}):n=v.filter(function(a){return"infographicHeader"===
a.attributes.type?(d=a,!1):!0})})();var r={type:c.attributes.type,isDefault:c.attributes.isDefault,style:{width:k.ptToPx(c.attributes.width),height:k.ptToPx(c.attributes.height),padding:c.attributes.padding?k.ptToPx(c.attributes.padding):void 0,backgroundColor:c.attributes.backgroundColor},preserveTextSize:c.attributes.preserveTextSizeWhenResizing,background:p?p.map(m):null,header:d&&m(d),variableTables:null,foreground:q?q.map(m):null,dataDrilling:null};r.variableTables=n.map(function(a){function c(b){if(b&&
b.isMissing){b.alias=g.description&&g.description.text;if(!b.alias&&e.variableProvider.isPlayerOnly){var a=e.variableProvider.toCalculator(b.templateName);b.alias=a&&a.variable.alias}b.alias=b.alias?b.alias+" ("+l.missingVariable+")":l.missingVariable}}var g={style:k.ptToPxObj({left:a.attributes.left,top:a.attributes.top,width:a.attributes.width,height:a.attributes.height})},f;a.tags.forEach(function(b){if("dataDrillingPanels"===b.name)f=b;else{var a=b.attributes.type,c=m(b),d=c.data.data[0],h=c.data.columns[0].field;
b={isContrastColor:b.attributes.isContrastColor,isHighlighted:b.attributes.isHighlighted,style:w.mixin({width:c.data.columns[0].style.width,height:d.style.height,left:c.style.left,top:c.style.top},d.style.fields[h])};delete b.style.overrideStyle;"shape"===a&&(b.shapeJson=d.fieldInfos[h].shapeJson,1.6>e.revisionVersion&&(b.style.width-=3,b.style.height-=3,b.shapeJson.style.width-=3,b.shapeJson.style.height-=3));"image"===a?b.imageJson=d.fieldInfos[h].imageJson:"variable"===a?b.fieldInfo=d.fieldInfos[h]||
y.createFieldInfoFromMissingVariable():"description"===a&&(b.text=d[h],b.fieldInfo=d.fieldInfos[h]);g[a]=b}});c(g.variable.fieldInfo);g.description&&c(g.description.fieldInfo);if(f&&(a=(a=t.queryTopJson(f,"dataDrillingPanel")[0])&&t.queryTopJson(a,"section")[0])){a=e.parsers.getParser("section").parseSection(a,e);if(1.9>e.revisionVersion&&1===a.stack.length&&"table"===a.stack[0].id){var d=a.stack[0];u.resizeTableJsonToFitWidth(d,700);u.resizeTableJsonToFitHeight(d,600)}x.setDataDrilling(r,g.variable.fieldInfo.templateName,
{sectionJson:a})}return g});return r}}});