// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.33/esri/copyright.txt for details.
//>>built
require({cache:{"url:esri/dijit/RasterFunctionEditor/templates/RFxMultidimensionalDefinitionEditor.html":'\x3cdiv class\x3d"esri-rfx-multidimensionalDefinition-editor"\x3e\r\n  \x3cdiv class\x3d"esri-rfx-raster-variable-grid"\x3e\r\n    \x3cdiv data-dojo-attach-point\x3d"_rasterVariableDiv"\x3e\x3c/div\x3e\r\n  \x3c/div\x3e\r\n  \x3cdiv data-dojo-attach-point\x3d"_dimensionDefinitionDivContainer"\x3e\x3c/div\x3e\r\n  \x3cdiv data-dojo-attach-point\x3d"_byValuesGridDivContainer" class\x3d"esri-rfx-mdimdef-byValues-grid hidden"\x3e\x3c/div\x3e\r\n  \x3cdiv data-dojo-attach-point\x3d"_byRangesGridDivContainer" class\x3d"esri-rfx-mdimdef-byRanges-grid hidden"\x3e\x3c/div\x3e\r\n  \x3cdiv data-dojo-attach-point\x3d"_byIterationDivContainer" class\x3d"esri-rfx-mdimdef-byIteration-form hidden"\x3e\r\n    \x3cdiv data-dojo-attach-point\x3d"_byIterationFormDiv"\x3e\x3c/div\x3e\r\n  \x3c/div\x3e\r\n\x3c/div\x3e\r\n'}});
define("esri/dijit/RasterFunctionEditor/RFxMultidimensionalDefinitionEditor","dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/i18n!../../nls/jsapi dojo/text!./templates/RFxMultidimensionalDefinitionEditor.html dojo/has dojo/Evented ../../kernel dijit/_WidgetBase dijit/_TemplatedMixin dijit/_WidgetsInTemplateMixin dijit/_OnDijitClickMixin ./EditableGridMixin ./RFxGridBase dijit/form/Select dijit/form/NumberTextBox ./RFxRasterVariableGrid".split(" "),function(k,h,B,m,p,q,C,r,t,u,v,w,x,n,y,
z,A){k=k("RFxMultidimensionalDefinitionEditor",[t,u,v,w,x],{declaredClass:"esri.dijit.RasterFunctionEditor.RFxMultidimensionalDefinitionEditor",templateString:p,widgetsInTemplate:!0,rasterVariableGrid:null,byValuesGrid:null,byRangesGrid:null,_dimensionDefinitionSelect:null,_iterationFormDimensionSelect:null,_iterationFormStartOfFirstIterationSelect:null,_iterationFormEndOfFirstIterationSelect:null,_iterationFormTimeUnitsContainer:null,_iterationFormStepTextbox:null,_iterationFormTimeUnits:null,selectedVariables:[],
definitionType:"",widgetState:{},dimensionDefinition:{ALL:"ALL",BY_VALUES:"BY_VALUES",BY_RANGES:"BY_RANGES",BY_ITERATION:"BY_ITERATION"},dimensionDefinitionLabels:{ALL:"mdimDefTypeAll",BY_VALUES:"mdimDefTypeByValues",BY_RANGES:"mdimDefTypeByRanges",BY_ITERATION:"mdimDefTypeByIteration"},esriTimeUnitLabels:{HOURS:"esriTimeUnitsHours",DAYS:"esriTimeUnitsDays",WEEKS:"esriTimeUnitsWeeks",MONTHS:"esriTimeUnitsMonths",YEARS:"esriTimeUnitsYears"},stdTimeDimension:"StdTime",defaultWidgetDataByValuesGrid:[{Dimension:[],
Value:[]}],defaultWidgetDataByIterationForm:{dimension:[],startValue:[],endValue:[],stepValue:3,units:"HOURS"},defaultWidgetDataByRangedGrid:[{Dimension:[],MinValue:[],MaxValue:[]}],constructor:function(){this.inherited(arguments);this.widgetState={};this._i18n=m.rasterFunctions.enumLabels;this._i18n=h.mixin(this._i18n,m.rasterFunctions.rfxArgs)},postCreate:function(){this.inherited(arguments);this._generateLabelNode(this._i18n.mdimDefinition,this._dimensionDefinitionDivContainer);var a=this._generateDropdownOptions(this.dimensionDefinitionLabels);
this._dimensionDefinitionSelect=this._generateDropdownNode(a,this._dimensionDefinitionDivContainer);this._generateLabelNode(this._i18n.predictDimensionValues,this._byValuesGridDivContainer);this._generateLabelNode(this._i18n.rangesName,this._byRangesGridDivContainer);this._generateLabelNode(this._i18n.dimensionName,this._byIterationFormDiv);this._iterationFormDimensionSelect=this._generateDropdownNode([],this._byIterationFormDiv);this._addBreakLine(this._byIterationFormDiv);this._generateLabelNode(this._i18n.iterationStart,
this._byIterationFormDiv);this._iterationFormStartOfFirstIterationSelect=this._generateDropdownNode([],this._byIterationFormDiv);this._addBreakLine(this._byIterationFormDiv);this._generateLabelNode(this._i18n.iterationEnd,this._byIterationFormDiv);this._iterationFormEndOfFirstIterationSelect=this._generateDropdownNode([],this._byIterationFormDiv);this._addBreakLine(this._byIterationFormDiv);this._generateLabelNode(this._i18n.stepName,this._byIterationFormDiv);this._addBreakLine(this._byIterationFormDiv);
this._iterationFormStepTextbox=this._generateTextBoxNode(this._byIterationFormDiv);this._iterationFormTimeUnitsContainer=document.createElement("div");this._iterationFormTimeUnitsContainer.classList.add("hidden");this._byIterationFormDiv.appendChild(this._iterationFormTimeUnitsContainer);this._generateLabelNode(this._i18n.dimensionUnit,this._iterationFormTimeUnitsContainer);this._addBreakLine(this._iterationFormTimeUnitsContainer);a=this._generateDropdownOptions(this.esriTimeUnitLabels);this._iterationFormTimeUnits=
this._generateDropdownNode(a,this._iterationFormTimeUnitsContainer);if(this.layerArg&&this.layerArg.input){var a=this.layerArg.input,b;this.set("labelAttr","alias");0<a.declaredClass.indexOf("RFxRasterInput")&&a.value&&(b=a.getSelectedLayer(a.get("value").name),b.on("load",h.hitch(this,function(){b.getMultidimensionalInfo().then(h.hitch(this,function(a){b.multidimensionalInfo=a;this.defaultValue&&"string"===typeof this.defaultValue&&(this.defaultValue=JSON.parse(this.defaultValue));this.selectedVariables=
this.defaultValue&&this.defaultValue.variables;this.defaultValue&&this.defaultValue.definitionType?(this.definitionType=this.defaultValue&&this.defaultValue.definitionType,this._dimensionDefinitionSelect.set("value",this.definitionType),this.widgetState[this.definitionType]=this.defaultValue):this.definitionType=this._dimensionDefinitionSelect.value}))})));this._dimensionDefinitionSelect.on("change",this._handleDimensionDefinitionSelectChange.bind(this));this.rasterVariableGrid=new A({layerArg:this.layerArg,
defaultValue:this.defaultValue&&this.defaultValue.variables},this._rasterVariableDiv);this.rasterVariableGrid.startup();this.rasterVariableGrid.on("variable-grid-update",function(a){this._handleRasterVariableGridChange(a)}.bind(this))}},onRasterChange:function(){if(this.layerArg&&this.layerArg.input){var a=this.layerArg.input,b;0<a.declaredClass.indexOf("RFxRasterInput")&&a.value&&(b=a.getSelectedLayer(a.get("value").name),b.on("load",h.hitch(this,function(){b.getMultidimensionalInfo().then(h.hitch(this,
function(a){b.multidimensionalInfo=a;this.rasterVariableGrid.onRasterChange();this.widgetState={}}))})))}},_handleDimensionDefinitionSelectChange:function(a){this.definitionType=a;this.defaultValue=this.widgetState[a];switch(this.definitionType){case this.dimensionDefinition.BY_VALUES:this._createByValuesGrid();this._byValuesGridDivContainer.classList.remove("hidden");this._byRangesGridDivContainer.classList.add("hidden");this._byIterationDivContainer.classList.add("hidden");break;case this.dimensionDefinition.BY_RANGES:this._createByRangesGrid();
this._byValuesGridDivContainer.classList.add("hidden");this._byRangesGridDivContainer.classList.remove("hidden");this._byIterationDivContainer.classList.add("hidden");break;case this.dimensionDefinition.BY_ITERATION:this._configureByIterationForm();this._byValuesGridDivContainer.classList.add("hidden");this._byRangesGridDivContainer.classList.add("hidden");this._byIterationDivContainer.classList.remove("hidden");break;default:this._byValuesGridDivContainer.classList.add("hidden"),this._byRangesGridDivContainer.classList.add("hidden"),
this._byIterationDivContainer.classList.add("hidden")}},_handleRasterVariableGridChange:function(a){this.selectedVariables=a.filter(function(a){return a.Select});switch(this.definitionType){case this.dimensionDefinition.BY_VALUES:this._createByValuesGrid();break;case this.dimensionDefinition.BY_RANGES:this._createByRangesGrid();break;case this.dimensionDefinition.BY_ITERATION:this._configureByIterationForm()}},_getDimensionNameOfVariables:function(a,b){var c=[];(a&&a.variables).filter(function(a){return b.some(function(c){return c===
a.name||c.value===a.name})}).forEach(function(a){a.dimensions.forEach(function(a){a={label:a.name+"",value:a.name+"",selected:!1,disabled:!1};this._itemInArray(c,a)||c.push(a)}.bind(this))}.bind(this));return c},_getDimensionValues:function(a,b){var c=[];a.variables.forEach(function(a){a.dimensions.forEach(function(a){a.name===b&&a.values.forEach(function(b){b={label:b+"",value:b+"",selected:!1,disabled:!1};if(a.name===this.stdTimeDimension){var d=(new Date(Number(b.value))).toISOString().slice(0,
22);b.label=d;b.value=d}this._itemInArray(c,b)||c.push(b)}.bind(this))}.bind(this))}.bind(this));return c},_createByValuesGrid:function(){var a=this._getGridSchema(["Dimension","Value"],["dropdown","dropdown","dropdown"],[this._i18n.dimensionName,this._i18n.valueName]),b=this._getGridStoreData(),c=this._getDefaultValueObject(b[0]);this.byValuesGrid&&this.byValuesGrid.destroy();this._byValuesGridDiv=document.createElement("div");this._byValuesGridDivContainer.appendChild(this._byValuesGridDiv);this.byValuesGrid=
new n({schema:a,data:b,hasIdColumn:!0,isExtensible:!0,defaultBlankObject:c},this._byValuesGridDiv);this.byValuesGrid.keepScrollPosition=!0;this.byValuesGrid.on("grid-data-change",this._handleByValuesGridChange.bind(this))},_handleByValuesGridChange:function(){this.defaultValue=this._getWidgetState(!0);var a=this._getGridStoreData();this.byValuesGrid.updateStoreValue(a);this.defaultValue=this._getWidgetState(!0)},_createByRangesGrid:function(){var a=this._getGridSchema(["Dimension","MinValue","MaxValue"],
["dropdown","dropdown","dropdown"],[this._i18n.dimensionName,this._i18n.minValue,this._i18n.maxValue]),b=this._getGridStoreData(),c=this._getDefaultValueObject(b[0]);this.byRangesGrid&&this.byRangesGrid.destroy();this._byRangesGridDiv=document.createElement("div");this._byRangesGridDivContainer.appendChild(this._byRangesGridDiv);this.byRangesGrid=new n({schema:a,data:b,hasIdColumn:!0,isExtensible:!0,defaultBlankObject:c},this._byRangesGridDiv);this.byRangesGrid.keepScrollPosition=!0;this.byRangesGrid.on("grid-data-change",
this._handlByRangesGridChange.bind(this))},_handlByRangesGridChange:function(){this.defaultValue=this._getWidgetState(!0);var a=this._getGridStoreData();this.byRangesGrid.updateStoreValue(a);this.defaultValue=this._getWidgetState(!0)},_configureByIterationForm:function(){var a=this._getGridStoreData();this._iterationFormDimensionSelect.set("options",a.dimension);this._iterationFormStartOfFirstIterationSelect.set("options",a.startValue);this._iterationFormEndOfFirstIterationSelect.set("options",a.endValue);
this._iterationFormStepTextbox.set("value",a.stepValue);this._iterationFormTimeUnits.set("value",a.units);var b=a.dimension.filter(function(a){return a.selected})[0],c=a.startValue.filter(function(a){return a.selected})[0],a=a.endValue.filter(function(a){return a.selected})[0];this._iterationFormDimensionSelect.set("value",b&&b.value);this._iterationFormStartOfFirstIterationSelect.set("value",c&&c.value);this._iterationFormEndOfFirstIterationSelect.set("value",a&&a.value);b&&b.value===this.stdTimeDimension?
this._iterationFormTimeUnitsContainer.classList.remove("hidden"):this._iterationFormTimeUnitsContainer.classList.add("hidden");this._iterationFormDimensionSelect.on("change",this._handleByIterationDimensionChange.bind(this))},_handleByIterationDimensionChange:function(){this.defaultValue=this._getWidgetState(!1);this._configureByIterationForm();this.defaultValue=this._getWidgetState(!1)},_getGridStoreData:function(){var a=this._getGridStoreDataSwitch();if(!a)switch(this.definitionType){case this.dimensionDefinition.BY_VALUES:return this.defaultWidgetDataByValuesGrid;
case this.dimensionDefinition.BY_RANGES:return this.defaultWidgetDataByRangedGrid;case this.dimensionDefinition.BY_ITERATION:return this.defaultWidgetDataByIterationForm}return a},_getGridStoreDataSwitch:function(){if(this.layerArg&&this.layerArg.input){var a=this.layerArg.input,b;if(0<a.declaredClass.indexOf("RFxRasterInput")&&a.value){b=(b=a.get("value"))&&(b.name||b.datasetName.name);var a=a.getSelectedLayer(b),c;switch(this.definitionType){case this.dimensionDefinition.BY_VALUES:c=this._createByValuesDataObject(a);
break;case this.dimensionDefinition.BY_RANGES:c=this._createByRangesDataObject(a);break;case this.dimensionDefinition.BY_ITERATION:c=this._createByIterationFormObject(a)}return c}}},_createByValuesDataObject:function(a){var b=[],c=[],d=[];if(!a||!a.loaded)return this.defaultWidgetDataByValuesGrid;var e=a.multidimensionalInfo;if(!e||!e.variables)return this.defaultWidgetDataByValuesGrid;if(this.defaultValue&&this.defaultValue.dimensions){a=this.defaultValue.dimensions;var f=this.defaultValue&&this.defaultValue.values,
c=this._getDimensionNameOfVariables(e,this.selectedVariables);a.forEach(function(a,g){this._isItemInDropdown(c,a)||(a=c[0].value);d=this._getDimensionValues(e,a);this._makeDropdownSelection(c,a);this._makeDropdownSelection(d,f[g]);b.push(this._cloneData({Dimension:c,Value:d}))},this)}else c=this._getDimensionNameOfVariables(e,this.selectedVariables),d=this._getDimensionValues(e,c[0]?c[0].value:""),b.push({Dimension:c,Value:d});return b},_createByRangesDataObject:function(a){var b=[],c=[],d=[],e=[];
if(!a||!a.loaded)return this.defaultWidgetDataByRangedGrid;var f=a.multidimensionalInfo;if(!f||!f.variables)return this.defaultWidgetDataByRangedGrid;if(this.defaultValue&&this.defaultValue.dimensions){a=this.defaultValue.dimensions;var l=this.defaultValue&&this.defaultValue.minValues,g=this.defaultValue&&this.defaultValue.maxValues,c=this._getDimensionNameOfVariables(f,this.selectedVariables);a.forEach(function(a,h){this._isItemInDropdown(c,a)||(a=c[0].value);d=this._getDimensionValues(f,a);e=this._getDimensionValues(f,
a);this._makeDropdownSelection(c,a);this._makeDropdownSelection(d,l[h]);this._makeDropdownSelection(e,g[h]);b.push(this._cloneData({Dimension:c,MinValue:d,MaxValue:e}))},this)}else c=this._getDimensionNameOfVariables(f,this.selectedVariables),a=c[0]?c[0].value:"",d=this._getDimensionValues(f,a),e=this._getDimensionValues(f,a),b.push({Dimension:c,MinValue:d,MaxValue:e});return b},_createByIterationFormObject:function(a){var b,c,d;if(!a||!a.loaded)return this.defaultWidgetDataByIterationForm;d=a.multidimensionalInfo;
if(!d||!d.variables)return this.defaultWidgetDataByIterationForm;if(this.defaultValue&&this.defaultValue.dimension){var e=this.defaultValue.dimension;a=this.defaultValue.startValue;var f=this.defaultValue.endValue,l=this.defaultValue.stepValue,g=this.defaultValue.units;b=this._getDimensionNameOfVariables(d,this.selectedVariables);c=this._getDimensionValues(d,e);d=this._getDimensionValues(d,e);this._makeDropdownSelection(b,e);this._makeDropdownSelection(c,a);this._makeDropdownSelection(d,f);b={dimension:b,
startValue:c,endValue:d,stepValue:l,units:g}}else b=this._getDimensionNameOfVariables(d,this.selectedVariables),e=b[0]?b[0].value:"",c=this._getDimensionValues(d,e),d=this._getDimensionValues(d,e),a=a.timeInfo&&a.timeInfo.interval,this._makeDropdownSelection(b,e),b={dimension:b,startValue:c,endValue:d,stepValue:a&&a.value,units:a&&a.unit&&a.unit.toUpperCase()};return b},_getGridSchema:function(a,b,c){var d=[];return d=a.map(function(a,d){return{label:c[d],name:a,dataType:b[d]}})},_getDefaultValueObject:function(a){var b=
this._cloneData(a),c={label:" ",value:"",selected:!0,disabled:!0};Object.keys(b).forEach(function(a,e){0!==e&&(b[a]=[]);b[a].unshift(c)},this);return b},_cloneData:function(a){return h.clone(a)},_itemInArray:function(a,b){return a.some(function(a){return a.label===b.label})},_makeDropdownSelection:function(a,b){var c=!1;a.forEach(function(a){a.value===b?c=a.selected=!0:a.selected=!1});c||a.unshift({label:" ",value:"",selected:!0,disabled:!0})},_isItemInDropdown:function(a,b){return a.some(function(a){if(a.value===
b)return!0})},_generateLabelNode:function(a,b){var c=document.createElement("label");c.innerHTML=a;c.classList.add("esri-rfx-args-editor__tr--arg-name","esri-paddingTop-5");b.appendChild(c)},_generateDropdownNode:function(a,b){var c=document.createElement("div");b.appendChild(c);return new y({options:a},c)},_generateTextBoxNode:function(a){var b=document.createElement("div");a.appendChild(b);return new z(null,b)},_generateDropdownOptions:function(a){return Object.keys(a).map(function(b){return{value:b,
label:this._i18n[a[b]]}}.bind(this))},_parseByValuesGridData:function(a,b){var c=[],d=[];a.forEach(function(a){if("*"!==a.idNum){var f=a.Dimension.filter(function(a){return a.selected});a=a.Value.filter(function(a){return a.selected});1===f.length&&1===a.length&&(f=f[0].value,a=a[0].value,b||""!==f&&""!==a)&&(c.push(f),d.push(a))}});return{dimensions:c,values:d}},_parseByRangesGridData:function(a,b){var c=[],d=[],e=[];a.forEach(function(a){if("*"!==a.idNum){var f=a.Dimension.filter(function(a){return a.selected}),
g=a.MinValue.filter(function(a){return a.selected});a=a.MaxValue.filter(function(a){return a.selected});1===f.length&&1===g.length&&1===a.length&&(f=f[0].value,g=g[0].value,a=a[0].value,b||""!==f&&""!==g&&""!==a)&&(c.push(f),d.push(g),e.push(a))}});return{Dimension:c,MinValue:d,MaxValue:e}},_addBreakLine:function(a){var b=document.createElement("br");a.appendChild(b)},_getWidgetState:function(a){a||(a=!1);var b=this._dimensionDefinitionSelect.value,c=this.rasterVariableGrid.get("value"),c={definitionType:b,
variables:c};switch(b){case this.dimensionDefinition.BY_VALUES:var d=this.byValuesGrid.getStoreValue();a=this._parseByValuesGridData(d,a);c.dimensions=a.dimensions;c.values=a.values;break;case this.dimensionDefinition.BY_RANGES:d=this.byRangesGrid.getStoreValue();a=this._parseByRangesGridData(d,a);c.dimensions=a.Dimension;c.minValues=a.MinValue;c.maxValues=a.MaxValue;break;case this.dimensionDefinition.BY_ITERATION:c.dimension=this._iterationFormDimensionSelect.get("value"),c.startValue=this._iterationFormStartOfFirstIterationSelect.get("value"),
c.endValue=this._iterationFormEndOfFirstIterationSelect.get("value"),c.stepValue=this._iterationFormStepTextbox.get("value"),c.dimension===this.stdTimeDimension&&(c.units=this._iterationFormTimeUnits.get("value"))}return this.widgetState[b]=c},_getValueAttr:function(){return this._getWidgetState(!1)}});q("extend-esri")&&h.setObject("dijit.RasterFunctionEditor.RFxMultidimensionalDefinitionEditor",k,r);return k});