// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.33/esri/copyright.txt for details.
//>>built
require({cache:{"url:esri/dijit/RasterFunctionEditor/templates/RFxRasterVariableGrid.html":'\x3cdiv class\x3d"esri-rfx-raster-variable-grid"\x3e\r\n    \x3cdiv data-dojo-attach-point\x3d"_rasterVariableDiv"\x3e\r\n    \x3c/div\x3e\r\n\x3c/div\x3e\r\n'}});
define("esri/dijit/RasterFunctionEditor/RFxRasterVariableGrid","dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/has dojo/Evented dijit/_WidgetBase dijit/_TemplatedMixin dijit/_WidgetsInTemplateMixin dijit/_OnDijitClickMixin ../../kernel dojo/text!./templates/RFxRasterVariableGrid.html ./EditableGridMixin ./RFxGridBase".split(" "),function(c,f,h,k,l,m,n,p,q,r,t,u,d){c=c("RFxRasterVariableGrid",[m,n,p,q,l,u],{declaredClass:"esri.dijit.RasterFunctionEditor.RFxRasterVariableGrid",templateString:t,
widgetsInTemplate:!0,constructor:function(a){this.names=["Select","Variables"];this.dataTypes=[d.DATA_TYPES.boolean,d.DATA_TYPES.string];this.isEditable=[!0,!1];a.containerNode&&(this.container=a.containerNode)},postCreate:function(){this.inherited(arguments);this._createGridBase();this.rasterVariableGrid.on("grid-data-change",f.hitch(this,function(a){this._updateValue(a)}))},startup:function(){this.inherited(arguments);this.setVariableOptions(this.layerArg)},onRasterChange:function(){this.setVariableOptions()},
setVariableOptions:function(){if(this.layerArg&&this.layerArg.input){var a=this.layerArg.input,b;if(0<a.declaredClass.indexOf("RFxRasterInput")&&a.value&&(b=(b=a.get("value"))&&(b.name||b.datasetName.name),a=a.getSelectedLayer(b)))if(a.loaded)this._createDataObject(a);else a.on("load",f.hitch(this,function(a){this._createDataObject(a.target)}))}},_getSchema:function(){return this.names.map(function(a,b){return{name:a,dataType:this.dataTypes[b],isEditable:this.isEditable[b]}},this)},_createGridBase:function(){var a=
this._getSchema(),b=this._createDataObject(this.value);this.rasterVariableGrid=new d({schema:a,data:b,hasIdColumn:!1,isExtensible:!1,showHeader:!1},this._rasterVariableDiv);this.rasterVariableGrid.startup();this.rasterVariableGrid.keepScrollPosition=!0},_updateValue:function(a){var b=!1;a.forEach(function(a){a.Select&&(b=!0)});b||(a[0].Select=!0,setTimeout(function(){this.rasterVariableGrid.updateStoreValue(a)}.bind(this),0));this.emit("variable-grid-update",a)},_createDataObject:function(a){var b=
[],g="",c=!1,d=!1;if(!a)return b;a.getMultidimensionalInfo().then(f.hitch(this,function(a){a.variables&&a.variables.forEach(f.hitch(this,function(a,e){c=0==e;e=h.map(a.dimensions,function(a){return a.name+"\x3d"+a.values.length}).join(",");g=a.name+" ["+e+"] ("+(a.description||"")+"})";e=!1;this.defaultValue&&0<this.defaultValue.length&&(c=!1,e=this.defaultValue.includes(a.name));a={Select:c||e,Variables:g,value:a.name};b.push(a);a.Select&&(d=!0)}));d||(b[0].Select=!0);this.rasterVariableGrid.updateStoreValue(b);
this.emit("variable-grid-update",b)}))},_getValueAttr:function(){var a=this.rasterVariableGrid.getStoreValue(),b=[];a.forEach(function(a){a.Select&&b.push(a.value)});1>b.length&&b.push(a[0]&&a[0].value);return b}});k("extend-esri")&&f.setObject("dijit.RasterFunctionEditor.RFxRasterVariableGrid",c,r);return c});