// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.33/esri/copyright.txt for details.
//>>built
define("esri/dijit/RasterFunctionEditor/utils","dojo/_base/lang dojo/_base/url dojo/has dojo/on dojo/Deferred dojo/_base/array ../../kernel ../../request ../../lang ../../config ../../layers/ArcGISImageServiceLayer ../../layers/ImageServiceParameters ../../layers/MosaicRule ../../layers/RasterFunction ../../tasks/Geoprocessor ../../tasks/JobInfo ../../renderers/colorUtils ../../renderers/colorRampUtils".split(" "),function(f,z,A,m,B,g,n,r,t,u,C,D,E,F,G,H,p,v){function w(a){if(a){var b=g.map([a.FromColor,
a.ToColor],function(a){a=p.toRGB({h:a.Hue,s:a.Saturation,v:a.Value});return[a.r,a.g,a.b]});return{fromColor:b[0],toColor:b[1],type:"algorithmic",algorithm:a.Algorithm}}}function x(a){if(a)return a=p.toHSV(p.getDojoColor(a)),{type:"HsvColor",Hue:a.h,Saturation:a.s,Value:a.v,AlphaValue:255}}function y(a){if(a){var b=a.toJson?a.toJson():void 0;return{Algorithm:b&&b.Algorithm||"esriHSVAlgorithm",type:"AlgorithmicColorRamp",FromColor:x(a.fromColor),ToColor:x(a.toColor)}}}var q={},e,d,h;f.mixin(q,{fetchRFT:function(a,
b,c,k,e){var d=new B,l;l=(l=(l=a.name)&&l.slice(-8))&&".rft.xml"===l.toLowerCase();return a&&a.itemDataUrl?l?e?this.convertRFT({url:e+"/ConvertRasterFunctionTemplate",rft:{itemId:a.id},format:"json"},b,k,c):(c("errorUtilitiesServiceNotAvailable"),d.reject(Error("errorUtilitiesServiceNotAvailable")),d.promise):r({url:a.itemDataUrl,callbackParamName:"callback",content:{f:"json"},handleAs:"json",load:b,error:c}).then(k):(c("errorRetrievingRFTItem"),d.reject(Error("errorRetrievingRFTItem")),d.promise)},
convertRFT:function(a,b,c,k){var f=a.url,g=function(){h&&(h.remove(),h=null);d&&(d.remove(),d=null)};e||(e=new G(f),m(e,"error",g));d=m(e,"job-complete",function(a){d&&(d.remove(),d=null);a.jobInfo.jobStatus!==H.STATUS_SUCCEEDED?(g(),k(a)):e.getResultData(a.jobInfo.jobId,"outputRasterFunction")});h=m(e,"get-result-data-complete",function(a){h&&(h.remove(),h=null);var b=a&&a.result&&a.result.value;b&&b.url&&(a={url:b.url,handleAs:"json",load:c,error:k},b=(new z(b.url)).authority,-1===u.defaults.io.corsEnabledServers.indexOf(b)&&
u.defaults.io.corsEnabledServers.push(b),r(a))});a={inputRasterFunction:JSON.stringify(a.rft),format:a.format};return e.submitJob(a,b,null,k)},getRasterJsonFromLayer:function(a){if(!a)return null;var b=a.url,c=a.credential;t.isDefined(c)?(b=b+"?token\x3d"+c.token,c.referer&&(b+=c.referer)):n.id.getCredential(b).then(f.hitch(this,function(a){a=n.id.findCredential(b);b=b+"?token\x3d"+a.token;a.referer&&(b+=a.referer)}));c={url:b,name:a.name};a.renderingRule&&(c.renderingRule=a.renderingRule.toJson?
a.renderingRule.toJson():a.renderingRule);a.mosaicRule&&(c.mosaicRule=a.mosaicRule.toJson?a.mosaicRule.toJson():a.mosaicRule);return c},getLayerIdfromRasterValue:function(a,b){if(a&&b){var c;g.some(b,function(b){if(b&&b.url===a.url&&b.name===a.name&&a.name)return c=b.id,!0});return c}},getColorRampFromArg:function(a){if(a){var b,c;a.type&&-1<a.type.toLowerCase().indexOf("colorramp")?b=a:a.value&&-1<a.value.type.toLowerCase().indexOf("colorramp")&&(b=a.value);if(b)return a=b.type.toLowerCase(),"multipartcolorramp"===
a?c=v.fromJson({type:"multipart",colorRamps:g.map(b.ArrayOfColorRamp,function(a){return w(a)})}):"algorithmiccolorramp"===a&&(c=v.fromJson(w(b))),c.id=c.name=b.Name,c}},getRFxArgColorRampValue:function(a){if(a){if(a.fromColor&&a.toColor)return f.mixin(y(a),{Name:a.name});if(a.colorRamps){var b=g.map(a.colorRamps,y);return{type:"MultiPartColorRamp",NumColorRamps:b.length,ArrayOfColorRamp:b,Name:a.name}}}},RFX_VARIABLE_TYPE:"RasterFunctionVariable",RFX_TEMPLATE_TYPE:"RasterFunctionTemplate",ARGUMENT_ARRAY_TYPE:"ArgumentArray",
getArgRFT:function(a){if(a){if("RasterFunctionTemplate"===a.type)return a;if(a.value&&"RasterFunctionTemplate"===a.value.type)return a.value}},getEnumData:function(a){if(Array.isArray(a))return a.forEach(function(a){a.key=a.key.toString()}),a},getImageServiceTitle:function(a){a=a.split("/");return a[a.length-2]},isReferencedObject:function(a){if(a&&t.isDefined(a._object_ref_id))return!0},functionTypes:{local:"LocalFunction",gpAdapter:"GPAdapterFunction",pythonAdapter:"PythonAdapterFunction"},defaultRasterNodeProps:{name:"Raster",
isDataset:!0,isPublic:!1,type:"RasterFunctionVariable"},getArcGISImageServiceLayerItem:function(a){if(a){a=f.clone(a);a.name||(a.name=this.getImageServiceTitle(a.url));var b=new D;a.mosaicRule&&(b.mosaicRule=new E(a.mosaicRule));a.renderingRule&&(b.renderingRule=new F(a.renderingRule));b=new C(a.url,{id:a.name+(new Date).toString(),imageServiceParameters:b});b.name=a.name;return b}}});A("extend-esri")&&f.setObject("dijit.RasterFunctionEditor.utils",q,n);return q});