// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.33/esri/copyright.txt for details.
//>>built
define("esri/layers/rasterLib/renderer/RasterUniqueValueRenderer",["dojo/_base/declare","dojo/_base/lang","./RasterRenderer","../function/ColormapFunction","../../../renderers/colorRampGenerator"],function(t,w,u,r,v){return t([u],{declaredClass:"esri.layers.rasterLib.renderer.RasterUniqueValueRenderer",rendererName:"UniqueValue",field:"",alias:"",uniqueValueInfos:null,constructor:function(d){d&&d.colormap&&(this.colormap=d.colormap,this._function=new r(d),this._function.outputPixelType="U8",this._function.renderTexture=
!0)},bind:function(d){this.inherited(arguments);if(!this._function){var c=(this.raster&&this.raster.rasterInfo||this._rawRasterInfo).vat;if(!c)throw"uv renderer requires data source to have raster attribute table";var a=this.attributeField||this.field1||this.field,f=this.infos||this.uniqueValueInfos;this.defaultColor=this.defaultColor||this.defaultSymbol&&this.defaultSymbol.color;var h,g=c.fields.filter(function(b){return"value"===b.name.toLowerCase()})[0];g&&(h=g.name);a||((a=c.fields.filter(function(b){return-1<
["classname","category"].indexOf(b.name.toLowerCase())})[0])||(a=c.fields.filter(function(b){return"esriFieldTypeString"===b.type})[0]),this.alias=(this.field=a=a&&a.name||h)&&a.alias||h);var k=[],p,e,q,l,m,n;if(!f){f=[];q=c.fields.filter(function(b){return"alpha"===b.name.toLowerCase()})[0];l=c.fields.filter(function(b){return"red"===b.name.toLowerCase()})[0];m=c.fields.filter(function(b){return"green"===b.name.toLowerCase()})[0];n=c.fields.filter(function(b){return"blue"===b.name.toLowerCase()})[0];
for(g=0;g<c.features.length;g++)e=c.features[g].attributes,(p=f.some(function(b){b.value===e[a]}))||(q&&l&&m&&n?f.push({value:e[a],alias:e[a],color:[e[l.name],e[m.name],e[n.name],e[q.name]]}):l&&m&&n?f.push({value:e[a],alias:e[a],color:[e[l.name],e[m.name],e[n.name]]}):f.push({value:e[a],alias:e[a]}));if(!(l&&m&&n))for(p=v.createRandomColorRamp({size:f.length}),g=0;g<f.length;g++)f[g].color=p[g];this.uniqueValueInfos=f}if(f)f.forEach(function(b){k=k.concat(c.features.filter(function(c){return b.value==
c.attributes[a]}).map(function(a){return[a.attributes[h]].concat(b.color||b.symbol&&b.symbol.color)}))}),this.defaultColor&&c.features.filter(function(a){k.some(function(b){return b[0]===a.attributes[h]})||k.push([a.attributes[h]].concat(this.defaultColor))});else throw"missing uniqueValueInfos property";this._function=new r({colormap:k});this.colormap=k;this._function.outputPixelType="U8";this._function.renderTexture=!0;this._function.setProcessingContext(this._processingContext)}},draw2D:function(d){d=
this._clonePixelData(d);return d=this._function._colorize(d)},drawGL:function(d){this._function._colorizeGL(d)},toJson:function(d){var c={field:this.field,uniqueValueInfos:this.uniqueValueInfos,defaultColor:this.defaultColor};d&&(c.colormap=this.colormap);return{rendererName:this.rendererName,rendererArguments:c}},toCommonRendererJson:function(){var d=this.attributeField||this.field1||this.field,c=(this.infos||this.uniqueValueInfos).map(function(a){return{value:a.value,label:a.alias,symbol:{color:3===
a.color.length?a.color.concat([255]):a.color,type:"esriSFS",style:"esriSFSSolid"}}});return{type:"uniqueValue",field1:d,uniqueValueInfos:c}}})});