// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.33/esri/copyright.txt for details.
//>>built
define("esri/layers/rasterLib/renderer/rasterRendererHelper","dojo/_base/declare dojo/_base/lang ../../PixelBlock ./RasterColormapRenderer ./RasterUniqueValueRenderer ./RasterRGBRenderer ./RasterStretchColorRampRenderer ./RasterClassBreaksRenderer ./RasterShadedReliefRenderer".split(" "),function(y,z,A,r,t,u,v,w,x){var n=function(){function a(a){b[a.prototype.rendererName]=a}var b={};a(r);a(u);a(v);a(t);a(w);a(x);return b}();return{wellKnownRenderers:n,isSupported:function(a){if(!a)return!1;var b=
!0;n[a.rendererName]||(b=!1);return b},create:function(a){if(!a)return null;var b;a.rendererName?(b=a.rendererName,a=a.rendererArguments):(b="uniqueValue rasterStretch rasterShadedRelief rgb rasterColormap classBreaks".split(" ").indexOf(a.type),b="UniqueValue Stretch ShadedRelief RGB Colormap ClassBreaks".split(" ")[b],"rasterStretch"===a.type&&a.bandIndex&&1<a.bandIndex.length&&(b="RGB"));return(b=n[b])?new b(a):null},createDefaultRenderer:function(a){if(a&&a.raster){var b=a.raster.rasterInfo,d=
a.raster.dataType;if(b){var c=a.raster.rasterFunction,g=["Stretch","Colormap","ContrastAndBrightness"];if(c&&"U8"===b.pixelType&&-1<g.indexOf(c.functionName))c.renderTexture=!0;else if("Processed"!==d||!(a.useWebGL&&c&&c.renderTexture||!a.useWebGL&&"U8"===b.pixelType)){c&&(b=c.rasterInfo);var c=b.bandCount,f=b.colormap,e=b.vat,g=b.histograms,l;g&&0===g.length&&(g=null);var h=b.statistics&&b.statistics.map(function(a){return[a.min,a.max,a.mean,a.stddev]}),m=b.keyProperties&&(b.keyProperties.bandProperties||
b.keyProperties.BandProperties);if(1===c&&f&&0<f.length)l=this._getDefaultColormapRenderer(e,f);else if(1===c&&e&&e.features&&0<e.features.length)l=new t({});else{f=0;e=!1;d||!a.raster||!a.raster.tileInfo||void 0!==a.raster.tileInfo.tileType&&"Map"!==a.raster.tileInfo.tileType?"U8"===b.pixelType&&"Processed"===d?(f=5,h=h||[[0,255,0,0],[0,255,0,0],[0,255,0,0]],e=!1):"U8"===b.pixelType||"Elevation"===d?(f=5,e=h?!1:!0):"Scientific"===d?(f=5,e=h?!1:!0,l=this._getDefaultScientificColorRamp()):g&&0<g.length?
(f=6,e=!1):h?(f=5,e=!1):(f=6,e=!0):(h=[[0,255,0,0],[0,255,0,0],[0,255,0,0]],f=5,e=!1);h||(f=5,e=!0);var k,n,p,q;if(3<=c&&m&&!(a.bandIds||a.raster&&a.raster.imageServiceParams&&a.raster.imageServiceParams.bandIds)){for(a=0;a<m.length;a++)m[a].BandName&&"red"===m[a].BandName.toLowerCase()&&(n=a),m[a].BandName&&"green"===m[a].BandName.toLowerCase()&&(p=a),m[a].BandName&&"blue"===m[a].BandName.toLowerCase()&&(q=a);void 0!==n&&void 0!==p&&void 0!==q&&(k=[n,p,q])}2===c&&(k=[0,0,0]);k&&(h=k.map(function(a){return h[a]}));
k={stretchType:f,min:0,max:255,dra:e,minPercent:.25,maxPercent:.25,useGamma:!1,computeGamma:!1,statistics:h,histograms:g,numberOfStandardDeviations:2.5,bandIndex:k};1===c?(l&&(k.colorRamp=l,k.invert=!0),l=new v(k)):l=new u(k)}return l}}}},_getDefaultColormapRenderer:function(a,b){if(b||b.length){var d=[],c=this._ratContainsColormap(a);if(c)var g=this._getRATValueClassNameMap(a);b.forEach(function(a){var b=g?g[a[0]]:a[0];d.push({color:[a[1],a[2],a[3]],value:a[0],label:c?null!=b?b:"":a[0]})});return new r({colormapInfos:d})}},
_ratContainsColormap:function(a){if(!a||!a.fields)return!1;var b,d,c;return a.fields.some(function(a){a&&a.name&&(a=a.name.toLowerCase(),"red"===a&&(b=!0),"green"===a&&(d=!0),"blue"===a&&(c=!0));return b&&d&&c})},_getRATValueClassNameMap:function(a){if(!a||!a.fields)return null;var b={},d,c;a.fields.forEach(function(a){if("classname"===a.name.toLowerCase()||"class_name"===a.name.toLowerCase())d=a.name;"value"===a.name.toLowerCase()&&(c=a.name)});a.features.forEach(function(a){a=a.attributes;b[a[c]]=
d?a[d]:a[c]});return b},_getDefaultScientificColorRamp:function(){return{type:"multipart",colorRamps:[{fromColor:[255,0,0],toColor:[255,255,0]},{fromColor:[255,255,0],toColor:[0,255,255]},{fromColor:[0,255,255],toColor:[0,0,255]}]}}}});