// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.33/esri/copyright.txt for details.
//>>built
define("esri/layers/rasterLib/renderer/RasterClassBreaksRenderer",["dojo/_base/declare","dojo/_base/lang","./RasterRenderer","../function/ColormapFunction","../function/RemapFunction"],function(l,m,n,p,q){return l([n],{declaredClass:"esri.layers.rasterLib.renderer.RasterClassBreaksRenderer",rendererName:"ClassBreaks",renderTexture:!0,constructor:function(a){a=a||{};this._function=new q(a);this._function.outputPixelType="U8";var b=a.classBreakInfos;a=a.minValue;null!=a&&b&&(this._function.functionArguments.colorBreaks=
this._getSortedColorBreaks(a,b))},bind:function(a){this.inherited(arguments);this.isColormapFunction=!1;var b=this.raster&&this.raster.rasterInfo||this._rawRasterInfo,c=b&&b.vat;if(c&&"u8"===b.pixelType.toLowerCase()&&this.classBreakInfos){var f,d=this.field;if(b=c.fields.filter(function(a){return"value"===a.name.toLowerCase()})[0])f=b.name;var k=c.features.sort(function(a,b){return parseFloat(a.attributes[d])-parseFloat(b.attributes[d])})[0].attributes[d];this.isColormapFunction=!0;var e=[],g=this.field,
h=this.classBreakInfos;h.forEach(function(a,b){c.features.forEach(function(c){var d=h[b-1]&&h[b-1].classMaxValue||k;c.attributes[g]<=a.classMaxValue&&(c.attributes[g]>d||c.attributes[g]===k)&&(d=a.symbol.color,e.some(function(a){return a[0]===c.attributes[f]})||e.push([c.attributes[f]].concat(d)))})});this._function=new p({colormap:e});this.colormap=e;this._function.outputPixelType="U8";this._function.renderTexture=!0}this._function&&this._function.setProcessingContext(m.mixin({useProcessedData:!0},
this._processingContext))},draw2D:function(a){if(this.isColormapFunction)return this._updateColormapParameters(),a=this._clonePixelData(a),a=this._function._colorize(a);this._updateRemapParameters();return this._function._remap(a)},drawGL:function(a){this.isColormapFunction?(this._updateColormapParameters(),this._function._colorizeGL(a)):(this._function.renderTexture=!0,this._updateRemapParameters(),this._function._remapGL(a))},toJson:function(){var a=this._function.toJson().rasterFunctionArguments;
return{rendererName:this.rendererName,rendererArguments:a}},toCommonRendererJson:function(){var a,b=this.classBreakInfos,c=this.colorBreaks;if(null==b&&c)for(b=[],a=0;a<c.length-1;a++)b.push({classMaxValue:c[a+1].value,symbol:{color:c[a].mappedColor,type:"esriSFS",style:"esriSFSSolid"},label:c[a].value+" - "+c[a+1].value});return{type:"classBreaks",field:"Value",minValue:null!=this.minValue?this.minValue:c[0].value,classBreakInfos:b}},_updateRemapParameters:function(){var a=this.classBreakInfos,b=
this.minValue;null!=b&&a&&(this._function.functionArguments.colorBreaks=this._getSortedColorBreaks(b,a))},_getSortedColorBreaks:function(a,b){b=b.map(function(a){return{maxValue:a.classMaxValue,color:a.symbol.color}}).sort(function(a,b){return a.maxValue-b.maxValue});var c=[{value:a,mappedColor:b[0].color}];for(a=0;a<b.length;a++)c.push({value:b[a].maxValue,mappedColor:a===b.length-1?b[a].color:b[a+1].color});return c},_updateColormapParameters:function(){this._function.functionArguments.colormap=
this.colormap}})});