// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.33/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/ReportPlayer/dataProvider/commands/createHTML/HTMLStringBuilder","dojo/dom-attr dojo/dom-class dojo/dom-construct dojo/dom-geometry dojo/dom-style dojo/query esri/dijit/geoenrichment/utils/DomUtil esri/dijit/geoenrichment/utils/DynamicStyleUtil esri/dijit/geoenrichment/ReportPlayer/config ./HeaderFooterRenderer ../../../PlayerViewModes ../../../core/supportClasses/DocumentOptions".split(" "),function(u,v,h,w,q,f,x,y,k,z,p,A){var B={processTooltips:function(a){f(".selectableLegendRootLabel",
a).forEach(function(b){b.title=b.innerHTML})}},e={PROPS_TO_REMOVE:{"data-dojo-attach-point":1,id:1,widgetid:1},buildHtmlStringForPlayer:function(a,b){var d=[],c=e._preprocessMainNode(a,d);if(k.isPlayerOnServer)return e._getPageNodes(a,c,b),{domString:c};a=e._getPageNodes(a,c,b);b=e._cleanUpAndCombinePageNodes(a);a.forEach(function(b){h.destroy(b)});return{domString:b,additionalStyleNodes:d}},_preprocessMainNode:function(a,b){function d(b){f("."+b,c).forEach(function(b){q.set(b,{maxWidth:"none",maxHeight:"none",
width:"auto",height:"auto"})})}var c=k.isPlayerOnServer?a.domNode:h.toDom(a.domNode.outerHTML);e._processNode(c,b);a.getViewMode()===p.FULL_PAGES?(d("esriGEReportPlayer_reportContainerGrid"),d("reportContainerGrid_mainContainer")):a.getViewMode()===p.PANELS_IN_STACK_ALL&&(d("esriGEReportPlayer_reportContainerStackAll"),f(".reportContainerStackAll_zoomFillerContainer",c)[0].style.margin="0");!k.isPlayerOnServer&&B.processTooltips(c);return c},_processNode:function(a,b){function d(b,a){return a?"line"===
b.nodeName&&b.getAttribute("x1")===b.getAttribute("x2")&&b.getAttribute("y1")===b.getAttribute("y2")?!1:!0:!(x.isHidden(b)||"none"===q.get(b,"display"))}function c(b,a){a=void 0===a?!0:a;for(var c in e.PROPS_TO_REMOVE)(a||"id"!==c)&&u.remove(b,c)}function f(a,e){"svg"===a.nodeName&&(e=!0);if(!e&&!k.isPlayerOnServer){var n=y.getStyle(a.id);n&&n.forEach(function(a){b.push(a)});c(a,!n)}if(!d(a,e))return h.destroy(a),!1;if(a.children)for(var n=a.children.length,g=0,t=0;g+t<n;)f(a.children[g],e)?g++:t++;
return!0}var e=this;f(a)},_getPageNodes:function(a,b,d){return a.getViewMode()===p.PANELS_IN_STACK_ALL?e._getPageNodes_stackAll(a,b,d):e._getPageNodes_fullPages(a,b,d)},_getPageNodes_stackAll:function(a,b,d){if(!a.splitPages())return(e._providePageHeaderFooter(1,a,!0,[b])||a.needAutoScale())&&e._tryApplyNewPageSize(a,b),e._processAllPanelsInStacks(b),[b];d=h.create("div",{"class":"esriGEBehindScreen"},document.body);d.appendChild(b);e._providePageHeaderFooter(1,a,!0,[b]);["esriGEReportPlayerPrint_reportHeader",
"esriGEReportPlayerPrint_reportDataSource","esriGEReportPlayerPrint_reportFooter"].map(function(a){(a=f("."+a,b)[0])&&h.destroy(a)});var c=f(".esriGEReportPlayer_infographicsPageStack",b)[0],m=0,c=f(".infographicPageStack_infographicRow",c).map(function(a){a=w.getMarginBox(a).h;m=Math.max(m,a);return a}),g=[];if(1===c.length)g.push({height:c[0],indexes:[0]});else if(2===c.length)g.push({height:c[0]+c[1],indexes:[0,1]});else{var n=A.getPageBox(a.getDocumentOptions()),r=Math.max(b.clientWidth*n.h/n.w,
c[0]+c[1],m),l;c.forEach(function(a,b){l?l.height+a<=r?(l.indexes.push(b),l.height+=a):(l={height:a,indexes:[b]},g.push(l)):(l={height:a,indexes:[b]},g.push(l));l.height>=r&&(l=null)})}var k=f(".reportContainerStackAll_groupLabelsContainer",b)[0].clientHeight,c=g.map(function(a){var c=h.toDom(b.outerHTML);f(".reportContainerStackAll_zoomFillerContainer",c)[0].style.height=a.height+k+"px";e._processAllPanelsInStacks(c,function(b,c){-1===a.indexes.indexOf(c)&&h.destroy(b)});return c});e._providePageHeaderFooter(c.length,
a,!0,c);h.destroy(d);return c},_processAllPanelsInStacks:function(a,b){f(".esriGEReportPlayer_infographicsPageStack",a).forEach(function(a){f(".infographicPageStack_infographicRow",a).forEach(function(a,d){var c=f(".section_stackNode",a)[0];v.add(c,"infographicPageStack_infographicSectionNode_stackNode");b&&b(a,d)})})},_getPageNodes_fullPages:function(a,b,d){var c=[],m=f(".reportContainerGrid_gridContainerWrapper",b);k.isPlayerOnServer?c=m:1<m.length?(m.forEach(function(a){a.parentNode.removeChild(a)}),
f(".esriGEReportPlayer_reportContainerGrid",b).forEach(function(a,b){0<b&&a.parentNode.removeChild(a)}),m.forEach(function(a){var d=h.toDom(b.outerHTML);f(".reportContainerGrid_gridStackContainer",d)[0].appendChild(a);c.push(d)})):c.push(b);d=e._providePageHeaderFooter(a.getNumberOfPages(),a,d,c,k.isPlayerOnServer)||a.needAutoScale();if(k.isPlayerOnServer){var g=d&&{w:c[0].clientWidth,h:c[0].clientHeight};d&&-1!==a.getDocumentOptions().pagesize.indexOf("x")&&a.setNewPageSize(g.w,g.h);d&&f(".reportContainerGrid_gridZoomFillerContainer",
b).forEach(function(a){a.style.width=g.w+"px";a.style.height=g.h+"px"});f(".esriGEReportPlayer_reportContainerGrid",b).forEach(function(a){a.style.position="absolute";a.style.left="0";a.style.top="0"});m.forEach(function(a){a.style.position="absolute";a.style.left="0";a.style.top="0"})}else d&&e._tryApplyNewPageSize(a,c[0]);return c},_tryApplyNewPageSize:function(a,b){if(-1!==a.getDocumentOptions().pagesize.indexOf("x")){var d=h.create("div",{"class":"esriGEBehindScreen"},document.body);d.appendChild(b);
a.setNewPageSize(b.clientWidth,b.clientHeight);d.removeChild(b);h.destroy(d)}},_providePageHeaderFooter:function(a,b,d,c,e){var f=b.getDocumentOptions(),h=b.getHeaderFooterParams(),k=!1;c.forEach(function(b,g){var l=Math.floor(g/a),m=g%a;k=z.addHeaderAndFooterToPage({pageNode:e?b:b.children[0],headerFooterParams:h&&h[l],documentOptions:f,pageIndex:d?g:m,numPages:d?c.length:a})||k});return k},_cleanUpAndCombinePageNodes:function(a){return function(a){return a&&a.replace(/esriMapsAnalystXNonSelectable|esriGENonSelectable|esriMapsAnalystXClickable|dojogfxstrokestyle="solid"/g,
"")}(a.map(function(a){return a.outerHTML}).join(""))}};return e});