// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.33/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/ReportPlayer/printing/PrintableContainer","dojo/_base/declare dojo/_base/lang esri/dijit/geoenrichment/Deferred esri/dijit/geoenrichment/when dojo/dom-class dojo/dom-construct esri/dijit/geoenrichment/utils/DomUtil esri/dijit/geoenrichment/utils/async/AsyncQueue ./_PrintSettingsSupport ../PlayerResizeModes ../PlayerViewModes ./VisualStateConverter ../core/supportClasses/DocumentOptions".split(" "),function(t,u,v,e,w,m,n,h,x,y,f,z,A){return t(x,{domNode:null,_player:null,
_viewModel:null,_initRollBackFunc:null,_pageSettingsRollBackFunc:null,_pageSettings:null,_pageFitParams:null,_headerFooterParams:null,_allowDataDrilling:!1,_allowFallbackMaps:!1,_splitPages:!1,_needAutoScale:!1,_commandId:null,constructor:function(a,d){this._player=a;this._viewModel=d;this.domNode=a.printableDiv},initialize:function(a){var d=this;this._commandId=a.commandId;return e(this._doInitialize(a),function(){return e(d._checkPrintSettings(a),function(a){return"cancel"===a?null:d})})},_doInitialize:function(a){function d(){var q=
h.executeFunctions([function(){k&&m.destroy(k);g&&g.resolve();n.showNodeFromBackground(c.domNode)},function(){c.getAllReportContainers().forEach(function(a,b){a.showPageAt&&a.showPageAt(p[b])})},function(){b.viewMode===f.PANELS_IN_STACK_ALL&&c.getAllReportContainers()[0].setPrinted(!1);c._setPrintMode(!1);c._setAnimationSuspended(!1);return b.resize()},function(){if(l)return b.viewMode=l,b.refresh({waitUntilAllContentIsReady:!1})}],0);a.onShowWaiting(q);return q}var c=this;if(this._player.isPlayerOnServer)this._setPrintMode(!0);
else{var p={},k,l,b=this._player;b.playerToolbar&&b.playerToolbar.closePopup();this._setAnimationSuspended(!0);var g,r=e(function(){return h.executeFunctions([function(){b.viewMode===f.PANELS_IN_STACK_ALL&&c.getAllReportContainers()[0].scrollToTop();b.resizeMode===y.FIT_WINDOW?k=m.create("div",{innerHTML:b.domNode.innerHTML,"class":"esriGEAbsoluteStretched esriGEReportPlayerPrintViewCopy"},b.printBackgroundView):(g=new v,a.onShowWaiting(g.promise))},function(){if(b.viewMode===f.PANELS_IN_STACK_ALL)c.getAllReportContainers()[0].setPrinted(!0);
else if(b.viewMode!==f.FULL_PAGES){l=b.viewMode;var a=b.getVisualState();b.viewMode=f.FULL_PAGES;return e(b.refresh({waitUntilAllContentIsReady:!0}),function(){return b.setVisualState(z.convertToFullPages(a,b.getReportData().templateJson))})}},function(){c._setPrintMode(!0);return h.executeFunctions(c.getAllReportContainers().map(function(a,b){return function(){a.resetZoom&&a.resetZoom();p[b]=a.getCurrentPageIndex&&a.getCurrentPageIndex();a.showAllPages&&a.showAllPages();a.collapseContent&&a.collapseContent()}}),
0)},function(){n.hideNodeInBackground(c.domNode,"report-player-being-printed")}],0)}(),function(){c._initRollBackFunc=d;return b.getRenderPromise()});a.onShowWaiting(r);return r}},_setPrintMode:function(a){w[a?"add":"remove"](this.domNode,"esriGEReportPlayerPrint esriGEReportPlayer "+(this._player.isPlayerOnServer?"isPlayerOnServer":""));this._player.setPrintMode(a)},_animationAllowedMemo:void 0,_setAnimationSuspended:function(a){a?(this._animationAllowedMemo=this._viewModel.isAnimationAllowed(),
this._viewModel.setAnimationAllowed(!1)):this._viewModel.setAnimationAllowed(this._animationAllowedMemo)},getViewMode:function(){return this._player.viewMode},getCurrentReportContainer:function(){return this._player.getCurrentReportContainer()},getAllReportContainers:function(){return this._player.getAllReportContainers()},getHeaderFooterParams:function(){return this._headerFooterParams},getDocumentOptions:function(){return u.mixin({},this.getCurrentReportContainer().documentOptions,this._pageSettings)},
getFitParams:function(){return this._pageFitParams},setNewPageSize:function(a,d){this._pageSettings.pagesize=A.combineCustomSizeString(a,d,"px");this._pageFitParams={w:a,h:d,hAlign:"center",vAlign:"top"}},getSelectedCommandId:function(){return this._commandId},allowDataDrilling:function(){return this._allowDataDrilling},allowFallbackMaps:function(){return this._allowFallbackMaps},splitPages:function(){return this._splitPages},needAutoScale:function(){return this._needAutoScale},getNumberOfPages:function(){return this.getCurrentReportContainer().getNumberOfPages()},
stop:function(){if(!this._player.isPlayerOnServer){var a=this;return e(this._pageSettingsRollBackFunc&&this._pageSettingsRollBackFunc(),function(){return e(a._initRollBackFunc&&a._initRollBackFunc())})}}})});