// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.33/esri/copyright.txt for details.
//>>built
define("esri/layers/rasterLib/function/rasterUtils",["dojo/_base/lang"],function(w){return{mask:function(a,c){if(a&&a.pixels&&a.pixels.length){a=this._clonePixelBlock(a);var e=c.includedRanges,f=c.noDataInterpretation;c=c.noDataValues;if(null===e&&null===c)return a;var g=a.pixels,b=a.mask,h=a.width*a.height,l=g.length,d;if(null!==c&&c.length!==l)throw"expect "+l+" elements in noDataValues";if(null!==e&&e.length!==2*l)throw"expect "+2*l+" elements in IncludeRanges";var q,m,p,n,k;if(null==b){b=new Uint8Array(h);
for(d=0;d<h;d++)b[d]=1;a.mask=b}if(0===f)for(f=0;f<l;f++)if(p=g[f],q=null===e?null:e[2*f],m=null===e?null:e[2*f+1],n=null===c?null:parseFloat(c[f]),null===q||null===m)for(d=0;d<h;d++)b[d]&&(k=p[d],k===n&&(b[d]=0));else if(null===n)for(d=0;d<h;d++)b[d]&&(k=p[d],k<q||k>m)&&(b[d]=0);else for(d=0;d<h;d++)b[d]&&(k=p[d],k<q||k>m||k===n)&&(b[d]=0);else{var r=new Uint8Array(h);for(d=0;d<h;d++)r[d]=b[d];for(f=0;f<l;f++)if(p=g[f],q=null===e?null:e[2*f],m=null===e?null:e[2*f+1],n=null===c?null:parseFloat(c[f]),
null===q||null===m)for(d=0;d<h;d++)r[d]&&(k=p[d],k!==n&&(r=0));else if(null===n)for(d=0;d<h;d++)r[d]&&(k=p[d],k<=q&&k<=m&&(r=0));else for(d=0;d<h;d++)r[d]&&(k=p[d],k<=q&&k<=m&&k!==n&&(r=0));for(d=0;d<h;d++)b[d]&&r[d]&&(b[d]=0)}return a}},calculateStatisticsHistograms:function(a,c){a=this._clonePixelBlock(a);c=a.pixelType;var e=a.pixels,f=a.mask,g=e.length,b,h,l,d,q=[],m,p,n,k,r;for(l=0;l<g;l++){m={min:-.5,max:255.5,size:256,counts:new Uint32Array(256)};p=m.counts;k=e[l];if("U8"===c)if(f)for(d=0;d<
a.width*a.height;d++)f[d]&&p[k[d]]++;else for(d=0;d<a.width*a.height;d++)p[k[d]]++;else{b=a.statistics[l].minValue;h=a.statistics[l].maxValue;m.min=b;m.max=h;h=(h-b)/256;n=new Uint32Array(257);if(f)for(d=0;d<a.width*a.height;d++)f[d]&&n[Math.floor((k[d]-b)/h)]++;else for(d=0;d<a.width*a.height;d++)n[Math.floor((k[d]-b)/h)]++;for(d=0;255>d;d++)p[d]=n[d];p[255]=n[255]+n[256]}q.push(m);b=a.statistics[l].minValue;h=a.statistics[l].maxValue;for(d=n=r=k=0;d<m.size;d++)k+=p[d],r+=d*p[d];r/=k;for(d=0;d<m.size;d++)n+=
p[d]*Math.pow(d-r,2);p=Math.sqrt(n/(k-1));d=(r+.5)*(m.max-m.min)/m.size+m.min;m=p*(m.max-m.min)/m.size;a.statistics[l]={min:b,minValue:b,max:h,maxValue:h,mean:d,stddev:m}}a.histograms=q;return a},buildIndexedColormap:function(a,c){if(!a)return null;var e=0;0>a[0][0]&&(e=a[0][0]);var f=Math.max(256,a[a.length-1][0]-e);if(65536<f)return null;var g=new Uint8Array(4*f),b=[],h=0,l=5===a[0].length;if(c)for(b=a[h],c=b[0]-e;c<f;c++)g[4*c]=b[1],g[4*c+1]=b[2],g[4*c+2]=b[3],g[4*c+3]=l?b[4]:255,c===b[0]-e&&(b=
h===a.length-1?b:a[++h]);else for(c=0;c<a.length;c++)b=a[c],h=4*(b[0]-e),g[h]=b[1],g[h+1]=b[2],g[h+2]=b[3],g[h+3]=l?b[4]:255;return{indexedColormap:g,offset:e,alphaSpecified:l}},colorize:function(a,c){if(null!==a&&null!==a.pixels){a=this._clonePixelBlock(a);var e=a.pixels,f=a.width*a.height,g=a.mask,b=c.indexedColormap,h=c.indexedColormapOffset,l=b&&b.length-1,d=c.indexed2DColormap;c=c.alphaSpecified;if(3<=e.length)throw"colormap only works on single band image";var q=e[0],m=new Uint8Array(q.length),
p=new Uint8Array(q.length),n=new Uint8Array(q.length),k=0;if(b)if(g)for(e=0;e<f;e++)g[e]&&(k=4*(q[e]-h),k<h||k>l?g[e]=0:(m[e]=b[k],p[e]=b[k+1],n[e]=b[k+2],g[e]=b[k+3]));else{g=new Uint8Array(f);for(e=0;e<f;e++)k=4*(q[e]-h),k<h||k>l?g[e]=0:(m[e]=b[k],p[e]=b[k+1],n[e]=b[k+2],g[e]=b[k+3]);a.mask=g}else if(g)for(e=0;e<f;e++)g[e]&&(b=d[q[e]],m[e]=b[0],p[e]=b[1],n[e]=b[2],g[e]=b[3]);else{g=new Uint8Array(f);for(e=0;e<f;e++)b=d[q[e]],m[e]=b[0],p[e]=b[1],n[e]=b[2],g[e]=b[3];a.mask=g}a.pixels=[m,p,n];a.statistics=
null;a.pixelType="U8";a.maskIsAlpha=c;return a}},convolute:function(a,c){a=this._clonePixelBlock(a);var e=a.pixels,f=a.width,g=a.height,b=f*g,h=e.length,l,d,q,m,p,n,k=[],r=[],x=c.normalizedKernel,y=c.kernelRows,v=c.kernelCols,u;for(c=0;c<h;c++){q=e[c];m=new Float32Array(b);m.set(q);for(p=1;p<g-1;p++)for(u=p*f,n=1;n<f-1;n++){for(l=r=0;l<y;l++)for(d=0;d<v;d++)r+=q[u+n+(l-1)*f+d-1]*x[l*v+d];m[u+n]=r}k.push(m)}a.pixels=k;return a},contrastBrightnessStretch:function(a,c){if(null!==a&&null!==a.pixels){a=
this._clonePixelBlock(a);var e=a.pixels,f=a.mask,g=a.width*a.height,b=e.length,h;h=c&&c.contrastOffset;c=c&&c.brightnessOffset;if("U8"!==a.pixelType)throw"the contrast and brightness function only supports 8 bit unsigned integer data";var l=this._createContrastBrightnessLUT(h,c);if(null==f)for(h=0;h<g;h++)for(c=0;c<b;c++)e[c][h]=l[e[c][h]];else for(h=0;h<g;h++)if(f[h])for(c=0;c<b;c++)e[c][h]=l[e[c][h]];a.pixelType="U8";return a}},isNull:function(a,c){if(null!==a&&null!==a.pixels){a=this._clonePixelBlock(a);
c=a.mask;var e=a.pixels[0],f=e.length,g;if(c){for(g=0;g<f;g++)e[g]=c[g]?0:1;a.mask=null}else if(e.fill)e.fill(0);else for(g=0;g<f;g++)e[g]=0;return a}},setNull:function(a){if(null!==c&&null!==c.pixels){var c=this._clonePixelBlock(a);a=c.mask;var e=c.pixels[0],f=e.length,g;a=a||new Uint8Array(f);for(g=0;g<f;g++)a[g]=e[g]?0:1;c.mask=a;return c}},local:function(a,c){if(!c)return a[0];var e=c.rasterCountNeeded;c=c.functor;var f=this._clonePixelBlock(a[0]);if(null!==f&&null!==f.pixels){var g=f.width*f.height,
b;a=(b=a[1])&&b.pixels[0];var h=b&&b.mask,l=f.mask,d=f.pixels[0];if(2===e)if(!l&&h)l=h;else if(l&&h)for(b=0;b<g;b++)l[b]=l[b]&&h[b]?1:0;f.mask=l;if(1===e)if(null==l)for(b=0;b<g;b++)d[b]=c(d[b]);else for(b=0;b<g;b++)l[b]&&(d[b]=c(d[b]));else if(2===e)if(null==l)for(b=0;b<g;b++)d[b]=c(d[b],a[b]);else for(b=0;b<g;b++)l[b]&&(d[b]=c(d[b],a[b]));f.mask=l;f.calculateStatistics();return f}},remapColor:function(a,c){a=this._clonePixelBlock(a);var e=a.width*a.height,f=c.length,g=Math.floor(f/2),b=c[Math.floor(g)],
h=c[0].value,l=c[c.length-1].value,d=a.pixels[0],q,m,p,n,k,r,x=!1,y=new Uint8Array(e),v=new Uint8Array(e),u=new Uint8Array(e),t=a.mask,w=4===c[0].mappedColor.length;t&&0!==t.length||(t=new Uint8Array(e),t.fill(w?255:1),a.mask=t);for(k=0;k<e;k++)if(t[k])if(q=d[k],q<h||q>l)y[k]=v[k]=u[k]=t[k]=0;else{x=!1;r=g;m=b;p=0;for(n=f-1;1<n-p;){if(q===m.value){x=!0;break}q>m.value?p=r:n=r;r=Math.floor((p+n)/2);m=c[Math.floor(r)]}x||(m=q===c[n].value?c[n]:c[p]);y[k]=m.mappedColor[0];v[k]=m.mappedColor[1];u[k]=
m.mappedColor[2];t[k]=m.mappedColor[3]}a.pixels=[y,v,u];a.mask=t;a.pixelType="u8";a.maskIsAlpha=w;return a},_clonePixelBlock:function(a){if(a.clone)return a.clone();var c=w.clone(a),e,f;if(a.pixels&&a.pixels[0]&&0<a.pixels[0].length&&!(c.pixels&&c.pixels[0]&&0<c.pixels[0].length))for(c.pixels=[],e=a.pixels.length,f=0;f<e;f++)c.pixels[f]=new a.pixels[f].constructor(a.pixels[f]);if(a.statistics)for(c.statistics=[],e=a.statistics.length,f=0;f<e;f++)c.statistics[f]=w.clone(a.statistics[f]);a.mask&&(c.mask=
new Uint8Array(a.mask));return c},_createContrastBrightnessLUT:function(a,c){if(this._contrastCache&&this._contrastCache.contrastOffset===a&&this._contrastCache.brightnessOffset===c)return this._contrastCache.lut;var e=Math.min(Math.max(a,-100),100),f=Math.min(Math.max(c,-100),100),g,b,h=new Uint8Array(256);for(g=0;256>g;g++)0<e&&100>e?b=(200*g-25500+510*f)/(2*(100-e))+128:0>=e&&-100<e?b=(200*g-25500+510*f)*(100+e)/2E4+128:100===e?(b=200*g-25500+256*(100-e)+510*f,b=0<b?255:0):-100===e&&(b=128),h[g]=
255<b?255:0>b?0:b;this._contrastCache={contrastOffset:a,brightnessOffset:c,lut:h};return h}}});