// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.33/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/ReportPlayer/core/supportClasses/templateJsonUtils/query/TemplateJsonQueryUtil",["./_SectionJsonCollector","../../../infographics/InfographicTypes"],function(h,g){var d={},e={process:function(a,b,c,d,f){var k=d;d=function(a,b,c){a&&k.apply(this,arguments)};f={processLevel:b,objJson:c,processFunc:d,ignoreComparisonCalculators:f&&f.ignoreComparisonCalculators};a!==b||"field"===a&&"field"===b?"document"===a?e._processTemplateJson(c,f):"section"===a?e._processSectionJson(c,
f):"table"===a?e._processTableJson(c,f,null):"tableRow"===a?e._processTableDataObj(c,f,null):"field"===a&&e._processFieldInfo(c,f,null):d(c)},_processTemplateJson:function(a,b){a.sectionsTables?a.sectionsTables.forEach(function(a){e._processTableJson(a,b)}):h.collectSectionJsons(a,{saveParentInfo:!1,processFieldInfoFunc:function(a){"field"===b.processLevel&&b.processFunc(a)}}).forEach(function(a){e._processSectionJson(a,b)})},_processSectionJson:function(a,b){"section"===b.processLevel&&b.processFunc(a);
a.stack&&a.stack.forEach(function(a){"sectionElement"===b.processLevel&&b.processFunc(a);"table"===a.id&&e._processTableJson(a,b)})},_processTableJson:function(a,b,c){"table"===b.processLevel&&b.processFunc(a);a.data.data.forEach(function(a){"tableRow"===b.processLevel&&b.processFunc(a,c);e._processTableDataObj(a,b,c)});a.backgroundSectionJson&&e._processSectionJson(a.backgroundSectionJson,b);a.foregroundSectionJson&&e._processSectionJson(a.foregroundSectionJson,b);a.backgroundFloatingTablesSectionJson&&
e._processSectionJson(a.backgroundFloatingTablesSectionJson,b);a.foregroundFloatingTablesSectionJson&&e._processSectionJson(a.foregroundFloatingTablesSectionJson,b)},_processTableDataObj:function(a,b,c){if(a.fieldInfos)for(var d in a.fieldInfos)e._processFieldInfo(a.fieldInfos[d],b,c,"tableCell")},_processFieldInfo:function(a,b,c,d){if(a){"field"!==b.processLevel||b.skipVariables&&(a.hasVariable||a.script)||b.processFunc(a,c,d);a.triggerJson&&a.triggerJson.fieldInfo&&a.templateName!==a.triggerJson.fieldInfo.templateName&&
e._processFieldInfo(a.triggerJson.fieldInfo,b,a,"trigger");a.dataDrillingPanelInfo&&e._processSectionJson(a.dataDrillingPanelInfo.sectionJson,b);a.tooltipInfo&&a.tooltipInfo.fieldInfo&&e._processFieldInfo(a.tooltipInfo.fieldInfo,b,a,"fieldTooltip");a.linkFieldInfo&&e._processFieldInfo(a.linkFieldInfo,b,a,"linkFieldInfo");if(a.isRichText)for(var f in a.richTextJson.fieldInfos)e._processFieldInfo(a.richTextJson.fieldInfos[f],b,a,"richTextPart");a.isInfographic&&e._processInfographicFieldInfo(a,b);a.isChart&&
e._processChartFieldInfo(a,b);a.isReportSection&&a.sectionJson&&e._processSectionJson(a.sectionJson,b)}},_processInfographicFieldInfo:function(a,b){var c=a.infographicJson;switch(c.type){case g.STATIC:c.header&&e._processTableJson(c.header,b,a);c.variableTables&&c.variableTables.forEach(function(c){c.variable&&e._processFieldInfo(c.variable.fieldInfo,b,a,"staticInfographicVariable");c.description&&c.description.fieldInfo&&e._processFieldInfo(c.description.fieldInfo,b,a,"staticInfographicDescription")});
if(c.dataDrilling)for(var d in c.dataDrilling){var f=c.dataDrilling[d];f&&f.sectionJson&&e._processSectionJson(f.sectionJson,b)}break;case g.AGE_PYRAMID:case g.TAPESTRY:case g.PRIZM5:case g.RELATED_VARS:case g.ONE_VAR:!b.ignoreComparisonCalculators&&c.fieldInfos&&c.fieldInfos.forEach(function(c){e._processFieldInfo(c,b,a,"dynamicInfographicVariable")});break;case g.AREA_DETAILS:c.titleSectionJson&&e._processSectionJson(c.titleSectionJson,b,a);c.attributesSectionJson&&e._processSectionJson(c.attributesSectionJson,
b,a);c.notesSectionJson&&e._processSectionJson(c.notesSectionJson,b,a);break;case g.LOCATOR_TABLE:c.titleSectionJson&&e._processSectionJson(c.titleSectionJson,b);e._processSectionJson(c.headerSectionJson,b);e._processSectionJson(c.dataSectionJson,b);c.summarySectionJson&&e._processSectionJson(c.summarySectionJson,b);c.summaryFooterSectionJson&&e._processSectionJson(c.summaryFooterSectionJson,b);break;case g.COMPARISON_TABLE:c.titleSectionJson&&e._processSectionJson(c.titleSectionJson,b),b.ignoreComparisonCalculators||
e._processSectionJson(c.dataSectionJson,b)}},_processChartFieldInfo:function(a,b){var c=a.chartJson.visualProperties;c.chartIcons&&c.chartIcons.forEach(function(c){e._processFieldInfo(c,b,a,"chartIcon")});c.floatingIcons&&c.floatingIcons.forEach(function(c){e._processTableJson(c,b,a,"floatingIcon")});c.floatingTexts&&c.floatingTexts.forEach(function(c){e._processTableJson(c,b,a,"floatingText")});b.ignoreComparisonCalculators&&a.chartJson.comparisonInfo&&(b=Object.assign({},b),b.skipVariables=!0);
c.tooltip&&c.tooltip.fieldInfo&&e._processFieldInfo(c.tooltip.fieldInfo,b,a,"chartTooltip");a.chartJson.dataDrillingPanelInfo&&e._processSectionJson(a.chartJson.dataDrillingPanelInfo.sectionJson,b);a.chartJson.seriesItems.forEach(function(c){c.points.forEach(function(c){e._processFieldInfo(c.fieldInfo,b,a,"chartPointField");c.iconFieldInfo&&e._processFieldInfo(c.iconFieldInfo,b,a,"chartPointIcon");c.captionFieldInfo&&e._processFieldInfo(c.captionFieldInfo,b,a,"chartPointCaption")})})}};d.DOCUMENT=
"document";d.SECTION="section";d.TABLE="table";d.SECTION_ELEMENT="sectionElement";d.TABLE_ROW="tableRow";d.FIELD="field";d.process=e.process;d.processTemplateFieldInfos=function(a,b,c){e.process("document","field",a,b,c)};d.processSectionFieldInfos=function(a,b,c){e.process("section","field",a,b,c)};d.processSectionElements=function(a,b){e.process("document","sectionElement",a,b)};d.processTableFieldInfos=function(a,b,c){e.process("table","field",a,b,c)};d.processChartFieldInfos=function(a,b){a.seriesItems.forEach(function(a){a.points.forEach(function(a){a.fieldInfo&&
b(a.fieldInfo,"series")})});var c=a.visualProperties.tooltip;if(c&&c.fieldInfo&&c.fieldInfo.isRichText)for(var e in c.fieldInfo.richTextJson.fieldInfos)b(c.fieldInfo.richTextJson.fieldInfos[e],"tooltip");a.dataDrillingPanelInfo&&d.processSectionFieldInfos(a.dataDrillingPanelInfo.sectionJson,function(a){b(a,"dataDrilling")})};d.hasMultiFeatureChart=function(a){var b=!1;d.processTemplateFieldInfos(a,function(a){a.isChart&&(b=b||a.chartJson&&!!a.chartJson.isMultiFeatureChart)});return b};d.hasComparisonInfographicTable=
function(a){var b=!1;d.processTemplateFieldInfos(a,function(a){a.isInfographic&&(b=b||a.infographicJson&&a.infographicJson.type===g.COMPARISON_TABLE)});return b};d.isGraphicReport=function(a){return!!a.sectionsTables};d.hasDynamicColumns=function(a){return d._checkTableAttributes(a,function(a){return 0<a.dynamicColumns})};d.hasDynamicRows=function(a){return d._checkTableAttributes(a,function(a){return 0<a.dynamicRows})};d._checkTableAttributes=function(a,b){var c;d.isGraphicReport(a)?d.processTemplateFieldInfos(a,
function(a){a.isReportSection&&a.sectionJson&&a.sectionJson.stack&&a.sectionJson.stack.some(function(a){if("table"===a.id&&a.attributes&&b(a.attributes))return c=!0})}):c=d.collectSectionJsons(a).some(function(a){return a.stack&&a.stack.some(function(a){return"table"===a.id&&a.attributes&&b(a.attributes)})});return c};d.hasMultiFeatureSections=function(a){return d.isGraphicReport(a)?d.hasMultiFeatureChart(a)||d.hasDynamicColumns(a)||d.hasComparisonInfographicTable(a):!1};d.calcNumberOfMaps=function(a,
b){var c=0;d.collectSectionJsons(a).forEach(function(a){c+=d.calcNumberOfMapsInSectionJson(a,b)});return c};d.calcNumberOfMapsInSectionJson=function(a,b){var c=0;a.stack&&a.stack.forEach(function(a){a.isMap&&(b&&b(a),c++)});d.processSectionFieldInfos(a,function(a){a.isMap&&(b&&b(a.mapJson),c++)});return c};d.calcNumberOfMapsInTableJson=function(a){var b=0;d.processTableFieldInfos(a,function(a){a.isReportSection&&(b+=d.calcNumberOfMapsInSectionJson(a.sectionJson))});return b};d.collectSectionJsons=
h.collectSectionJsons;d.getParentBox=h.getParentBox;d.setParentBox=h.setParentBox;d.getParentStyle=h.getParentStyle;return d});