// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.33/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/ReportPlayer/dataProvider/supportClasses/CustomReportsManager","dojo/_base/declare dojo/_base/lang esri/dijit/geoenrichment/Deferred esri/dijit/geoenrichment/when ./PortalManager ./ReportTemplateData ./StandardGraphicReportTemplates esri/dijit/geoenrichment/utils/PortalUtil esri/dijit/geoenrichment/utils/PortalQueryUtil esri/dijit/geoenrichment/utils/UrlUtil ../../config ../../countryConfig".split(" "),function(f,l,p,g,m,q,r,t,u,h,n,v){var w=f(null,{cache:null,constructor:function(){this.cache=
{}}});f={TEMPLATE_TYPE:"Report Template",PLAYER_STANDARD_INFOGRAPHIC_TYPEKEYWORD:"esriReportPlayerStandardInfographic",GALLERY_INFOGRAPHIC_TYPEKEYWORD:"esriWebGalleryInfographicReport",MOBILE_INFOGRAPHIC_TYPEKEYWORD:"esriMobileFactsInfographicReport",GALLERY_INFOGRAPHIC_USER:"esri_reports",_reportsCache:null,resetCache:function(){this._reportsCache=new w},getCustomReports:function(a){var d=this,c=h.getPortalUrl(a.portalUrl);return g(m.getPortalInfo(c),function(e){var b=e.user.username,b={q:u.combineQueryString({type:"Report Template",
typeKeywords:a.typeKeywords,owner:!a.publicOnly&&b}),sortField:"modified",sortOrder:"desc"};return t.queryCommon(h.combine(c,"sharing/rest/search"),b).then(function(b){b=b.map(function(b){return d.prepareCustomReportFromItem(b,e.portal.url,a)});return d._getCountryReports(b,a.countryID)})})},_getCountryReports:function(a,d){return a&&("*"===d?a:a.filter(function(a){return!a.countries||a.countries.split(",").some(function(a){return d===a.trim()})}))},prepareCustomReportFromItem:function(a,d,c){function e(a){return"string"===
typeof a?"true"===a:!!a}var b=l.mixin({},a.properties||a.details);b.isGraphicReport=e(b.isGraphicReport);b.isMultiFeature=e(b.isMultiFeature);b.reportID=a.id;d={title:a.title,templateData:d&&new q(a,d),modified:a.modified instanceof Date?a.modified.getTime():a.modified};c&&c.attachItemProperty&&(d[c.attachItemProperty]=a);l.mixin(d,b);return d},getCustomReportByID:function(a){var d=this,c=this._reportsCache.cache[a.reportID];if(c)return c;c=h.getPortalUrl(a.portalUrl);return this._reportsCache.cache[a.reportID]=
g(m.getPortalInfo(c),function(c){return c.user.getItem(a.reportID).then(function(b){return b&&d.prepareCustomReportFromItem(b,c.portal.url,a)})}).otherwise(function(c){delete d._reportsCache.cache[a.reportID];return a.ignoreError?null:(new p).reject(c)})},tryFindReportIdByAlias:function(a){var d=this,c=r.aliasToID(a.countryID,a.reportID);if(!c)return null;var e=h.getPortalUrl(a.portalUrl);return g(this.getCustomReportByID({reportID:c,portalUrl:e,ignoreError:!0,attachItemProperty:a.attachItemProperty}),
function(b){return b?b&&(a.returnObject?b:b.reportID):g(d.getCustomReports({portalUrl:e,countryID:a.countryID,typeKeywords:"esriReportPlayerStandardInfographic",publicOnly:!0,attachItemProperty:a.attachItemProperty}),function(b){function c(a){a=a.split(".");return Number((Number(a[0])+Number(a[1])/100).toFixed(2))}var d=c(n.jsapiVersion),e,f,g=-Infinity,h=Infinity;b.forEach(function(b){if(b.playerAlias===a.reportID){var k=c(b.jsapiVersion);d>=k&&k>g&&(g=k,e=b);d<k&&k<h&&(h=k,f=b)}});b=e||f;a.strictVersionCheck&&
b&&b.jsapiVersion!==n.jsapiVersion&&(b=null);return b&&(a.returnObject?b:b.reportID)})})},itemUpdated:function(a){delete this._reportsCache.cache[a]},getFakeCustomReportByContext:function(a){return{title:"Generic template",type:"esriReportTemplateStandard",coverage:a.countryID,countries:a.countryID,hierarchy:a.hierarchy||v.getHierarchyID(),isGraphicReport:!0,isMultiFeature:!1,reportID:null}}};f.resetCache();return f});