// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.33/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/ReportPlayer/dataProvider/supportClasses/ReportDataProcessor","esri/dijit/geoenrichment/when esri/dijit/geoenrichment/promise/all esri/dijit/geoenrichment/Deferred ./tasks/EnrichAreasTask ./tasks/RunReportTask ./data/AreaCalculatorsUtil ./data/VariablesUtil ./CustomReportsManager ./stdGeographies/StdGeographiesModel esri/dijit/geoenrichment/utils/DateUtil ../../core/supportClasses/templateJsonUtils/fieldInfo/FieldLibrary ../../core/supportClasses/templateJsonUtils/fieldInfo/FieldInfoNameUtil ../../core/supportClasses/templateJsonUtils/query/TemplateJsonQueryUtil ../../core/supportClasses/templateJsonUtils/TemplateJsonAnalyzer ../../core/infographics/utils/InfographicJsonUtil ../../config ../../countryConfig".split(" "),
function(k,l,m,r,t,g,u,v,w,n,p,q,x,y,z,h,f){return{runReportAndGetData:function(a,b){return l([v.getCustomReportByID(a),b]).then(function(b){var c=b[0];b=b[1];return(new t).execute({portalUrl:a.portalUrl,analysisAreas:a.analysisAreas,countryID:a.countryID,hierarchy:a.hierarchy,report:{reportID:c.reportID,portalUrl:c.templateData.getPortalUrl(!0),modified:c.modified,isMultiFeature:c.isMultiFeature},attachmentsStore:b,cacheResult:h.runReportTask.cacheResult}).then(function(a){return{taskIDs:a.taskIDs,
areaData:a.areaData,reportInfo:a.reportInfo}},function(c){a.fieldData.errors.push(c);return(new m).reject(c)})})},runReportFromVariables:function(a){var b={};a.variables.fullNames.forEach(function(a){var c=q.createFieldNameFromSource(a);b[a.substr(a.indexOf(".")+1)]=c});return(new r).enrichAreas({portalUrl:a.portalUrl,analysisAreas:a.analysisAreas,countryID:a.countryID,hierarchy:a.hierarchy,fields:u.convertForEnrich(a.variables),comparisonLevels:a.comparisonLevels||z.getDefaultLevels()}).then(function(d){var c=
a.analysisAreas.map(function(){return{}});g.addEnrichFeatures(d,b,q.DATA_COLLECTIONS_CALCULATOR_NAME,c);return{areaData:c}},function(b){a.fieldData.errors.push(b);return(new m).reject(b)})},applyRunReportAndGetDataResults:function(a,b){if(a&&a.areaData){var d=b.templateJson;b.fieldData.specialTradeAreaCalculatorName=d.metadata.specialTradeAreaCalculatorName;delete d.metadata;b.fieldData.runReportTaskIDs=a.taskIDs;b.fieldData.areaData=a.areaData;(b.fieldData.reportInfo=a.reportInfo)&&this._populateReportDataFromReportInfo(a.reportInfo,
b);this._reportDataFromAreas(b.analysisAreas,b.fieldData.areaData);this._reportDataFromReport(b.reportObject,b.fieldData,b.combinedAreasInfo);return this._populateReportDataFromAttachmentsStore(b)}},_populateReportDataFromReportInfo:function(a,b){b.reportTitle=b.reportObject.title=b.reportTitle||a.Title||"";a.country&&!f.getCurrentCountry()&&(f.setCountry(a.country),f.setHierarchyID(null));a.stdLevels&&!f.getGeographiesModel()&&f.setGeographiesModel(new w({levels:a.stdLevels}));if(h.updateVariableInfoFromDataXml||
h.isPlayerOnServer){var d=a.variables;x.processTemplateFieldInfos(b.templateJson,function(a){if(a.hasVariable&&a.variableID&&a.templateName){var c=a.templateName.indexOf("."),e=a.templateName.substr(0,c),c=a.templateName.substr(c+1);(e=d[e]&&d[e][c])&&e.alias&&(a.alias=e.alias,a=b.templateVariableProvider.get(a.templateName))&&(a.alias=e.alias,e.vintage&&(a.vintage=e.vintage),e.source&&(a.source=e.source))}})}a=y.collectVariablesStats(b.templateJson);if(a=b.templateVariableProvider.getVariablesDataVintageDescription({usedVariablesCache:a}))b.reportObject.dataVintageDescription=
a},_populateReportDataFromAttachmentsStore:function(a){var b=a.attachmentsStore,d=[];a.analysisAreas.forEach(function(c,f){b.supportsMultipleAreas&&b.setCurrentAnalysisAreaIndex(f);0===f&&d.push(k(b.getNotes(),function(b){b&&b.length&&(a.fieldData.metadata[p.SITENOTES_FIELD_NAME]=b.map(function(a){return a.text}).join("\x3cbr/\x3e\x3cbr/\x3e"),b.forEach(function(b,c){a.fieldData.metadata[p.getSiteNoteFieldNameAt(c+1)]=b.text}))}));d.push(k(b.getAttributes(),function(b){if(!b||!b.length)return null;
var c={attributes:{}};b.forEach(function(a){c.attributes[a.name]=a});(b=a.fieldData.areaData[f])&&g.addFeatureAttributesCalculator(c,b)}))});return l(d)},_reportDataFromAreas:function(a,b){a.forEach(function(a,c){if(c=b[c])g.addFeatureAttributesCalculator(a.feature,c),g.addAreaInfoCalculator(a,c)})},_reportDataFromReport:function(a,b,d){var c=b.metadata;a&&!c.Title&&(c.Title=a.title);c.Subtitle=b.reportInfo&&b.reportInfo.Subtitle||"";c.Source=a.dataVintageDescription||"Esri";c.Date=n.getReportFooterDate();
c.Copyright="\u00a9 "+n.getFullYear()+" Esri";c.ProductLabel="";c.ProductUrl="";c.PhoneNumber="";c.TrialUrlText="";a.isMultiFeature&&(c.SITE_NAME=d.locationName||d.name,c.STORE_NAME=d.locationName||d.name,c.AREA_DESC2=d.description||d.name,c.STORE_ADDR=d.address)}}});