// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.33/esri/copyright.txt for details.
//>>built
require({cache:{"url:esri/dijit/geoenrichment/ReportPlayer/core/templates/SimpleInfographic.html":'\x3cdiv class\x3d"esriGESimpleInfographic"\x3e   \r\n    \x3cdiv data-dojo-attach-point\x3d"mainViewDiv" class\x3d"esriGEAbsoluteStretched"\x3e\x3c/div\x3e\r\n\x3c/div\x3e\r\n\r\n\r\n'}});
define("esri/dijit/geoenrichment/ReportPlayer/core/infographics/simpleInfographic/SimpleInfographic","dojo/_base/declare dojo/_base/lang esri/dijit/geoenrichment/when dojo/dom-construct dojo/dom-style dijit/_WidgetBase dijit/_TemplatedMixin ../utils/InfographicLayoutResizer ../utils/InfographicJsonConversionUtil ../utils/InfographicThemeUtil ../../supportClasses/tableJson/TableJsonUtil ../../sections/supportClasses/InfographicBenchmarkController ../../sections/supportClasses/InfographicValueController esri/dijit/geoenrichment/ReportPlayer/core/sections/SectionTypes esri/dijit/geoenrichment/ReportPlayer/core/supportClasses/ElementUsageTypes esri/dijit/geoenrichment/ReportPlayer/core/supportClasses/ViewModes esri/dijit/geoenrichment/utils/InvokeUtil esri/dijit/geoenrichment/utils/ObjectUtil dojo/text!../../templates/SimpleInfographic.html".split(" "),function(q,
m,r,t,l,u,v,w,x,y,h,z,A,B,k,n,d,e,C){return q([u,v],{isSimpleInfographic:!0,templateString:C,viewModel:null,theme:null,parentWidget:null,currentFeatureIndex:null,currentFeatureAttributes:null,getPreviewValueFunction:null,isEditMode:!1,adjustElementsWhenResized:!1,_sections:null,_currentInfographicJson:null,_updatePromise:null,updateInfographic:function(a){if(this.domNode)if(this._currentInfographicJson=this._applyThemeToJson(a),this.isEditMode)this._doUpdateInfographic();else return this.onContentLoadingStart(),
this._updatePromise=d.invoke(this,"_doUpdateInfographic",50),this.onShowWaiting(this._updatePromise),this._updatePromise["finally"](function(){this.onContentLoadingEnd()}.bind(this)),this._updatePromise},refresh:function(){this.updateInfographic(this._currentInfographicJson)},_doUpdateInfographic:function(){if(this.domNode){this._destroySections();var a=this._currentInfographicJson;this._syncJsonDimensions();var c=this.viewModel.getStaticInfographicDefaultStyles(this.theme);l.set(this.domNode,"backgroundColor",
a.style.backgroundColor||c&&c.backgroundColor);l.set(this.domNode,{width:a.style.width+"px",height:a.style.height+"px"});this._preRender();this._renderHeader();this._renderVariableTables();this._postRender()}},_infographicValueController:null,_preRender:function(){this._infographicValueController=new A;this._infographicValueController.setVariableTables(this._currentInfographicJson.variableTables)},_renderHeader:function(){if(this._currentInfographicJson.header){var a=this._currentInfographicJson.header;
this._createSection(h.getTableWidth(a),h.getTableHeight(a),[a],a.style,null,-1,null)}},_renderVariableTables:function(){this._currentInfographicJson.variableTables.forEach(function(a){this._renderVariableTable(a)},this)},_renderVariableTable:function(a){var c=x.variableTableToNormalTables(a);return this._createSection(a.style.width,a.style.height,c.tableJsons,a.style,a,this._currentInfographicJson.variableTables.indexOf(a),c)},_createSection:function(a,c,h,d,e,p,f){var g=-1===p,b={};b.initialWidth=
a;b.initialHeight=c;b.json={type:B.DETAILS,stack:h};b.viewModel=this.viewModel;b.theme=this.theme;b.parentWidget=this;b.currentFeatureIndex=this.currentFeatureIndex;b.currentFeatureAttributes=this.currentFeatureAttributes;b.initialViewMode=this.isEditMode&&!this.getPreviewValueFunction?n.EDIT:n.PREVIEW_VALUES;b.elementUsageType=g?k.INFOGRAPHIC_HEADER_SECTION:k.INFOGRAPHIC_SECTION;b.getPreviewValueFunction=this.getPreviewValueFunction;b.infographicValueController=!g&&this._infographicValueController;
f&&this.viewModel.isBenchmarkedArea&&this.viewModel.isBenchmarkedArea(this.currentFeatureIndex)&&(a=new z,a.isVariableInShape=f.isVariableInShape,a.iconTableIndex=f.iconIndex,a.descTableIndex=f.descriptionIndex,a.backgroundColor=this.domNode.style.backgroundColor,b.infographicBenchmarkController=a);this.viewModel.dynamicReportInfo&&(b.tableParams={enableNumberAnimation:!0,allowSorting:!1});m.mixin(b,this._prepareSectionCreationParams(e,g));b=this.viewModel.layoutBuilder.createElement("section",b,
this.mainViewDiv);l.set(b.domNode,{position:"absolute",left:(g?0:d.left||0)+"px",top:(g?0:d.top||0)+"px"});b._variableTableParams={variableTable:e,variableTableIndex:p,elementsIndexHash:f};this._sections.push(b);return b},_prepareSectionCreationParams:function(a,c){return null},_postRender:function(){},getHeaderTable:function(){var a=this.getHeaderSection();return a&&a.getTables()[0]},getHeaderSection:function(){return this._sections.filter(function(a){return a.elementUsageType===k.INFOGRAPHIC_HEADER_SECTION})[0]},
getSectionIconTable:function(a){return a.getTables()[a._variableTableParams.elementsIndexHash.iconIndex]},getSectionVariableTable:function(a){return a.getTables()[a._variableTableParams.elementsIndexHash.variableIndex]},getSectionDescriptionTable:function(a){return a.getTables()[a._variableTableParams.elementsIndexHash.descriptionIndex]},getVariableSections:function(){return this._sections.filter(function(a){return a.elementUsageType===k.INFOGRAPHIC_SECTION})},getVisualState:function(){return null},
setVisualState:function(a){},_applyThemeToJson:function(a){var c=this.viewModel.getStaticInfographicDefaultStyles(this.theme);return y.applyThemeSettingsToJson(a,c)},notifyShown:function(){r(this._updatePromise,function(){this._sections&&this._sections.forEach(function(a){a.notifyShown()})}.bind(this))},width:null,height:null,resize:function(a,c){void 0!==a&&(this.width=a,this.height=c);if(this.isEditMode)this._checkNeedResize()&&this._doUpdateInfographic();else return this._checkNeedResize()&&d.invoke(this,
"_doUpdateInfographic",50)},_checkNeedResize:function(){return this._currentInfographicJson&&this.width&&this.height&&(!e.compareEqual(this._currentInfographicJson.style.width,this.width,1)||!e.compareEqual(this._currentInfographicJson.style.height,this.height,1))},_syncJsonDimensions:function(){this._checkNeedResize()&&w.resizeLayout(this._currentInfographicJson,this.width,this.height,{preserveHeaderPosition:!0,allowResizeInnerElements:!0,ignoreMinMaxConstraints:this.adjustElementsWhenResized,updateFontSize:this.adjustElementsWhenResized&&
!this._currentInfographicJson.preserveTextSize})},toJson:function(){return m.clone(this._currentInfographicJson)},onContentLoadingStart:function(){},onContentLoadingEnd:function(){},onShowWaiting:function(a){},_destroySections:function(){this._sections=this._sections||[];this._sections.forEach(function(a){a.destroy()});this._sections.length=0;this.domNode&&t.empty(this.mainViewDiv)},destroy:function(){this._destroySections();this.inherited(arguments)}})});